### ISSUE TITLE
[question] Aeotech Gen 2 DSB28

### ISSUE THREAD

**Issue by haavardNO** [AlCalzone/node-zwave-js#3346]
I have a Aeotech Gen DSB28. I have been using this device for several years and it has been working fine.
Used it with different controllers and it has worked fine. It also worked in the beginning with zwave2mqtt. But at some point it stopped to work. Due to several reasons I have not been able to report it until now.

I am able to add the device, and it looks ok. But I am not able to get it to auto report. I have tried to use the UI to set it up. And also the aeotech excel sheet and do it manually by setting parameter 101-103 and 111-113. 
When I click refresh, I am able to poll new values.
Any ideas?
![image](https://user-images.githubusercontent.com/27728530/133764278-efbaa4a2-90ad-4c1b-b0a2-606087869f89.png)

![image](https://user-images.githubusercontent.com/27728530/133764441-8b41c655-9683-41ab-8a8f-6c74798e82ec.png)

[node_106.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7184734/node_106.json.zip)

**Comment by AlCalzone** [comment]
Please make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs), loglevel `debug` or `silly` and attach it here as a file.
Also, seeing the configured associations would be good.

**Comment by haavardNO** [comment]
No problem. 
See attached.
There seams to be no groups set up. Could that be the cause?
![image](https://user-images.githubusercontent.com/27728530/133785964-36578232-d3e3-4f39-ace3-6c855f614b3e.png)


[zwavejs2mqtt-store-8.zip](https://github.com/zwave-js/node-zwave-js/files/7185764/zwavejs2mqtt-store-8.zip)

**Comment by haavardNO** [comment]
That fixed the issue.
I have no idea when that might have happened, since I dont play with groups at all. But when I add the following it works.
![image](https://user-images.githubusercontent.com/27728530/133786821-ef60bbc4-1cbf-4520-bdf4-d984f4694012.png)

Thanks for your help @AlCalzone

**Comment by AlCalzone** [comment]
Did you recently do a network heal? Maybe the route was removed but not re-added due to a communication error in the process.

Anyways, a re-interview should have detected and fixed this.

**Comment by haavardNO** [comment]
Hmm did a lot of faultfinding. Including a exclude reset and re include in to network...

**Comment by AlCalzone** [comment]
Ok, so no clear cause then. At least we found it.

**Comment by haavardNO** [comment]
Thanks again 😊

**Comment by robertsLando** [comment]
Weird that in the node export the lifeline association was there 🤷🏼‍♂️

**Comment by kpine** [comment]
> 
> 
> Weird that in the node export the lifeline association was there 🤷🏼‍♂️

Are you talking about the `"groups"` field in the node JSON? If so, I've noticed that it just shows all the groups the the device supports, not the ones that are currently defined.

If I understand correctly, you are using [`driver.controller.getAllAssociationGroups(nodeId)`](https://github.com/zwave-js/zwavejs2mqtt/blob/713815da3711179e218171922f7adc84df9b77c0/lib/ZwaveClient.ts#L763) to export the groups, and that returns all supported groups. If your goal is to show the currently defined associations, I think you would want to use [`driver.controller.getAllAssociations(nodeId)`](https://zwave-js.github.io/node-zwave-js/#/api/controller?id=managing-associations) instead. You're already doing this in the UI, so maybe the dump can show it as well?

**Comment by robertsLando** [comment]
Sorry, you are right, those are available groups, I fetch groups only when user ask for them in the page. Stupid me 😆
