### ISSUE TITLE
Missing device configuration: GoControl WO15EMZ5-1

### ISSUE THREAD

**Issue by pdobrien3** [AlCalzone/node-zwave-js#3352]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

GoControl Smart Wall Outlet

### Manufacturer ID

0x014f

### Product Type

0x574f

### Product ID

0x3535

### Firmware Version

1.35

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/2527

### Do you have a manual?

https://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/2527/WO15EMZ5-1%20Instructions.pdf

**Comment by pdobrien3** [comment]
Also found it under the OpenHAB at https://opensmarthouse.org/zwavedatabase/1186

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 2527 from zwa

@pdobrien3 the bot should create a PR with a starter template. That likely needs to be cleaned up to match our style guide though.

**Comment by blhoward2** [comment]
The easiest way to edit this is for you to push a PR onto the bot's branch `import-config-1631993009`.
