### ISSUE TITLE
Add `forceSceneControllerGroupCount` compat flag for Leviton VRCZ4

### ISSUE THREAD

**Issue by Ikcelaks** [AlCalzone/node-zwave-js#3355]
This depends on #3354 
@blhoward2 reported this in zwave-js/zwavejs2mqtt#1640
https://blog.gruby.com/2019/01/04/setting-up-a-leviton-vrcz4-m0z-for-use-with-home-assistant/

The device has 4 `Association CC` groups but supports 8 `Scene Controller Configuration CC` groups. The `forceSceneControllerGroupCount` flag should be set to 8.

**Comment by AlCalzone** [comment]
@blhoward2 we have two VRCZ4 configs: [VRCZ4](https://devices.zwave-js.io/?jumpTo=0x001d:0x0701:0x0206:0.0) and [VRCZ4-MR](https://devices.zwave-js.io/?jumpTo=0x001d:0x1202:0x0243:0.0). Which one do you have? I suspect we have to add the flag to both, but I'd like to verify.

**Comment by j9brown** [comment]
I think this flag is also required for VRCS4.

**Comment by blhoward2** [comment]
Agreed, both and the VRCS4. The difference is the one has a relay and the other is purely a scene controller. They all work the same way.

**Comment by AlCalzone** [comment]
If anyone has time, go ahead

**Comment by j9brown** [comment]
Yep, there are several variants of VRCS4 and VRCZ4, all of which have 8 scene groups.

FWIW, in my house I have: VRCS4-M0Z, VRCS4-MRZ, VRCZ4-MRX, and VRCZ4-MRZ.

Thanks for taking care of this!
