### ISSUE TITLE
Qubino Flush 2 relay / temperature sonsor attached to TS port not recognized as expected. 

### ISSUE THREAD

**Issue by havanablck80** [AlCalzone/node-zwave-js#3370]
I am having trouble with device:
ZMNHBD

Temperature sensor is recognizer as I3 I suppose.

Yours, 
Ville

**Comment by AlCalzone** [comment]
1. Read the device manual. You have to exclude and re-include the device after attaching a temperature sensor
2. Please fill out the issue template next time.

**Comment by havanablck80** [comment]
> 1. Read the device manual. You have to exclude and re-include the device after attaching a temperature sensor
> 2. Please fill out the issue template next time.

Indeed, thanks! Sorry.
