### ISSUE TITLE
Load templates from embedded dir if missing from user config dir

### ISSUE THREAD

**Issue by kpine** [AlCalzone/node-zwave-js#3471]
**Is your feature request related to a problem? Please describe.**
I was customizing a device config file, but it failed to load because a template file was not available in the user config directory. I don't have any intention of editing the template file, so I would just like to store the single device file. One of the easy things about the user config directory is I can just throw in a device file w/o having to worry about naming and directory structure. For a file that requires templates that becomes slightly more complicated. It also means if the config file is being used long-term, I don't need to maintain the template, only the single device file.

**Describe the solution you'd like**
When loading a user config file and the template file is not found, try to fallback to the embedded template file.

**Describe alternatives you've considered**
Save the template(s) into the user config dir with an identical directory structure compared to the embedded dir. This reduces the relative ease of customizing a device config though.

**Additional context**
```text
2021-10-05T05:52:32.925Z CONFIG   Error parsing config file zw062.json: Could not parse config file /usr/src/app
                                  /store/config/templates/master_template.json: ENOENT: no such file or director
                                  y, open '/usr/src/app/store/config/templates/master_template.json'
                                  Import stack:
                                    in #base_0-100_nounit
                                    in /usr/src/app/store/config/zw062.json
```

```text
$ pwd
/srv/apps/z2m/data/config
$ ls
14287.json  zw062.json
```

**Comment by AlCalzone** [comment]
If anyone wants to work on this, go for it.
