### ISSUE TITLE
Some NAS-DS01Z not recognized

### ISSUE THREAD

**Issue by Crazyachmed** [AlCalzone/node-zwave-js#3480]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

I bought a batch of "Neo NAS-DS01Z" Door-Window-Sensors. All of them work just fine, but some are not recognized fully. I attached the debug log for an interview of Node 046, which is one of the sensors with the issue.

### Device information

Adapter Version in iobroker: 2.2.0
Installed DB: 8.4.2-20210929

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [X] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwavejs2mqtt` branch:

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwavejs_2021-10-08.log](https://github.com/zwave-js/node-zwave-js/files/7313217/zwavejs_2021-10-08.log)

**Comment by AlCalzone** [comment]
The device that isn't recognized has a fingerprint of
```
manufacturer id: 0x0258
product type:    0x0200
product id:      0x1022
```
which we don't have a configuration file for. Please fill out the following issue template and provide all information you have there:
https://github.com/zwave-js/node-zwave-js/issues/new?assignees=&labels=config+%E2%9A%99&template=device_config.yml&title=Missing+device+configuration%3A+%3Center+manufacturer+and+device+name%3E

Especially the manual (photo or PDF) with the config parameters would be helpful.

**Comment by Crazyachmed** [comment]
I don't have any kind of information. This seems to be a new HW revision, because I received some of the "old" type in the same package. I can't find the new IDs in the Z-Wave Product Catalog.

The new revision has the same manufacturer ID, but product ID 0x1022 instead of 0x1082 and product type 0x0200 instead of 0x0003. Does it still make sense to open an issue template with the minimal amount of information I have or is there a way to copy the definition of the old device to the new IDs?

**Comment by AlCalzone** [comment]
If they have the same configuration params etc, we just add the new IDs to the existing device. Your driver logs above contain most of the information that's requested in the template.

Except the manual of course, which is why we ask for it. Although if you can confirm that your mixed bag of devices has the same manuals for both revisions, that's good enough for me.

**Comment by Crazyachmed** [comment]
Yeah, they were all the same. So no need to open a new ticket?

**Comment by AlCalzone** [comment]
Not necessary, this one will do 👍🏻

**Comment by AlCalzone** [comment]
@zwave-js-bot add fingerprint 0x0200:0x1022 to 0x0258:0x0003:0x1082
