### ISSUE TITLE
Class 'ZWaveNode' incorrectly implements interface 'SecurityClassOwner'.

### ISSUE THREAD

**Issue by bchabrier** [AlCalzone/node-zwave-js#3503]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Compilation with `tsc` shows errors

What do you observe?
Errors:
```
node_modules/zwave-js/build/lib/node/Node.d.ts:21:22 - error TS2420: Class 'ZWaveNode' incorrectly implements interface 'SecurityClassOwner'.
  Property 'securityClasses' is missing in type 'ZWaveNode' but required in type 'SecurityClassOwner'.

21 export declare class ZWaveNode extends Endpoint implements SecurityClassOwner {
                        ~~~~~~~~~

  node_modules/@zwave-js/core/build/security/SecurityClass.d.ts:24:14
    24     readonly securityClasses: Map<SecurityClass, boolean>;
                    ~~~~~~~~~~~~~~~
    'securityClasses' is declared here.


Found 1 error.
```

What did you expect to happen?
No errors

  1. Install latest version of zwave-js with: `yarn add zwave-js`
  2. Import the module with: `import { Driver } from 'zwave-js';`
  3. Compile with: `tsc`

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [x] Other _(please describe)_: using zwave-js in my own typescript project

### Which branches or versions?

version:
`node-zwave-js` branch: 8.4.1 

version of node etc:
```
$ ts-node -vv
ts-node v10.2.1
node v14.18.0
compiler v4.1.3
```

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

It worked from version 8.0.5 to 8.0.8.
It doesn't work since version 8.1.0.

### Attach Driver Logfile

None

**Comment by AlCalzone** [comment]
Huh, I always enable `skipLibCheck` in `tsconfig.json`, so I never noticed this.
