### ISSUE TITLE
Missing configuration command class on Sunricher wall panels

### ISSUE THREAD

**Issue by mgjbroadbent** [AlCalzone/node-zwave-js#3535]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

The command class attribute is not detected by zwavejs when including the wall panel into the network.

What do you observe?

The configuration panel is not visible in the zwave2mqtt UI.  The command class information is not present in the configuration file.

What did you expect to happen?

The configuration panel should be visible and allow parameter #3 to be configured.

The wall panel documentation states support for the configuration command class.  In the a legacy openzwave configuration file, the configuration command class is listed in the capabilities that are detected.

https://www.sunricher.com/media/resources/manual/SR-ZV9001T-CCT-EU%20Instruction.pdf
https://www.sunricher.com/media/resources/manual/SR-ZV9001T-RGBW-EU%20Instruction.pdf

  1. Include a ZV9003T variant wall panel (config `0x0330/zv9003t-rgbw.json`) into the zwave network using v8.1.0 or later of zwavejs.
  2. Examine configuration of included node and see command class 0x70 is missing.

### Device information

Manufacturer: Sunricher (0x0330)
Model name: ZV9003T-RGBW
Node ID in your network: 26

Also affected is ZV9003T-CCT - node 19.

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 8.5.0
`zwavejs2mqtt` branch: 5.9.0

### Did you change anything?

yes (please describe)

### If yes, what did you change?

I have tried modifying the configuration `node-zwave-js/packages/config/config/devices/0x0330/zv9003t-rgbw.json` and added the following section to force the command class to appear:

```
	"compat": {
		"commandClasses": {
			"add": {
				"0x70": {
					"isSupported": true,
					"isControlled": false,
					"secure": false,
					"version": 1
				}
			}
		}
	},
```

This makes the parameter configuration appear however, attempting to get the configuration results in a timeout waiting for the response.

```
2021-10-17T10:57:48.533Z DRIVER » [Node 026] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      43
                                  └─[ConfigurationCCGet]
                                      parameter #: 3
2021-10-17T10:57:48.549Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-10-17T10:57:48.600Z DRIVER « [REQ] [SendData]
                                    callback id:     43
                                    transmit status: OK
2021-10-17T10:57:58.610Z CNTRLR   [Node 026] Timed out while waiting for a response from the node
```

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[zwavejs_20211017.txt](https://github.com/zwave-js/node-zwave-js/files/7359774/zwavejs_20211017.txt)

I have included the complete driver startup and also reinterviewed node 26.

**Comment by AlCalzone** [comment]
The support of CCs is not determined by config files (although we can override information reported by the device). Your device doesn't list the `Configuration CC` in its NIF:
```
2021-10-17T11:22:08.812Z CNTRLR « [Node 026] node info received
                                  supported CCs:
                                  · Z-Wave Plus Info
                                  · Association
                                  · Association Group Information
                                  · Multi Channel Association
                                  · Transport Service
                                  · Version
                                  · Manufacturer Specific
                                  · Device Reset Locally
                                  · Powerlevel
                                  · Security
                                  · Security 2
                                  · Supervision
                                  · Central Scene
                                  · Firmware Update Meta Data
                                  controlled CCs:
                                  · Multilevel Switch
                                  · Color Switch
                                  · Scene Activation
                                  · Scene Actuator Configuration
```
and the fact that it does not respond to the query makes me thing that it actually does not support the CC.
Your device is on firmware 1.10, so maybe that was only added later?

Unfortunately it is pretty common that these chinese manufacturers include manuals that don't match the device's firmware and there's no changelog or anything to figure out changes between firmwares.

**Comment by mgjbroadbent** [comment]
Thanks for the detailed response and appreciate you looking into it.  I'll attempt to find a resolution through the reseller I bought it from.

Closing this issue.
