### ISSUE TITLE
[feat] Enable Priority Route functionality

### ISSUE THREAD

**Issue by Malkierian** [AlCalzone/node-zwave-js#3544]
**Is your feature request related to a problem? Please describe.**
Heal Network doesn't make the nodes take the shortest route they actually can, in fact I've tried several and they have set very inefficient routes (my controller is positioned such that nothing more than 2 hops should be necessary with my current setup except for one node, yet it refuses to update node connections to reflect this).

**Describe the solution you'd like**
The ability to set Application Priority Routes to effectively minimize the number of hops.

**Describe alternatives you've considered**
Currently there are no alternatives

**Additional context**
https://i.imgur.com/mKcKaZi.png
This is my current network map. However, from north to south, the order of node placement is actually
Front Door Light/Mailbox Door -> R Bedroom Light -> Kitchen Extender -> Scene Controller -> Controller -> Garden Extender -> Quail Light Dimmer. This was after I moved the controller from my room to a central location and healed the network twice. Garden Extender should be connected directly to the Controller and the Mailbox Door should be connected to the Front Door Light. This network map doesn't make any sense.

**Comment by AlCalzone** [comment]
First things first: I'm not against implementing that functionality.

> This network map doesn't make any sense.

Just to be clear: This map **only** indicates neighbors, not which routes will be taken.

I'm not yet sure why but I've seen tons of examples where neighbors are also missing from that map, so don't put too much weight into it. Maybe the routes haven't settled yet - there's a ton of magic happening we don't have influence over. Unless you have actual connectivity issues and/or have verified the incorrect routes with a Zniffer, I'd avoid premature optimization.

I do have a theory you could help me test: Which stick are you using? Which firmware (should be visible in the driver log on startup, "serial API version")?

**Comment by Malkierian** [comment]
I'm using the Zooz ZST10 700.

Where do I access the driver logs?

**Comment by AlCalzone** [comment]
https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs - make sure to set the loglevel to debug

**Comment by Malkierian** [comment]
Ah, I'd forgotten to save the settings when I enabled them before. Was wondering why they weren't showing up in Store.

Anyway, here's some details:
Driver version 8.4.1
Library version: 7.15
I assume library and firmware version are the same thing in this instance, since they're both 7.15.

**Comment by AlCalzone** [comment]
Yep, 7.15 seems correct. Did you include all devices on that version or did you do any firmware updates meanwhile?

Silabs seem to have fixed something very recently in 7.16, which could explain weird neighbor information, but I'm still trying to get a bigger picture.

**Comment by Malkierian** [comment]
Yeah, the stick was brand new like 2 weeks ago, so everything has been added since then.

**Comment by AlCalzone** [comment]
Ok that could support my theory:
Firmware 7.16 fixes a bug where inclusion is done with a too high TX power. Normally the power is reduced, so nodes at the brink of connectivity don't include on direct range if they can't communicate reliably and are instead forced to mesh. Now if they were barely included but later don't see their neighbors, this could explain the weird neighbor situation you're having.

That doesn't help you though 😅
