### ISSUE TITLE
Z-Wave node sensor entities no longer display value 254

### ISSUE THREAD

**Issue by th3dll** [AlCalzone/node-zwave-js#3587]
Battery powered PIR Sensors occasionally go into deep sleep causing a string of false motion events. With the original Z-Wave integration for Home Assistant there was a clear indicator by having a code value 254 intermingled with the 8 and 0 events. Zwave-JS seems to ignore or possibly convert them into an 8 or 0 value. I no longer see any indicator in any history logs.

"Node Sensor" entities, which are now disabled by default, still allows me to find the old style code values, but the functionality is not the same. They are now converting old numeric values into "Motion detection" and "Idle". If you dig into the attributes of the state you can see the numerical values of 0 and 8. However, I don't think the value of 254 has been included or expected and is therefore ignored as garbage signal. This has diminished functionality for me as I can no longer clearly eliminate false alarms in any automation.

**Comment by AlCalzone** [comment]
254 is the "unknown" notification, which zwave-js writes into a value ID
```jsonc
{
	commandClass: 113,
	endpoint: /* probably 0 */,
	property: /* probably "Home Security" or 7 */,
	propertyKey: "unknown",
}
```
You should be getting this as a separate value update, but I can't tell without seeing the logs that are requested in the [bug report issue template](https://github.com/zwave-js/node-zwave-js/issues/new?assignees=&labels=&template=bug_report.yml).

**Comment by th3dll** [comment]
I appreciate your help and apologize for not following the proper procedures of submitting a bug report. I'm not sure I'm going to get the proper logs. I have two things working against me on this:

1. The deep sleep doesn't occur frequently (for better or worse). 
2. I'm not sure how to aggregate logs for an extended period. I only see an option to collect logs from within the web interface. Is there another way to aggregate debug level logs into a file or files? I'm having the problem of leaving a browser tab open for an extended period of time and when i come back, it auto-refreshes the page and I can see at some point it timed out of keeping logs. It's obvious lots of missing log entries are not there. I'm not sure I'll ever get an accurate log without another means. 

I respect if you need to close this from it missing critical info. I'll try and find another way to get more accurate output and submit again if possible.

**Comment by AlCalzone** [comment]
You can use zwavejs2mqtt to write log files and download them later. The log file rotation stores the last 7 days, which might be enough to replicate the issue.
