### ISSUE TITLE
Air temperature doesn't refresh on Eurotronics Spirit radiator valves

### ISSUE THREAD

**Issue by lucode** [AlCalzone/node-zwave-js#3593]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
I use those devices since about 2 years and hadn’t much troubles yet. About 6 month ago I did migrate from Open Z-Wave to Z-Wave JS (V0.1.45 currently) in combination with Z-Wave JS to MQTT.
I’m not quite sure if the problem exists since the migration, or if it is caused by an update.

What do you observe?
When I started to use my heating again I noticed that the air temperature wasn’t accurate anymore. In fact my HA Z-Wave setup does not refresh those values anymore. When I go to to the Z-Wave JS to MQTT Dashboard I can manually refresh the values and they get accurate then.
What did you expect to happen?
The sensor data should get updated regularly.
  1. Go to 'MQTT Z-Wave Dashboard'
  2. Click on 'a Eurotronic Valve'
  3. Scroll down to 'Multilevel Sensor' and refresh the Air Temperture
  4. See that the value gets updated now.

### Device information

Manufacturer: Eurotronics (Manufacturer ID: 0x0148)
Model name: Spirit
Node ID in your network:  7 (example dump)

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:  HA version: 0.1.45,  version 8.4.1
`zwavejs2mqtt` branch: : HA 0.27.0  version 8.4.1

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

It did work with Open Z-Wave beta, but I'm not sure if it did with Z-Wave JS in a previous version.

### Attach Driver Logfile

```
{
  "id": 7,
  "name": "Tstat Salon Entree",
  "loc": "Salon",
  "values": [
    {
      "id": "7-49-0-Air temperature",
      "nodeId": 7,
      "commandClass": 49,
      "commandClassName": "Multilevel Sensor",
      "endpoint": 0,
      "property": "Air temperature",
      "propertyName": "Air temperature",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Air temperature",
      "ccSpecific": {
        "sensorType": 1,
        "scale": 0
      },
      "stateless": false,
      "unit": "°C",
      "list": false,
      "value": 21.58,
      "lastUpdate": 1634825645858,
      "newValue": 21.58
    },
  
  "productLabel": "Spirit",
  "productDescription": "Thermostatic Valve",
  "manufacturer": "Eurotronics",
  "firmwareVersion": "0.15",
  "protocolVersion": 3,
  "zwavePlusVersion": 1,
  "zwavePlusNodeType": 0,
  "zwavePlusRoleType": 7,
  "nodeType": 1,
  "endpointsCount": 0,
  "endpointIndizes": [],
  "isSecure": "unknown",
  "supportsSecurity": false,
  "supportsBeaming": true,
  "isControllerNode": false,
  "isListening": false,
  "isFrequentListening": "1000ms",
  "isRouting": true,
  "keepAwake": false,
  "maxDataRate": 100000,
  "deviceClass": {
    "basic": 4,
    "generic": 8,
    "specific": 6
  },
  "deviceId": "328-1-3",
  "status": "Alive",
  "interviewStage": "NodeInfo",
  "statistics": {
    "commandsTX": 95,
    "commandsRX": 75,
    "commandsDroppedRX": 0,
    "commandsDroppedTX": 0,
    "timeoutResponse": 0
  },
  "lastActive": 1634900408260,
  "batteryLevel": 95,
  "_name": "Tstat Salon Entree (Salon)"
}
```
Here the log file plus some debug logs about node 7. It shows that the regular polling includes Air temp but does not update the value. But after a manual refresh it does it.
[log_MQTT_21-07.txt](https://github.com/zwave-js/node-zwave-js/files/7411041/log_MQTT_21-07.txt)
[zwavejs_2021-10-25.log](https://github.com/zwave-js/node-zwave-js/files/7411112/zwavejs_2021-10-25.log)

**Comment by AlCalzone** [comment]
Z-Wave JS doesn't poll automatically to keep the network load as low as possible. If you actually need to poll, you need to setup associations yourself.

That being said, this could be an incorrect lifeline association preventing the device from reporting on its own. Try updating to a version that includes zwave-js 8.5.0 or higher, then re-interview your device and see if this fixes it.

**Comment by marcus-j-davies** [comment]
Not entirely related.

but we (thats means @AlCalzone 😉 )
found an issue with this device with a NR User

in that, the offset reports the user value -1, whether this is a reporting  issue with the device, or its supplying a -1 on the provided value is unknown.


further info if you need it.
https://github.com/zwave-js/node-red-contrib-zwave-js/discussions/140

**Comment by lucode** [comment]
Ok could update the Z-Wave (zwavejs2mqtt) version in the meantime and after re-interviewing the problems seems to be resolved.
```
zwavejs2mqtt: 5.10.1
zwave-js: 8.6.1
```
Also the new security level feature does show up correctly now. 
I did as well had a look at the associations but couldn't figure out how to do it. For my understanding a association is between z-wave nodes and not between a node and the server, except the lifeline as it is setup by default. But I might be wrong here.

**Comment by AlCalzone** [comment]
> except the lifeline as it is setup by default

And that one is sometimes wrong or missing :)

**Comment by lucode** [comment]
Frankly I don't have a clue about how I can handle those associations in zwavejs2mqtt.
![image](https://user-images.githubusercontent.com/2928740/140088115-31ae8844-6615-4bb7-93bf-3ac35e4b70bd.png)
And if I look at another z-wave climate thermostat (Heltun); it has the same association and works perfectly well in updating the air temp. BTW after an hour or so HA doesn't show the actual temps anymore.

**Comment by AlCalzone** [comment]
That looks like it is already set up correctly. If not, check out the driver logs if anything is coming in at all.

**Comment by lucode** [comment]
Here's the log of the Air temp section.

```
   {
      "id": "7-49-0-Air temperature",
      "nodeId": 7,
      "commandClass": 49,
      "commandClassName": "Multilevel Sensor",
      "endpoint": 0,
      "property": "Air temperature",
      "propertyName": "Air temperature",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Air temperature",
      "ccSpecific": {
        "sensorType": 1,
        "scale": 0
      },
      "stateless": false,
      "unit": "°C",
      "list": false,
      "value": 20.78,
      "lastUpdate": 1635934607143,
      "newValue": 20.78
    },
```
It seems the node is only active when the setpoint is getting changed from the HA scheduler.
![image](https://user-images.githubusercontent.com/2928740/140108323-99cb12bd-4d37-400e-9445-b47663b29435.png)

**Comment by lucode** [comment]
That's the same log if the Heltung sensor that works fine:
The difference are   "stateless": false, and  "list": false on the spirit are not listed on the Heltung.  List seems to be the interesting one.

```
   {
      "id": "2-49-0-Air temperature",
      "nodeId": 2,
      "commandClass": 49,
      "commandClassName": "Multilevel Sensor",
      "endpoint": 0,
      "property": "Air temperature",
      "propertyName": "Air temperature",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Air temperature",
      "ccSpecific": {
        "sensorType": 1,
        "scale": 0
      },
```

**Comment by lucode** [comment]
I think I did find the final step of the solution. While browsing again to the manual I stumbled on the parameter 5, which defines the threshold (Delta) when the air temp is going to be send. This was still on the default value of 0.5 °C. So small temp changes, which are required for my automation are not transmitted at all. In a heating steps of 0.5 °C are often used but before the upgrade to the latest version even those haven't been transferred. The history was a string also at night when my room temp goes down by 2  °C .
![image](https://user-images.githubusercontent.com/2928740/140148645-dc1a386a-449b-4bea-b64b-78dac3afede1.png)
 Now it works as it should:
 
![image](https://user-images.githubusercontent.com/2928740/140162001-3d89369c-e0d2-4bc5-99f3-c8bd186a392c.png)

**Comment by stellavision** [comment]
That parameter setting according to the manual should be a multiple of 0.1, 5 (default) being 0.5 degree and 1 being 0.1 degree change. Mine automatically reports the temp when it is set to 1 (0.1) but not when it is set to the default 5 (0.5) and temperature report only changes if I manually poll it. 

![image](https://user-images.githubusercontent.com/8455871/140175581-5a07e362-2b52-470a-87c2-41bef0dab988.png)

**Comment by AlCalzone** [comment]
Good catch - I've opened https://github.com/zwave-js/node-zwave-js/pull/3659 to update the parameters

**Comment by lucode** [comment]
> That parameter setting according to the manual should be a multiple of 0.1, 5 (default) being 0.5 degree and 1 being 0.1 degree change. Mine automatically reports the temp when it is set to 1 (0.1) but not when it is set to the default 5 (0.5) and temperature report only changes if I manually poll it.
> 
My thermostat did stop polling again (with param set to 0.2 degree). What do you mean with manual polling exactly @stellavision.

**Comment by AlCalzone** [comment]
Polling means sending a GET request to the device so it responds with a report. Z-Wave JS doesn't do that automatically, except for verification after a SET. For modern devices like this one, it shouldn't be necessary to poll.

It could also be that the device tries to send an update but the reports are getting lost due to a bad connection to the controller.

**Comment by lucode** [comment]
THX @AlCalzone for the clarification. IMPORTANT the automatic polling does only work if I set the Temp report para to 0.1 degree. 0.5 and 0.2 don't poll at all, others I haven't tested.

**Comment by AlCalzone** [comment]
You mean automatic **reporting**, not polling 😉

**Comment by lucode** [comment]
I just fixed another issue with not reported states on nodes and could fix it with downgrade of the Z-Wave JS to MQTT HA Addon.

That the versions will rise the different problems:
```
zwavejs2mqtt: 5.10.1
zwave-js: 8.6.1

Z-Wave JS to MQTT: 0.28.0
```
Z-Wave JS to MQTT: 0.27.0 with the same other versions will fix all the issues including the Eurotronic not reporting Air temperature changes above 0.1 degree.

**Comment by lucode** [comment]
Ok seems to be fixed in the newest version.

```
Z-Wave JS to MQTT, V 0.30.0
zwavejs2mqtt: 5.12.0
zwave-js: 8.7.6
```

**Comment by Wri84** [comment]
Sorry for gravedigging. I've got the problem on the most current version of everything (since I reinstalled everything just this week).

While I'm able to set heat/off and so on, the current temperature measured at the thermostat is only updated when actively hitting refresh in zjsui.

Was there a setting you changed, which helped with the auto reporting?

**Comment by lucode** [comment]
No issues here with.
zwave-js-ui: 8.2.2
zwave-js: 10.3.0
home id:

**Comment by Wri84** [comment]
So I have actually one out of 5 thermostats that is working, while all the others do not.

[Pastebin debug.log of the working node](https://pastebin.com/1m3NhUV8)

[and of one not working node](https://pastebin.com/SKfTaRp5)

Has anyone any ideas, how this could be? As I've said, this is on a fresh installation.

Help would be really appreciated, as it's getting colder and colder :)

**Comment by lucode** [comment]
Did you play around with the Temp report threshold? That's the only method so far to fix it. And ev. to re-interview the node.
![image](https://user-images.githubusercontent.com/2928740/200272263-afa82837-5dd7-4444-bc9c-ddf07e8a974e.png)

**Comment by cadwizzard** [comment]
I think i'm seeing something very familiar with the CometZ valves - rendering them almost useless to control heating
![Screenshot_20240121_184858_Home Assistant](https://github.com/zwave-js/node-zwave-js/assets/7688705/76eb7bb9-842b-464c-a7b3-9a148d6c899b)
@AlCalzone could you please let me know exactly where to report it. I feel directed to report in HA core issues after looking through the checklists in, but i'm using JSUI. I'll post where you suggest best. Thanks

**Comment by AlCalzone** [comment]
@cadwizzard if the device is reporting unreliably, and you've excluded connectivity issues [[1]](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting) [[2]](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/network-health?id=testing-the-connection-strength), then I'm afraid the correct place to report it is info@eurotronic.org 🤷‍♂️
Neither Z-Wave JS nor HA can do anything about the device not sending the reports.

**Comment by cadwizzard** [comment]
> @cadwizzard if the device is reporting unreliably, and you've excluded connectivity issues [[1]](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting) [[2]](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/network-health?id=testing-the-connection-strength), then I'm afraid the correct place to report it is info@eurotronic.org 🤷‍♂️
> Neither Z-Wave JS nor HA can do anything about the device not sending the reports.

I think that it's maybe not the TRV itself the more I look into this. Every one behaves the same, it's not connectivity as I have several dispersed in a very well connected mesh (most of 60 nodes are powered, except the trvs).
After interview they can be fine for a while in JSUI, reporting every .5 degree then seemingly intermittent with a manual sensor refresh getting the right info straight away. 
Other people in other posts are seeing this weirdness. Re-interview seems to solve it for a while each time. The symptoms are almost exactly the same as were fixed for the spirit. 
Maybe they are sending messages that are being misinterpreted?

(I posted here too also help anyone searching the same for the CometZ)

I have these (4) currently in use in a house with nearly 20 spirits.

I'd really like to submit in the right place and have someone who knows what they are looking at to check logs etc..  or I'll simply have to just remove them all (this behaviour just leaves the boiler on forever with all the valves closed)

**Comment by AlCalzone** [comment]
> Maybe they are sending messages that are being misinterpreted?

If that's maybe the case, [here](https://github.com/zwave-js/node-zwave-js/discussions/new?category=request-support-investigate-issue) is the right place. I'll need some additional info to go with the logs, e.g. some timestamps where you expected a change but got none. Note that it [may be a while](https://github.com/zwave-js/node-zwave-js/issues/6521) until I can look at it.

**Comment by cadwizzard** [comment]
Thanks. I'll post as much info as possible and leave one of these included
in a room that has two TRVs (so I can use a spirit to reliably run the
boiler there).
That way the timing works to your schedule and commitments ;)

Thanks again.

**Comment by cadwizzard** [comment]
@AlCalzone and to point others in the right direction in relation to CometZ --> https://github.com/zwave-js/node-zwave-js/discussions/6634
