### ISSUE TITLE
Missing device configuration: HomeSeer HS-WX300

### ISSUE THREAD

**Issue by chasebolt** [AlCalzone/node-zwave-js#3609]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

HomeSeer HS-WX300

### Manufacturer ID

0x000c

### Product Type

0x4447

### Product ID

0x4036

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4176?selectedFrequencyId=-1

### Do you have a manual?

https://docs.homeseer.com/display/HSPRODKB/HS-WX300+User+Guide

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4176 from zwa

**Comment by AlCalzone** [comment]
The bot created a starter file in the linked PR. It does need to be revised manually, see my comments in the PR and our style guide.
To help with this, create a PR with target branch `import-config-1635405166`.
