### ISSUE TITLE
Leviton ZW15R/ZW4SF devices not communicating to controller

### ISSUE THREAD

**Issue by kars85** [AlCalzone/node-zwave-js#3615]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Randomly lost manufacturer and product information on Leviton ZW15R outlet and Leviton ZW4SF fan controller. 
What do you observe?
Device interviews are unsuccessful and show Unknown manufacturer 0xXXXX | 0xXXXX
What did you expect to happen?
For device discovery to identify. I have one other ZW15R that interviews successfully in the mesh.

### Device information

Manufacturer: Leviton
Model name: ZW15R
Node ID in your network: 21

Manufacturer: Leviton
Model name: ZW4SF
Node ID in your network: 5

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

zwavejs2mqtt: 5.10.1
zwave-js: 8.6.1

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Identified fine yesterday. Updated to latest build and after restart, failed to identify.

### Attach Driver Logfile

[zwavejs_2021-10-28.log](https://github.com/zwave-js/node-zwave-js/files/7435264/zwavejs_2021-10-28.log)

**Comment by kars85** [comment]
Here is an updated log file after I query the device (Node 21) through a node red flow via home assistant. Uploading in case seeing some traffic helps
[zwavejs_2021-10-28_after_query.log](https://github.com/zwave-js/node-zwave-js/files/7435333/zwavejs_2021-10-28_after_query.log)
.

**Comment by AlCalzone** [comment]
```
2021-10-28T14:50:46.846Z DRIVER « [Node 021] [REQ] [BridgeApplicationCommand]
                                  └─[SecurityCCCommandEncapsulation]
                                    │ sequenced: false
                                    └─[SecurityCCCommandsSupportedReport]
                                        reportsToFollow: 0
                                        supportedCCs:
                                        controlledCCs:
2021-10-28T14:50:46.847Z CNTRLR « [Node 021] received secure commands (S0)
                                  supported CCs:
                                  controlled CCs:
```

They were probably included with S2 but for some reason don't get queried with S2. Can you share the `<homeid>.json` cache file?

**Comment by kars85** [comment]
@AlCalzone 
[df45a4d8.json.log](https://github.com/zwave-js/node-zwave-js/files/7435404/df45a4d8.json.log)

**Comment by AlCalzone** [comment]
Node 21 at least was previously determined not to have been granted an S2 class:
```
            "securityClasses": {
                "S2_AccessControl": false,
                "S2_Authenticated": false,
                "S2_Unauthenticated": false,
                "S0_Legacy": true
            },
```
You can try shutting down z2m, removing this section from the affected nodes and re-interviewing them afterwards.

**Comment by kars85** [comment]
> 
> 
> Node 21 at least was previously determined not to have been granted an S2 class:
> 
> ```
>             "securityClasses": {
>                 "S2_AccessControl": false,
>                 "S2_Authenticated": false,
>                 "S2_Unauthenticated": false,
>                 "S0_Legacy": true
>             },
> ```
> 
> You can try shutting down z2m, removing this section from the affected nodes and re-interviewing them afterwards.

That worked on my first device I removed that section from Node 21. Reinterviewing brought the S2 properties back into my cache file.

Initially when the device was paired, z2m indicated S2 pairing went fine. So, I'm wondering from that initial point (when the device worked to now (not working), how that S2 pairing got wonky in z2m. No way to really find out I guess, without digging through log archives.

For my own edification, the S2 association is held on the device and it tells the controller of it's prior stored pairing configuration and updates the <homeid>.json with its properties? Here is the new cache for that node:

Update: That process of removing worked on my second node (5), as well.

```       "21": {
            "id": 21,
            "interviewStage": "Complete",
            "deviceClass": {
                "basic": 4,
                "generic": 16,
                "specific": 0
            },
            "isListening": true,
            "isFrequentListening": false,
            "isRouting": true,
            "supportedDataRates": [
                40000,
                100000
            ],
            "protocolVersion": 3,
            "nodeType": "Routing End Node",
            "supportsSecurity": false,
            "supportsBeaming": true,
            "securityClasses": {
                "S2_AccessControl": false,
                "S2_Authenticated": true,
                "S2_Unauthenticated": true,
                "S0_Legacy": false
            },```

**Comment by AlCalzone** [comment]
> For my own edification, the S2 association is held on the device and it tells the controller of it's prior stored pairing configuration and updates the .json with its properties?

No, the device and controller separately keep track of the granted security classes. It is possible to test which ones were granted, but that process can take a couple of seconds since timeouts may be involved. Therefore this information doesn't get reset on a re-interview, but this might be necessary.
