### ISSUE TITLE
Heltun TPS05 missing parameters 31-35 and have wrong text in param 51-55

### ISSUE THREAD

**Issue by johanschelin** [AlCalzone/node-zwave-js#3616]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
- "Errors" in the device template

What do you observe?
- Parameters 31-35 is missing, and is controlling the functionality of the LEDs.
- Parameters 51-55 has wrong label on option 5 (5 = momentary push)

What did you expect to happen?
- Parameters 31-35 is missing, and is controlling the functionality of the LEDs. (Off, relaycontroled, controller-controled)
- Parameters 51-55 has wrong label on option 5 (5 = momentary push)

### Device information

Manufacturer: Heltun
Model name:  Touchpanel TPS05

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
zwavejs2mqtt: 5.8.0
zwave-js: 8.4.1
home id: 4110551221
home hex: 0xf50208b5

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

Attaching image of missing 31-35 and wrong label on option 5 in param 51-55

![image](https://user-images.githubusercontent.com/65488934/139294008-834c35fe-45eb-49c5-9e8e-3310bd8e2019.png)
![image](https://user-images.githubusercontent.com/65488934/139294029-e7bac08f-8e1d-4164-808d-e438a373338a.png)

**Comment by johanschelin** [comment]
And here is the correct values/labels from the latest manual:
![image](https://user-images.githubusercontent.com/65488934/139311426-8f0ab45f-cdb1-4bcf-8509-5e22ad231eb4.png)
![image](https://user-images.githubusercontent.com/65488934/139311435-095a7a67-2fe3-4cf1-bf59-61dfc332d10a.png)

**Comment by AlCalzone** [comment]
Is it possible those were added/changed in a newer firmware?
/cc @popescunsergiu since you've been going strong with the Heltun devices

**Comment by johanschelin** [comment]
No they have been there from the start (I was one of Heltuns first ever customers). So I think @popescunsergiu just missed them by mistake. Well done by the way @popescunsergiu - Im thankful for your work!

**Comment by AlCalzone** [comment]
@zwave-js-bot config help wanted

**Comment by AlCalzone** [comment]
@zwave-js-bot config help wanted
