### ISSUE TITLE
Missing device configuration: Minoston Outdoor Dimmer Plug

### ISSUE THREAD

**Issue by brisketfingers** [AlCalzone/node-zwave-js#3621]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Minoston Outdoor Dimmer Plug

### Manufacturer ID

0x0312

### Product Type

0xff07

### Product ID

0xff03

### Firmware Version

1.0

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4254?selectedFrequencyId=2

### Do you have a manual?

https://products.z-wavealliance.org/products/4254/pics

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4254 from zwa

**Comment by AlCalzone** [comment]
The bot has created a starter template, but that usually needs to be cleaned up and aligned to our style guide.
If you'd like to help, you can create a PR on the branch in the bot's PR.

**Comment by AlCalzone** [comment]
Ok never mind. We do have a file, it just needs another fingerprint added.
