### ISSUE TITLE
The command class Application Status is not implemented (ZW0303) - Remotec ZXT-600

### ISSUE THREAD

**Issue by geirsf** [AlCalzone/node-zwave-js#3662]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Any setpoint-command

What do you observe?
- DRIVER Dropping message because it could not be deserialized: The command class Application Status is not implemented (ZW0303), and then 
- CNTRLR [Node 019] Timed out while waiting for a response from the node (ZW0201)

What did you expect to happen?
The setpoint value to be updated. 

  Any set point command to Remotec ZXT-600

### Device information

Manufacturer: Remotec
Model name: ZXT-600
Node ID in your network: 19

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:8.6.1
`zwavejs2mqtt` branch: 5.10.1

### Did you change anything?

no

### Did this work before?

Yes, no problems in earlier versions of zwave-js.

### If yes, where did it work?

zwavejs2mqtt : 5.9.0
zwave-js 8.5.0

### Attach Driver Logfile

[zwavejs_2021-11-04.log](https://github.com/zwave-js/node-zwave-js/files/7476891/zwavejs_2021-11-04.log)

**Comment by AlCalzone** [comment]
`Application Status CC` has never been supported, but I think the default wait time before refreshing the setpoint was longer in 8.5.0. The response looks like the device wants the driver to wait 2 more seconds.

**Comment by geirsf** [comment]
Thanx for you feedback.  Is it possible, since the ZXT-600 is an IR device, that the shorter refreshing time conflicts with  The RF Protection State?

From the Z-Wave Application Command Class Specification (SDS13781 V15):

> The RF Protection State field used to set the RF protection state of the device. In the case where a
> device set into a RF Protection State which instructs the device not to answer to a “normal operation”
> Command, the device MUST return the Application Rejected Request Command (Status = 0) of the
> Application Status Command Class. Refer to the Application Status Command Class.
>

**Comment by AlCalzone** [comment]
Protection CC is something different. Also, the device sends a "busy, wait 2 seconds" command, not request rejected.

**Comment by AlCalzone** [comment]
I'll just revert the verification delay for thermostats to 5 seconds, that shouldn't hurt.

**Comment by geirsf** [comment]
Ah, great, hopefully it will do the trick.
