### ISSUE TITLE
Add conditional items

### ISSUE THREAD

**Issue by blhoward2** [AlCalzone/node-zwave-js#3672]
Make these conditional

- [ ] device label
- [ ] device description
- [ ] compat flags
- [ ] comments

like parameters, to address minor device model variations.

**Comment by AlCalzone** [comment]
We need to think about how to display this in the config browser. These things would become conditional, but I don't think it makes sense to put the condition below them in the browser:
![image](https://user-images.githubusercontent.com/17641229/164493344-1249e4e9-2551-48cd-9411-77211ff78893.png)
![image](https://user-images.githubusercontent.com/17641229/164493757-20d09af1-6035-4d17-8611-8c7605485bae.png)

The comments/warnings might work, but the label definitely doesn't.

---

Maybe we'd need to extend the variants in the nav bar to more things than just the firmware?
![image](https://user-images.githubusercontent.com/17641229/164494811-3bd6be24-ddd8-4254-8a9a-e5d65b9da4b7.png)
