### ISSUE TITLE
Typo in Sunricher SR-ZV9001T4-DIM config file?  (Manufacturer says ProductID 0x0300 config DB says 0x0003)

### ISSUE THREAD

**Issue by davidbbs** [AlCalzone/node-zwave-js#3676]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Including a SR-ZV9001T4-DIM-EU device

What do you observe?
No config options available via Home Assistant.

What did you expect to happen?
Expected to be able to set the association groups

The ZwaveJS DB (https://devices.zwave-js.io/?jumpTo=0x0330:0x0003:0xa10d:0.0) says the product identifier is 0x0003.

But the manufacturer PDF (https://www.sunricher.com/media/resources/manual/Z-Wave%20Wall%20Controller%20SR-ZV9001T4-DIM-EU.pdf) the product identifier is 0x0300.

I think there may be a typo between 0x0003 (wrong, but in the DB) and 0x0300 (right, from the manufacturer).

### Device information

Manufacturer: Sunricher
Model name: SR-ZV9001T4-DIM-EU
Node ID in your network: 46

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 8.7.5

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[zwave_js_dump.json.zip](https://github.com/zwave-js/node-zwave-js/files/7492067/zwave_js_dump.json.zip)

**Comment by AlCalzone** [comment]
The [Z-Wave alliance](https://products.z-wavealliance.org/products/2704) knows it under the existing fingerprint, so yours seems to be an additional one.

@zwave-js-bot add fingerprint 0x0300:0xa10d to 0x0330:0x0003:0xa10d:0.0
