### ISSUE TITLE
Incorrect parameter range for HomeSeer Floodlight Sensor HS-FLS100+

### ISSUE THREAD

**Issue by COCottonwood** [AlCalzone/node-zwave-js#3701]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Unable to input parameter value of zero due to incorrect range in homeseer_template.json file.  Current parameter min to max is 10 to 900, but actual parameter min-max is 0 to 255.  

For HomeSeer HS-FLS100+, Lux_Trigger_Threshold, allowed values are 0, 30-200, 255. Value 0 will NOT activate floodlight. Value 30 represents 10 lux, Value 200 represents 900 lux. Value 255 will activate floodlight regardless of ambient light level

What do you observe?
![Zwave JS HomeSeer HS-FLS100+ parameter options](https://user-images.githubusercontent.com/94188816/141510515-453abf2e-8882-4564-b60b-b871c68ef1be.jpg)

What did you expect to happen?

Per the manual (located at - https://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/2947/HS-FLS100-user-manual2b-A501112779R.pdf )

![HomeSeer HS-FLS100+ Manual](https://user-images.githubusercontent.com/94188816/141510590-54c9e2e7-e81b-41d9-a9ab-99f2fae33d22.jpg)

Parameter file needs to be updated as follows:

	"lux_trigger_threshold": {
		"label": "Light Level Threshold",
		"description": "Allowed values are 0, 30-200, 255. Value 0 will NOT activate floodlight. Value 30 represents 10 lux, Value 200 represents 900 lux. Value 255 will activate floodlight regardless of light level",
		"valueSize": 2,
		"minValue": 0,
		"maxValue": 255,
		"defaultValue": 50,
		"unsigned": true
	},

  2. Click on '...'
  3. Scroll down to '...'

### Device information

Manufacturer: HomeSeer
Model name: HS-FLS100+
Node ID in your network: 

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:  
`zwavejs2mqtt` branch:

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

No Log file needed

**Comment by AlCalzone** [comment]
The same template is shared by the [HS-FLS100-G2](https://devices.zwave-js.io/?jumpTo=0x000c:0x0201:0x000c:0.0) which actually uses the range stated there. We'll rather need a second template with the 0..255 range.

**Comment by COCottonwood** [comment]
Thank you for looking at this... I figured that the template was mis-applied.  Is there any more information that you need from me?

**Comment by AlCalzone** [comment]
No but if you like to help, providing a PR with the changes will speed things up

**Comment by COCottonwood** [comment]
So... I'm not a programmer, I'm a Systems engineer (EE degree).  I thought this was a "PR".  I listed the code changes above... (but not sure if that is the correct format to allow the non-contiguous range of 0, 30-200, 255).

**Comment by AlCalzone** [comment]
No, this is an issue. A PR ([Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#about-pull-requests)) means making the changes in your copy of the repo and providing them so they can be merged.

We also have some [documentation](https://zwave-js.github.io/node-zwave-js/#/config-files/contributing-files) on contributing device file changes and predefined environments to make this easier for you.

If this is out of your league, let me know.

**Comment by COCottonwood** [comment]
Please go ahead and fix it correctly… I know the technical info, but may not format it right.

Robert Apodaca

**Comment by COCottonwood** [comment]
Just updated to 2022.2.0 and the Integrations show my device changed from HS-FLS100+ to a HS-FLS100-G2 which is incorrect.  The Z-Wave JS Config DB still needs to be updated as described in the bug report above.

**Comment by vinmar1** [comment]
FYI - Updated to 2022.2.0 mine still shows as HS-FLS100+ but still cannot set correct parameters

**Comment by blhoward2** [comment]
You have to reinterview the device to pickup a new device file.

**Comment by COCottonwood** [comment]
Thanks.  I did re-interview, and then went to configure but still can't put in "0" for parameter 2.  Parameter 2 also still shows up as "LUX" units, and it should be unit-less values of 0, 30-200, 255.  It did change back to HS-FLS100+ though.

**Comment by COCottonwood** [comment]
Currently on CORE 2022.2.1; SUPERVISOR 2022.01.1; HOME ASSISTANT OS 7.2

**Comment by COCottonwood** [comment]
![image](https://user-images.githubusercontent.com/94188816/152565879-c6dc4390-8970-4385-8531-1b763c8f4d76.png)

**Comment by vinmar1** [comment]
I'm on Frontend version: 20220203.0 ; core-2022.2.2 ; OS 7.2 (latest updates)

Did a re-interview successfully with the same results as above...

**Comment by blhoward2** [comment]
Yeah, the core versions are irrelevant. You need to wait for the addon to pickup the right zwavejs version, then update it, then reinterview.

**Comment by vinmar1** [comment]
Got ya... makes perfect sense should have realized that, Thanks!!

**Comment by COCottonwood** [comment]
@blhoward2 - Thanks!  Does that happen automatically or can I do re-boot or re-start of something to force it?

**Comment by blhoward2** [comment]
I don’t know as none of us run Supervised. I believe that you have to manually check for updates somehow in the Supervisor. Addon releases happen apart from core releases though, so it may have been out a while ago or not out yet. It’s just when they get around to updating. I don’t believe any updates are automatically applied, ever.

**Comment by vinmar1** [comment]
If you go to the Supervisor screen, then go to the “Add-on Store” tab, on the top right there are 3 dots. Click those, and in the menu that opens, click “Check For Updates” that will trigger an update of all addon repositories but there are none yet.

**Comment by COCottonwood** [comment]
Thanks... just checked the ADD-ON STORE for my version of Z-Wave JS (0.1.52) and it is pointing to 8.10.2 and this fix isn't until database 8.11.2 

Z-Wave JS
Current version: 0.1.52
Bump Z-Wave JS to 8.10.2

**Comment by vinmar1** [comment]
Just an FYI and a BIG THANKS! I upgraded today and got the new database re-interviewed and re-started all is wonderful! Just want to thank you guys for a great product and the support!!

**Comment by devWaves** [comment]
Is this still working for everyone? I am unable to set any parameters on my HS-FLS100+. They always revert to default . I have no issues with setting params on other devices

I am on the latest HA and latest zwave js ui. Running on an RPi 4

![image](https://user-images.githubusercontent.com/79881052/231832427-35aebf47-4890-4070-a14a-b18e736d4245.png)

[HS-FLS100-zwavejs.log](https://github.com/zwave-js/node-zwave-js/files/11224732/HS-FLS100-zwavejs.log)


It was suggested on HA forums that the zwave-js device configuration would need to be updated to disable "Supervision with Configuration CC" since other Homeseer devices also require this

https://github.com/zwave-js/node-zwave-js/blob/13c509216bd653abd74d43a6bcd3498367bba20f/packages/config/config/devices/0x000c/hs-wd200.json#L130-L140

I tried to create my own device config and put in store/config with the changes, but it would never load the file. I can create a PR to get the device config updated if that is needed

Thanks

**Comment by AlCalzone** [comment]
@devWaves that might be the case. I only have the FLS100-G2 variant and there Supervision seems fixed.

> I tried to create my own device config and put in store/config with the changes, but it would never load the file.

Did you re-interview? You also have to put the referenced templates in a folder `templates`:
- [this](https://raw.githubusercontent.com/zwave-js/node-zwave-js/master/packages/config/config/devices/0x000c/templates/homeseer_template.json)
- [and this](https://raw.githubusercontent.com/zwave-js/node-zwave-js/master/packages/config/config/devices/templates/master_template.json)

**Comment by devWaves** [comment]
@AlCalzone thanks! I was missing the templates folder and I was able to add the custom device config now. I didn't see that mentioned here https://zwave-js.github.io/zwave-js-ui/#/device-support/custom-device-files

Adding the code to disable "Supervision with Configuration CC" as mentioned above works and I am now able to set the parameters without errors

I will open a PR to change the device config. Thanks again

PR created: https://github.com/zwave-js/node-zwave-js/pull/5663
