### ISSUE TITLE
GE/Jasco Fan 

### ISSUE THREAD

**Issue by TiddlyWiddly** [AlCalzone/node-zwave-js#3705]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

Turning on the fan and turning off the fan via toggle in the HA UI

What do you observe?
When turning on: the toggle immediately turns itself off, then a second or two later turns itself back on.
When turning off: the toggle turns itself off and then turns itself back on. then I need to toggle off again (two press to toggle off)

What did you expect to happen?

I expected the toggles to behave normally.

Add a toggle switch to control the GE Fan switch and turn it on or off.

### Device information

Manufacturer: GE/Jasco
Model name: Model #55258 / ZW4002
Node ID in your network: 9

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 0.1.47
`node-zwave-js` branch:
`zwavejs2mqtt` branch:

Home Assistant Add-on

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

I'm not sure how to get this log file when using haos and ZWave-JS as an add-on, but I found someone else has this exact behavior here: https://community.home-assistant.io/t/ge-enbrighten-fan-controller-incorrectly-reporting-on-off-state/334036

I am happy to pull the logs, I just don't know how. The logging tabs in the configuration logs and supervisor logs don't seem to be updating while i'm activating/deactivating the toggles.

It appears that the device as a model does not behave correctly. While ZWave-JS is handling the reporting of the device correctly, I think that this incorrect behavior should be "coded around" in order for the device to behave more appropriately.

**Comment by AlCalzone** [comment]
The log in the thread you linked indicates that the device reports on its own after the SET, but does so before it has reached the final value. This cancels the verification GET that zwave-js does after a few seconds. The fix would be the same as in https://github.com/zwave-js/node-zwave-js/issues/3523, so I'm going to close this one as a duplicate.
