### ISSUE TITLE
HeatIt devises to DB

### ISSUE THREAD

**Issue by Tom-ahawk** [AlCalzone/node-zwave-js#3767]
Please add devises from HeatIt - https://heatit.com
* Rotary Dimmer
* Temperature sensor
* Thermostat
* Leakage stopper

**Product Sheets*
[HEATIT Leakage Stopper.pdf](https://github.com/zwave-js/node-zwave-js/files/7574497/HEATIT.Leakage.Stopper.pdf)
[Heatit Z-Dim Rotary Dimmer.pdf](https://github.com/zwave-js/node-zwave-js/files/7574498/Heatit.Z-Dim.Rotary.Dimmer.pdf)
[Heatit Z-Temp2.pdf](https://github.com/zwave-js/node-zwave-js/files/7574499/Heatit.Z-Temp2.pdf)
[HeatIt Z-TRM3 Termostat Z-Wave.pdf](https://github.com/zwave-js/node-zwave-js/files/7574500/HeatIt.Z-TRM3.Termostat.Z-Wave.pdf)

**Comment by marcus-j-davies** [comment]
Sorry - but this is to vague of information.
we need more then just device manuals (we also need device ID's product ID's etc etc)


Pease split your requests, and for each device, please use the Missing Configuration template
It's there so we capture everything we need (and please follow instructions)

![image](https://user-images.githubusercontent.com/55892693/142732855-011e6645-2ce7-4f74-a8b9-4d8d9cc49473.png)
