### ISSUE TITLE
Missing checks

### ISSUE THREAD

**Issue by blhoward2** [AlCalzone/node-zwave-js#3775]
During the fw split deprecation works, I observed some checks we're missing:

1. Device file fw min was higher than its max
2. A duplicate definition existed because the device was included in one file with a range 0.0-255.255, and another where the range was less than full (e.g. 3.0-5.0).

**Comment by AlCalzone** [comment]
2. is fixed by https://github.com/zwave-js/node-zwave-js/pull/5619
