### ISSUE TITLE
Not compatible with ZLINK products

### ISSUE THREAD

**Issue by carbonappsx** [AlCalzone/node-zwave-js#3783]
Can you add this to the database, could not get it to recognize my switches, just registered them as nodes. 

https://zlinkproducts.com/product/in-wall-dimmer/

**Comment by AlCalzone** [comment]
Please choose the appropriate issue template and fill in the requested information:
![grafik](https://user-images.githubusercontent.com/17641229/143030755-a73170a8-fbc8-4bfa-8637-02d6e52f30ce.png)
