### ISSUE TITLE
Missing device configuration: Aeotec MultiSensor 7 ZWA024-C

### ISSUE THREAD

**Issue by mrm47s** [AlCalzone/node-zwave-js#3802]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Aeotec ZWA024-C

### Manufacturer ID

0x0371

### Product Type

0x0002

### Product ID

0x0018

### Firmware Version

1.1

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4061

### Do you have a manual?

[ES - MultiSensor 7(1).pdf](https://github.com/zwave-js/node-zwave-js/files/7617749/ES.-.MultiSensor.7.1.pdf)

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4061 from zwa

**Comment by henrikrox** [comment]
@AlCalzone hello my friend, do you have everything you need regarding ZWA024/multisensor 7? I bought 3 today and using them as powered, they can be added to zwavejs, but it has a general nodexx status. And i cant edit the configuration. Thank you, and have a nice christmas :)

**Comment by AlCalzone** [comment]
Its being worked on: https://github.com/zwave-js/node-zwave-js/pull/3855

In the meantime you should be able to change the config parameters in zwavejs2mqtt by entering the param no., value size and value in the respective field.

**Comment by henrikrox** [comment]
> Its being worked on: #3855
> 
> In the meantime you should be able to change the config parameters in zwavejs2mqtt by entering the param no., value size and value in the respective field.

nice, i tried using zwavejs2mqtt once along side zwavejs but i was confused on how they worked together, guess i have to try again.  thank you for your fast repsonse.
