### ISSUE TITLE
OBSERVATION: Not sure if this is zwave-js, zwavejs2mqtt, or HA, or an issue with a Device Config file

### ISSUE THREAD

**Issue by GrizzlyAK** [AlCalzone/node-zwave-js#3847]
I don't know if this is a bug, oversight, deficiency in the Device Config file, HA, zw2m, or HA, but did want to point it out just in case. I'm using zw2m v5.12.0, zwjs v8.7.6, with a locally installed Config file (the one currently in Master) for the ZEN15 (including templates).
FYI, @blhoward2 

I updated the FW on 5 Zooz ZEN15s from 1.4 to 1.6 using the zw2m CP OTA update (which worked perfectly, btw!). This update added the two new Config Params (#33 & #34), shown below (from the Config file - zen15.json:

```	
{
	"#": "33",
	"$if": "firmwareVersion >= 1.6",
	"label": "Auto-On Timer",
	"valueSize": 1,
	"unit": "minutes",
	"minValue": 0,
	"maxValue": 99,
	"defaultValue": 0,
	"unsigned": true,
	"options": [
		{
			"label": "Disable",
			"value": 0
		}
	]
},
{
	"#": "34",
	"$if": "firmwareVersion >= 1.6",
	"label": "Auto-Off Timer",
	"valueSize": 1,
	"unit": "minutes",
	"minValue": 0,
	"maxValue": 99,
	"defaultValue": 0,
	"unsigned": true,
	"options": [
		{
			"label": "Disable",
			"value": 0
		}
	]
},

```
Upon successfully completing the FW update and restarting the device (re-interview) (all automatic), in each case the new Parameters appeared in Configuration with the custom value 255, NOT the Default. When clicked on, Default was the other option in the drop-down, and could be set, but it is curious that the default was not chosen upon restart. All other existing parameters were as they were prior to the update. See image below.
![Capture4](https://user-images.githubusercontent.com/4411963/144729364-9a55f2c0-ee2e-4ad8-8ad7-07fc1a5d98ae.JPG)

**Comment by blhoward2** [comment]
Eh, it's not much of anything. We don't set the default ever automatically as it would clobber things. It's just for the UIs to display the default if they like. We just display what the manufacturer says the default is supposed to be. If it started at 255 then that's what the manufacturer had it set to and we fetched the value. 

What's more curious is why they're setting it to a value not in the range defined. 

Do you have a log of the device reporting 255 for the Get?

**Comment by GrizzlyAK** [comment]
I see, that makes sense.

> What's more curious is why they're setting it to a value not in the range defined.

right

**Comment by GrizzlyAK** [comment]
let me check.

**Comment by GrizzlyAK** [comment]
Yeah, the device reported 255. Down toward the bottom is where I changed it.

![image](https://user-images.githubusercontent.com/4411963/144729822-5a551246-4f35-4cb6-a3ec-e741c1533b5d.png)

**Comment by AlCalzone** [comment]
I wonder if 255 is just the default "empty" memory and they didn't set the value during upgrade on the device

**Comment by blhoward2** [comment]
I let Zooz know.

**Comment by blhoward2** [comment]
Zooz said they will fix this in new fw, likely in January.
