### ISSUE TITLE
[Home Assistant] Cannot add devices that were previously removed

### ISSUE THREAD

**Issue by giovi321** [AlCalzone/node-zwave-js#3875]
[zwavejs2mqtt-store(1).zip](https://github.com/zwave-js/zwavejs2mqtt/files/7676218/zwavejs2mqtt-store.1.zip)

### Version

Build/Run method:
[ ] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[x] Pkg

Zwavejs2Mqtt version: zwavejs2mqtt: 5.12.0.060278d
Z-Wave JS version: zwave-js: 8.7.6

### Describe the bug

After excluding a node (TVR valve Eutronics Spirit) I am unable to include them back. Same for a Danfoss LC13.
EDIT: the Eutronics Spirit was marked as dead after I replaces the batteries therefore I removed it.

**Comment by AlCalzone** [comment]
You'll have to check the manual on how to factory reset the devices. Chances are they still think they are included and therefore won't send the necessary commands to get included.
