### ISSUE TITLE
Missing device configuration: <enter manufacturer and device name>

### ISSUE THREAD

**Issue by TeckPete** [AlCalzone/node-zwave-js#3887]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Yale yrd256

### Manufacturer ID

0x0129

### Product Type

0x8002

### Product ID

0xA570

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/3882?selectedFrequencyId=2

### Do you have a manual?

![80B20A9E-51E8-4642-BE43-D1792DE94219](https://user-images.githubusercontent.com/35778227/145702819-c6180fcb-17e6-4caa-a412-4717c3a76751.jpeg)
![D7348438-84FF-412D-9F38-F17A6FFAFC49](https://user-images.githubusercontent.com/35778227/145702823-73ba30bb-4b71-490e-8bf5-12cef50e363c.jpeg)
![C4441CCD-BBDF-4FAC-99F8-CEF8874A1881](https://user-images.githubusercontent.com/35778227/145702824-65f693fb-58f5-4894-b793-27b302d6f47d.jpeg)

**Comment by marcus-j-davies** [comment]
The Identifier you have provided is already supported.
https://devices.zwave-js.io/?jumpTo=0x0129:0x8002:0xa570:0.0 - (YRD256-ZW3 )

However, the one in your screenshot: 0x0131:0x0003:0x1111 is not found - which is some Zipato device?

What ID's are we looking at here in your report - My head hurts!

Please could you correct where necessary, including the title
> Missing device configuration: \<enter manufacturer and device name\>

**Comment by blhoward2** [comment]
Please post the actual dump, not a screenshot. We need to be able to scroll through it. What node is at issue?

**Comment by TeckPete** [comment]
When I try to upload the zwave_jsdump.json I get an error saying the file type is not supported. So how do I include it?

**Comment by blhoward2** [comment]
Just zip it and upload the zip file.

**Comment by TeckPete** [comment]
[zwave_js_dump.zip](https://github.com/zwave-js/node-zwave-js/files/7708699/zwave_js_dump.zip)

**Comment by AlCalzone** [comment]
Node 14 in your dump has almost no information and the bit that's there seems like zwave-js wasn't able to determine which security classes it uses. It is also missing the identification part, which is probably why its not being identified properly. To better diagnose this, please do the following:

1. Make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` or `silly`
2. Exclude the node, and re-include it. Leave the log active
3. Wait until it is interviewed completely
4. Send me the logfile to the e-mail in my profile, referencing this issue

**Comment by TeckPete** [comment]
So I did it and during inclusion this time it pulled the correct attribute's not sure why I tried this 3 times before but it's working great not thanks anyway.
