### ISSUE TITLE
Missing device configuration: EVA LOGIK ZW39 Z-Wave Smart Plug (Dimmer)

### ISSUE THREAD

**Issue by vgehts** [AlCalzone/node-zwave-js#3902]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

EVA LOGIK ZW39 Z-Wave Smart Plug (Dimmer)

### Manufacturer ID

0x0312

### Product Type

0xc000

### Product ID

0xc002

### Firmware Version

2.2 

### Is the device listed on the Z-Wave Alliance website?

Older version: https://products.z-wavealliance.org/products/2358

### Do you have a manual?

[ZW39001.pdf](https://github.com/zwave-js/node-zwave-js/files/7716711/ZW39001.pdf)

**Comment by AlCalzone** [comment]
@zwave-js-bot config help wanted

**Comment by blhoward2** [comment]
@zwave-js-bot import config 2358 from zwa

**Comment by blhoward2** [comment]
We weren't actually missing this file, though it was misdescribed. I've corrected that in the PR.
