### ISSUE TITLE
Missing device configuration: Fibaro FGS-214

### ISSUE THREAD

**Issue by arakasi55** [AlCalzone/node-zwave-js#3931]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Fibaro FGS-214

### Manufacturer ID

0x010f

### Product Type

0x0404

### Product ID

0x3000

### Firmware Version

5.0

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/3949?selectedFrequencyId=-1

### Do you have a manual?

https://manuals.fibaro.com/content/manuals/en/FGS-2x4/FGS-2x4-T-EN-1.0.pdf

**Comment by AlCalzone** [comment]
@zwave-js-bot add fingerprint `0x0404:0x3000` to `0x010f:0x0404:0x1000:5.0`

**Comment by AlCalzone** [comment]
@zwave-js-bot add fingerprint `0x0404:0x3000` to `0x010f:0x0404:0x1000:5.0`
