### ISSUE TITLE
From zwave-js/zwavejs2mqtt - Looses connection to controller....

### ISSUE THREAD

**Issue by doug62** [AlCalzone/node-zwave-js#3941]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

See: https://github.com/zwave-js/zwavejs2mqtt/issues/2081

zwave-js: 1) Looses the ability to update nodes (after < 5 minutes w 150 devices) ; 2) Ability to read from nodes still functions; 3) Neighbors and devices slowly disappear

zwavejs2mqtt: 6.1.1
zwave-js: 8.9.0-beta.1
home id: 3741021741
home hex: 0xdefb762d

### Device information

Manufacturer:  Aeotec might be a common factor
Model name: All models
Node ID in your network: All nodes

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Prior version may have worked.

### Attach Driver Logfile

See other thread - has logs and suspicions.

**Comment by candrea77** [comment]
zwave-js: 8.9.0-beta.1 seems to be broken. 
Please, try update to zwave-js: 8.9.0-beta.3 and test it again.

Use docker image (master) to update to zwave-js: 8.9.0-beta.3
