### ISSUE TITLE
Missing device configuration: <enter manufacturer and device name>

### ISSUE THREAD

**Issue by arakasi55** [AlCalzone/node-zwave-js#3960]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

AEON Labs Nano Shutter 3

### Manufacturer ID

0x0086

### Product Type

0x0203

### Product ID

0x008d

### Firmware Version

2.3

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/2907?selectedFrequencyId=4

### Do you have a manual?

https://help.aeotec.com/support/solutions/articles/6000198818-nano-shutter-technical-specifications-

**Comment by AlCalzone** [comment]
@zwave-js-bot add fingerprint `0x0203:0x008d` to `0x0086:0x0003:0x008d`
