### ISSUE TITLE
Missing device configuration: Zooz ZSE43

### ISSUE THREAD

**Issue by yieldhog** [AlCalzone/node-zwave-js#3971]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Zooz ZSE43

### Manufacturer ID

0x027a

### Product Type

0x7000

### Product ID

0x7000

### Firmware Version

1.10

### Is the device listed on the Z-Wave Alliance website?

Not yet

### Do you have a manual?

[zooz-700-series-tilt-shock-xs-sensor-zse43-manual.pdf](https://github.com/zwave-js/node-zwave-js/files/7781816/zooz-700-series-tilt-shock-xs-sensor-zse43-manual.pdf)

**Comment by AlCalzone** [comment]
I've converted the IDs to hex.

> Product Type 0x7000
> Product ID 0x7000

seems a bit suspicous. Are you sure? Where is this info from?

**Comment by yieldhog** [comment]
> 

Hi, coming from zwavejs2mqtt -- sorry if incorrect, first time I'm adding a device:

```
Product: 0x7000
Product code: Unknown product 0xe003
Product type: 28672 (from "Manufacturer Specific" menu)
Manufacturer: Showing correct as Zooz

Device ID: 634-57347-28672 (0x027a-0x7000-0xe003)
```

**Comment by AlCalzone** [comment]
That looks better 👍🏻
