### ISSUE TITLE
Philio PAN06 newly included device Relay 1 status not updated. 

### ISSUE THREAD

**Issue by gratjetost** [AlCalzone/node-zwave-js#4078]
Hello,

I'm having an issue with one of my Philio PAN06 double relay switch.
Last year I made an issue topic  #3541 that contained and fixed the problem when I switched my wall switches the on/off status was not send. adding parameter 11 fixed this issue.
I have 3 PAN06 modules. 
2 of them are never re-included since the issue from topic  #3541. Only added parameter 11 with value 2.  These 2 send the status from relay 1 and relay 2 correctly when I switch my switches on the wall.
But the PAN06 module that I used to track the issue from  #3541 is a couple of times removed and re-included.
This module is now only sending the on/off status from relay 2 correctly. Relay 1 i not updating at all when I switch my wall switch.

clarification of the attached files.
the config files are taken from the z-wave-JS control panel from the tab Debug info.
node 47 is never re-included. only manual added parameter 11 with value 2. (100% working)
node 37 is never re-included. after fixing topic  #3541 only re-interviewed the device. (100% working)
node 53/54 is removed and re-included several times after topic  #3541. (relay 1 is not sending status, relay 2 is sending status)

All nodes have the same configrations, and groups applied.
Only difference I see between node 53 and the other ones is one configuration parameter 1 where the text is swapped from value 1 and value 3. 
Changing these values doesn't make any difference. Relay 2 is still not reporting its status.

It looks like the issue is introduced with the new configuration from topic #3541 Because the old PAN06 modules that are not reincluded still work with manual set parameter 11 to 2.

[node_47_HK_mid_oldest_config_working.txt](https://github.com/zwave-js/node-zwave-js/files/7862623/node_47_HK_mid_oldest_config_working.txt)
[zwavejs_2022-01-10_node_47_working2.log](https://github.com/zwave-js/node-zwave-js/files/7862624/zwavejs_2022-01-10_node_47_working2.log)
[zwavejs_2022-01-10_node_47_working1.log](https://github.com/zwave-js/node-zwave-js/files/7862625/zwavejs_2022-01-10_node_47_working1.log)
[zwavejs_2022-01-10_not_working_switch_node-53-relay1.log](https://github.com/zwave-js/node-zwave-js/files/7862626/zwavejs_2022-01-10_not_working_switch_node-53-relay1.log)
[zwavejs_2022-01-10_working_switch_node-53-relay2.log](https://github.com/zwave-js/node-zwave-js/files/7862627/zwavejs_2022-01-10_working_switch_node-53-relay2.log)
[zwavejs_2022-01-12_not_working_PAN06_node_53.log](https://github.com/zwave-js/node-zwave-js/files/7862628/zwavejs_2022-01-12_not_working_PAN06_node_53.log)
[zwavejs_2022-01-12_working_PAN06_node_34.log](https://github.com/zwave-js/node-zwave-js/files/7862629/zwavejs_2022-01-12_working_PAN06_node_34.log)
[node_53_HK_serre_new_config_relay1_not_working_relay2_working.txt](https://github.com/zwave-js/node-zwave-js/files/7862630/node_53_HK_serre_new_config_relay1_not_working_relay2_working.txt)
[node_34_carport_new_config_working_relay1_and_2.txt](https://github.com/zwave-js/node-zwave-js/files/7862631/node_34_carport_new_config_working_relay1_and_2.txt)

**Comment by AlCalzone** [comment]
Please check which associations are assigned on each node - I can't see that info in the files you posted. This seems like the non-working one is missing an assocation that exists on the others.

**Comment by gratjetost** [comment]
@AlCalzone I checked the group associations. They are for all 3 modules the same.
See screenshots. node 54 is the non working PAN54, node 37 is the working PAN06.
For the node 54 I already tried removing and adding the groups again.
Tried all combinations. non work. If I remove all associations no input from the wall switches are shown.

![node-54-group-associations_non_working](https://user-images.githubusercontent.com/11716629/149391634-d46ecac2-0a92-454f-94d3-62166da4f42e.png)
![node-34-group-associations_working](https://user-images.githubusercontent.com/11716629/149391637-e95bc361-4c36-4744-af5b-61ef8a52dd92.png)


.

**Comment by AlCalzone** [comment]
And the configuration parameters are also all the same? Then I have no clue why the one isn't working...
Maybe it needs a factory reset after exclusion. Or maybe change the config parameters controlling the reporting to a different value and back.

**Comment by gratjetost** [comment]
Yes configurations are also the same. only with the text from parameter 1 is swapped between the working and not working PAN06.

not working node 54:
![node_54_config_not_working](https://user-images.githubusercontent.com/11716629/149392813-575fc046-5078-4954-be81-fe8eb4f80902.png)

working node 34: 
![node_34_config_working](https://user-images.githubusercontent.com/11716629/149392817-02aa9463-4c2e-44d1-a4ee-a8db1a47d381.png)

But swapping this parameter is also not changing anything. Already tried a factory reset for the non working PAN06 without succes,

**Comment by gratjetost** [comment]
When I check the history of the config file I do see a lot of changes. 

https://github.com/zwave-js/node-zwave-js/commit/5ebe3a2aa4ecb9aac6ece170f7adfde32b0247a4#diff-5d825834fe1b97b1c1687bfcab1f5142de9db24f951119eb6d55b8c945b87bf4

maybe something went wrong there? For the working PAN06 modules I added the associations manually. (That didn't work in october 2021 when we were busy with ticket #3541 

When I removed and re-assigned my non working PAN06 the associations were filled in automatically.

All my PAN06 modules are FW version 1.0.

edit: on 5 december. 2 PAN06 config files were combined to one. before that all my devices worked fine. I think something went wrong there. 
packages/config/config/devices/0x013c/pan06_0.0-1.7.json 
this config file was made after our ticket #3541 and that worked correctly.

**Comment by AlCalzone** [comment]
There is no difference between these:
> For the working PAN06 modules I added the associations manually
> my non working PAN06 the associations were filled in automatically

and regarding
> on 5 december. 2 PAN06 config files were combined to one. before that all my devices worked fine. I think something went wrong there.

our device files per se have no influence on how a device behaves. Only how the driver interprets the messages by the device and which associations are set up.

---

Do you have a [test config file somewhere](https://zwave-js.github.io/zwavejs2mqtt/#/device-support/custom-device-files) that might get picked up?
I'm a bit confused that your working devices have the "Selected endpoint" parameter options in the same order as our current file:
https://github.com/zwave-js/node-zwave-js/blob/bce3b25236bf0fb3db8f00d79b63d75438844826/packages/config/config/devices/0x013c/pan06_0.0-1.7.json#L51-L63

but the non-working one has the opposite order (and a different value for that param). If the non-working one gets included with the linked file in place, it should have the same options as the other ones.
Also if value 3 is actually set, according to the current device file this means it only has reporting for "Relay 2" enabled, which is exactly what's happening, right?

**Comment by gratjetost** [comment]
I've been playing around with parameter 1 for the non working device, thats why it was still on value 3. 
but setting it to 1, 2 or 3, doesn't make any difference.
I don't have a custom config file. 
Didn't even know that I could do that. 
I'm running HASOS on my raspberry pi 4. 
this is my store folder:
![store_file](https://user-images.githubusercontent.com/11716629/149401243-dcba0aa0-e6bc-4baf-9b63-eacefbf3f966.png)

how can I add a custom config? maybe I can try to get that "old" config file to verify if that is a working config file.

**Comment by AlCalzone** [comment]
> how can I add a custom config?

I linked you above. I don't expect any change though. We **only** set associations automatically and these are already the same for all devices.

Just for my sanity, can you please:
- set the configuration parameters exactly like for the other two devices
- make sure the associations are the same
- toggle both relays and post a driver log of that?

**Comment by gratjetost** [comment]
Yes, but I don't have a config folder. and If I open a SSH connection I don't know where it should be located.

toggle relays by the wall switches? (physical buttons)

**Comment by gratjetost** [comment]
Log file from node 54:
first I turned off and on the "working" relay for a couple of times. 
keep in mind that "source 1" is the source from that parameter 1.
after that I turned off and on the non working relay a couple of times.

![2022-01-13 21_29_36-Configuration - Home Assistant](https://user-images.githubusercontent.com/11716629/149404667-d0d9b53c-7c08-46e2-86bb-801153a1d285.png)

If I'm correct source 1 are the top 2 switches.  that source one is ilnked to parameter 1 settings.
source 2= (2) (not working relay)
source 3= (3) (working relay)

ps. switching (2) in lovelace works fine. light turns on and off.

[zwavejs_2022-01-13.log](https://github.com/zwave-js/node-zwave-js/files/7865802/zwavejs_2022-01-13.log)

**Comment by gratjetost** [comment]
Did some extra checks. First reverted back to core-2021.12.6 and zwave2mqtt 0.32.1.
It really looks like an issue with the association of relay 1.  But cannot figure out what goes wrong.
When I press the refresh button in the configuration panel in the binary switch list. THEN the value changes....
I really want to try the old config file. But I still don't know where to put it on the SD card. I  just cannot find that store/config folder anywhere.

**Comment by AlCalzone** [comment]
> When I press the refresh button in the configuration panel in the binary switch list. THEN the value changes....

That's different because the driver actively asks for the value then.

> I really want to try the old config file. But I still don't know where to put it on the SD card. I just cannot find that store/config folder anywhere.

Just create it. Quote from the docs I linked you:
> if you need to test a custom config device file, you may do so **by creating a folder inside your store folder named config** and placing the file inside that folder

Its not going to change what the device reports though. The others send something from endpoint 2, this one doesn't.

**Comment by gratjetost** [comment]
@AlCalzone after a long talk on discord we concluded the device is broken. 
@blhoward2 also thanks for the thinking. 
Only thing to fix is the value description of parameter 1:

Value Description parameter 1
1  Relay 1 and Relay 2 (Default)
2  Relay 1
3  Relay 2

thanks for all the help.

**Comment by gratjetost** [comment]
issue solved. No clue what happened. did a clear associations in the configuration. re-added the associations in the groups tab. and now both relays send there state.
