### ISSUE TITLE
Track which device file was the basis of an interview and flag devices with outdated interviews

### ISSUE THREAD

**Issue by blhoward2** [AlCalzone/node-zwave-js#4079]
Hash the device file used during a device interview and compare the hash value of current device files at startup. Also export a function so that UIs can call this function after device files are pulled (zjs2mqtt). Flag devices with outdated interviews so that UIs can display a reinterview flag or prompt on the device. 

Per prior conversations, we don't want to automatically reinterview because a device could be a battery device or there could be an issue, and all information about a device is lost after triggering a reinterview.

**Comment by kpine** [comment]
> and all information about a device is lost after triggering a reinterview.

That's been [fixed](https://github.com/zwave-js/node-zwave-js/issues/3776)?

**Comment by blhoward2** [comment]
Sort of. It's been delayed until it actually starts. There is still a concern if the interview doesn't complete before it goes back to sleep if we were doing this unattended.
