### ISSUE TITLE
Qubino Flush 1d relay - i2 not displaying in home assistant

### ISSUE THREAD

**Issue by plasterer41** [AlCalzone/node-zwave-js#4106]
Trying to use the i2 functionality on qubino flush 1d relay to show when a magnetic contact sensor is open or closed however the i2 entity is not showing up on home assistant despite amending the relevant parameter when configuring the device. Any thoughts?

**Comment by AlCalzone** [comment]
Did you exclude and re-include the device again after changing the configuration, as described in the manual?

**Comment by plasterer41** [comment]
Thanks very much for that. It worked perfectly!!!
