### ISSUE TITLE
Config: Missing «Tampering» sensor on Aeotec ZWA024 Multisensor 6

### ISSUE THREAD

**Issue by jmgiaever** [AlCalzone/node-zwave-js#4129]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What do you observe?

The device reports `Tampering, product remove` sensor, but it's not recognized in the driver.

```
2022-01-19T20:13:16.358Z DRIVER « [Node 196] [REQ] [ApplicationCommand]
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 4
                                    └─[NotificationCCEventSupportedReport]
                                        notification type: Home Security
                                        supported events:
                                        · Motion detection
                                        · Tampering, product moved
```

![screenshot_from_2022-01-19_21-21-40](https://user-images.githubusercontent.com/7188121/151032839-79ec0570-c5f3-49e0-9d80-08382c9190ee.png)

It isn't created after the inclusion either. See attached log. I hit the wall next to it after the inclusion at the device reports «tampering», but nothing is created or shows up anywhere else.

What did you expect to happen?

The sensor to be recognized.

### Device information

Manufacturer: Aeotec
Model name: ZWA024
Node ID in your network: 196

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [X] Other _(please describe)_

### Which branches or versions?

version:
zwavejs2mqtt: 6.4.1.d772a4e
zwave-js: 8.11.2

Snap package

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[zwavejs_current_purged (1).log](https://github.com/zwave-js/node-zwave-js/files/7936025/zwavejs_current_purged.1.log)

**Comment by AlCalzone** [comment]
For anyone stumbling across this:
> Tampering, product moved

is an event (**stateless**), not a value (**stateful**)

but
> Motion detection

is a state of the Motion Sensor Status variable
