### ISSUE TITLE
[question] NVM size is 0 - How is the size determined?

### ISSUE THREAD

**Issue by andyboeh** [AlCalzone/node-zwave-js#4170]
I wanted to move to a new controller and tried to back up NVM. Unfortunately, it doesn't work:

```
2022-01-31 21:52:50.646 INFO ZWAVE: Calling api backupNVMRaw with args: [ [length]: 0 ]
2022-01-31 21:52:50.691 INFO ZWAVE: Unknown NVM size - cannot backup! (ZW0207) backupNVMRaw undefined
```
How is the NVM size determined? 

Additional information: My controller is connected over TCP using ser2net. The controller itself is an embedded module in a SERCOMM NA502.

**Comment by AlCalzone** [comment]
0 is not the NVM size, that's the length of the method argument array.

> Unknown NVM size

is because the response by the stick doesn't match any of the defined NVM sizes. 
Please make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` or `silly`, try the backup again and attach the log here as a file.

**Comment by andyboeh** [comment]
I redacted the home ID; looks like the manufacturer is reported as 0xff
[zwavejs_2022-01-31.log](https://github.com/zwave-js/node-zwave-js/files/7976588/zwavejs_2022-01-31.log)

**Comment by AlCalzone** [comment]
```
2022-01-31T20:52:50.677Z SERIAL « 0x0107012903ffffff2c                                                 (9 bytes)
2022-01-31T20:52:50.678Z DRIVER « [RES] [GetNVMId]
                                    manufacturer: 0xff
                                    memory type:  EEPROM
                                    memory size:  Unknown
```
That's the intersting bit. Z-Wave JS can't know how large the memory is, so it doesn't know how much it can read.
I'm not sure what the correct behavior in this case is and how the device would react to an out-of-bounds read (return nothing? wrap around?). So for safety reasons, I chose not to operate on unknown memory sizes.

**Comment by andyboeh** [comment]
Hm...does Z-Wave JS identify the memory size based on the ID returned by the chip? Is the memory external or on the SoC?

The Z-Wave module is a separate PCB, it looks like this: https://www.digikey.be/en/products/detail/silicon-labs/ZM5304AE-CME3R/4135431

I'm not sure what the smaller IC is. The markings are S8U S78 77, I couldn't find any information on that.

Edit: It's the EEPROM. ON-SEMI 256Kb Serial SPI EEPROM CAT25256.

**Comment by AlCalzone** [comment]
> does Z-Wave JS identify the memory size based on the ID returned by the chip

No, the size information is part of the response (the third `0xff`).
https://github.com/zwave-js/node-zwave-js/blob/3b116f8c95535ef6e561fa862bec9d0ddaf1a3f9/packages/zwave-js/src/lib/serialapi/nvm/GetNVMIdMessages.ts#L23-L37

AFAIK, the `get_NVM_id` command is the only way to get any information about the (external) NVM on 500 series controllers:
![grafik](https://user-images.githubusercontent.com/17641229/151945423-4c4c491c-a938-43ce-82c8-efc8712bec42.png)

**Comment by andyboeh** [comment]
Yeah, looks so - the information is in the NVR flash page, but if there is no way to access that via the serial API, I'm screwed.

**Comment by andyboeh** [comment]
I just found a tool "TestNVM.py" on github that should be able to dump the NVM. They seem to just dump 2Mbit: https://github.com/drzwave/TestNVM/blob/a57c42406c54b24609b3aa5e74d5ebf494f0506f/TestNVM.py#L411

I'll modify it for TCP and see what happens.
