### ISSUE TITLE
ShenZhen Sunricher Technology, Ltd. SR-ZV9101FX-RU

### ISSUE THREAD

**Issue by Inoy-D** [AlCalzone/node-zwave-js#4175]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

ShenZhen Sunricher Technology, Ltd. SR-ZV9101FX-RU

### Manufacturer ID

0x0330

### Product Type

 0x021A

### Product ID

0xD002

### Firmware Version

1.5

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/2759

### Do you have a manual?

https://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/2759/Z-Wave%20LED%20Dimmer%20SR-ZV9101FX-RU%20User%20Manual.pdf

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 2759 from zwa

**Comment by AlCalzone** [comment]
The bot has created a PR but the file only serves as a starter template. It needs to be cleaned up to conform with our style guide, see above.

For anyone who wants to help out:
- fork the repo if you haven't already
- edit branch `import-config-1643837042` in your fork
- create a pull request with your branch `import-config-1643837042` as the source and our branch `import-config-1643837042` as the target

**Comment by Inoy-D** [comment]
Hi, i don’t see  branch import-config-1643837042 in my fork:  https://github.com/Inoy-D/node-zwave-js/branches/all?query=import-config-1643837042

  
>Четверг, 3 февраля 2022, 2:25 +05:00 от AlCalzone ***@***.***>:
> 
> 
>The bot has created a PR but the file only serves as a starter template. It needs to be cleaned up to conform with our style guide, see above.
>For anyone who wants to help out:
>*  fork the repo if you haven't already
>*  edit branch import-config-1643837042 in your fork
>*  create a pull request with your branch import-config-1643837042 as the source and our branch import-config-1643837042 as the target
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <zwave-js/node-zwave-js/issues/4175/1028371746 @ github . com> 
 
 
С уважением, Дмитрий Сулимов.

**Comment by Inoy-D** [comment]
I found a similar device in the configuration database for another country

**Comment by AlCalzone** [comment]
> Hi, i don’t see  branch import-config-1643837042 in my fork

You might have to sync the fork first.
