### ISSUE TITLE
Minimum value of Parameter range for HomeSeer Floodlight Sensor HS-FLS100+ is rejected

### ISSUE THREAD

**Issue by COCottonwood** [AlCalzone/node-zwave-js#4187]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Previous PR#3701 was CLOSED but NOT fixed.  [https://github.com/zwave-js/node-zwave-js/issues/3701](url)

What causes the bug?

Unable to input parameter value of zero.  It is still using MIN of 10 and MAX of 900

For HomeSeer HS-FLS100+, Lux_Trigger_Threshold, allowed values are 0, 30-200, 255. Value 0 will NOT activate floodlight. Value 30 represents 10 lux, Value 200 represents 900 lux. Value 255 will activate floodlight regardless of ambient light level

What do you observe?

Zwave JS HomeSeer HS-FLS100+ parameter options:

![image](https://user-images.githubusercontent.com/94188816/152566846-24437888-6a17-42b6-bbd3-0ee920e0d893.png)

This does NOT match the Z-Wave JS Database

![image](https://user-images.githubusercontent.com/94188816/152567362-d1ec51fb-b504-480a-b5b5-61c72efe7a27.png)

What did you expect to happen?

Per the HomeSeer HS-FLS100+ Manual (located at - https://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/2947/HS-FLS100-user-manual2b-A501112779R.pdf
 
![image](https://user-images.githubusercontent.com/94188816/152567160-3235408c-18f5-4718-b28c-2937641bca25.png)

What did you see? 

![image](https://user-images.githubusercontent.com/94188816/152566107-2c148b5c-0e64-4263-9f4c-ff9e8dd6497d.png)

### Device information

Manufacturer: HomeSeer
Model name: HS-FLS100+
Node ID in your network:

Currently on CORE 2022.2.1; SUPERVISOR 2022.01.1; HOME ASSISTANT OS 7.2

From Z-Wave log from RE-INTERVIEW:

2022-02-05T13:56:24.907Z CNTRLR   [Node 046] Interview stage completed: NodeInfo
2022-02-05T13:56:24.912Z CNTRLR   [Node 046] Interviewing Manufacturer Specific...
2022-02-05T13:56:24.913Z CNTRLR » [Node 046] querying manufacturer information...
2022-02-05T13:56:25.485Z CNTRLR   [Node 046] [+] [Manufacturer Specific] manufacturerId: 12         [Endpoint 0]
2022-02-05T13:56:25.488Z CNTRLR   [Node 046] [+] [Manufacturer Specific] productType: 513           [Endpoint 0]
2022-02-05T13:56:25.491Z CNTRLR   [Node 046] [+] [Manufacturer Specific] productId: 11              [Endpoint 0]
2022-02-05T13:56:25.493Z SERIAL » [ACK]                                                                   (0x06)
2022-02-05T13:56:25.498Z DRIVER « [Node 046] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -74 dBm
                                  └─[ManufacturerSpecificCCReport]
                                      manufacturer id: 0x0c
                                      product type:    0x0201
                                      product id:      0x0b

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:

Diagnostics
Driver Version: 8.10.2
Server Version: 1.14.1
Home ID: XXXXX
Server URL: ws://core-zwave-js:3000

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

No Log file needed

**Comment by COCottonwood** [comment]
FYI - I am Currently on CORE 2022.2.1; SUPERVISOR 2022.01.1; HOME ASSISTANT OS 7.2 today, and I re-interviewed the node, and still have this failure.  

Do I need to remove this device and re-add it, because I would have to climb up on a ladder to re-add it as it is mounted on the corner of my house (and I have 5 of these)?

**Comment by COCottonwood** [comment]
PLEASE DO NOT TAKE ANY ACTION ON THIS YET... I might have opened this ISSUE too early. 

I was just informed that I need to wait for the Z-Wave JS addon to pickup the right zwavejs version, then update it, then re-interview.  See https://github.com/zwave-js/node-zwave-js/issues/3701

**Comment by AlCalzone** [comment]
Let me know how it goes

**Comment by COCottonwood** [comment]
Issue resolved, I did open this by mistake.
