### ISSUE TITLE
[Bug]: Did not find a matching NVM 500 parser implementation

### ISSUE THREAD

**Issue by duylong** [AlCalzone/node-zwave-js#4202]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.4.1

### ZwaveJS version

8.11.1

### Describe the bug

Hello,
I tried to restore my NVM to an Aeotec Z-Stick Gen5 and I get the error "Error while calling api restoreNVM: Did not find a matching NVM 500 parser implementation!". My backup is wrong or there is a bug in the restoration? 

### To Reproduce

My backup comes from a Razberry controller. Restore not possible to another controller despite conversion? 

### Expected behavior

The error is not explicit, I cannot identify the real reason for the problem to restore successfully.

**Comment by AlCalzone** [comment]
Pretty sure that firmware 1.2 works.

**Comment by AlCalzone** [comment]
To clarify: when transferring the NVM between two 500 series sticks, the protocol version of both firmwares must normally be the same. If both are from Z-Wave SDK 6.61 or higher, an automatic conversion will be done to lift this constraint. Conversion between <6.61 and >=6.61 NVMs is not possible though.

I'm not sure if the checks currently consider the situation where both the source and target are running the same pre-6.61 SDK, so I'm tagging this as a bug again.

**Comment by vignez2991** [comment]
I have tried to backup and restore with the same version, but still i am getting the same error.
FW: v7.20.0
SDK: v7.20.0

zwave-js-ui: 9.8.3
zwave-js: 12.4.3

Also My chip was 800 Series Silicon Labs but it is showing as 700 Series USB Controller

**Comment by AlCalzone** [comment]
See https://github.com/zwave-js/node-zwave-js/issues/5257 - 800 series NVM backup/restore isn't supported yet
