### ISSUE TITLE
Missing device configuration: Nexia One Touch NX1000

### ISSUE THREAD

**Issue by AB398** [AlCalzone/node-zwave-js#4230]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Nexia One Touch NX1000

### Manufacturer ID

0x0178

### Product Type

0x5343

### Product ID

0x4735

### Firmware Version

1.26

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/1344/

### Do you have a manual?

http://www.nexiahome.com/wp-content/uploads/2015/07/One-Touch.pdf

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 1344 from zwa

**Comment by AlCalzone** [comment]
The bot has created a PR but the file only serves as a starter template. It needs to be cleaned up to conform with our style guide, see above.

For anyone who wants to help out:
- fork the repo if you haven't already. If you have, synchronize your fork so you get the new branch.
- edit branch `import-config-1644762285` in your fork
- create a pull request with your branch `import-config-1644762285` as the source and our branch `import-config-1644762285` as the target
