### ISSUE TITLE
Missing device configuration: EcoNet Controls Z-Vent (EV100)

### ISSUE THREAD

**Issue by RJ-Make** [AlCalzone/node-zwave-js#4232]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

EcoNet Controls Z-Vent

### Manufacturer ID

0x0157 (343)

### Product Type

0x0100 (256)

### Product ID

0x0100 (256)

### Firmware Version

1.93

### Is the device listed on the Z-Wave Alliance website?

https://devices.zwave-js.io/?jumpTo=0x0157:0x0100:0x0100:0.0

### Do you have a manual?

It's not much

[Z-Vent EV100 Instruction Guide.pdf](https://github.com/zwave-js/node-zwave-js/files/8056087/Z-Vent.EV100.Instruction.Guide.pdf)

Here are "Diagnostics" for the 2 I have. 

[zwave_js-1c40bc7c97f6bb6632189a8f69594fc1-Office Supply Vent-f309c34aa5b5d9a237ea27badaa37d99.json.txt](https://github.com/zwave-js/node-zwave-js/files/8056092/zwave_js-1c40bc7c97f6bb6632189a8f69594fc1-Office.Supply.Vent-f309c34aa5b5d9a237ea27badaa37d99.json.txt)

[zwave_js-1c40bc7c97f6bb6632189a8f69594fc1-Living Room Supply Register-2f9d6aa214224a59be87819f28caa4bd.json.txt](https://github.com/zwave-js/node-zwave-js/files/8056093/zwave_js-1c40bc7c97f6bb6632189a8f69594fc1-Living.Room.Supply.Register-2f9d6aa214224a59be87819f28caa4bd.json.txt)

**Comment by AlCalzone** [comment]
You linked to our own device config, which matches the info you gave. So this is wrong:
![grafik](https://user-images.githubusercontent.com/17641229/153889388-0161c274-8685-4f42-bb4c-e0686c677277.png)

I can't see any config parameters in the manual you linked, so there doesn't seem to be anything missing.

**Comment by RJ-Make** [comment]
I think I miss understood what I needed to provide, my apologies I'm new to all this. 

The vent is being picked up as an On / Off light switch in z-wavejs, and perhaps a dimmer in z2mqt. 

Neither operate the vent in Home Assistant. (They worked fine in HomeSeer)

![Screenshot_20220214-182713.png](https://user-images.githubusercontent.com/8496835/153964246-e8630656-60b1-47a0-b223-07e655e4dcdd.png)

![Screenshot_20220214-182806.png](https://user-images.githubusercontent.com/8496835/153964261-b0ebe7a4-f4ff-451a-b26b-04bec55f1147.png)

What do I need to provide to debug?

**Comment by AlCalzone** [comment]
If you open a new issue "bug report", it should ask you for the relevant info
