### ISSUE TITLE
Aeotec Wall Switch (ZWA038-A) - Association Group Command Config: Incorrect Enums

### ISSUE THREAD

**Issue by tommyjlong** [AlCalzone/node-zwave-js#4267]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Aeotec Illumino Wall Switch (ZWA038-A) documentation shows config parameter 82 as:
```
Parameter  Name                                    Information            Size  MIN MAX Default  Description
Number
 82        Association                            Setting command for      1     1   2     1     1- Basic Set
           Control                                association group.                             2- Binary Switch Set
           Settings 
```
The Enums are `1` and `2`
What do you observe?
ZWaveJS2MQTT GUI only allows values `0` (Basic Set) and `1` (Binary Switch).  Default is `1`.

What did you expect to happen?
ZWaveJS2MQTT GUI should allow values `1` (Basic Set) and `2` (Binary Switch). Default is `1`

Device File:
../devices/0x0371/zwa038.json
```
		{
			"#": "82",
			"$import": "~/0x0086/templates/aeotec_template.json#wallmote_command_type"
		},
```
Imports:
../devices/0x0086/templates/aeotec_template.json
```
	"wallmote_command_type": {
		"$import": "~/templates/master_template.json#base_0-1_nounit",
		"label": "Command Type to Send Association Groups",
		"options": [
			{
				"label": "Basic CC Set",
				"value": 0
			},
			{
				"label": "Binary Switch CC Set",
				"value": 1
			}
		]
	},
```
Basic CC Set should have value `1` and Binary Switch CC Set should have value `2`.
I confirmed setting value to 2 works using:
```
mosquitto_pub -t 'z2mqtt/_CLIENTS/ZWAVE_GATEWAY-nucz2m/api/writeValue/set'  -m '{"args":[ { "nodeId": 28, "commandClass": 112, "endpoint": 0, "property": 82 }, 2 ] }'
```
After doing this, the associated device responds as if it received a Binary Switch CC.

### Device information

Manufacturer:  Aeotec
Model name:  ZWA038-A
Node ID in your network: 28

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [X] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 8.11.2
`node-zwave-js` branch:
`zwavejs2mqtt` branch: 6.5.0.12038bd

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

Hopefully self-explanatory without a Log file

**Comment by AlCalzone** [comment]
Thanks for the detailed report. This also affects the illumino Wall Dimmer, I've updated both files in #4269
