### ISSUE TITLE
Notification CC: Embedded User Code Reports are not converted to event parameters correctly

### ISSUE THREAD

**Issue by matjoker** [AlCalzone/node-zwave-js#4336]
Hello,
Not sure if it's a bug or not. I' using a danalock zwave door lock. After a keypad unlock operation, I'm geeting the notification below:
![image](https://user-images.githubusercontent.com/15871046/156918233-fab14754-7b28-4f98-aa54-d0ced0edceb9.png)

I wonder why the parameters are not parsed as a User Code command class disapying the userID.

Thanks for your help.

Matthieu

**Comment by robertsLando** [comment]
@AlCalzone Am I doing something wrong?

**Comment by AlCalzone** [comment]
Per the specifications, the parameters should contain a serialized `User Code CC`. Some devices don't respect this and send a 1-byte user ID instead. However it looks like this one is neither. @matjoker Is there a documentation for the device explaining what is contained there?

**Comment by matjoker** [comment]
Hello,
I reviewed the User Code CC and the parameters from my lock look good.
https://www.silabs.com/documents/login/miscellaneous/SDS13781-Z-Wave-Application-Command-Class-Specification.pdf
The User Code Report command is described on Page 625.
2 first digits: UserID (01 for me)
2 following ones: User ID Status (01 for occupied in my case)
Next ones: UserID code coded in ASCII (30 to 39)

Looks like the parameters from my lock are good, but not parsed by zwavejs.

Thanks for your help

Matthieu

**Comment by AlCalzone** [comment]
Oh... then that payload is missing the two header bytes that identify it as a User Code CC 🙈.
I just love how the manufacturers take so many liberties implementing the specs.

I mean, **this exact use case** is explicitly spelled out in the Notification CC specs, but the yellow part is missing in your case:
![grafik](https://user-images.githubusercontent.com/17641229/157212489-18b021b9-3286-4c1a-958c-b01f65530785.png)

---

Anyways, I can try to work around it, but this is a device bug that should be reported to the manufacturer.

**Comment by matjoker** [comment]
Good to know, thanks for your help!
will try to report the bug to the manufacturer!

don't waste your time with a work around, it isn't a big deal.

Matthieu

**Comment by AlCalzone** [comment]
Actually, @matjoker could you send me the serial message (should be a few lines above the quoted log) via e-mail? This might be something else.

**Comment by matjoker** [comment]
reprod

**Comment by matjoker** [comment]
Sorry, having issues with my internet connection. Will try to reproduce it remotely as I'm not on site and I'll get back to you.
Thanks

**Comment by matjoker** [comment]
Hello, here is the full message:
![image](https://user-images.githubusercontent.com/15871046/158023194-18c6a068-8f08-43f3-94f4-fb3bd685a7df.png)

Thanks

Matthieu

**Comment by AlCalzone** [comment]
Thanks. So the user code report is complete. I take back what I said earlier - this is a bug.

You might want to censor the user code though or remove the screenshot.

**Comment by matjoker** [comment]
Thanks AlCalzone,
Deleted the message.
