### ISSUE TITLE
Provide full version number of controller firmware

### ISSUE THREAD

**Issue by kpine** [AlCalzone/node-zwave-js#4351]
**Is your feature request related to a problem? Please describe.**
The firmware version reported for controllers currently only shows the major and minor version numbers, e.g. `7.17`. A controller might be programmed with firmware version `7.17.02`, but I can't know this.

**Describe the solution you'd like**
The Serial API Get Protocol Version command provides more detailed version information, like the revision number. Using this information, the driver could provide a more complete version number: e.g. `7.17.02` instead of `7.17`.

**Describe alternatives you've considered**
N/A

**Additional context**
Example output from Silicon Labs zw_programmer utility, which uses this command:
```
$ zw_programmer -s /dev/zwave -t
Using serial device /dev/zwave
Connected to Serial device: OK
Serial version: 9, Chip type: 7, Chip version: 0, SDK: 7.17.02, SDK Build no: 151 SDK git hash: 30303030303030303030303030303030
Chip library: 7, ZW protocol: 7.17, NVM: bridge7.16
nvm_id: bridge7.16
Closing Serial connection
```

**Comment by AlCalzone** [comment]
> The Serial API Get Protocol Version

~~Did I miss this somewhere? Got a link to the specification?~~

**Edit:** Ohh, it's a new 7.xx API command
