### ISSUE TITLE
Controller stays in SmartStart inclusion mode even if there aren't any planned provisioning entries

### ISSUE THREAD

**Issue by kpine** [AlCalzone/node-zwave-js#4369]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Not sure how it happened, but the controller is reporting that it's in SmartStart inclusion mode, even though all my provisioned entries are included. I'd expect it to be Idle.

Not sure how to reproduce, possibly:
1. Add a QR code for SmartStart inclusion
2. Power on the node, and it gets included
3. SmartStart inclusion mode is not disabled?

### Device information

N/A

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 8.11.6
`zwavejs2mqtt` branch: 6.5.2

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

In debugging an HA issue, I noticed that the controller was in SmartStart inclusion mode due to an unprovisioned node. I removed the entry and the state went to idle.

Some days later I had to re-include a node, so I performed the exclusion, then re-imported the QR code and added it via SmartStart. Today, I noticed that the inclusion state is back to SmartStart, but all nodes are provisioned.

### Attach Driver Logfile

Sent privately.

**Comment by AlCalzone** [comment]
I'm unable to reproduce this. The only thing I could imagine is that there is a provisioning entry with a DSK that's not known to belong to any included nodes.
