### ISSUE TITLE
Missing device configuration: <zooz zen51>

### ISSUE THREAD

**Issue by danielsza** [AlCalzone/node-zwave-js#4393]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Zooz zen51

### Manufacturer ID

Zooz

### Product Type

0x0104

### Product ID

0x0201

### Firmware Version

1.10

### Do you have a manual?

https://www.getzooz.com/downloads/zooz-700-series-z-wave-plus-dry-contact-relay-zen51-manual.pdf

**Comment by zetlen** [comment]
Should be closed by #4262 once it's reviewed and merged.
