### ISSUE TITLE
Home Assistant - Integration firmware version decimals missing

### ISSUE THREAD

**Issue by Tom-ahawk** [AlCalzone/node-zwave-js#4401]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Using Aeotec Z-Wave Z-Stick (700) I miss the exact firmware version to be displayed in HA/Integrations/Devises/700 Series-based Controller.

It displays 7.17 and not 7.17.12

Checking Silicon Labs for firmware updates once a moth and it would be useful to have the correct firmware displayed in HA as a reference.

![image](https://user-images.githubusercontent.com/35527507/159774219-089def30-a541-4e12-a916-5426d917b476.png)

Investigated by HA and they directed my to Zwave-js:
https://github.com/home-assistant/core/issues/68560

### Device information

[Diagnostics of Z-Wave network.txt](https://github.com/zwave-js/node-zwave-js/files/8335775/Diagnostics.of.Z-Wave.network.txt)

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
Current version: 0.1.55

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[Diagnostics of Z-Wave network.txt](https://github.com/zwave-js/node-zwave-js/files/8335765/Diagnostics.of.Z-Wave.network.txt)

**Comment by AlCalzone** [comment]
This is already fixed on master and will be included in the upcoming v9 release of the driver.
https://github.com/zwave-js/node-zwave-js/pull/4355
