### ISSUE TITLE
Query CC versions for CCs that only exist on endpoints

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#4413]
See https://github.com/zwave-js/node-zwave-js/discussions/4402 for context

Essentially the device doesn't expose the `Multilevel Sensor CC` on the root device, so the driver never queries the CC version.
As a result, the endpoints are interviewed with `Multilevel Sensor CC V1`, which only queries the default sensor reading.

**Comment by espenthingstad** [comment]
I see that each time I do a reload of the Zwave JS integration, then the values on the sensor are updated. 
See attached e.g. the consumption trendline.
<img width="482" alt="Screenshot 2022-03-29 at 18 53 07" src="https://user-images.githubusercontent.com/80642192/160664838-b2fd658e-1271-492b-b21f-02c8a613a827.png">

**Comment by AlCalzone** [comment]
> each time I do a reload of the Zwave JS integration, then the values on the sensor are updated

I'm not sure if HA re-queries the values then or why that is. I suggest opening an issue in https://github.com/home-assistant/core for this.

The issue you described in https://github.com/zwave-js/node-zwave-js/discussions/4402 will be fixed in the upcoming v9 release.
