### ISSUE TITLE
Often dead FIBARO Roller Shutter 2 nodes in Zwave-js

### ISSUE THREAD

**Issue by vladimiro13** [AlCalzone/node-zwave-js#4466]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

After migration from open zwave to zwave-js I have problems with often dead state with all my fibaro Roller Shutter 2 (fw 25.25).  I have zwave gw AEOTEC Z-Stick Gen5. Sometimes the nodes fall for only a few minutes, sometimes for a longer period and no action helps and they have to recover on their own (various long time). Automation for zwave ping on all nodes every 10 minutes and active sending of reports (power / status) from fibaro nodes didn't helped me. 
I attach a sample of dead state of one of the shutter nodes (Node 010), a similar situation is for each one node (at different times).
I also attach a part of the silly log at the time of the crash the one (node 10) of the nodes
![shutter_FGR222_dead_example](https://user-images.githubusercontent.com/33814870/163175999-384a0f47-8071-41a1-b9cd-ba41e2d4e751.png)
[dead_node_10_20220413-11:35:04_log_silly.txt](https://github.com/zwave-js/node-zwave-js/files/8481253/dead_node_10_20220413-11.35.04_log_silly.txt)
.

### Device information

Manufacturer: Fibaro
Model name: Roller Shutter 2
Node ID in your network: Node 010
Zwave GW: AEOTEC Z-Stick Gen5
Driver version: 8.11.9
Server version: 1.15.0
Home assistant version: 2022.4.1

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: homeassistant/amd64-addon-zwave_js:0.1.55

### Did you change anything?

yes (please describe)

### If yes, what did you change?

I migrated zwave nodes from open zwave to zwave-js.

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

2022-04-13T09:35:03.251Z SERIAL « 0x010c0004000806310504220000eb                                      (14 bytes)
2022-04-13T09:35:03.252Z CNTRLR   [Node 008] [Multilevel Sensor] Power: metadata updated            [Endpoint 0]
2022-04-13T09:35:03.254Z CNTRLR   [Node 008] [~] [Multilevel Sensor] Power: 0 => 0                  [Endpoint 0]
2022-04-13T09:35:03.255Z SERIAL » [ACK]                                                                   (0x06)
2022-04-13T09:35:03.256Z DRIVER « [Node 008] [REQ] [ApplicationCommand]
                                  └─[MultilevelSensorCCReport]
                                      type:  Power
                                      scale: Watt
                                      value: 0
2022-04-13T09:35:04.775Z SERIAL « 0x01070013810100ed86                                                 (9 bytes)
2022-04-13T09:35:04.777Z SERIAL » [ACK]                                                                   (0x06)
2022-04-13T09:35:04.778Z DRIVER « [REQ] [SendData]
                                    callback id:     129
                                    transmit status: NoAck
2022-04-13T09:35:04.784Z CNTRLR   [Node 010] The node did not respond after 1 attempts, it is presumed dead
2022-04-13T09:35:04.785Z CNTRLR   [Node 010] The node is now dead.
2022-04-13T09:35:04.786Z CNTRLR   [Node 010] ping failed: Failed to send the command after 1 attempts (Status No
                                  Ack) (ZW0204)
2022-04-13T09:35:04.843Z SERIAL « 0x01100004000e0a32022144000000b3000009                              (18 bytes)
2022-04-13T09:35:04.844Z CNTRLR   [Node 014] [~] [Meter] value[65537]: 1.79 => 1.79                 [Endpoint 0]
2022-04-13T09:35:04.845Z SERIAL » [ACK]                                                                   (0x06)
2022-04-13T09:35:04.845Z DRIVER « [Node 014] [REQ] [ApplicationCommand]
                                  └─[MeterCCReport]
                                      type:       Electric
                                      scale:      kWh
                                      rate type:  Consumed
                                      value:      1.79
                                      time delta: 0 seconds

**Comment by AlCalzone** [comment]
Please **attach** the logfile as a file and don't just paste it into the issue text.

That said, your stick is temporarily not able to get a response from the device (NoACK), which is usually an indicator of a bad connectivity. Pinging the nodes just works around the symptoms.

I suggest you do the following:
1. read the intro to the troubleshooting guide https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index
2. make sure you've followed the general tips here: https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting - a bad controller placement can easily cause what you're experiencing
3. Try doing a network heal, especially if you've moved the controller as part of step 2.
4. If that doesn't help, use zwavejs2mqtt to check the health of each node's route to the controller (node 1). You might find some don't have a strong link

**Comment by vladimiro13** [comment]
Hi, thanks for the feedback. I attached file dead_node_10_20220413-11:35:04_log_silly.txt, what is part of silly log. But now, I attach new full silly log, from the time when some nodes were again dead (But now exceptionally only for a while, later the situation will definitely be worse). I don't think network or distance is a problem, because nodes fall both 30 meters and 7 meters away from zwave stick gateway. And before that I didn't have this problem for about 3 years via open zwave. Sometimes there is no problem, nodes alive and the actions (open/close) work correctly also and other times they fall into a dead state repeatedly.
As I wrote, I do not use zwavejs2mqtt but only the zwave-js addon under home-assistant. So, is zwavejs2mqtt needed for troubleshooting? 
Thanks.
[zwave_js.log](https://github.com/zwave-js/node-zwave-js/files/8482741/zwave_js.log)

**Comment by vladimiro13** [comment]
Hi. Just a while ago, several points fell again, so I'm adding a newer log again.
Thanks for help.
[zwave_js_new.log](https://github.com/zwave-js/node-zwave-js/files/8482780/zwave_js_new.log)

**Comment by AlCalzone** [comment]
> And before that I didn't have this problem for about 3 years via open zwave

I've lost track of how often I had this same argument. You did have the problem, you probably just didn't notice, since the commands are retried internally and best case all you see are longer delays. I've used OZW before I started Z-Wave JS and it simply didn't surface the communication errors as visibly as Z-Wave JS does.

`NoAck` means the communication between the controller and node is disrupted physically, as in packets get lost on the air. The host software cannot influence this at all. This instance where node 7 retries sending its report a few times while the controller is having trouble reaching node 8 looks like this is a bidirectional problem:
```
# outgoing message to node 8
2022-04-13T14:55:00.015Z DRIVER » [Node 008] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      219
                                  └─[NoOperationCC]
...
2022-04-13T14:55:00.026Z DRIVER « [RES] [SendData]
                                    was sent: true

# node 7 tries to reach the controller a few times but doesn't get an acknowledgement
2022-04-13T14:55:01.254Z DRIVER « [Node 007] [REQ] [ApplicationCommand]
                                  └─[MultilevelSensorCCReport]
                                      type:  Power
                                      scale: Watt
                                      value: 0
...
2022-04-13T14:55:01.263Z DRIVER « [Node 007] [REQ] [ApplicationCommand]
                                  └─[MultilevelSensorCCReport]
                                      type:  Power
                                      scale: Watt
                                      value: 0
...
2022-04-13T14:55:01.758Z DRIVER « [Node 007] [REQ] [ApplicationCommand]
                                  └─[MultilevelSensorCCReport]
                                      type:  Power
                                      scale: Watt
                                      value: 0

# controller failed to reach node 8
2022-04-13T14:55:02.148Z DRIVER « [REQ] [SendData]
                                    callback id:     219
                                    transmit status: NoAck
```

I'm not sure if you followed my advice from the previous post already, especially the part about the controller placement and USB extension:
> [zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting) - a bad controller placement can easily cause what you're experiencing

If not, I strongly suggest you start with that - if I had to estimate, the success rate of that simple change is like 80-90%.

The information isn't included in your log, but since many nodes seem to go dead at the same time, I'd guess that most of them route through a single node and that node is having problems. Optimizing the controller placement and then healing the network can alleviate this problem by giving the nodes good alternative routes.

**Comment by vladimiro13** [comment]
Hi AlCalzone, thanks for your reply and time. 

As for the location of the controller, as I wrote before the distance of controller to the node is from 7 to 30 meters, while the frequency of problems is the same for most nodes, even the nearest ones.
But I have a USB controller behind the TV, so I'll try to change the position and I will see if there is a change.

The problem with the communication issue can also cause by often (every 60 seconds) sending reports from all (9) nodes and zwave ping from the controller to all nodes (every 5 min)? Although I did it due to stay all nodes alive.

I also want to ask you about the mentioned healing of the network or roads to nodes. Did you mean action/button "Heal Network" in Diagnostics options?
Or how can I affect these paths between zwave nodes?

Thanks.

**Comment by AlCalzone** [comment]
> As for the location of the controller, as I wrote before the distance of controller to the node is from 7 to 30 meters, while the frequency of problems is the same for most nodes, even the nearest ones.

The distance does not matter if the controller or a node is affected by radio interference. https://www.usb.org/sites/default/files/327216.pdf gives some details, including the noise spectrum of USB 3.0, which is actually the highest around the 900 MHz that Z-Wave uses:
![grafik](https://user-images.githubusercontent.com/17641229/163667436-2d583ea0-5e11-4198-af75-6c5bc4db1cd0.png)

Frequent reports and bulk commands that are repeated due to connectivity issues certainly make the matter worse.

> I also want to ask you about the mentioned healing of the network or roads to nodes. Did you mean action/button "Heal Network" in Diagnostics options?
Or how can I affect these paths between zwave nodes?

In zwavejs2mqtt, you can either heal the entire network (Actions -> Advanced -> Heal Network) or individual problematic nodes (Open node dropdown -> Advanced -> Heal Node). Both actions try to optimize the routes.

You can also test the connection quality of each node on the network map:
![grafik](https://user-images.githubusercontent.com/17641229/163667579-a78158fb-4640-44a4-b9c1-7418bc6227be.png)

**Comment by vladimiro13** [comment]
Hi AlCalzone.
Thanks for the answers. I will try to change the position of the USB controller next week and let me know if it helped. According to the description, this can really be related, as I use USB 3.1 ports on the intel nuc with a directly connected USB zwave dongle. I will try to use a USB extension cable.
I have also just increased the frequency of reports, I will see if the dead status will not increase again.

Next question, to render a real zwave map I need to install zwavejs2mqtt and this is not a problem besides running zwave-js configuration?

Thanks.

**Comment by vladimiro13** [comment]
Hi AlCalzone.
Thanks for the answers. I will try to change the position of the USB controller next week and let me know if it helped. According to the description, this can really be related, as I use USB 3.1 ports on the intel nuc with a directly connected USB zwave dongle. I will try to use a USB extension cable.
I have also just increased the frequency of reports, I will see if the dead status will not increase again.

Next question, to render a real zwave map I need to install zwavejs2mqtt and this is not a problem besides running zwave-js configuration?

Thanks.

**Comment by AlCalzone** [comment]
You can switch between the two addons, both work with the official Z-Wave JS integration:
https://www.home-assistant.io/integrations/zwave_js/#how-do-i-switch-between-the-official-z-wave-js-add-on-and-zwavejs2mqtt

**Comment by vladimiro13** [comment]
Hi AlCalzone. 
I am happy to confirm that by changing the position of the zwave USB stick away from Intel nuc (and USB 3 ports), my problem with the frequent dead status of all nodes has been eliminated. Thank you for your help.
