### ISSUE TITLE
`handleUnsolicitedMessage` not called while waiting for a controller callback

### ISSUE THREAD

**Issue by ghost** [AlCalzone/node-zwave-js#4467]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Ever since zwavejs2mqtt 6.5.0 I have been having trouble with multiple security sensors from different manufacturers getting stuck showing an intrusion as the The "idle" report is randomly getting dropped.  I haven't noticed any other types of sensor reports getting dropped, or any failed commands.

It appears each time this happens the notification report is actually being received, but randomly not getting forwarded from an internal endpoint to the external endpoint to where it can be processed by zwavejs2mqtt or zwavejs_server.

Example of an idle notification not dropped:
```
2022-04-12T11:32:52.559Z SERIAL « 0x01110004001f0b7105070000ff07000108007c                            (19 bytes)
2022-04-12T11:32:52.561Z CNTRLR   [Node 031] [~] [Notification] notificationMode: "push" [Endpoint 0] [internal]
                                   => "push"
2022-04-12T11:32:52.561Z SERIAL » [ACK]                                                                   (0x06)
2022-04-12T11:32:52.562Z DRIVER « [Node 031] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   7
                                      notification status: 255
                                      notification state:  idle
                                      event parameters:    0x08
2022-04-12T11:32:52.566Z CNTRLR   [Node 031] [~] [Notification] Home Security[Motion sensor status] [Endpoint 0]
                                  : 8 => 0
2022-04-12T11:32:52.767Z SERIAL « 0x01090004001f038003ff92     
```
Example of a dropped notification:
```
2022-04-13T11:45:13.684Z SERIAL « 0x01110004001f0b7105070000ff07000108007c                            (19 bytes)
2022-04-13T11:45:13.686Z CNTRLR   [Node 031] [~] [Notification] notificationMode: "push" [Endpoint 0] [internal]
                                   => "push"
2022-04-13T11:45:13.687Z SERIAL » [ACK]                                                                   (0x06)
2022-04-13T11:45:13.688Z DRIVER « [Node 031] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   7
                                      notification status: 255
                                      notification state:  idle
                                      event parameters:    0x08
2022-04-13T11:45:13.969Z SERIAL « 0x01090004001f038003ff92                                            (11 bytes)
```
The key difference between the exchanges seems to be this line and I can't come up with a reason why it's missing.   Every time there is a dropped report, this line is missing and the notification appears to have been correctly decoded.  
```
2022-04-12T11:32:52.566Z CNTRLR   [Node 031] [~] [Notification] Home Security[Motion sensor status] [Endpoint 0]
                                  : 8 => 0
```
The preceding `CNTRLR notificationMode: "push" [Endpoint 0] [internal]` line is always present.

This doesn't seem to be specific to any particular notification CC implementation.  My Ring security sensors are affected in an identical manner and they use different command class versions.  

### Device information

Manufacturer: Vision Security
Model name: ZP3111-5
Node ID in your network:  31

Manufacturer: Ring
Model name: 4SD1S7-0EN0 / 4SDAE9-0EU0
Node ID in your network:  64

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 9.0.1
`zwavejs2mqtt` branch: 6.7.0

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Before zwavejs2mqtt 6.5.0

### Attach Driver Logfile

[logs.txt](https://github.com/zwave-js/node-zwave-js/files/8481917/logs.txt)
[zwavejs_2022-04-13.log](https://github.com/zwave-js/node-zwave-js/files/8481962/zwavejs_2022-04-13.log)

**Comment by AlCalzone** [comment]
Doesn't seem to be the previous state being idle already either 🤔

**Comment by AlCalzone** [comment]
Do you happen to have any other logs where the same happens? I have a suspicion, but would like to confirm.

**Comment by AlCalzone** [comment]
Nevermind, I was able to reproduce this in a test case
