### ISSUE TITLE
[Bug]: Timeout respons - node communication version 9 

### ISSUE THREAD

**Issue by prilly-dev** [AlCalzone/node-zwave-js#4508]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.7.4

### ZwaveJS version

9.0.4

### Describe the bug

I have problems with timeout respons in the zwave communication with devices with S0 and S2, it seems to be most problematic with locks like ID-Lock 150 and danalock

![bilde](https://user-images.githubusercontent.com/66376450/164884689-757600ac-14ce-44df-8607-a922186eb68b.png)

It seems that the timeout is related to bum to version 9

![bilde](https://user-images.githubusercontent.com/66376450/164884725-09b54c2b-f196-44e5-b11a-d35c38cf7bdb.png)

reinterviewing nodes with S0 and S2 seems to always have some kind of timeout respons issue, this is resulting in incomplete node capabilities. i also see this issue most noticable when refreshing user code v1 on the id_lock 150, this list is109 codes 

to mee it seems the lock cant respond fast enough, might be related to nonce issue i think, then timeout repons is generated.

All my nodes has direct connection to the zwave controller, there are no communication issues with the controller itself.
this issue might also be related to upgrading zstick gen5 to gen5+ firmware, but i doubt that it the case as i have tried a different gen5 controller.

![bilde](https://user-images.githubusercontent.com/66376450/164884945-31205d73-6f71-4602-9b89-3599f0dc08af.png)

there are some latency when route changes:

![bilde](https://user-images.githubusercontent.com/66376450/164885015-b8b75c49-0147-4ee6-ba57-af5ab85ea3ad.png)

### To Reproduce

add S0 id lock to controller, perform interview and then refresh usercode v1 class, wait and timeout respons will increase

### Expected behavior

solid communication, no timeout respons.

**Comment by prilly-dev** [comment]
it seems the RTT + 1 sec might be a problem when route changes and rtt avrage goes from 30-40ms to 1200ms then it hits timeout.

**Comment by jmgiaever** [comment]
I guess this is a Zwavejs issue and not zwavejs2mqtt @AlCalzone ?

**Comment by muddro1** [comment]
Having same issue with Schlage lock BE469ZP

**Comment by jmgiaever** [comment]
Remember logs, from Zwavejs

**Comment by AlCalzone** [comment]
> it seems the RTT + 1 sec might be a problem when route changes and rtt avrage goes from 30-40ms to 1200ms then it hits timeout.

The initially large delay may be an incorrect test result caused by the target node being a FLiRS device. Those take up to a second to wake up and then stay awake for the remaining communication.

The initial delay should also be part of the RTT, so the lock gets ~2s to respond after that - which should be more than enough when it normally responds within a handful of milliseconds. Also, the S0 nonces are also factored in here, so in reality the timeout will be even higher.

The link quality seems to be suboptimal though, see test round 4 where failures started to occur under -2 dBm. Please check that you've followed all of the general troubleshooting steps outlined here:
https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting

If that doesn't help either, I need logs of the timed out communication please!

**Comment by prilly-dev** [comment]
This was just an example of a timeout, in this particular test we only see one test with high latency, but i practice there are multiple ones, let me retest and upload a screenshot.

All troubleshooting of connectivity issues has been tested, if i downgrade to zwavejs version 8 this is no longer a issue, there are no connection issues.

I will get a logg for you

**Comment by AlCalzone** [comment]
> there are no connection issues.

Your health check results beg to differ, but I'll wait for the log.

**Comment by prilly-dev** [comment]
I did test with zstick gen5 stick and only one node id lock 150 in a new network, timeour reponses are seen there also and this is happening when the stick is exactly 1 meter away from the lock on a extension cord. I also have RTH-K18 RF SPECTRUM ANALYZATOR, that i have concluded that there are no interference that can explain this behaviour. And again, downgrading to zwavejs version 8 fixes the issue

**Comment by prilly-dev** [comment]
There are multiple reasons this healthcheck can produce issues like this, interference is just one of them. I will provide some logs later today

**Comment by prilly-dev** [comment]
So you said:
`
The initially large delay may be an incorrect test result caused by the target node being a FLiRS device. Those take up to a second to wake up and then stay awake for the remaining communication`

When route changes and the communication goes through a new node that needs wakeup, what mechanism is making shure the delay is not introduced again? As i initialy wrote this problems with latency is happening when route changes

In the test provided the target node is the zstick gen5 controller itself

**Comment by AlCalzone** [comment]
Routing only uses mains powered nodes as repeaters, not sleeping or FLiRS nodes.

**Comment by muddro1** [comment]
So just re-upped back to 6.7.4 and did a reinterview on my BE469ZP. Same issue I had before, with an incomplete interview. You'll notice it isn't even able to grab the manufacturer, product, product code, and in the past, it also wouldn't pick up the firmware. It is also missing a bunch of the typical values categories, namely the one for user codes:

![image](https://user-images.githubusercontent.com/15880479/165302527-4f2cd352-f6e1-4500-bf38-8a45ad11c0d6.png)[zwavejs_2022-04-26.log](https://github.com/zwave-js/node-zwave-js/files/8563264/zwavejs_2022-04-26.log)

I've also attached my logs.

**Comment by prilly-dev** [comment]
> So just re-upped back to 6.7.4 and did a reinterview on my BE469ZP. Same issue I had before, with an incomplete interview. You'll notice it isn't even able to grab the manufacturer, product, product code, and in the past, it also wouldn't pick up the firmware. It is also missing a bunch of the typical values categories, namely the one for user codes:
> 
> ![image](https://user-images.githubusercontent.com/15880479/165302527-4f2cd352-f6e1-4500-bf38-8a45ad11c0d6.png)[zwavejs_2022-04-26.log](https://github.com/zwave-js/node-zwave-js/files/8563264/zwavejs_2022-04-26.log)
> 
> I've also attached my logs.

What did the statistics tab say under that node? Could you expand it?

**Comment by AlCalzone** [comment]
@muddro1 your lock doesn't respond at all to the requests during the interview. It tells the driver which commands are supported securely, then there's radio silence aside from the protocol-level acknowledgements (which are received almost immediately btw).

Right at the very end, it responds once to a query that was sent 11 seconds earlier - but not the ones that were sent prior.

**Comment by muddro1** [comment]
> at did the statistics tab say under that node? Could you expand i

Keep in mind this is going backwards every version of zwave and doing a refresh until it works. Havent gotten there yet:

![image](https://user-images.githubusercontent.com/15880479/165306335-0dd33d43-4826-4ee8-b868-1d7c75fbdc80.png)

**Comment by muddro1** [comment]
> @muddro1 your lock doesn't respond at all to the requests during the interview. It tells the driver which commands are supported securely, then there's radio silence aside from the protocol-level acknowledgements (which are received almost immediately btw).
> 
> Right at the very end, it responds once to a query that was sent 11 seconds earlier - but not the ones that were sent prior.

Didn't seem to have this problem before and not sure why its arising. The lock is less than 5 feet from the controller, and the controller is on a USB. Any troubleshooting I can do?

**Comment by AlCalzone** [comment]
> Any troubleshooting I can do?

I'm inclined to say this is on the lock side and not the controller side.
- Switch batteries
- Exclude, factory reset, re-include the lock

**Comment by prilly-dev** [comment]
> > Any troubleshooting I can do?
> 
> I'm inclined to say this is on the lock side and not the controller side.
> 
>     * Switch batteries
> 
>     * Exclude, factory reset, re-include the lock

I have done this multiple times, its weird we see excatly the same issues on atlest 3 different locktypes with both s0 and s2, where s0 seems to be the worst

**Comment by muddro1** [comment]
> > > Any troubleshooting I can do?
> > 
> > 
> > I'm inclined to say this is on the lock side and not the controller side.
> > ```
> > * Switch batteries
> > 
> > * Exclude, factory reset, re-include the lock
> > ```
> 
> I have done this multiple times, its weird we see excatly the same issues on atlest 3 different locktypes with both s0 and s2, where s0 seems to be the worst

Got it working again, but had to replace batteries. Ways I got it working before was also unplugging batteries and replugging them. Odd that its only 4 feet away and the batteries reported @ 97% and would need to be changed.

**Comment by AlCalzone** [comment]
> I have done this multiple times, its weird we see excatly the same issues on atlest 3 different locktypes with both s0 and s2, where s0 seems to be the worst

I went by the log I got from @muddro1. Your issue may be different.

**Comment by prilly-dev** [comment]
so i have done some logging in silly mode, i have done a interview of the node that is the id lock 150 and refreshed usercode v1 class.

[zwavejs_2022-04-26.log](https://github.com/zwave-js/node-zwave-js/files/8564871/zwavejs_2022-04-26.log)

**Comment by AlCalzone** [comment]
@prilly-dev
The communication looks okay-ish. Round-trip times of 100..150 ms at 40 kbps, which does seem normal. However, I'm seeing this over 200 times in your log:
```
ACK RSSI:               Receiver saturated
```
which means the RSSI at the controller was too high to measure precisely. Not sure if this is a problem, you're the first user where I saw this at all. Doesn't sound good though.

---

Then there's a longer stretch of timeouts, but this is due to a different issue:
Z-Wave JS queries the Configuration CC without security encapsulation, because the lock didn't report the CC to require security. These are the ones that don't:
```
2022-04-26T15:49:35.883Z CNTRLR « [Node 025] node info received
                                  supported CCs:
                                  · Z-Wave Plus Info
                                  · Manufacturer Specific
                                  · Security
                                  · Device Reset Locally
                                  · Powerlevel
                                  · Configuration
                                  controlled CCs:
```
and these are the ones that do:
```
2022-04-26T15:49:36.551Z CNTRLR « [Node 025] received secure commands (S0)
                                  supported CCs:
                                  · Version
                                  · Door Lock
                                  · User Code
                                  · Association
                                  · Association Group Information
                                  · Notification
                                  · Firmware Update Meta Data
                                  · Battery
                                  controlled CCs:
```
However, the lock responds with security-encapsulated configuration reports, which are not considered to be responses to the un-encapsulated requests:
```
2022-04-26T15:50:00.322Z DRIVER » [Node 025] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      101
                                  └─[ConfigurationCCGet]
                                      parameter #: 4
...
2022-04-26T15:50:01.215Z DRIVER « [Node 025] [REQ] [ApplicationCommand]
                                  └─[SecurityCCCommandEncapsulation]
                                    │ sequenced: false
                                    └─[ConfigurationCCReport]
                                        parameter #: 4
                                        value size:  1
                                        value:       2
```
IMO this is a **bug in the lock firmware**.

The next stretch of timeouts happen when the user codes are queried. At first the lock claims that it supports 109 codes:
```
2022-04-26T15:49:56.844Z DRIVER « [Node 025] [REQ] [ApplicationCommand]
                                  └─[SecurityCCCommandEncapsulation]
                                    │ sequenced: false
                                    └─[UserCodeCCUsersNumberReport]
                                        supported users: 109
```
but later when Z-Wave JS queries all codes, it only responds twice:
* Request for code 1 returns code 1
* Request for code 2 also returns code 1 (!)
* Requests for codes 3..109 time out (no response)

In the meantime, the lock does promptly respond to the Nonce requests and there are no dropped commands, so this doesn't seem to be a physical communication issue.

I'm also leaning towards calling this a **bug in the lock firmware**.

**Comment by prilly-dev** [comment]
I did found at what this saturated is, if you look closely it specifies node 5 as repeater node. Communication goes from node 25 (lock) -> node 5 (fibaro dimmer 2) - node 1 (zstick gen 5). Node 5 is less then 20 cm from the lock, its built inn the wall right by the door. So its the reciver at node 5 that reports saturated not the controller. All messages sent from the lock -> controller seems to be repeated by node 5. What i found out is that saturated reciver is of no problem ref: https://drzwave.blog/category/z-wave-mesh/

What i did notice is that there are expired nonce when refreshing usercode v1 from the lock, parameters is default not set in the lock either if usercodes are not enabled and set from the user side. It seems it claims that values are not passed from the lock it might be the lock is not passing them because its actualy not set and there are no values. It seems that the updates that do work on refresh are from the parameter 1 (usercode enabled) parameter 2 (usercode) and 109/110 as this are set by user

**Comment by AlCalzone** [comment]
> it might be the lock is not passing them because its actualy not set and there are no values

Doesn't matter, it still has to respond:
![image](https://user-images.githubusercontent.com/17641229/165480460-bc5b72d8-691c-4f40-af02-2a5fdb9c192c.png)

and tell us that the code isn't occupied using the User ID status:
![image](https://user-images.githubusercontent.com/17641229/165480952-91e589b4-aa99-425e-a72f-8add58e13436.png)

**Comment by AlCalzone** [comment]
FWIW, this isn't true:
> its the reciver at node 5 that reports saturated not the controller.

The repeater ACK is a separate field in the transmit report and it is N/A in your case. Not all nodes support reporting it.
The field in your reports is definitely at the controller. Here's an example:
```
2022-04-26T15:47:22.421Z DRIVER « [REQ] [SendData]
                                    callback id:            3
                                    transmit status:        OK, took 80 ms
                                    repeater node IDs:      5, 9
                                    routing attempts:       1
                                    protocol & route speed: Z-Wave, 40 kbit/s
                                    ACK RSSI:               Receiver saturated
                                    ACK RSSI on repeaters:  N/A, N/A
                                    ACK channel no.:        1
                                    TX channel no.:         1
```

**Comment by prilly-dev** [comment]
> FWIW, this isn't true:
> 
> > its the reciver at node 5 that reports saturated not the controller.
> 
> The repeater ACK is a separate field in the transmit report and it is N/A in your case. Not all nodes support reporting it. The field in your reports is definitely at the controller. Here's an example:
> 
> ```
> 2022-04-26T15:47:22.421Z DRIVER « [REQ] [SendData]
>                                     callback id:            3
>                                     transmit status:        OK, took 80 ms
>                                     repeater node IDs:      5, 9
>                                     routing attempts:       1
>                                     protocol & route speed: Z-Wave, 40 kbit/s
>                                     ACK RSSI:               Receiver saturated
>                                     ACK RSSI on repeaters:  N/A, N/A
>                                     ACK channel no.:        1
>                                     TX channel no.:         1
> ```

Yes you probably have right there, but reciver saturated is of no problem.

**Comment by prilly-dev** [comment]
it might seems you have right regarding buggy firmware, this id lock is in general a buggy lock. let me see what the maker of thr lock has to say.

as i told you i habe more locks this is a issue with, i have a danalock v3 btzw that also has issues with usercode class, i will provide you with logs from this unit later today.

**Comment by AlCalzone** [comment]
Hope you don't also have a Schlage lock, as these seem to be nightmares too.

**Comment by prilly-dev** [comment]
![bilde](https://user-images.githubusercontent.com/66376450/165551048-2b4c0ef9-77b9-4bd5-9841-11e5947fa0dd.png)

it indeed seems to be undefines values in usercode for the idlock, i will try to sett all values to 2 to see if this might change anything, i have reported this issues to idlock, generic respons from them, i will wait and see what they come up with.
