### ISSUE TITLE
Minoston mp22zd got combined into mp22z but they are two different switches with different config

### ISSUE THREAD

**Issue by kevinwmerritt** [AlCalzone/node-zwave-js#4523]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

The switch mp22zd uses the device config mp22z.json. These are two different switches but somehow the config got combined at some point.

I would like to fix some bugs with the `paramInformation` for mp22zd BUT before I make a PR for that, is it acceptable for me to make a PR to split out mp22zd into its own `.json` file?

Thank you.

### Device information

Manufacturer: mp22zd
Model name: Minoston
Node ID in your network: 

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwavejs2mqtt` branch:

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

N/A

**Comment by AlCalzone** [comment]
Looks like the ZD variant was incorrectly determined to be the same as the Z variant in https://github.com/zwave-js/node-zwave-js/pull/3855

> is it acceptable for me to make a PR to split out mp22zd into its own .json file?

Go for it 👍️
