### ISSUE TITLE
[Bug]: Device disappears, auto-removed after 1 missed ping

### ISSUE THREAD

**Issue by karalabe** [AlCalzone/node-zwave-js#4575]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

5.4.2

### ZwaveJS version

8.0.5

### Describe the bug

A qubino shutter device just disappered from the list of tracked devices.

Looking through the logs, about half a day before I noticed, the device didn't respond to a ping and was pronounced dead. The device still worked properly when directing it from a button, so it wasn't offline or anything.

Exactly 10 minutes after presuming the device dead, zwavejs clean up all the entries related to it and removed the device altogether. I can't imagine why it would do that just because of 1 failed ping.

Here are the logs:

```
[In the beginning it works as usual]
2022-05-04 05:16:33.135 INFO ZWAVE: Node 55: value updated: 38-1-currentValue 0 => 89
2022-05-04 05:17:25.226 INFO ZWAVE: Node 55: value updated: 38-2-currentValue 99 => 0
2022-05-04 05:17:33.971 INFO ZWAVE: Node 55: value updated: 38-2-currentValue 0 => 0

[Here we miss one ping and the device is marked dead]
2022-05-04T05:17:55.358Z CNTRLR   [Node 055] Node 55 did not respond after 1 attempts, it is presumed dead
2022-05-04 05:17:55.361 INFO ZWAVE: Node 55 is now dead
2022-05-04T05:17:55.379Z CNTRLR   [Node 055] ping failed: Node 55 did not respond after 1 attempts, it is presum

[Here at exactly 10 minutes later (down to 150ms, so must be automated task) all the device entities are removed and the device itself it also removed]
2022-05-04 05:18:05.550 INFO ZWAVE: Node 55: value removed: 114-0-manufacturerId
2022-05-04 05:18:05.552 INFO ZWAVE: Node 55: value removed: 114-0-productType
[... lots of removed entities ...]
2022-05-04 05:18:05.810 INFO ZWAVE: Node 55: removed
```

If you're curious, here are the [entire lifetime logs](https://gist.github.com/karalabe/ac635b20d99542f631c85f4f831e39c6) for this entity.

Seems to match the issue reported in zwave-js/node-zwave-js#4592, though I think there the user didn't have any logs to back up the issue with.

### To Reproduce

No idea

### Expected behavior

If a node goes dead for whatever reason, it should most definitely not be removed. Now I've no idea even what to do, I have to somehow unpair and repair them? Get new device IDs, redo all the itegrations, it's a horribly place to be at. Zwavejs should never ever ever just auto-delete stuff.

**Comment by AlCalzone** [comment]
FWIW, the removal happens **10 seconds** after the node is dead.

Z-Wave JS definitely doesn't remove devices on its own, except when the device itself sent a `Device Reset Locally Notification`, which means the device has been factory reset by physical interaction and is de facto no longer a part of the network.

Unfortunately, this is impossible to diagnose without driver logs, since the application logs don't include any Z-Wave traffic.

**Comment by karalabe** [comment]
Well, this was at 5AM in the morning, so pretty much nothing happened then, nobody touched it, nor did any autmations run that could have triggered it. Is there a way to enable/collect driver logs so maybe we can have it available next time?

**Comment by AlCalzone** [comment]
zwavejs2mqtt lets you write [driver logfiles](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs) which are rotated every 7 days by default.

**Comment by karalabe** [comment]
Seems the device was excluded. After doing the inclusion dance, it showed up with a new ID without having to exclude or reset it first. Either way have device logs enabled now, but I doubt it will happen again. It's the first time since I started using this project that it happened, over almost a year.

**Comment by AlCalzone** [comment]
Alright, I'm going to close here then. When you have something new, feel free to reopen.

**Comment by karalabe** [comment]
I still think there's a fault somewhere which caused an error to be escalated into exclusion, since everything was idle. But yeah, not much more information to say.

**Comment by AlCalzone** [comment]
Feel free to check yourself. This is the only instance where the driver calls `removeFailedNode` on its own or sends a `RemoveFailedNodeRequest` to the controller:
https://github.com/zwave-js/node-zwave-js/blob/0e4517cb796825f71a1507fb69ef061329334b14/packages/zwave-js/src/lib/driver/Driver.ts#L3024-L3043

And even then, the device must fail to respond to a ping **after** it sent the notification.
