### ISSUE TITLE
Zwaveproducts.com/Zlink WD-100 doesn't ever respond with updated values after turning on or off

### ISSUE THREAD

**Issue by evilpark** [AlCalzone/node-zwave-js#4610]
I noticed this issue was posted a year ago, but the solution wasn't clear.  I'm still having this issue with my WD-100 switches at firmware v50.3, I have one new switch at firmware v50.6 that does in fact work, just not the other 6 switches at the .3 level.

I'm running version 9.2.1 under zwavejs2mqtt version 6.9.0

**Comment by evilpark** [comment]
Disregard, removing and re-adding the device fixed the problem.  Either by running a newer version of zwavejs from before, or updating the firmware on my Zooz 700 series controller.

But it works now!

**Comment by AlCalzone** [comment]
This might have also been fixed by re-interviewing without removing the device
