### ISSUE TITLE
More Zooz devices (ZEN71, maybe ZEN30) fail to interview

### ISSUE THREAD

**Issue by george-compton** [AlCalzone/node-zwave-js#4615]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

I believe this is the same problem as #4585, but in different Zooz products -- ZEN 71 and maybe ZEN30v2 switches.

What causes the bug?
Three Zooz ZEN71 wall switches that I installed over the last few days timed out during interview attempts, though all three eventually succeeded after many re-interviews.

Coincidentally, I updated the firmware on three Zooz ZEN30 switches a week ago, which knocked them off the network.  When I re-included them, it took multiple re-interview attempts before I got successes.

What do you observe?
In the ZWave to MQTT node list, the Interview column would never get to Complete.  I only had the zwavejs2mqtt INFO logging enabled during the most of the ZEN71 interview attempts, but from what I remember, that log consistently reported timeouts while querying for information about configuration parameter 8 (IIRC).  It would retry 5 times, then give up.  I'd request a re-interview, which also typically timed out the same way, but I eventually got at least one re-interview success on all three switches.  

Today, after installing the third ZEN71 switch (and getting many failed interviews again), I discovered issue #4585 and turned on the zwavejs DEBUG logging to see if this problem is similar.  I was able to capture both a failed interview and a successful one.  I see a bunch of those four character messages in the log just before a timeout on the failed attempt.  See timestamp 2022-05-11T21:39:32.779Z for example.  To my untrained eye, that looks like the symptom you describe in 4585.

I am not sure whether the ZEN30 failures had the same symptoms, since it was a week ago, and I can't remember the specifics.  Today, while writing this bug report, I re-interviewed one the ZEN30 switches a few times also to see if I could reproduce the problem there.  I did capture some timeouts and successes, but they don't look the same to me.  If you'd like, I can open a separate bug for them.  

What did you expect to happen?
After the popup telling me about SmartStart inclusion of the new device and after the new node shows up in the ZWave to MQTT node list, then that node's row should show a completed interview and all of the row's other fields (e.g., Manufacturer, Product, Firmware) should show the correct values, all without any manual intervention.  Ditto for after I request a re-interview.  

  1. Install a new ZEN71 switch.
  2. Scan its QR code, and add it to the SmartStart provisioning in the ZWave to MQTT Home Assistant add-on.
  3. Wait for the switch to be added to the network.  Dismiss the "Node XYZ has been added to the network with S2 Authenticated" popup.
  4. Look at the node list (Control Panel tab) and note that the new node's interview never reports complete.  Look at the ZWave to MQTT log and see that the interview timed out five times before giving up.
  5. Request a re-interview in the node's Advanced popup.
  6. Repeat steps 4 and 5 until the stars align and it works.

### Device information

Manufacturer: Zooz
Model name: ZEN71 700 Series On/Off Switch
Node ID in your network: 127

Manufacturer: Zooz
Model name: ZEN30 VER 2.0
Node ID in your network: 117

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Z-Wave JS: 9.0.7
Zwavejs2Mqtt: 6.8.1
Home Assistant Z-Wave JS to MQTT add-on: 0.39.0, installed from the Home Assistant Add-On Store

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwavejs_2022-05-11.log](https://github.com/zwave-js/node-zwave-js/files/8673887/zwavejs_2022-05-11.log)

**Comment by george-compton** [comment]
I also have a ZEN76 switch, but I haven't installed it yet and don't know when I will have a chance.  When I do, I'm guessing I'll see the same symptoms, since it's from the same generation as the ZEN71s.

**Comment by AlCalzone** [comment]
Looks like a duplicate of https://github.com/zwave-js/node-zwave-js/issues/3964. I thought that's a pretty fringe issue but it is **very** reproducible in your log. I'll make sure to prioritize that higher.
