### ISSUE TITLE
Minoston MP21ZP: Parameter 1 labeled incorrectly

### ISSUE THREAD

**Issue by Ragingfire105** [AlCalzone/node-zwave-js#4627]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

The descriptions for values 0 and 1 of parameter 1, LED Indicator, are inverse from the device behavior. 

Value 0 should read, "On when load is on"
Value 1 should read, "On when load is off"

### Device information

Manufacturer: Minoston
Model name: MP21ZP
Node ID in your network: 37

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 0.1.58

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

I don't believe a log file is necessary.

**Comment by dfederm** [comment]
I'll take this as I'm about to send a PR to add config for MP22ZP and noticed this discrepancy.
