### ISSUE TITLE
Add additional CC specific properties to docs

### ISSUE THREAD

**Issue by raman325** [AlCalzone/node-zwave-js#4632]
**Is your feature request related to a problem? Please describe.**
There are CC specific properties which are hard to understand the value of unless you read the code. Looking at the `CCValueOptions` interface, all of the following properties would potentially be useful to add to the documentation:
- internal (might not be that useful if the CC isn't exposed at all outside of the driver)
- minVersion (could help with troubleshooting)
- forceCreation (not sure what this is useful for yet)
- stateful (lets us know whether setValue will trigger a `value notification` or a `value updated` event)
- secret (let's us know that this CC should not be logged - probably not necessary, but it wouldn't hurt)

Ideally, this information could also be queryable by a consumer of the driver and/or added to value metadata so that consumer applications know how to appropriately handle the CC/value. As an example, we know that if a CC is not stateful, it will send `value notification`s, and if the application knows that it can update the UI for that command class accordingly.

**Describe the solution you'd like**
Home Assistant generates template automation triggers for users based on discovery of the values on a Z-Wave JS node. Right now, we have hard coded the templates for `value notification`s for Basic, Central Scene, and Scene Activation CCs, but it would be nice to be able to discover this information dynamically so that we don't fall behind.

I understand that this may be a large ask, so at a minimum it would be nice to at least see this information in the docs so that I don't have to hunt for it in the code.

**Describe alternatives you've considered**
Right now I resort to looking through the code and asking Al

**Additional context**
Add any other context or screenshots about the feature request here. If you want to propose an API, share your thoughts how it could be used (syntax).

**Comment by AlCalzone** [comment]
This should be solved since v10. Can you check if your use-case is supported?
