### ISSUE TITLE
CT101 Thermostat Device Driver Not reporting humidity 

### ISSUE THREAD

**Issue by ur7x** [AlCalzone/node-zwave-js#4643]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?  The ZWave Device Driver for the CT101 thermostat does not report humidity

What do you observe?  Added the Thermostat to ZWave JS and ZWave2MQTT and it reports temperature fine, but there is no defined property/event for Humidity.  There is a setting for humidity sensitivity.  Which should trigger a report, it never reports.

What did you expect to happen?  The thermostat will report temperature and humidity.. 

1 Add Thermostat as a new Zwave  node
2 Check Multi Level Sensor V2 in ZWave2MQTT
3) Only Air Temp... No Humidity report. 

This was reported and a fix was attempted:
https://github.com/zwave-js/node-zwave-js/pull/3079

But on my device this does not work.  

### Device information

Manufacturer: Radio Thermostat
Model name: CT110
Node ID in your network: 2

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:  9.2.2
`zwavejs2mqtt` branch:  0.40.0

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

Device Diagnostics 

[zwave_js-3333c9afebd50ae21deb4c660e5cafa6-Family Room CT101-ed7c91b32e7cd1c5d8740a79fde9e007.json(2).txt](https://github.com/zwave-js/node-zwave-js/files/8734983/zwave_js-3333c9afebd50ae21deb4c660e5cafa6-Family.Room.CT101-ed7c91b32e7cd1c5d8740a79fde9e007.json.2.txt)

Zwave Log

[zwavejs2mqtt_2022-05-19(2).log](https://github.com/zwave-js/node-zwave-js/files/8735180/zwavejs2mqtt_2022-05-19.2.log)

**Comment by ur7x** [comment]
I left both a Log file from the device diagnostics and from Zwave2MQTT 
If a different log file is needed please let me know which one is needed and how to get it. 
Since I'm using the a Zwave2MQTT addon  the ZWave JS integration is not creating a log file (maybe that is the issue?)

**Comment by ur7x** [comment]
[zwavejs_2022-05-20.log](https://github.com/zwave-js/node-zwave-js/files/8742341/zwavejs_2022-05-20.log)

Hi there, I think this is what you need.

**Comment by kpine** [comment]
You should post the driver log that includes a Re-interview of the device. But from the log you did post, there were never any humidity reports.

**Comment by ur7x** [comment]
Got it...  Sorry this Zwave JS  and Zwave2MQTT is a little new to me...  is this the complete and correct log?

[zwavejs_2022-05-20(3).log](https://github.com/zwave-js/node-zwave-js/files/8742501/zwavejs_2022-05-20.3.log)

This is from the ZWave JS start right through a re-interview of the thermostat.

**Comment by elbarsal** [comment]
This is a known quirk in the implementation for that version of device. I had previously sorted a solution on OpenZwave. ZWaveJS does handle the issue appropriately, but it seems you need to get it to listen to all endpoints to read the humidity (as duplicate endpoints get ignored).

My solution was to copy the default CT101 config file into config\0x0098\ and modify the file, adding a line to the "compat" section to preserve endpoints, like this:

`
"compat": {
                // The device has two endpoints. The temperature gets reported via the root, humidity is on endpoint 2.
                "preserveEndpoints": "*",
                "mapRootReportsToEndpoint": 1
        }`

I may have added too much (preserving * is non-selective) but it works. I am currently polling the value, but I think it may even notify on changes as well (I haven't stopped polling it).

Quick note - it does appear that only the version with productID 0x000d has this issue (at least for me - I have two different versions of this device) so my custom config file only lists that version.

**Comment by ur7x** [comment]
> 



> My solution was to copy the default CT101 config file into config\0x0098\ and modify the file, adding a line to the "compat" section to preserve endpoints, like this

Can I get a little more info on your solution.  I found the current ct101.json file at https://github.com/zwave-js/node-zwave-js/blob/cd1995e49724edd1c284ea901b9c15865f22e8cb/packages/config/config/devices/0x0098/ct101.json

I added it to the "config\0x0098' directory is that within the storage section of Zwave JS

Once that is done I restarted the Zwave JS service? And now it is using the local driver...  
Is that right?

And yes my device ID is also 0x00d (13) 

I will make your suggested change and see what it does.

*EDIT*

Sadly, preserve end points didn't work with my thermostat. 
I can verify that Zwave JS is using the local device driver.

*EDIT again*

After performing a re-interview of the node and it now reports Temp and  Humidity

**Comment by AlCalzone** [comment]
> My solution was to copy the default CT101 config file into config\0x0098\ and modify the file, adding a line to the "compat" section to preserve endpoint

Hm, the device classes for the affected variant are probably different from the one I originally added the fix for.
We now have the ability to selectively apply compat flags to certain variants included in a config file:
https://github.com/zwave-js/node-zwave-js/pull/4501

Would you be willing to open a PR that adds the `preserveEndpoints` flag for productID 0x000d?
Otherwise, I can do this on monday.

**Comment by ur7x** [comment]
I have tried various "Compat" variables including the recommendation above and none will get the Thermostat to report humidity.
Do we need to manually define the two End Points?

**Comment by ebarsaloucc** [comment]
I didn't need to do so - but I did need to re-interview the device - have you done so?

Edit: Didn't need to add anything manually, I mean. If you interview the device, when you look in your logs it gives a message about ignoring duplicate endpoints (I forget the exact text, I'm sorry) and that is what the preserve endpoints solves. 

I did add humidity polling for the device after it was discovered though, using the General configuration. Before using preserve endpoints, the humidity command class was not available for that device.

Second edit for ur7x - I see in your log dump you had the same issue I had ("2022-05-20T17:50:35.228Z CNTRLR   [Node 002] Endpoints seem unnecessary b/c they have different device classes, ignoring all...") - if you re-interview, that should not be there, but perhaps you do have to poll. I haven't tried not polling - I like getting readings at least every 10 minutes - but I will try.

I verified that I was using the modified configuration by changing the device name, and it does show up for me.

**Comment by ur7x** [comment]
Re-interview WORKED... 

Funny with each JSON edit I would only see it applied if I restarted Zwave JS...  Never thought to re-interview. 

Re interview with the suggested json change and Humidity is now reporting!  Thanks.

**Comment by AlCalzone** [comment]
> Never thought to re-interview.

It's mentioned in the documentation for the custom config files though 😉

https://zwave-js.github.io/zwavejs2mqtt/#/device-support/custom-device-files?id=using-custom-device-configuration-files

▶️ Second big blue box
