### ISSUE TITLE
Missing device configuration: Fakro ARF Solar

### ISSUE THREAD

**Issue by szeryf85** [AlCalzone/node-zwave-js#4644]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Fakro ARF Solar

### Manufacturer ID

0x0085

### Product Type

0x0004

### Product ID

0x0012

### Firmware Version

1.1

### Is the device listed on the Z-Wave Alliance website?

No

### Do you have a manual?

[ARF_FAKRO_instrukcja_uzytkowania.pdf](https://github.com/zwave-js/node-zwave-js/files/8740378/ARF_FAKRO_instrukcja_uzytkowania.pdf)

**Comment by AlCalzone** [comment]
Is there an English manual? 😅

**Comment by szeryf85** [comment]
> Is there an English manual? 😅

I can't find in English :(

**Comment by OXINARF** [comment]
https://www.fakro.com/att/COMMON/offer/servis/user_manuals/EN/ARF-ARF-D-ARP-SOLAR_EN.pdf

I don't know Polish and didn't compare the two completely but this seems to be it.

**Comment by szeryf85** [comment]
Yes, this manual is correct.

**Comment by futurexdesign** [comment]
Looking at the parameters in the manual, the device takes the same configuration values, and association groups as the ARZ ZWave Solar:  https://devices.zwave-js.io/?jumpTo=0x0085:0x0003:0x0112:0.0

@AlCalzone Would the appropriate fix be to add this product type & product ID to that existing config file, or to create a new one with the same parameter details?

**Comment by AlCalzone** [comment]
@futurexdesign To avoid confusion between ARF/ARZ/... variants, I'd make a copy of the file and change label and product type/id in the copy.
