### ISSUE TITLE
Problem with Fibaro Smart Module (Double)  FGS214 & FGS224

### ISSUE THREAD

**Issue by faustinio** [AlCalzone/node-zwave-js#4646]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Both devices are marked as "unknown product" in the control panel (despite the fact that they are in the database of devices ZwaveJS)

![2022-05-22_20-21-06](https://user-images.githubusercontent.com/31499553/169707536-38b9ef64-0f6f-4c92-8186-f8b281644358.png)

### Device information

Manufacturer: Fibargroup (0x010f)
Model name: Smart Module (0x0404) / Double Smart Module (0x0204) 
Node ID in your network: 7, 8, 10, 11, 14, 15, 22, 26 

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 9.2.2
`zwavejs2mqtt` branch: 6.9.1

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[zwavejs_2022-05-22.log](https://github.com/zwave-js/node-zwave-js/files/8749917/zwavejs_2022-05-22.log)

**Comment by AlCalzone** [comment]
We actually don't have these fingerprints yet.
