### ISSUE TITLE
Node inclusion fails

### ISSUE THREAD

**Issue by klontje85** [AlCalzone/node-zwave-js#4653]
Hello,

I have been setting up a new controller (Aeon Z-Stick 7 with latest firmware) with zwavejs2mqtt. I have succesfully included 9 nodes into my network, but now I have 2 nodes left that will not be accepted. I get the error "Node inclusion failed" after I put the device in inclusion mode. The debug log (relevant entries) is attached. Any idea as to what causes this issue?

[zwavejs2mqtt-debug.log](https://github.com/zwave-js/zwavejs2mqtt/files/8775408/zwavejs2mqtt-debug.log)

zwavejs2mqtt: 6.10.0
zwave-js: 9.3.0

**Comment by robertsLando** [comment]
@AlCalzone

**Comment by AlCalzone** [comment]
Please make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` or `silly` and attach it here as a file.

**Comment by klontje85** [comment]
Please find both logs attached. I disabled logging, deleted old logs, re-enabled logging, and started the inclusion.

[zwavejs2mqtt-store.zip](https://github.com/zwave-js/node-zwave-js/files/8778512/zwavejs2mqtt-store.zip)

**Comment by klontje85** [comment]
I was able to include a Fibaro relay module, but unable to include any of the three remaining Qubino modules (of which I already have 8 of them that did successfully include). Node ID numbering did go up with every (failed) attempt as the Fibaro module got assigned ID 17 and the last successful module before that was 11.

**Comment by klontje85** [comment]
@AlCalzone I was able to include another Qubino module, the only modules that are still failing are all of the same type: https://qubino.com/mini-dimmer-tech-2/. I have tried including a new one which worked find but was <1m away from the controller. The other modules are about 10m away from the controller but no concrete or steel in between.

**Comment by AlCalzone** [comment]
> 2022-05-26T11:08:19.455Z CNTRLR   handling add node request (status = Failed)

This is all zwave-js sees from the inclusion attempt. This means there is something wrong during the protocol-level communication during the inclusion attempt, where the driver is not yet involved.

Did you follow the general troubleshooting yet?
https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting

**Comment by klontje85** [comment]
@AlCalzone I did, my controller is on a 3m passive USB extension cord away from interference. I have just ordered a 20m active USB extension cable and will try to bring the controller next to the module that fails to include and re-try. It does seem weird there is no reason provided, and would expect inclusion to not even be attempted if it were out of range.

**Comment by AlCalzone** [comment]
I don't think it is out of range. Maybe the end device is affected by interference and not the stick? Unfortunately without a Zniffer, you won't be able to see what is being exchanged and what isn't. 

> will try to bring the controller next to the module that fails to include and re-try

Although this might be an option, do know that this should not be done regularly: https://github.com/zwave-js/node-zwave-js/issues/1995
