### ISSUE TITLE
Crashes with Timeout when during Inclusion after an Exclusion

### ISSUE THREAD

**Issue by iklein99** [AlCalzone/node-zwave-js#4654]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
If I exclude a device, then turn around and start Inclusion, then press the button on the device, after about 30 seconds, I get an unhandled exception.
What do you observe?
I get this message: "ZWaveError: Timeout while waiting for a callback from the controller (ZW0200)
    at Driver.sendMessage (/Users/iklein99/Library/Mobile Documents/com~apple~CloudDocs/Node/raz-hub/node_modules/zwave-js/src/lib/driver/Driver.ts:3525:23)"

Nothing shows up in the logs (debug mode).  Last entry there is "Starting inclusion process with strategy Default..."
What did you expect to happen?
The inclusion to succeed, or timeout gracefully.

1. Exclude a device
2. Put into Inclusion mode
3. Press button on device
4. Wait about 30 seconds
[error.txt](https://github.com/zwave-js/node-zwave-js/files/8779282/error.txt)
[zwavejs_2022-05-26.log](https://github.com/zwave-js/node-zwave-js/files/8779286/zwavejs_2022-05-26.log)

### Device information

Manufacturer: Z stick:  Zooz, 
Model name: S2 Stick 700
Node ID in your network: 1 

Note - reproduced with 2 different devices, both binary switches

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [X] Other _(please describe)_

### Which branches or versions?

I installed the library with npm.  I'm building my own code.

version:
`node-zwave-js` branch: 9.3.0

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[zwavejs_2022-05-26.log](https://github.com/zwave-js/node-zwave-js/files/8779344/zwavejs_2022-05-26.log)

**Comment by AlCalzone** [comment]
This is thrown as an error in the `stopExclusion` method you're calling from application code:
```
ZWaveError: Timeout while waiting for a callback from the controller (ZW0200)
    at Driver.sendMessage (/Users/iklein99/Library/Mobile Documents/com~apple~CloudDocs/Node/raz-hub/node_modules/zwave-js/src/lib/driver/Driver.ts:3525:23)
    at ZWaveController.stopExclusion (/Users/iklein99/Library/Mobile Documents/com~apple~CloudDocs/Node/raz-hub/node_modules/zwave-js/src/lib/controller/Controller.ts:1627:22)
    at ZwaveManager.stopExclusion (/Users/iklein99/Library/Mobile Documents/com~apple~CloudDocs/Node/raz-hub/src/zwave/ZwaveManager.ts:363:44)
```

All these methods interacting with the stick can throw and you need to catch errors in application code.

> Timeout while waiting for a callback from the controller (ZW0200)

means that the Z-Wave stick was not responsive and did not reply with an expected callback. This often indicates that the stick is in a bad state, which usually cannot be handled gracefully.

**Comment by iklein99** [comment]
Thanks.  Not sure how I missed that but I do see that in the backtrace.
