### ISSUE TITLE
[Bug]: Zooz Zen72  with v10.0 fails inclusion

### ISSUE THREAD

**Issue by laheym** [AlCalzone/node-zwave-js#4659]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.11.0

### ZwaveJS version

9.3.0

### Describe the bug

Zooz Zen72 Dimmer Switch with latest v10.0 cannot be included.  It always gets stuck at NodeInfo. 

Using Zooz ZST10-700 zwave controller updated to v7.17.2 firmware.  Zwavejs2mqtt running in container on rpi 3 / rasberry pi os lite 64bit v11
![Screenshot 2022-05-28 013931](https://user-images.githubusercontent.com/96606874/170813773-6d389cd4-8f4e-4ccb-aa72-e7c5413aef61.png)
[zwavejs2mqtt-store (3).zip](https://github.com/zwave-js/zwavejs2mqtt/files/8790641/zwavejs2mqtt-store.3.zip)
.

### To Reproduce

- start inclusion with Web UI with S2
- start inclusion on Zooz Zen72 switch
- accept security choices and enter dsk key

### Expected behavior

Inclusion should succeed

### Additional context

I'm willing to loan (or donate) a switch if it helps.

**Comment by laheym** [comment]
I am able to include other zwave devices (zooz zen34, zooz zen30, etc) without issue.  But am having issues with Zen72 (and I think zen76).

**Comment by AlCalzone** [comment]
I'm not seeing any reference to that node in the log you posted. Please make another driver log, re-interview the node and then post the log. I don't need the zwavejs2mqtt logs.

**Comment by laheym** [comment]
I've subsequently tried to include many additional nodes.  It's seems that the issue may be with the 10.0 firmware from Zooz.  v1.3 on zen77 and zen76s work the first try, but after upgrading to v10, I get the same failed interviews.

with the zen72, etc on v10 firmware, I am eventually able a successful interview the.  I am able to do this by completing the following in various order, sometimes multiple times each: restart of the container, soft reset the controller and reinterview the node. I have not yet isolated a sequence that will reliably interview the noded

**Comment by laheym** [comment]
> I'm not seeing any reference to that node in the log you posted. Please make another driver log, re-interview the node and then post the log. I don't need the zwavejs2mqtt logs.

it's Node 28 in the original logs.  I will repeat on another zen72 and give you that log,

**Comment by laheym** [comment]
I am including two nodes that fail interviews.  The first (Node37) is a Zen 77 that I successfully included with v1.3 firmware on the first attempt, but when I upgraded the firmware to 10.10 it attempted to reinterview and failed.  I have repeatedly tried to reinterview, reset the container, reset the controller, but it is stubbornly stuck at nodeinfo.   the second (node38) is a zen 72 that came from the factory with firmware 10.0.  Like other v10 zen72s that I have tried to include it fails the interview.

![Screenshot 2022-05-31 010216](https://user-images.githubusercontent.com/96606874/171103487-f8683a7d-142e-41bb-ab88-7580fd46b74a.png)
[zwavejs2mqtt-store (4).zip](https://github.com/zwave-js/node-zwave-js/files/8802438/zwavejs2mqtt-store.4.zip)

**Comment by AlCalzone** [comment]
Ok it looks like this is caused by the same issue that https://github.com/zwave-js/node-zwave-js/pull/4595 works around. https://github.com/zwave-js/node-zwave-js/issues/4585#issuecomment-1121140769 has an explanation.

So, this workaround needs to be applied for Zen72, 76 and 77 too, did I forget anything?

**Comment by laheym** [comment]
those are the three devices that I have been with this issue, thanks!

**Comment by kaechele** [comment]
There is a newer version of the firmware available. Maybe this issue is fixed there.
Oddly, the version number is 2.0 (released in May 2022, whereas 10.0 was released in June 2021).
See: https://www.support.getzooz.com/kb/article/849-zen72-700-series-dimmer-change-log/

**Comment by laheym** [comment]
> There is a newer version of the firmware available. Maybe this issue is fixed there.

that is a pretty odd versioning scheme. - I guess it's to keep in sync with the HW version.
