### ISSUE TITLE
Vision 4in1 Multisensor issues

### ISSUE THREAD

**Issue by larrygoodstuff** [AlCalzone/node-zwave-js#4687]
I have a Vision 4in1 Multisensor that worked fine in the old Zwave integration in Home assistant, but is not fully identified in Zwave JS. Wondering if it needs to be added to the database? I've attached the manual. Anyone else having issues?
[vision_4in1_door_window_sensor.pdf](https://github.com/zwave-js/node-zwave-js/files/8831271/vision_4in1_door_window_sensor.pdf)

**Comment by marcus-j-davies** [comment]
Hi @larrygoodstuff,

if this is missing from the DB, we somewhat need more information to be able to help.
Please could you follow the issue template here, or log it under the **bug report** template, if its found on the DB

![image](https://user-images.githubusercontent.com/55892693/172000290-e1c2f808-9e26-4ce5-86a8-b71f6d3cf0e4.png)
