### ISSUE TITLE
[Bug]: Zooz ZSE44 sensor is inconsistently identified by zwavejs

### ISSUE THREAD

**Issue by laheym** [AlCalzone/node-zwave-js#4703]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.12.0

### ZwaveJS version

9.3.0

### Describe the bug

Zooz ZSE44 are reported as unknown manufacturer/product after initial inclusion. 
Sometimes (but not always) they are correctly identified after repeatedly re-interviewing them.
This seems somewhat similar to zwave-js/node-zwave-js#4659, but with this issue, the interview completes, but device isn't identified.

In my example Node 48 and 49 are both the same device (ZSE44) and were both listed as "Unknown Manufacturer" / "Unknown Product" after inclusion.  Eventually I was able to get Node 48 to be identified after serval re-interviews.  I can't seem to get Node49 to work no matter how many times I try the re-interview.
 
![zwavejs2mqtt_screenshot](https://user-images.githubusercontent.com/96606874/172942774-35955751-ceee-41fe-b9af-fe50954501f5.png)
[zwavejs2mqtt-store (6).zip](https://github.com/zwave-js/zwavejs2mqtt/files/8873932/zwavejs2mqtt-store.6.zip)

### To Reproduce

try to include a ZSE44

### Expected behavior

ZSE should be correctly identified on the first inclusion attempt

### Additional context

Nodes are in direct range of zst10-700 stick connected by usb extension cable to rpi 3b+. Running zwavejs/zwavejs2mqtt:latest image with docker-compose on rasberry pi os lite arm64 bullseye

**Comment by laheym** [comment]
I tried applying zwave-js/node-zwave-js#4666 with partial success.  Re-interview of node 49 still failed, but it was identified when I excluded and re-included (as Node 50), However FW is still listed as undefined.

updated screenshot and logs attached for comparison with and without zwave-js/node-zwave-js#4666 workaround.

![zwavejs2mqtt_screenshot_zse44-2](https://user-images.githubusercontent.com/96606874/172948608-8c1e48eb-3b0a-46db-a1f4-d31b51ed3e68.png)
[zwavejs2mqtt-store (9).zip](https://github.com/zwave-js/zwavejs2mqtt/files/8874088/zwavejs2mqtt-store.9.zip)

**Comment by AlCalzone** [comment]
Honestly, I have no clue what the hell is going on here. The device seems to randomly not understand S2-encrypted commands.

The communication is a bit like this:
```
zwave-js -> node

-> encrypted command
<- response to encrypted command

-> next encrypted command
<- could not decode

[... establish shared secret again ...]

-> encrypted command
<- response to encrypted command

-> next encrypted command
<- could not decode 🤷🏻
```

Meanwhile some commands from the node are re-transmitted, which might indicate connectivity issues. I have my test stick plugged directly into USB3 ports on my laptop (worst case!), a test sensor is plugged into a different USB port on a different PC and yet I'm getting ACK RSSI in the order of -75 dBm. Yours are at -90 for direct range and -107 when routing through node 29 - no clue why it chooses that route. That might be a tad close to the background noise. Can you perform a health check for the node (network map, click node, click on health check button in the dialog) and post the results?

Also, it seems you're running into https://github.com/zwave-js/node-zwave-js/issues/3964 aswell. Which exact stick do you have? Wonder if that is actually the Zooz 700 series stick? AFAIK zst10-700 gets shown for all 700 series sticks.

**Comment by laheym** [comment]
The stick is labed as a "Zooz s2 stick 700 zst10 700"

It's pretty weird.  Earlier today , I couldn't get a health check to even finish on Node 48 OR 49.  And when I tried other nodes (between neighbors and with the zooz stick) they would finish with 0/10 heath. I did a reset of the container host (rpi) and power cycled the stick (by temporarily disconnecting it).  now both ZSE44 nodes heath statuses are completing with reasonable results.

I'm attaching a picture of my testing setup for node 48. (normally it's mounted on the wall in a central location). node 49 is mounted in the bathroom (with door open) about 10 feet away.  AFAIK except for the zwave network there are no other 900 mhz radios in my house.

Do you think I should try buying a new zwave stick? Do you have any other recommendations? and other diagnostic tests,


![PXL_20220611_004325643](https://user-images.githubusercontent.com/96606874/173169998-b8272afb-c676-440b-ac21-537c52e051d4.jpg)

![Screenshot 2022-06-10 215022](https://user-images.githubusercontent.com/96606874/173170004-bff99dec-c8c0-4fa8-ae48-fc206af36d3b.png)


![Screenshot 2022-06-10 220536](https://user-images.githubusercontent.com/96606874/173170273-376fc412-929d-4cd1-86eb-c6103f148d8d.png)

**Comment by Botched1** [comment]
I have eight zse44, but I haven't seen this issue - likely because all of mine are paired with no security.

I only pair perimeter security devices with security (in general).

**Comment by AlCalzone** [comment]
> they would finish with 0/10 heath

It would be interesting to know what caused this result. Latency, failures, SNR, commands not being sent at all?

> now both ZSE44 nodes heath statuses are completing with reasonable results.
> node 49 is mounted in the bathroom (with door open) about 10 feet away. AFAIK except for the zwave network there are no other 900 mhz radios in my house.

You mention 48 and 49, but posted a screenshot of 50, I'm assuming thats the one in the bathroom? The SNR margins are pretty low (should be above 17 dBm), despite the other measurements being good. That means there is either a lot of noise or the node has a borderline connectivity and the slightest additional noise will lead to dropped packets.

There could be other sources of interference, e.g. water heater or other electrical devices near the nodes. Maybe the device is located somewhere where there is a lot of metal between it and the stick or near to it, causing reflections?

**Comment by laheym** [comment]
> There could be other sources of interference, e.g. water heater or other electrical devices near the nodes. Maybe the device is located somewhere where there is a lot of metal between it and the stick or near to it, causing reflections?

ahhh - I hadn't even thought about reflections.  The sensor is literally mounted to a large mirror in the bathroom.  I imagine that would cause a strong reflection with an offset of ~5mm / c  (the thickness of the glass + double sided tape + the back of the enclosure).  

When I get a few minutes I will test the SNR Ratio at with different mounting locations and post the results.

> The device seems to randomly not understand S2-encrypted commands.

Would radio issues cause this behavior? (I would have thought we would see modem errors - not decryption errors)

**Comment by AlCalzone** [comment]
If there are radio issues on the device, individual bits might get flipped in a way that the packet still has a correct checksum, and gets identified as an S2 encapsulation command, but the command fails to decrypt.

Can't verify this for certain though since we don't have access to the raw data the device receives.
