### ISSUE TITLE
qubino mini dimmer 

### ISSUE THREAD

**Issue by gbone001** [AlCalzone/node-zwave-js#4712]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

QUBINO mini dimmer

### Manufacturer ID

0x351

### Product Type

0x8458

### Product ID

0x4867

### Firmware Version

1.2

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4479

### Do you have a manual?

[Qubino_Mini Dimmer PLUS installation manual_eng_multilanguage_A4_ENFRDESV_5.2.pdf](https://github.com/zwave-js/node-zwave-js/files/8903603/Qubino_Mini.Dimmer.PLUS.installation.manual_eng_multilanguage_A4_ENFRDESV_5.2.pdf)

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4479 from zwa

**Comment by AlCalzone** [comment]
@gbone001 it doesn't look like the entry in the ZWA DB matches the IDs you posted. That one resolves to a device we already have a file for.

**Comment by darkbasic** [comment]
Don't we really have an entry for Qubino Mini Dimmer? I briefly tested a couple of them and I remember it was fine, maybe my memory is failing me though...

**Comment by AlCalzone** [comment]
closing due to lack of information
