### ISSUE TITLE
Zen30 physical switch doesn't update zwavejs binary switch

### ISSUE THREAD

**Issue by rosskyl** [AlCalzone/node-zwave-js#4724]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
When I press the bottom switch on a zooz Zen30 the value isn't updated in zwavejs2mqtt or home assistant. I can control it just fine from those two places. I think the switch is sending the updated value to 57-38-1 while the zwavejs is looking for 57-37-0.
What do you observe?
Pressing the bottom switch on a zen30 doesn't update the value/binary switch.
What did you expect to happen?
The binary switch should show on when I press the bottom switch.
  1. Ensure the switch is off both physically and in software
  2. Press the bottom switch
  3. Home assistant and zwavejs2mqtt/zwavejs are not updated

### Device information

Manufacturer: Zooz
Model name: Zen30
Node ID in your network: Node 57
Switch firmware: 3.0

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: zwavejs2mqtt version 6.12.0 zwavejs version 9.3
`node-zwave-js` branch:
`zwavejs2mqtt` branch: Latest (6.12.0)

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

I believe it worked on previous firmware versions of the switch

### Attach Driver Logfile

[zwavejs_2022-06-20.log](https://github.com/zwave-js/node-zwave-js/files/8942125/zwavejs_2022-06-20.log)

**Comment by rosskyl** [comment]
Issue might be related to https://github.com/zwave-js/node-zwave-js/issues/2536.

**Comment by AlCalzone** [comment]
Possibly a duplicate of https://github.com/zwave-js/node-zwave-js/issues/4715

I'm waiting for confirmation from Zooz how the endpoints are supposed to work here.

**Comment by AlCalzone** [comment]
This should be fixed by #4736

To test, follow the instructions at https://zwave-js.github.io/zwavejs2mqtt/#/device-support/custom-device-files

you'll need these files in the custom config folder:
- [zen30.json](https://raw.githubusercontent.com/zwave-js/node-zwave-js/b27d403f815b66acdee91181458015bb5a90d0dc/packages/config/config/devices/0x027a/zen30.json)
- [templates/master_template.json](https://raw.githubusercontent.com/zwave-js/node-zwave-js/master/packages/config/config/devices/templates/master_template.json)
- [templates/zooz_template.json](https://raw.githubusercontent.com/zwave-js/node-zwave-js/master/packages/config/config/devices/0x027a/templates/zooz_template.json)

The 2nd and 3rd go into a new subdirectory `templates` if that was not obvious.

Don't forget to re-interview the device.

**Comment by rosskyl** [comment]
That kind of solves the issue. I've not got 2 binary switches and 1 multi level switch. In the image below, the light is the multi level switch which works as intended. The fan is the original binary switch. The light/fan is the new switch added from this custom config.
Both the fan and light/fan control the physical switch. Only the light/fan switch responds to the physical switch press. When I toggle the fan switch, the light/fan switch also toggles. But when I toggle the light/fan switch, the fan switch does not respond.
Was this intended to work this way to keep it backwards compatible with the previous firmware?

![image](https://user-images.githubusercontent.com/9472151/175043404-f33a1904-d536-4c28-a5f3-9352d476c292.png)

**Comment by rosskyl** [comment]
In addition to that, the light/fan is not available right away until either the virtual switch or the physical switch are toggled.

**Comment by AlCalzone** [comment]
can you share some driver logs? Interview and operating the device. The latter ideally with comments what you did when. We might have to change how the associations are created too.

I'm afraid you will have to live with the one switch being doubled, because Zooz aren't following the specs here.
The dimmer is only available via the root device, the switch is on endpoint 1 (and mirrored on the root device), kinda half and half.
As I wrote in https://github.com/zwave-js/node-zwave-js/issues/4715, they really should have put both on one endpoint each and have the root device mirror both.

**Comment by rosskyl** [comment]
Attached is the log file. It seems in home-assistant the switch shows as unavailable the first time you interview it but after toggling the original switch the new switch becomes available even after re-interviewing. So it's a one time thing to deal with. Ideally there would only be one switch but I understand that can't be the case. They should be synced up though or one of them disabled and/or labeled.
[zwavejs2mqtt_2022-06-22.log](https://github.com/zwave-js/node-zwave-js/files/8958724/zwavejs2mqtt_2022-06-22.log)

**Comment by AlCalzone** [comment]
Thats not a driver log. You posted the correct file when opening the issue, so I didn't link to the instructions again. Anyways, here they are:
https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs, loglevel `debug` or `silly`

**Comment by blhoward2** [comment]
> That kind of solves the issue. I've not got 2 binary switches and 1 multi level switch. In the image below, the light is the multi level switch which works as intended. The fan is the original binary switch. The light/fan is the new switch added from this custom config. Both the fan and light/fan control the physical switch. Only the light/fan switch responds to the physical switch press. When I toggle the fan switch, the light/fan switch also toggles. But when I toggle the light/fan switch, the fan switch does not respond. Was this intended to work this way to keep it backwards compatible with the previous firmware?
> 
> ![image](https://user-images.githubusercontent.com/9472151/175043404-f33a1904-d536-4c28-a5f3-9352d476c292.png)

This is sort of how it will work in HA with the root endpoint preserved. You normally need to disable the fan/switch one which should turn on if either of the other endpoints is on. But the correct endpoint should still be toggling when the switch is manually changed.

**Comment by AlCalzone** [comment]
I'm more concerned about this:
> It seems in home-assistant the switch shows as unavailable the first time you interview it but after toggling the original switch the new switch becomes available even after re-interviewing.

**Comment by rosskyl** [comment]
Unfortunately I can't reproduce the issue. I think it's a one time issue that's fixed by toggling either the virtual switch or the physical switch. I can still send you a device log but I don't think it will show much.

**Comment by AlCalzone** [comment]
Does it stay even if you re-interview? Then it might have been a temporary fluke.

**Comment by rosskyl** [comment]
Yes it does stay after I re-interview. I think it was something from when the custom config was first added.
