### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by anonymous66va** [AlCalzone/node-zwave-js#4729]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

PKG executable

### Zwavejs2Mqtt version

0.43.0

### ZwaveJS version

0.1.61

### Describe the bug

Fibaro FgK101 no longer work.
They were perfect before the last update.
I have many nodes but only FGK101 stuck during the interview process.
I've tried everything :
wakeup / exclude & reinclude , but nothing , the behavior is always the same (the interview stucks in an infinite loop).
Please avoid suggesting any actions described above. I have tried everything and more
![ScreenHunter 408](https://user-images.githubusercontent.com/85165779/174777996-f5684bdf-e130-4dc3-8097-e077c11090b7.jpg)
.

### To Reproduce

Update the software at the last release.

### Expected behavior

This is clearly a bug. I expect everything to work as it did before the latest release.

### Additional context

It would be much appreciated an option to abort the interview procedure.

**Comment by robertsLando** [comment]
@anonymous66va please attach zwavejs driver logs

**Comment by AlCalzone** [comment]
What @robertsLando said.

And the information from previous interview shouldn't just get forgotten, which it did here. Looks like somehow your upgrade caused the cache files to get lost. I'd look into that if I was you.

**Comment by anonymous66va** [comment]
[zwavejs_2022-06-24.zip](https://github.com/zwave-js/node-zwave-js/files/8984405/zwavejs_2022-06-24.zip)
Here the log file  for nodes 40 , 41 ,48

**Comment by AlCalzone** [comment]
I don't know what you did to your log, but this only includes the raw serial data, no human-readable interpretation. If you have any filters on, disable them please and try again. Please delete the existing logfile before starting and make sure to re-interview at least one of the problematic nodes while the log is being made.

**Comment by anonymous66va** [comment]
> I don't know what you did to your log, but this only includes the raw serial data, no human-readable interpretation. If you have any filters on, disable them please and try again. Please delete the existing logfile before starting and make sure to re-interview at least one of the problematic nodes while the log is being made.

Ciao , what am I doing wrong ?
Thanks a lot
![ScreenHunter 409](https://user-images.githubusercontent.com/85165779/175921398-590e817a-476f-43e2-a849-ff781d688497.jpg)

**Comment by AlCalzone** [comment]
Remove these:
![image](https://user-images.githubusercontent.com/17641229/175924965-2d09614f-b6b9-4de9-9e54-421680e0cb21.png)

**Comment by anonymous66va** [comment]
> Remove these: ![image](https://user-images.githubusercontent.com/17641229/175924965-2d09614f-b6b9-4de9-9e54-421680e0cb21.png)

I add node 3 & 40 just to have a filter on the problematic nodes.
I will follow your suggestion:
BR
antonio

**Comment by anonymous66va** [comment]
Ciao , as per your request I removed nodes 3 & 40 & tried to re-interviewed node 64.
I attach the log result.
I don't know where to check if the filer log is still working.
BR
antonio
[zwavejs_2022-06-27(1).log](https://github.com/zwave-js/node-zwave-js/files/8991887/zwavejs_2022-06-27.1.log)

**Comment by AlCalzone** [comment]
Ok, so the issue is that your devices report bogus alarm sensor types:
```
2022-06-27T11:05:45.096Z CNTRLR   [Node 064] [~] [Alarm Sensor] supportedSensorTypes: 8, [Endpoint 0] [internal]
                                  9,17,24,32,34,42 => 8,9,17,24,32,34,42
2022-06-27T11:05:45.097Z SERIAL » [ACK]                                                                   (0x06)
2022-06-27T11:05:45.098Z DRIVER « [Node 064] [REQ] [ApplicationCommand]
                                  └─[AlarmSensorCCSupportedReport]
                                      supported sensor types: unknown (0x08), unknown (0x09), unknown (0x11), un
                                  known (0x18), unknown (0x20), unknown (0x22), unknown (0x2a)
2022-06-27T11:05:45.101Z CNTRLR « [Node 064] received supported sensor types: 
                                  · unknown (0x08)
                                  · unknown (0x09)
                                  · unknown (0x11)
                                  · unknown (0x18)
                                  · unknown (0x20)
                                  · unknown (0x22)
                                  · unknown (0x2a)
```
and these break a stricter validation of API method arguments I put in place a while ago. I'll just tone down the strictness of that check in the next release, don't think it makes much sense to work around this.
