### ISSUE TITLE
RFC: Automatic firmware updates

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#4739]
This is meant to discuss the process for authoring the information for automatic firmware updates and actually doing them

## 1. Config file location

There are two options here:

1. Use the current configuration files and add firmware update information.  
   The downside is that these often span multiple different devices with identical behavior, which could require complex conditions to define available firmware updates. Also, changes in zwave-js might be blocking.  
   The upside is that they are "in plain sight".

2. Use a separate repo to store the firmware update information. This leaves more breathing room to do changes and probably make deploys easier.

## 2. Config file format

I suggest a format that is similar to the current zwave-js config files:

```jsonc
{
	// Each "devices" entry defines a single device for which this file
	// contains the available firmware updates.
	"devices": [
		{
			// The brand and label are used to display the information to end users
			// and allow them to double-check
			"brand": "Coolio",
			"label": "Z-Dim 7",

			// These are required to identify the device
			"manufacturerId": "0x1234",
			"productType": "0xabcd",
			"productId": "0xcafe",

			// The firmware version range is optional, the default is 0.0 - 255.255
			// This can be used to split the definitions into multiple files
			"firmwareVersion": {
				"min": "0.0",
				"max": "255.255"
			}
		}
		// ... more devices which support the same firmware updates
	],

	// Each entry in "firmwares" defines a single available firmware update
	"firmwares": [
		{
			// Each entry can further limit the conditions under which it is applicable.
			// Non-matching upgrades will not be offered.
			//
			// The syntax is the same as in https://zwave-js.github.io/node-zwave-js/#/config-files/conditional-settings?id=conditional-configuration-settings
			// This field is optional
			"$if": "firmwareVersion >= 1.1 && firmwareVersion < 1.7 && productId === 0xcafe",

			// The version field MUST indicate the version of the new firmware
			"version": "1.7",
			// The changelog field will be displayed to the user and is purely informational
			"changelog": "* Fixed some bugs\n*Added more bugs",

			// Optionally define the target chip. If not defined, target 0 will be used
			"target": 0,

			// The url MUST point to a publicly downloadable file in one of the supported
			// formats, e.g. ota, otz, hex, hec, gbl, etc.
			// Z-Wave JS will download this in the background when doing an upgrade.
			"url": "https://example.com/firmware/1.7.otz",
			// The integrity field contains an SHA-256 hash of the file
			// to verify that the correct file was downloaded
			"integrity": "cd19da525f20096a817197bf263f3fdbe6485f00ec7354b691171358ebb9f1a1"
		},
		{
			// Devices with multiple firmware targets can define
			// multiple downloads in a single entry.
			// The updates are applied in the order they are defined.

			// The version field MUST indicate the version of the new firmware
			"version": "1.7",
			// The changelog field will be displayed to the user and is purely informational
			"changelog": "* Fixed some bugs\n*Added more bugs",

			"files": [
				// Update chip 1 first
				{
					"target": 1,
					"url": "https://example.com/firmware/1.7_target1.otz",
					"integrity": "..."
				},
				// then chip 0
				{
					"target": 0,
					"url": "https://example.com/firmware/1.7_target0.otz",
					"integrity": "..."
				}
			]
		}
		// ... more firmware updates for the same file
	]
}
```

The files will be placed in a directory structure that separates by manufacturer. We will not enforce file name rules, but the following is suggested:

```
<manufacturer_name>/<brand>_<label>[_<version-or-range>].json
```

e.g.

```
coolioproducts/coolio_z-dim7.json
coolioproducts/coolio_z-dim7_1.1-1.6.json
```

## 3. Querying possible upgrades

The above will be exposed as a web service, e.g. under `https://firmware.zwave-js.io/api/v1/`. This service will be deployed on every push to the `master` branch.

The API must be versioned in order to be able to serve older versions of the driver, even if there is an upgrade to the schema.

This API will parse the above config files and respond to queries, e.g.:

```
POST https://firmware.zwave-js.io/api/v1/ HTTP/1.1
Content-Type: application/json

{
  "manufacturerId": "0x1234",
  "productType": "0xabcd",
  "productId": "0xcafe",
  "firmwareVersion": "1.1"
}
```

The response will be normalized to always return an array of files for the different firmware targets.

```
HTTP/1.1 200 OK
Content-Type: application/json

[
  {
    "version": "1.7",
    "changelog": "* Fixed some bugs\n*Added more bugs",
    "files": [
      {
        "target": 0,
        "url": "https://example.com/firmware/1.7.otz",
        "integrity": "cd19da525f20096a817197bf263f3fdbe6485f00ec7354b691171358ebb9f1a1"
      }
    ]
  }
]
```

The driver will offer a method to a) query this information, so applications can display it and b) download the firmware file and start an upgrade.

**Comment by robertsLando** [comment]
About config files I would vote for option 2, the rest is perfect as it is 🚀

**Comment by marcus-j-davies** [comment]
Absolutely 2!

~~I guess `2. Config file format` actually drives the responses for `3. Querying possible upgrades` ?~~

Read fully Marcus! 😅 
But yeah I'm with @robertsLando. My view is  the device config files are to align the driver with the device characteristics (and others of course). And I agree about having it 'detached' allowing us to alter things fairly quickly.

Example (an extreme one) - pulling a FW that may have security complications, if Device config files had the Info embedded, it can be sometime before any edits are affectively delivered to end users, whilst this example is extreme, we need a way to respond quickly.

**Comment by kaechele** [comment]
We would need to see how non-monotonic versioning would be handled (if it is actually a thing).
Eg. the [Zooz ZEN72 changelog](https://www.support.getzooz.com/kb/article/849-zen72-700-series-dimmer-change-log/) lists versions 1.01 -> 10.0 -> 10.10 -> 2.0.
I'm not sure whether 2.0 is even OTA or if this is just what comes out of the factory on the HW Revision 2 devices. But even then there would probably need to be a differentiation of the hardware revisions, I guess.
Maybe Zooz can comment on this.

**Comment by AlCalzone** [comment]
We should be able to model the non monotonic versions with this proposal, since we are able to say version X can go to versions A, B, C. But we are also able to say C can only go to D for example.

**Comment by AlCalzone** [comment]
https://github.com/zwave-js/firmware-updates and https://github.com/zwave-js/node-zwave-js/pull/4758
