### ISSUE TITLE
Thermostat Heatit Z-TRM3 -  Displays status wrong 

### ISSUE THREAD

**Issue by Tom-ahawk** [AlCalzone/node-zwave-js#4744]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
It might be the Z-TRM3 mapping for Z-Wave JS and how the "hvac_action" attribute is populated for this thermostat. 

What do you observe?
When in Home Assistant the Thermostat card displays "Idle" when the thermostat is set "Off". 
https://community.home-assistant.io/t/thermostat-card-displays-status-wrong/433703 

What did you expect to happen?
To see "Off" instead of "Idle"
  2. Click on '...'
  3. Scroll down to '...'

### Device information

Manufacturer: Heatit
Model name: Z-TRM3
Node ID in your network: 26

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 0.1.63 
`zwavejs2mqtt` branch:

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

In the Z-Wave JS integration there is a download button but in the Z-Wave JS Add-on it looks like you can only copy the latest entries (what you see on the screen not the log from start). Or its the two logs the same?

**Comment by kpine** [comment]
You're in the wrong place, this is a Home Assistant problem. HA decides what hvac_action to report when the thermostat mode is off. https://github.com/home-assistant/core/issues/new/choose

**Comment by Tom-ahawk** [comment]
I got feedback from the producer of the thermostat today, saying that  "hvac_mode  will be set to OFF, if hvac_action is displaying  status.”
