### ISSUE TITLE
Firmware updates arent working [question] 

### ISSUE THREAD

**Issue by no1warr1or** [AlCalzone/node-zwave-js#4757]
I'm having an issue with updating firmwares of zwave devices. I have 3 battery powered devices and 1 zwave switch that have updates. the issue im having is that the firmware will start however the progress bar will just disappear at random percentages. Looking at the event logs for the devices, you can see the firmware update process running and then will say "firmware update complete" when it has not completed. I was able to successfully get another zwave switch to update properly but it took a couple attempts to do so. Any ideas on what may be happening?

**Comment by robertsLando** [comment]
Please attach zwavejs driver debug level logs

**Comment by AlCalzone** [comment]
Without seeing logs, probably a flaky connection. The update process is driven by the end device and if it stops requesting the update fragments for a while, the driver will abort the update.

**Comment by no1warr1or** [comment]
Apologies for the delay. What I'm noticing is the devices are communicating fine then the response time will shoot through the roof 1000+ ms. Some of the nodes go dead then come back alive. And I have a ton of dropped commands. But when the log shows the update is "done" its not experiencing these symptom at that time. I will grab the logs on the next update (I'm waiting for a response from zooz on one) the others I just kept trying until they actually completed.

I've gone through some of the zwave troubleshooting. It's on a USB extension and it's as far away from my rack as I can get it. I'm wondering if the usb cable is picking up interference? 

I'll provide more information once I get the update file and get the time to diagnose the zwave network alittle more
