### ISSUE TITLE
Zwave 800 series support

### ISSUE THREAD

**Issue by imranoftherings** [AlCalzone/node-zwave-js#4785]
Now that Zwave 800 series has been released, are there plan to add support for this along with 800 series devices?

https://atrim.co/zwave/stick-hub/

**Comment by kdknigga** [comment]
Who is Atrim?

Also, they seem to think zwavejs2mqtt/node-zwave-js already supports their stick.

https://atrim.co/help/stick/setup-zwave-home-assistant.html

**Comment by AlCalzone** [comment]
@imranoftherings which features are you missing?

**Comment by imranoftherings** [comment]
I was looking to upgrade to zwave 700 stick, when I realized 800 is out. Atrim is releasing their new zwave stick next month where I live.

They mention compatibility with home assistant, so zwavejs might already work out of the box for it. I guess the main feature for 800 series is the long range antenna. Everything else from what I read is backwards compatible

https://community.silabs.com/s/share/a5U8Y000000bwgaUAA/zwave-500-vs-700-vs-800-why-use-the-new-800-series-for-smart-home-devices?language=en_US

**Comment by AlCalzone** [comment]
The serial API is backwards compatible mostly, so the default use case should work out of the box. Z-Wave Long Range is still on my TODO list though.
