### ISSUE TITLE
[Bug]: `getAvailableFirmwareUpdates` is calling `waitForWakeup` which throws

### ISSUE THREAD

**Issue by marcus-j-davies** [AlCalzone/node-zwave-js#4799]
More than happy to provide a log, but its pretty trivial 😅 

 `getAvailableFirmwareUpdates` is calling into  `node.waitForWakeup()`
 https://github.com/zwave-js/node-zwave-js/blob/bd5aa02022ee1c4adc96cf884a2a956081bf2eb2/packages/zwave-js/src/lib/controller/Controller.ts#L4995
 
 but `waitForWakeup()` will throw for devices that don't sleep.
https://github.com/zwave-js/node-zwave-js/blob/bd5aa02022ee1c4adc96cf884a2a956081bf2eb2/packages/zwave-js/src/lib/node/Node.ts#L507
 
 And the exception is not handled in `getAvailableFirmwareUpdates` which is thrown immediately  for none sleeping nodes.

maybe we should only have this wake up check if the WAKE UP cc is supported?
https://github.com/zwave-js/node-zwave-js/blob/bd5aa02022ee1c4adc96cf884a2a956081bf2eb2/packages/zwave-js/src/lib/controller/Controller.ts#L4993
 
 
![image](https://user-images.githubusercontent.com/55892693/178819412-4c45076d-dd9e-453b-91cb-68328d8b0542.png)

**Comment by marcus-j-davies** [comment]
I have taken liberty of suggesting a patch in the form of a PR.

**Comment by AlCalzone** [comment]
Nice, will check it on Monday
