### ISSUE TITLE
Rename Zooz ZEN20

### ISSUE THREAD

**Issue by blhoward2** [AlCalzone/node-zwave-js#4808]
Zooz released version 3 of the hardware but our device file reports version 2 for both. We need to split the file by firmware. 

"For the ZEN20, it is the same model, just a different version. Any device reporting 2.x firmware is a version 2, and any device reporting firmware 3.x is a version 3.0."

**Comment by AlCalzone** [comment]
fixed by https://github.com/zwave-js/node-zwave-js/pull/5550
