### ISSUE TITLE
currentColor is set after a Poll but not after interview

### ISSUE THREAD

**Issue by amilanov75** [AlCalzone/node-zwave-js#4811]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

The currentColor properties for RGBW devices is being reported as "null" for all properties i.e. R, G, B and WW.

The expected behaviour is that a value between 0 and 255 should always be reported against each channel.

The tested device is Fibaro RGBW2.

Testing 1:
An interview of the device will return "null"
A getValueDB (in NR) will then return "null"

Testing 2:
A poll of the device will return a value
A getValueDB (in NR) will then return a value

It is not clear why the value is being dropped in the first instance i.e. why null is being reported as there is no sign of "mass" interviews happening to reset the property from a valid value to "null".

Versions:
NR v3.0.0 
nr-zwave-js v7.1.0
Nr driver v9.3.0
node-js v14.18.3

Image info - message received after a poll:
prevValue = null (this was before a poll)
new Value = 0 this from the poll
![image](https://user-images.githubusercontent.com/23739630/179514363-d3084b5d-fa35-4f1a-8e45-e88bf30bf5c0.png)

### Device information

refer above

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [X] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

refer above

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### If yes, where did it work?

Not sure how long this has not been working for as my code will set the target colour whenever the light is turned on, if the target does not equal the current colour, so the issue would have been covered up.

### Attach Driver Logfile

Log file when interviewing device
[zwave-js.log](https://github.com/zwave-js/node-zwave-js/files/9132005/zwave-js.log)

**Comment by AlCalzone** [comment]
@marcus-j-davies the NR-plugin is listening for the `"value added"` event, right?
I do see these logs during the interview (same for the other channels), which means the values are being added/created there, as opposed to updated:
```
2022-07-18T11:12:47.920Z CNTRLR   [Node 042] [+] [Color Switch] currentColor[0]: 0                  [Endpoint 0]
2022-07-18T11:12:47.921Z CNTRLR   [Node 042] [+] [Color Switch] targetColor[0]: 0                   [Endpoint 0]
2022-07-18T11:12:47.921Z CNTRLR   [Node 042] [+] [Color Switch] currentColor: {"warmWhite":0}       [Endpoint 0]
2022-07-18T11:12:47.921Z CNTRLR   [Node 042] [+] [Color Switch] targetColor: {"warmWhite":0}        [Endpoint 0]
```

**Comment by marcus-j-davies** [comment]
@AlCalzone

I do, but I pass them to user land as **VALUE_UPDATED**, as their makeup is extremely similar.

https://github.com/zwave-js/node-red-contrib-zwave-js/blob/b21cf7a4bb65d78a9ad8a8d25cf0e2607c4f0e2d/zwave-js/zwave-js.js#L2026

I worked on this issue this morning on discord, after an interview, `currentColor` is **null** (not `undefined` which surprised me) - for all components (using `getValue`), but only after a `pollValue` are they available (at least that's what I witnessed) 😅 


I don't actually subscribe to any events until the node is marked as ready.
https://github.com/zwave-js/node-red-contrib-zwave-js/blob/b21cf7a4bb65d78a9ad8a8d25cf0e2607c4f0e2d/zwave-js/zwave-js.js#L1998

So value added isn't really triggered in NR for the very first interview

Could not subscribing to `value added` during an interview stop anything being committed to the DB 🤔 
but then, I would expect to see the value after a 2nd interview

**Comment by marcus-j-davies** [comment]
Is this another endpoint madness thing?, as the endpoint in question is 1, but logs shows 1 & 0 🤷 
not sure how it all fits in with the interview stage

**Comment by AlCalzone** [comment]
I also thought of an endpoint thing first, but both endpoints have the values. Also, the driver only uses `null` instead of `undefined` in a handful of locations. Values aren't one of them.

Do you read all values after the node is ready? Or how are the values reaching userland?

**Comment by marcus-j-davies** [comment]
> Do you read all values after the node is ready? Or how are the values reaching userland?

Nothing is read once ready, just the node events subscribed to.
the events are sent to userland like any other event.

value updated example
https://github.com/zwave-js/node-red-contrib-zwave-js/blob/b21cf7a4bb65d78a9ad8a8d25cf0e2607c4f0e2d/zwave-js/zwave-js.js#L2021

but in this reported case.

when executing `getValue` by the user - its returning `null` for `currentColor`, until `pollValue` is executed.
it seems after an interview it reverts back to `null` @amilanov75 please confirm that is the case.

getValue
https://github.com/zwave-js/node-red-contrib-zwave-js/blob/b21cf7a4bb65d78a9ad8a8d25cf0e2607c4f0e2d/zwave-js/zwave-js.js#L1181

pollValue
https://github.com/zwave-js/node-red-contrib-zwave-js/blob/b21cf7a4bb65d78a9ad8a8d25cf0e2607c4f0e2d/zwave-js/zwave-js.js#L1214

polling the value, its reporting the `prevValue` as `null` which seems to align with the value retrieved using `getValue` prior to the poll, after the poll - `getValue` is returning what would be expected.

![image](https://user-images.githubusercontent.com/55892693/179621553-9b70f4b8-1a60-4378-93c6-74b3494ac493.png)

Other properties are fine, i.e calling `getValue` for a binary Switch for example (no poll is needed)
it seems to be isolated to `currentColor`

**Comment by amilanov75** [comment]
"when executing getValue by the user - its returning null for currentColor, until pollValue is executed.
it seems after an interview it reverts back to null @amilanov75 please confirm that is the case."

Interview does not revert back to null, which means that as it stands, I do not know what is triggering a null value being populated in the first instance.

**Comment by marcus-j-davies** [comment]
Right! but yesterday when we were debugging, it was reverting to null after an interview? 

From discord:
> Node ID = 42
I noticed that after polling on the next refresh the values go back to null

By refresh you mean new interview?

**Comment by amilanov75** [comment]
Yes, but that was before I re-instated my code to work as expected, after which the lighting function was actually sending colour commands to the lights.

Do you recall me saying I was seeing inconsistent results. I said that after I sent a command to set the colour for a light, as I was then seeing the colour values stick i.e. the nulls did not return.

So, "something" happens to trigger the null values, after which we can only temporarily replace them with actual values with a poll, but once an actual colour command is sent, the messages report correct values, until the "something" event happens again.

Hence my statement above: "I do not know what is triggering a null value being populated in the first instance."

I am not sure how easy it would be to figure out what the "something" event is TBH.

**Comment by AlCalzone** [comment]
Which value IDs are we talking about anyways?
I can see that the value events for endpoint 1 reach NR:
```
2022-07-18T11:12:38.440Z CNTRLR   [Node 042] [~] [Color Switch] duration: {"value":0,"unit":"second [Endpoint 1]
                                  s"} => {"value":0,"unit":"seconds"}
2022-07-18T11:12:38.440Z NDERED » [Node: 42] [VALUE_UPDATED] [DIRECT] Forwarding payload...
2022-07-18T11:12:38.440Z NDERED » [Node: 42] [VALUE_UPDATED] [EVENT] Forwarding payload...
2022-07-18T11:12:38.441Z CNTRLR   [Node 042] [+] [Color Switch] currentColor[4]: 0                  [Endpoint 1]
2022-07-18T11:12:38.441Z NDERED » [Node: 42] [VALUE_UPDATED] [DIRECT] Forwarding payload...
2022-07-18T11:12:38.441Z NDERED » [Node: 42] [VALUE_UPDATED] [EVENT] Forwarding payload...
2022-07-18T11:12:38.441Z CNTRLR   [Node 042] [+] [Color Switch] targetColor[4]: 0                   [Endpoint 1]
2022-07-18T11:12:38.441Z NDERED » [Node: 42] [VALUE_UPDATED] [DIRECT] Forwarding payload...
2022-07-18T11:12:38.442Z NDERED » [Node: 42] [VALUE_UPDATED] [EVENT] Forwarding payload...
2022-07-18T11:12:38.442Z CNTRLR   [Node 042] [~] [Color Switch] currentColor: {"warmWhite":0,"red": [Endpoint 1]
                                  0,"green":0,"blue":0} => {"warmWhite":0,"red":0,"green":0,"blue":0}
2022-07-18T11:12:38.442Z NDERED » [Node: 42] [VALUE_UPDATED] [DIRECT] Forwarding payload...
2022-07-18T11:12:38.442Z NDERED » [Node: 42] [VALUE_UPDATED] [EVENT] Forwarding payload...
2022-07-18T11:12:38.443Z CNTRLR   [Node 042] [~] [Color Switch] targetColor: {"warmWhite":0,"red":0 [Endpoint 1]
                                  ,"green":0,"blue":0} => {"warmWhite":0,"red":0,"green":0,"blue":0}
2022-07-18T11:12:38.443Z NDERED » [Node: 42] [VALUE_UPDATED] [DIRECT] Forwarding payload...
2022-07-18T11:12:38.443Z NDERED » [Node: 42] [VALUE_UPDATED] [EVENT] Forwarding payload...
2022-07-18T11:12:38.443Z CNTRLR   [Node 042] [~] [Color Switch] hexColor: "000000" => "000000"      [Endpoint 1]
2022-07-18T11:12:38.444Z NDERED » [Node: 42] [VALUE_UPDATED] [DIRECT] Forwarding payload...
2022-07-18T11:12:38.444Z NDERED » [Node: 42] [VALUE_UPDATED] [EVENT] Forwarding payload...
```

but the events for endpoint 0 do not since they duplicate endpoint 1 and are filtered on the Z-Wave JS side.

**Comment by marcus-j-davies** [comment]
@AlCalzone to my knowledge it's all the property keys R,G,B,WW for currentColor on endpoint 1.

@amilanov75 I'm really hoping your flows are not setting null for targetColor in error, but I think the driver validates the value for them 🤞

**Comment by marcus-j-davies** [comment]
@amilanov75 you are using the ValueAPI right? and are not aware of your flows sending `null` values unknowingly or otherwise.
basically we should not be seeing `null` and the ValueAPI validates input

**Comment by amilanov75** [comment]
@marcus-j-davies 
Unless there is voodoo magic going on, there is no opportunity to change anything. My debug node is directly on the controller output, as per the images I shared with you yesterday

![image](https://user-images.githubusercontent.com/23739630/179754357-38b88f4c-e8f4-4431-8925-b1f3286f75ba.png)

This is why it took me so long to figure out yesterday, as I had to follow the path back to the controller and even then I didn't believe it so I wasted more hours more downstream, until I came back to the controller and conceded that the null values (for ALL RGBW properties) were coming directly from the controller

**Comment by amilanov75** [comment]
ok, so I have been looking at my lights and they are now ALL reporting values NOT null.

I have checked a light that I am fairly confident would not have been turned on in the last 24 hours and it has values again, so something has happened to start reporting value not nulls.

Either you can see something in the code, else it's an intermitted issue that may be hard to pin down.

**Comment by marcus-j-davies** [comment]
Ok,

On the basis your flows (and dashboards) are not somehow setting `null` values for `targetColor`, which will then translate to `currentColor `(i think 😅 ) - but then the driver should validate the value for `targetColor` if using the ValueAPI

I'm at a complete loss.
data is coming from the driver and to the driver, the module doesn't massage them to introduce a `null` value in anyway.

I'm lost, as i can see nothing.

`getValueDB` is just fetching the value from the drivers data cache
https://github.com/zwave-js/node-red-contrib-zwave-js/blob/b21cf7a4bb65d78a9ad8a8d25cf0e2607c4f0e2d/zwave-js/zwave-js.js#L1393

`setValue` is just passing it directly to the  driver
https://github.com/zwave-js/node-red-contrib-zwave-js/blob/b21cf7a4bb65d78a9ad8a8d25cf0e2607c4f0e2d/zwave-js/zwave-js.js#L1200

**Comment by amilanov75** [comment]
@marcus-j-davies  in the world of possible explanations, you have provided one that could work, albeit (hopefully) unlikely.
"Could I have introduced a bug into my code that sent a null value message to the controller. "

Have you tested if sending a null value, then translates into the null value being stored for future retrieval? If not, I can test it later to see if it does in fact do that.

I am scratching my head now to think about how to check the above hypothesis given all the code changes that I have been making on a daily basis.

Ok, let me test sending "null"  first....

**Comment by amilanov75** [comment]
Actually no, I am not going to do test the sending "null" hypotheses.

Recall what happened yesterday, the null value kept coming back right after a poll set it correctly. 

So, unless a null value being sent, does something weird/unexpected i.e. somehow makes the null stick - which really would be out there, that can't be the explanation.

**Comment by marcus-j-davies** [comment]
> Recall what happened yesterday, the null value kept coming back right after a poll set it correctly.

Ok - lets rule out any user flow being the cause.

Attach a debug node to the link node(s), right before they hit the controller.
then do stuff (including a poll - why not)

what we should NOT see is any message where the target is being set to `null`
I'm out of ideas - so clutching at straws

![image](https://user-images.githubusercontent.com/55892693/179769026-fd35387f-3520-49b4-beb6-99d53d6dc41c.png)

**Comment by amilanov75** [comment]
I thought about doing the same, then stopped myself as it didn't feel like a good use of time.

I'll do it later to be complete and see if anything ever pops up.

I thin k the better use of time is to see what happens IF you send a null value, as it's more likely that there was a bug in my code over the 3 day period between Fri-Sun when I diagnosed the issue must have happened.

Will look into it all later, when I get a chance, and report back.

**Comment by marcus-j-davies** [comment]
> IF you send a null value

The Driver should be validating values for the ValueAPI:setValue commands, and it does.

![image](https://user-images.githubusercontent.com/55892693/179786754-926d81b3-fa7e-4674-b7aa-05f2356631df.png)


So I would expect the same for Color Switch:`targetColor`
but if its not, and for some reason your sending `null` - then this may be the source of madness

**Comment by marcus-j-davies** [comment]
@AlCalzone

I am not sure if this is of Value or should be the desired affect, but I have just been able to set `null` for each colour component 

(connected to a friends VPN and tested  - as I do not have RGBW controllers)

and `null` is indeed returned for current colour.

I think this issue should _only_ stay open, if this was not intended i.e being able to set non-numericle values, or at least a value returning `NaN` in `parseInt()`

**Setting**

```javascript
{
    "mode": "ValueAPI",
    "method": "setValue",
    "params": [
        {
            "commandClassName": "Color Switch",
            "commandClass": 51,
            "endpoint": 0,
            "property": "targetColor",
            "propertyName": "targetColor"
        },
        {
            "warmWhite": null,
            "red": null,
            "green": null,
            "blue": null
        }
    ]
}

```

**Current Color**
```javascript
{
   "valueId": {
      "commandClassName": "Color Switch",
      "commandClass": 51,
      "endpoint": 0,
      "property": "currentColor",
      "propertyName": "currentColor"
   },
   "meta": {
      "type": "any",
      "readable": true,
      "writeable": false,
      "label": "Current Color"
   },
   "propertyid": "0-51-currentColor-",
   "endpoint": 0,
   "valueData": {
      "value": {
         "warmWhite": null,
         "red": null,
         "green": null,
         "blue": null
      }
   }
}
```

@amilanov75 
based on this, I am under the believe `null` was being sent from your flow somehow, and will indeed be committed, hence you will see `null` when fetching `currentColor`

**Comment by AlCalzone** [comment]
Ohh, it just verifies that each key is valid, but not the actual values.

**Comment by amilanov75** [comment]
Hi @marcus-j-davies, you beat me to it. I was just sitting down with a coffee about to test the above. Thank you for doing so yourself!.

For the time being and given that the issue happened so quickly, I would have to agree with you that my code (as we discussed, which was in transit and in which I'd already introduced a bug into that uncovered this issue was even happening) is currently the most likely candidate for causing null to be reported in the device messages. I can't think of any other event that happened over the 3 day period in question that could be reasonably attributed to the issue. I'd already updated NR to 3.0.0 one day before the three day window in which I determined that bug was happening, so that takes NR out of the question.

I will still put a look on my inbound messages, until the above bug is resolved, to see if "null" ever gets written, however unless a new bug is introduced into my code, I doubt this will be the case.

@marcus-j-davies  
In your testing, did you check after writing the null value if the exact same behaviour was happening as per the screenshots I shared with you in our PMs the other day? 
i.e. could you see a value in getValueDB by using getValue and then poll to see it return to null in the getValueDB?  
I think this is an important nuance of the bug that @AlCalzone should be aware of.
If not, I'll can run the tests again and provide fresh screenshoots + anything else @AlCalzone requests e.g. could also provide logs, if it helps - although not sure they will in this situation.

**Comment by AlCalzone** [comment]
I'm pretty sure this is fixed with the linked PR. `setValue` didn't throw, although the passed value was invalid, which caused the `currentColor` to get updated optimistically with invalid values.
