### ISSUE TITLE
[Bug]: Device show non existing value

### ISSUE THREAD

**Issue by thesebastianf** [AlCalzone/node-zwave-js#4817]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.11.0

### ZwaveJS version

9.3.0

### Describe the bug

[](url)I have a lot of that https://devices.zwave-js.io/?jumpTo=0x010f:0x0302:0x1000:25.25

Only one of it shows a sensor value that isn't even in the device.
![zwavejs](https://user-images.githubusercontent.com/13987575/179627221-03045c92-60ff-484f-a59d-5a6141015137.png)

### To Reproduce

no clue

### Expected behavior

should not show that value

**Comment by robertsLando** [comment]
@thesebastianf If you see it there it means the device is reporting that CC someway. Could you submit  a driver log please?

**Comment by AlCalzone** [comment]
Unfortunately there's nothing to be done about this I'm afraid. The air temperature one is likely from a command that got corrupted on air in a way that the checksum was still valid.

Multilevel Sensor CC V2 doesn't allow checking which sensors a device exposes, so Z-Wave JS has to trust the received commands. Including a device with Security can prevent this, but I don't recommend using S0 and this device doesn't support S2 yet.

If this really bugs you, you can re-interview the device and hope the value doesn't come back.

**Comment by thesebastianf** [comment]
thank you for explaining it
I did a reinterview and hope its solved
