### ISSUE TITLE
[Bug]: Temperature inconsistently converted to local units

### ISSUE THREAD

**Issue by mbbush** [AlCalzone/node-zwave-js#4818]
### Checklist

- [x]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.13.0

### ZwaveJS version

9.5.0

### Describe the bug

I live in the US and use Fahrenheit, but have not yet set that preference as a preferred scale. I have two different temperature sensors. When I view the sensor value from the control panel -> device -> values -> Multilevel Sensor v5, I sometimes see:

* The current temperature in Fahrenheit, followed by `°F` (good)
* The current temperature in Celsius, followed by `°F` (bad)
* The current temperature in Fahrenheit, followed by `°C` (bad)
* The current temperature in Celsius, followed by `°C` (good)

I've seen those all within a single browser session. If it's showing the Fahrenheit temperature, with `°F`, and I click refresh, it consistently switches to showing the Celsius temperature with `°F`. I haven't been able to identify when the ui shows `°F` vs `°C`.

### To Reproduce

Unset any preferred scales in the zwave settings. 
Set up a zwave device which reports temperature in Celsius.
View the current temperature using the control panel.

Observe that it (sometimes?) shows the Fahrenheit temperature with units of `°F` (good). If it does, and you click refresh for that command class, it changes the displayed number to the current Celsius temperature, while leaving the unit unchanged (bad). I've also sometimes seen the reverse, where it initially shows Celsius temperature with units of `°F`, and then when I refresh the number changes to Fahrenheit but the units stay the same.

### Expected behavior

I expect the displayed temperature value to always match its displayed units. 

### Additional context

I've observed logs of sensor reports in both Celsius and Fahrenheit. In all cases, the unit matched the numerical value. 

Once I set a preferred scale, I have no longer been able to reproduce the issue. But I still consider it a bug, on the premise that in the default configuration, the software should not display anything which is flat-out wrong. Choose either F or C, but don't use one scale for the number and the other for the unit.

**Comment by AlCalzone** [comment]
> Once I set a preferred scale, I have no longer been able to reproduce the issue.

This is exactly what preferred scales are for, since otherwise zwave-js has no way of knowing which scale you want when querying the device. The unit and value should be consistent though.

Please make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` or `silly` and attach it here as a file.
While making the log, query the device in a way that reproduces your issue.
