### ISSUE TITLE
Feature request: Schedule Entry Lock V3

### ISSUE THREAD

**Issue by jmgiaever** [AlCalzone/node-zwave-js#4821]
**Is your feature request related to a problem? Please describe.**

Needed to make temporary/time limited user codes on door locks that supports this CC. 

**Describe the solution you'd like**

To be able to adjust these parameters for each code slots.

**Additional context**

Imagine this would be heavily used by private and commercial users, and especially Property Management businesses/applications.

**Comment by oded996** [comment]
Hi @AlCalzone, I'm developing a key management integration integration for Home Assistant. I'm hoping to add support for user code scheduling.
 I can see that the foundational support for the Schedule CC was added in PR #4836
  
 I'm trying to figure out the last step needed to use this from Home Assistant. Is there an existing zwave-js-server command to access this API? If not, is that something that's on the roadmap?
