### ISSUE TITLE
Yale ZWAVE S2 Module missing manufacturer and lock versions

### ISSUE THREAD

**Issue by vectorcatch** [AlCalzone/node-zwave-js#4840]
When adding Yale Locks with the S2 ZWave module, the locks do not show the correct model name and info. They also cannot retrieve all of the lock codes at one time. The refresh only retrieves the master code and not the user codes.

Attached is a picture of the exact same lock. One with the Regular S0 module and one with the S2 module.

<img width="1512" alt="Screen Shot 2022-07-24 at 9 56 58 PM" src="https://user-images.githubusercontent.com/12199420/180678696-c0efbd09-8140-45a9-bbe6-ca77adc667a2.png">

**Comment by AlCalzone** [comment]
Please use this [bug report template](https://github.com/zwave-js/node-zwave-js/issues/new?assignees=&labels=&template=bug_report.yml) and fill it out completely, including logs of a re-interview of both locks.
