### ISSUE TITLE
[question] POPP Z-Weather strange humidity value

### ISSUE THREAD

**Issue by opensource-alt** [AlCalzone/node-zwave-js#4889]
Hello,

My POPP Z-Weather device gives a strange value of 100% humidity all the time (and the drew point is surely also incorrect).
Device issue (hardware) or multi sensor (software) read / parameter issue? 
I alredy reset the device settings twice, added back multiple times to the ZWave network without change. 
In use: latest zwave2mqtt (6.15.2). This parameter has always been bad (100% all the time) vith previous versions too (since a month ago at least, I didn't own the Z-Weater before).

Philippe

[zweater-debuginfo.txt](https://github.com/zwave-js/zwavejs2mqtt/files/9269470/zweater-debuginfo.txt)

**Comment by opensource-alt** [comment]
![Capture d’écran 2022-08-05 162450](https://user-images.githubusercontent.com/58864512/183097642-c1707ac4-a382-487f-a6d2-add28302110d.png)

**Comment by AlCalzone** [comment]
It also reports 100 for the illuminance and pressure. This can't be a coincidence. I'd contact the manufacturer in your case.

I can take a look at a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs), where you refresh these values, but I don't expect any software bug at this point. Make it loglevel `debug` or `silly` and attach it here as a file.

**Comment by opensource-alt** [comment]
100 for pressure was purely coincidental (see the new debug file: pressure is over 100 now). Illuminance is at 100% all day and change at night (the device change the report frequency below 20%). The only strange value is the humidity (it never changes, always 100%, an impossible value...) and drew point (I guess it's calculated with current air temp + humidity)

This is a used purchase. The previous owner told me that it had no strange value. He didn't use the same software though (and I can't verify his statement about the values with the other software)

[zweater-debuginfo.txt](https://github.com/zwave-js/node-zwave-js/files/9283451/zweater-debuginfo.txt)

**Comment by AlCalzone** [comment]
That's not a driver log. If you want me to look at it, please read the link in my previous post again.

**Comment by opensource-alt** [comment]
Sorry for the missing log file...
I filtered logs to the Popp Z-Weather node only (node ID 34) as there's many devices in my ZWave network (25 + controller). Tell me if it's more relevant to remove this filter.
I'm really unsure this issue could be related to ZWaveJS mishandling of this device but as the previous owner told me he didn't have those strange values...

[zwavejs_2022-08-09.log](https://github.com/zwave-js/node-zwave-js/files/9288779/zwavejs_2022-08-09.log)

**Comment by AlCalzone** [comment]
The sensor sends this value. Here's a breakdown of the command that is received:
```
010d00 040022 05 3105 05 01 64 b10034
├────┘ ├────┘ ├┘ ├──┘ ├┘ ├┘ ├┘ ├────┘ 
│      │      │  │    │  │  │  └ Protocol related
│      │      │  │    │  │  └ value 100
│      │      │  │    │  └ 0 decimal digits, scale 0 (%), 1 byte
│      │      │  │    └ Humidity
│      │      │  └ Multilevel Sensor Report
│      │      └ Length 5
│      └ Incoming packet from node 34
└ Protocol related
```
