### ISSUE TITLE
FGBS001 doesn't include DS18B20

### ISSUE THREAD

**Issue by jbougeniere** [AlCalzone/node-zwave-js#4909]
Hello,
I'm using Zwave-js 0.1.65 and HA supervised 2022.8.3 on rpi3B+ with aeotec stick 500.

Since release 2022.6 (I think), FGBS001 doesn't include temperature sensors except if they are close the component. Perhaps some noise on the line or delay too short for recognition.
More that, some values are totally out of range.
Could you please help me ?
Is someone has already had the same issue
Thks

**Comment by AlCalzone** [comment]
Please choose an appropriate issue template and fill it out completely when opening an issue. That helps us investigate your issue quicker because all the necessary information is there. That especially includes driver logs which highlight your problems.
