### ISSUE TITLE
Missing device configuration: Zooz ZEN14

### ISSUE THREAD

**Issue by billyburly** [AlCalzone/node-zwave-js#4920]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Zooz ZEN14

### Manufacturer ID

0x027a

### Product Type

0x7000

### Product ID

0xb003

### Firmware Version

1.10

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4674

### Do you have a manual?

https://cdn.shopify.com/s/files/1/0218/7704/files/zooz-outdoor-double-plug-zen14-manual.pdf

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4674 from zwa
