### ISSUE TITLE
Z-Wave JS Server version is incompatible: 1.15.0 a version is required that supports at least api schema 17

### ISSUE THREAD

**Issue by espenthingstad** [AlCalzone/node-zwave-js#4931]
Hello

I just had a power outtage on my Home Assistant server. I am running Zwave JS integration with a Aeotec Gen 5 zstick. 
When repowering the server, my Zwave integration stopped working, giving failure code: 
"Z-Wave JS Server version is incompatible: 1.15.0 a version is required that supports at least api schema 17"

Home Assistant Core version: 2022.6.6
Home Assistatn OS: 8.2
Zwave JS integration version: 0.1.65 

How 
<img width="285" alt="Screenshot 2022-08-17 at 19 32 20" src="https://user-images.githubusercontent.com/80642192/185214056-70ce279e-5699-4c61-93e5-08882da998d4.png">
do I find the Z-wave JS server, and how to update it?

**Comment by AlCalzone** [comment]
> Home Assistant

This repo is not meant for Home Assistant support. This one is: https://github.com/home-assistant/core/issues

Nonetheless, you probably need to upgrade the Z-Wave JS addon and/or the integration to the latest version.
