### ISSUE TITLE
[feat] Automatically reset security classes when re-interviewing an S2 authenticated device after firmware upgrade

### ISSUE THREAD

**Issue by cmamatey** [AlCalzone/node-zwave-js#4940]
**Is your feature request related to a problem? Please describe.**
I just used the OTA firmware upgrade feature for the first time last night with great results; great work contributors!
However when I updated the firmware on an S2 authenticated device, the re-interview process (automatically started when the upgrade finished) did not seem to work correctly. All details for the device were replaced with generic information like "Unknown manufacturer 0xXXXX", and additional re-interviews made no changes.

I learned the fix for me was to perform another interview, but this time to check the box for "Reset security classes". Once re-interviewed with this option selected, the device returned to the expected values and configurations.

**Describe the solution you'd like**
Enhance the firmware upgrade process such that when the device being updated is an S2 authenticated device, the "Reset security classes" option is automatically included during the interview action at the end of the firmware upgrade process. Ideally, this would prevent the device from ever entering the "Unknown manufacturer 0xXXXX" state.

**Describe alternatives you've considered**
None.

**Additional context**
I am unfamiliar with the implementation of S2 and am therefore unware of the potential impacts/risks of resetting security classes by default.

**Comment by jmgiaever** [comment]
I think this can be a cache issue, or that the ID of the device has changed, @AlCalzone ?

This should probably be filed in the node-zwavejs repository, but did you have logging (in debug mode) turned on during this process for zwavejs (not zwavejs2mqtt)?

In case you didn't, please turn it on before updating additional devices.

**Comment by AlCalzone** [comment]
Agree, I'm not sure why this should be necessary. This sounds like a corrupted cache file or a bug, but network keys shouldn't change.

**Comment by cmamatey** [comment]
Sorry, I wasn't sure which of the repos this belonged to; thanks for moving.
If memory serves, the same issue happened again when rolling back to the previous firmware version (rolled back due to a FW-specific issue).

I'm running the upgrade again now with debug enabled.
The log is going to be massive, so how would you like it to be shared?
Is there going to be anything in the log that I'm going to want to redact for privacy?

**Comment by jmgiaever** [comment]
Can manufacture id, product id etc change on a fw update @AlCalzone? Would this cause the cache entry to be invalidated and require a fresh re-interview?

**Comment by cmamatey** [comment]
Screenshot of issue:
![Before_Reset_Security](https://user-images.githubusercontent.com/5520553/186011550-9e27e0ee-6bb7-4d9c-8459-a5413638bf52.png)

Screenshot of normal display (before upgrade or after Reset security classes):
![After_Reset_Security](https://user-images.githubusercontent.com/5520553/186011562-b466daf5-5eba-4832-91d0-40b69f549919.png)

**Comment by cmamatey** [comment]
I have the log ready.
It is ~96k lines long, so I assume I need to attach as a file.
Before I do, is there anything that would be contained in the log that I'm going to want to redact for privacy/security reasons?

FYI it has happened every time for this particular device for both upgrades and downgrades.
That said, it is currently my only device configured with S2 authentication, and I would absolutely believe that S2 is not configured correctly on my system.
It's also just as likely that my controller (Nortek HUSBZB-1) doesn't support it properly; I was surprised when I was originally able to add the device to my network with S2 authentication.

**Comment by jmgiaever** [comment]
You can encrypt it as a zip file and attach it here, and send the encryption key in an email to @AlCalzone . You'll find his email on his profile. 

(User codes - if you have locks - can show up in the logs, it's fixed in the upcoming release)

**Comment by cmamatey** [comment]
[zwavejs_2022-08-22.zip](https://github.com/zwave-js/node-zwave-js/files/9397766/zwavejs_2022-08-22.zip)

The attached log file includes the following 4 key events:
1. Change logging to Debug
2. Firmware upgrade of Node 15 including interview with bad results
3. Additional interview with bad results
4. Final interview with Reset security classes checked, resulting in successful interview

The text "[Node 015] The node is ready to be used" in the log seems to be a pretty good indicator of where each event ends.

Emailing the encryption key to @AlCalzone now.

**Comment by AlCalzone** [comment]
I **think** the interview after the firmware update was just started too early. While the driver did wait for the specified wait time of 30 seconds, the device responded a bit strange after that. A few seconds later, things were better.

In addition you ran into a bug that will be fixed in the v10 release: https://github.com/zwave-js/node-zwave-js/pull/4923
