### ISSUE TITLE
Missing device configuration: Yale 3109+/4109+ (AUS/NZ)

### ISSUE THREAD

**Issue by ddahya** [AlCalzone/node-zwave-js#4951]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Yale 3109+/4109+ (AUS/NZ)

### Manufacturer ID

0x0129

### Product Type

0xc700

### Product ID

0x0005

### Firmware Version

33.17

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/3227

### Do you have a manual?

[Manual for YDM3109 plus.pdf](https://github.com/zwave-js/node-zwave-js/files/9428441/Manual.for.YDM3109.plus.pdf)
[Manual for YDM4109 plus.pdf](https://github.com/zwave-js/node-zwave-js/files/9428442/Manual.for.YDM4109.plus.pdf)

**Comment by blhoward2** [comment]
This device is in our database as the 4109plus.
