### ISSUE TITLE
Termostat Heatit Z-TRM3: No entity created when the device is added

### ISSUE THREAD

**Issue by cobch** [AlCalzone/node-zwave-js#4999]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

I am using Aeotec Z-Stick 7 with ZwaveJs addon on Home Assistant. I managed to add the device but not any entities is created and the node is described as not ready.
I have tried to heal and reinterview the device but it does not help. To exclude and include again but same problem, no entities coming with the device.
<img width="760" alt="1" src="https://user-images.githubusercontent.com/50397676/188140805-8d5212a8-c1a1-42ee-9906-f931f12dbc32.png">

### Device information

Manufacturer: Heatit
Model name: Z-TRM3
Node ID in your network: <4>

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: zwave-js: 0.1.68

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

_nothing useful_

**Comment by AlCalzone** [comment]
@cobch please make a log (loglevel debug) of the **entire** interview as described [here](https://www.home-assistant.io/integrations/zwave_js#how-to-access-the-z-wave-logs).
When done, download the log and **attach** it here by dragging and dropping into the textbox.

**Comment by cobch** [comment]
Sorry, I am not really good with Zwave since I started 2 days ago and nothing seems to work (-:
Here come the log when I pressed the button to increase and decrease the temperatur in the termostat.
[zwave_js.log](https://github.com/zwave-js/node-zwave-js/files/9478041/zwave_js.log)

**Comment by AlCalzone** [comment]
That is not the interview, those are just temperature measurements from the thermostat. Click on the 3 dots next to "Configure Device" and select Re-Interview **while** you have the log window open.

**Comment by cobch** [comment]
Here it comes. So sorry about the wrong log before...
[zwave_js (re-interview).log](https://github.com/zwave-js/node-zwave-js/files/9479201/zwave_js.re-interview.log)

**Comment by AlCalzone** [comment]
Thanks, found the problem!

**Comment by cobch** [comment]
Great to know but you keep the secret totally (-: Is it something I should fix by myself?

**Comment by perosb** [comment]
I was just about to report the same issue.
Not sure it's the same. My log is attached.

`[Node 124] Error during node interview: Node #124 (Endpoint 2) does not support the command GetSupportedSensor (ZW0302)`
Let me know if I should open a new issue or provide diferent logs.

[trm3.log](https://github.com/zwave-js/node-zwave-js/files/9479931/trm3.log)

edit: just looked at cobch's log and the error msg is the same at least.

**Comment by perosb** [comment]
@cobch it will most likely be a code change and a new release.

**Comment by AlCalzone** [comment]
Yeah I'll fix it on Monday and release a new version.

**Comment by suneworld** [comment]
I am experiencing the same problem. I have upgraded to 0.1.69 but it did not fix the issue.
I would at the same time say that I am very greatful for all the fantastic work on this addon and that I am absolutely waiting patiently for a fix :)

**Comment by perosb** [comment]
It's not released yet.
However, it worked for me in a version using nodejs-zwave < 10.

**Comment by suneworld** [comment]
> It's not released yet. However, it worked for me in a version using nodejs-zwave < 10.

It is possible to downgrade? If yes, how?

**Comment by danielfinans** [comment]
I am having the same problem as well. Let me know if there is any additional logs needed. Looking forward to testing if new version release will fix this.

**Comment by suneworld** [comment]
A rollback to version  0.1.65 fixed it for me. Looking forward to a fix in the current version :)

**Comment by AlCalzone** [comment]
Yeah I haven't released the fix yet because a few other bugs were identified that I also want to eliminate in one go. Otherwise this will just cause tons of comments like "still does not work after updating".

**Comment by AlCalzone** [comment]
Try 10.0.4 (contained in the HA addon 0.1.70) please. Again, a re-interview may be required to get devices to work.

**Comment by perosb** [comment]
10.0.4 works like a charm!

Thanks 🙏

**Comment by cobch** [comment]
I get 9 entities after upgraded to latest version so I guess it is working too (-:
Should I close the issue?

**Comment by AlCalzone** [comment]
Fine be me. If you don't mind, another interview log now that it is working would be nice.

**Comment by cobch** [comment]
I am away with my work but will do it as soon as I can (-:

**Comment by perosb** [comment]
[trm3.log](https://github.com/zwave-js/node-zwave-js/files/9498034/trm3.log)
My log attached

**Comment by AlCalzone** [comment]
Thanks. Not 100% in terms of handling S2-related collisions, but that's a separate issue.

**Comment by cobch** [comment]
> [trm3.log](https://github.com/zwave-js/node-zwave-js/files/9498034/trm3.log)
> My log attached

How many entities could you see? I have only 9 and do not find how to remote shut on/off heating floor )-:

**Comment by cobch** [comment]
@perosb How does it look on your side? I have not the on/off controller entity.
![image](https://user-images.githubusercontent.com/50397676/189138487-fd5b8113-bd1f-4a01-9e95-fe6e9ea30867.jpeg)

**Comment by perosb** [comment]
@cobch you can add a thermostat card to your views
![image](https://user-images.githubusercontent.com/982752/189157775-5be23d24-f390-41ab-ad7c-c6e2aa16b6d6.png)

or if you click the "Floor thermostat" entity you get a dropdown with control.
![image](https://user-images.githubusercontent.com/982752/189158224-17d5c0d0-0b38-4918-9c55-8cbae6d42cfc.png)

**Comment by cobch** [comment]
Thanks/Tack!
