### ISSUE TITLE
Issues with Fibaro device control and interviewing devices after 10.x

### ISSUE THREAD

**Issue by siwilson2000** [AlCalzone/node-zwave-js#5014]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug? After 10.x migration, device interview fails for Fibaro FGBS001

What do you observe? After migration to 10.x, a number of Fibaro modules could not be controlled properly. HA dashboard would show device transition to on or off but module would not change. In most cases a re-interview of the device followed by reboot of J-wave JS fixed the issue. However, a re-interview of Fibaro FGBS001 (Universal Binary Sensor) modules fails to complete and the devices no longer function. 

What did you expect to happen? Re-interview complete and device to report temps from endpoint sensors (DS18B20)

  1. Initiate re-interview
  2. Observer failure message (Error during node interview: Node #53 (Endpoint 3) does not support the command GetSupportedSensor! (ZW0302)

### Device information

Manufacturer: Fibaro
Model name: FGBS001 Universal Binary Sensor (Firmware 2.1)
Node ID in your network: <51 and 53 >

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5

Driver Version: 10.0.3
Server Version: 1.22.1
Home ID: 4263209394
Server URL: ws://core-zwave-js:3000

### Did you change anything?

yes (please describe)

### If yes, what did you change?

Migration to 10.x

### Did this work before?

Yes (please describe)

### If yes, where did it work?

All nodes were included and worked fine prior to 10.x

### Attach Driver Logfile

[zwave_js-2.log](https://github.com/zwave-js/node-zwave-js/files/9491272/zwave_js-2.log)

**Comment by AlCalzone** [comment]
I'm on mobile so it's hard to check right now. If you haven't already, can you also log an interaction with the device that fails?

**Comment by AlCalzone** [comment]
Please re-test with v10.0.4. This version is included in:
zwave_js addon: 0.1.70
or
zwavejs2mqtt: 7.1.0

**Comment by siwilson2000** [comment]
Thanks Al. I had to go back to 0.1.65 (which fixed the issues) as I am away for a couple of days. I’ll try 01.70 as soon as I get back.

**Comment by wburgers** [comment]
I've experienced the same kind of issues as @siwilson2000.
My Fibaro lights wouldn't operate anymore.
I have two FGD212 dimmers in my living room and a FGS223 in my study.
I can set the FGD212's to any value (0 - 99 or 255) but it didn't do anything.
Setting the binary switch for the FGS223 didn't do anything either.

After re-interviewing the devices, the lights operate as intended.
I've updated zwavejs2mqtt to version 7.1.0.

For now I'm leaving zwavejs2mqtt at version 7.1.0 as it is working after re-interviewing.
(Reporting the status back to HA is broken still, but I don't think that is an issue with node-zwave-js as the correct status is shown in the zwavejs2mqtt dashboard.
I'll try to update HA tomorrow to see if that resolves the second part of the problem.)

If you need any more logging I can try to revert back to the previous version, but I hope I can leave it at this version for now.

EDIT: after restarting zwavejs2mqtt again after the re-interviewing, the reporting to HA is also working again.
So re-interviewing fully fixed my issues now.

**Comment by AlCalzone** [comment]
I'm confused now. Do they or do they not work after re-interviewing with 10.0.4?

> Reporting the status back to HA is broken still

That should be fixed in the 2022.9.0 release.

**Comment by wburgers** [comment]
Sorry, wasn't clear on my end.
Yes everything works now after re-interviewing.
I'm not getting any errors during re-interviewing. 🚀 

What was confusing to me was that I even had to re-interview in the first place, but I now understand that can sometimes resolve issues after a new version 👍.

**Comment by AlCalzone** [comment]
Yeah, 9.x queried and used some information incorrectly, but it was never noticed. 10.x now uses the information correctly, but the old and incorrectly queried information throws it off. Unfortunately, this can only be fixed by querying the information again, a.k.a re-interviewing.

**Comment by siwilson2000** [comment]
I can confirm that upgrading to 22.9.1 and the 0.1.70 add-on worked for me. I had to re-interview all my devices and so far so good. Thanks for the quick turnaround on this.
