### ISSUE TITLE
Missing device configuration: Intermatic PE653

### ISSUE THREAD

**Issue by bluemantwo** [AlCalzone/node-zwave-js#5020]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Need to prevent 3.9 firmware from being treated like 3.4.  Version 3.9 firmware needs to be treated like 3.3 firmware.  Do not exclude any nodes, which 3.4 version does. 

### Manufacturer ID

0x0005

### Product Type

0x5045

### Product ID

0x0653

### Firmware Version

3.9

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/89

**Comment by AlCalzone** [comment]
I don't understand. The compat flags are only applied to v3.4:
https://github.com/zwave-js/node-zwave-js/blob/abb881094c31f728158d7ae460144160624d90a4/packages/config/config/devices/0x0005/pe653.json#L70
