### ISSUE TITLE
Missing device configuration: Fakro AMZ Solar / Device ID 0x0085-0x0005-0x0012

### ISSUE THREAD

**Issue by Sennevds** [AlCalzone/node-zwave-js#5034]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

FAKRO AMZ Solar

### Manufacturer ID

0x0085

### Product Type

0x0005

### Product ID

0x0012

### Firmware Version

1.1

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/2627

### Do you have a manual?

[180302 AMZ SOLAR_US User Manual.pdf](https://github.com/zwave-js/node-zwave-js/files/9536615/180302.AMZ.SOLAR_US.User.Manual.pdf)

Note: the configuration exist already but for Product ID 0x0002 and 0x0112
https://devices.zwave-js.io/?jumpTo=0x0085:0x0005:0x0002:0.0
This configuration is working also for Product ID 0x0012

**Comment by AlCalzone** [comment]
@zwave-js-bot add fingerprint `0x0005:0x0012` to `0x0085:0x0005:0x0002:0.0`
