### ISSUE TITLE
Isses with floor sensor for thermostat

### ISSUE THREAD

**Issue by pittbull** [AlCalzone/node-zwave-js#5075]
I've installed 5 thermostats ([Namron](https://www.elektroimportoren.no/docs/lib/4512744-Brukerveiledning-5.pdf)) in my house and I am seeing issues with one in particular. 

These thermostats have two sensors: room and floor, snd can operate with only the floor sensor active or floor+room. 

The one with problems is the one running in floor-only mode. It seems to have issues with mapping the floor temperature to current temperatur and when adjusting the set point the thermostats only kicks in when passing the room temperature (even though running with floor only). 

I have tried multiple resets and inclusion without a new result. 

How can I isolate the problem?

**Comment by robertsLando** [comment]
Please attach driver logs

**Comment by AlCalzone** [comment]
Please make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file.

The logfile should highlight the interaction that isn't working as expected.

**Comment by pittbull** [comment]
Thanks. The node in question is number 78.

[zwavejs2mqtt_2022-09-15.log](https://github.com/zwave-js/node-zwave-js/files/9578574/zwavejs2mqtt_2022-09-15.log)

**Comment by AlCalzone** [comment]
Wrong log. 
![grafik](https://user-images.githubusercontent.com/17641229/190498769-edad1020-6a82-4a6c-86de-c32feacb3203.png)

**Comment by pittbull** [comment]
My bad.

[zwavejs_2022-09-16.log](https://github.com/zwave-js/node-zwave-js/files/9581048/zwavejs_2022-09-16.log)

**Comment by AlCalzone** [comment]
Ok, that is the interview. Do you also have a log of this?

> The logfile should highlight the interaction that isn't working as expected.

**Comment by pittbull** [comment]
Well, I am hard pressed at supplying what you need as I cannot point to a specific. The problem, as I observe it, is that the current temperature indicator is not being supplied from the floor sensor in the thermostat, but rather the room sensor.

Any suggestions on how I can gather what you need?

**Comment by AlCalzone** [comment]
Do you mean on the actual thermostat itself? Or in Home Assistant / Z2M / ...?
The first we have no influence over.

**Comment by pittbull** [comment]
I mean in HA/Z2M and how I can capture the information you require.

**Comment by pittbull** [comment]
This shows the temperatures the thermostat is monitoring,  and what is being represented in HA. The thermostat is set to floor-only mode and it reads 20.5. The temperature in HA is from what I can see taken from the room sensor.

This unit is placed outside a bathroom with floor heating on the inside - so it doesn't make sense to monitor the room temperature :)

![IMG_0752](https://user-images.githubusercontent.com/1532149/191078709-a70731db-a070-49e1-89e1-1c2a85168b00.JPG)
![IMG_0753](https://user-images.githubusercontent.com/1532149/191078712-2ca23980-e492-4a95-a6ea-be9668b5e17e.JPG)
![IMG_0756](https://user-images.githubusercontent.com/1532149/191078716-303337d4-231f-4d6f-853a-944150b1bb93.JPG)

**Comment by AlCalzone** [comment]
Looking at your last screenshot, it seems like both measurements reach the driver and z2m displays them both, correct?
Which would make this an issue for [Home Assistant](https://github.com/home-assistant/core/issues), not this repository.

I'm not sure though what they can do about this, since the floor sensor gets reported on a different endpoint, which is a different logical device according to the specification.

**Comment by pittbull** [comment]
I see. Thanks for the feedback. I will try with HA.

**Comment by kpine** [comment]
If there's a configuration parameter to determine which temperature sensor to read from (from the manual, appears that would be parameter 10?), the integration can be customized to read from a specific sensor and endpoint. That's how Heat-It thermostats are done. https://github.com/home-assistant/core/blob/1021c90bb8723fc827efd49abd472a8817d1ec9a/homeassistant/components/zwave_js/discovery.py#L399-L48

**Comment by pittbull** [comment]
> If there's a configuration parameter to determine which temperature sensor to read from (from the manual, appears that would be parameter 10?), the integration can be customized to read from a specific sensor and endpoint. That's how Heat-It thermostats are done. https://github.com/home-assistant/core/blob/1021c90bb8723fc827efd49abd472a8817d1ec9a/homeassistant/components/zwave_js/discovery.py#L399-L48


Interesting, thanks for sharing. @AlCalzone any comments?

Confirming parameter 10 for sensor selection.

**Comment by AlCalzone** [comment]
If that param exists, this is still an issue for the HA Core repo, but with a possible solution.
