### ISSUE TITLE
Able to perform many parallel re-interviews for battery devices

### ISSUE THREAD

**Issue by kpine** [AlCalzone/node-zwave-js#5101]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

I can submit an "unlimited" (not sure the real number, I tried around 50) re-interview requests to a sleeping node, and all requests are honored.

What do you observe?

The driver will perform all interview steps N times in parallel for every request.

What did you expect to happen?

The driver would ignore the duplicate requests and only perform one re-interview.

It can be reproduced in either HA w/the integration, or zwave-js-ui, but the former is easier if you want to issue a _lot_ of commands. Use re-interview in zwave-js-ui a few times for the same effect.

  1. Go to the device page in HA for a sleeping device
  2. Click on the '...' overflow menu
  3. Click re-interview
  4. Click "Start re-interview" as many times as desired, e.g. 50 times. Clicking on the button won't show much feedback, but it is sending the commands to the driver
  5. Wake up the sleeping device to being the interview
  6. Observe the driver is performing all N interviews at the same time

### Device information

Any sleeping device presumably.

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 10.2.0
`zwave-js-ui` branch: 8.0.0

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/9631093/zwavejs_current.log)

**Comment by AlCalzone** [comment]
yeah, I think the real number is whatever your machine can handle 🙈
