### ISSUE TITLE
Schlage/Allegion BE469 issues with S0 inclusion

### ISSUE THREAD

**Issue by jnperry** [AlCalzone/node-zwave-js#5103]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

I have a couple old BE469 locks (the ones that only support S0 security).

They would claim to successfully pair, but after that they wouldn't respond to any commands and wouldn't update any entities.

At the point of failure, the logs show the door ignoring incoming packets and replying/notifying with no encryption:
2022-09-23T05:28:54.154Z CNTRLR   [Node 020] command must be encrypted but was received without Security encapsu
                                  lation - discarding it...

It seems like the lock has decided to stop using encryption, which is why it wouldn't reply to encrypted incoming packets and sends everything back unencrypted. Looking further, it appears this happens exactly 10 seconds after the S0 bootstrap, which is the timeout in the zwave spec if S0 bootstrap fails.  But looking at the logs, S0 bootstrap did not fail (and in fact it works until that 10 seconds is over).

Guessing it could be some sort of race condition where the lock is getting hit too quickly and somehow neglects to disable the 10 second S0 bootstrap timer, I added some 1 second delays between each phase of the S0 bootstrap.

After dozens of failed inclusions, after making that change, it worked perfectly the first time I tried to include it.

I'm not sure there is a great fix here though. It feels icky to add manual delays between each phase.
But if someone else is having this problem, I thought it could be useful information.

### Device information

Manufacturer: Allegion/Schlage
Model name: BE469
Node ID in your network: 

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwave-js-ui` branch:

### Did you change anything?

yes (please describe)

### If yes, what did you change?

added a bunch of silly sleeps to secureBootstrapS0

             // Request security scheme, because it is required by the specs
            await new Promise(r => setTimeout(r, 1000));
            await api.getSecurityScheme(); // ignore the result
            // Request nonce separately, so we can impose a timeout
            await new Promise(r => setTimeout(r, 1000));
            await api.getNonce();
            // send the network key
            await new Promise(r => setTimeout(r, 1000));
            await api.setNetworkKey(this.driver.securityManager.networkKey);
            await new Promise(r => setTimeout(r, 1000));

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/9632124/zwavejs_current.log)

**Comment by AlCalzone** [comment]
Which of these inclusion attempts (I count 6) are with the additional timeout and which are without?

**Comment by AlCalzone** [comment]
Ok, I see the mentioned error message, it starts after the inclusion as Node 20. The logs show a successful S0 bootstrapping:
```
2022-09-23T05:28:39.815Z DRIVER « [Node 020] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -82 dBm
                                  └─[SecurityCCCommandEncapsulation]
                                    │ sequenced: false
                                    └─[SecurityCCNetworkKeyVerify]
```
and it continues to communicate securely:
```
2022-09-23T05:28:40.233Z DRIVER « [Node 020] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -83 dBm
                                  └─[SecurityCCCommandEncapsulation]
                                    │ sequenced: false
                                    └─[SecurityCCCommandsSupportedReport]
                                        reportsToFollow: 0
                                        supportedCCs:
                                        · Anti-Theft
                                        · Association
                                        · Basic
                                        · Battery
                                        · Configuration
                                        · Door Lock
                                        · Notification
                                        · User Code
                                        controlledCCs:
```

The only times I see the error message are for the response to querying config parameter 6. The ones before that are received with encryption. After not responding with encryption, the entire lock seems to choke.

```
2022-09-23T05:45:07.028Z DRIVER » [Node 021] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ callback id:      75
                                  └─[SecurityCCCommandEncapsulation]
                                    │ nonce id: 154
                                    └─[ConfigurationCCGet]
                                        parameter #: 5

2022-09-23T05:45:07.189Z DRIVER « [Node 021] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -82 dBm
                                  └─[SecurityCCCommandEncapsulation]
                                    │ sequenced: false
                                    └─[ConfigurationCCReport]
                                        parameter #: 5
                                        value size:  1
                                        value:       255

...

2022-09-23T05:45:07.282Z DRIVER » [Node 021] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ callback id:      78
                                  └─[SecurityCCCommandEncapsulation]
                                    │ nonce id: 30
                                    └─[ConfigurationCCGet]
                                        parameter #: 6

2022-09-23T05:45:12.139Z CNTRLR   [Node 021] command must be encrypted but was received without Security encapsu
                                  lation - discarding it...
2022-09-23T05:45:12.143Z DRIVER « [Node 021] [REQ] [BridgeApplicationCommand]                        [discarded]
                                  │ RSSI: -82 dBm
                                  └─[ConfigurationCCReport]
                                      parameter #: 6
                                      value size:  4
                                      value:       50331648

...

2022-09-23T05:45:17.405Z CNTRLR » [Node 021] querying parameter #7 value...
2022-09-23T05:45:17.423Z SERIAL » 0x010e00a9011502984025000000004ffc                                  (16 bytes)
2022-09-23T05:45:17.424Z DRIVER » [Node 021] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ callback id:      79
                                  └─[SecurityCCNonceGet]

2022-09-23T05:45:17.462Z DRIVER « [REQ] [SendDataBridge]
                                    callback id:            79
                                    transmit status:        OK, took 10 ms
                                    routing attempts:       1
                                    protocol & route speed: Z-Wave, 40 kbit/s
                                    ACK RSSI:               -81 dBm
                                    ACK channel no.:        1
                                    TX channel no.:         1
2022-09-23T05:45:27.528Z CNTRLR   [Node 021] Timed out while waiting for a response from the node (ZW0201)
```

So it's not that the lock isn't included correctly, but it seems that the S0 part of its firmware seems to crash reliably when querying config param 6 - notice how it doesn't even respond to NonceGet requests afterwards. The fact that it worked the 4th time after your edits may be a coincidence, or maybe not - you can't really know with Schlage locks. Their newer models are also buggy as ****.

In any case, I'm afraid there isn't anything we can do about it. Timing in the security bootstrapping processes is critical for spec-compliance. Changing it may throw off some less buggy devices.
