### ISSUE TITLE
🚧 Maintenance Notification 🚧

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#5129]
![banner_image_1](https://user-images.githubusercontent.com/17641229/192778079-882cffd1-4b74-431d-99aa-d0c98516f3b8.png)

# I'll be on paternal leave for the rest of 2022

**This means ...**
... I won't respond to issues, unless I need to kill some time
... PRs adding new features won't get merged
... PRs contributing bugfixes will have to wait until I find some time reviewing them (no guarantees!)
... PRs concerning configuration files will have to wait for @blhoward2 to find some time reviewing them
... patch releases can be done by @robertsLando if necessary

**In case of emergency** (and I need to fix it), you can likely reach me on the [zwave-js Slack](https://join.slack.com/t/zwave-js/shared_invite/zt-8ns655f6-d407vtI~KjU~1z11jyaQ9Q)

---

Take care and see you in 2023 &ndash; I've still got big plans for Z-Wave JS!
_&ndash; AlCalzone_

**Comment by robertsLando** [comment]
Congrats mate! 😍  Enjoy every second of it  ❤️ Will take care of your other baby (zwave-js) in the meanwhile 💪🏼
