### ISSUE TITLE
[question] My switch does not work in v7.0.0 and later versions.

### ISSUE THREAD

**Issue by jsj0318** [AlCalzone/node-zwave-js#5132]
Hello.
First of all, I apologize for my poor English.

SWITCH : Dawon DNS Zwave Switch

I am inquiring because the switch that worked well before zwavejs2mqtt v6.14.1 has not been working since the update.

v6.14.1 and earlier debug log (work good)
---------------------------------------------------------------------------------------------------------------------
2022-09-29 08:40:50.575 INFO ZWAVE: Node 39: value updated: 37-1-currentValue false => true
2022-09-29 08:40:50.581 INFO ZWAVE: Node 39: value updated: 37-1-targetValue false => true
2022-09-29 08:40:50.615 INFO ZWAVE: Node 39: value updated: 113-1-alarmType 0 => 0
2022-09-29 08:40:50.619 INFO ZWAVE: Node 39: value updated: 113-1-alarmLevel 0 => 0
2022-09-29 08:40:50.639 INFO ZWAVE: Node 39: value updated: 113-1-Power Management-Mains status 2 => 3
2022-09-29 08:40:52.986 INFO ZWAVE: Node 39: value updated: 37-1-currentValue true => true

v.7.0.0 and later versions debug log (not work)
---------------------------------------------------------------------------------------------------------------------
2022-09-28 16:54:41.269 INFO Z-WAVE: Calling api writeValue with args: [
  {
    nodeId: 39,
    commandClass: 37,
    endpoint: 1,
    property: 'targetValue'
  },
  true,
  {},
  [length]: 3
]

The sensor values for that switch are displayed well.
Is there anything I need to check? Is there any more information I need to tell you?

Thank you.

**Comment by robertsLando** [comment]
Please try to re-interview your device

**Comment by jsj0318** [comment]
> Please try to re-interview your device

I tried it several times, but it didn't work.
exclusion and Inclusion same.

**Comment by robertsLando** [comment]
@jsj0318 Try uploading driver logs so please

**Comment by AlCalzone** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by jsj0318** [comment]
I am attaching the log file you mentioned.

The node number of the non-operating switch is
35, 38, 39, 51. The on-off test was done with node 51.

v6.14.1 (work good)
[work_good.log](https://github.com/zwave-js/node-zwave-js/files/9681993/work_good.log)


v.8.0.1 (not work)
[not_work.log](https://github.com/zwave-js/node-zwave-js/files/9682000/not_work.log)

thanks.

**Comment by AlCalzone** [comment]
Looks like the switch does not actually support Supervision CC, although it probably reports support for it. To disable supervision for that device, I need the device fingerprint (0x...-0x...0x....) that you find in the UI in the device panel.

**Comment by jsj0318** [comment]
> 
I don't know if the fingerprint you mentioned is correct, but I attach it.

0x018c-0x0065-0x0001

**Comment by AlCalzone** [comment]
I don't think we even have a config file for that.
Can you show a screenshot how it is currently recognized?

Do you have more info about it, like a manual and a link to the Z-Wave Alliance page for it?
I've found those three, but all of them have a different fingerprint:
https://products.z-wavealliance.org/products/1607?selectedFrequencyId=17
https://products.z-wavealliance.org/products/2532?selectedFrequencyId=17
https://products.z-wavealliance.org/products/2531?selectedFrequencyId=17

**Comment by jsj0318** [comment]
> 

Here's a screenshot

v6.14.1 (work good)
![work_good](https://user-images.githubusercontent.com/13990821/193394904-1255b0ef-e9a3-4b18-8c7f-c7e9cdb9d757.jpg)

v.8.0.1 (not work)
![not_work](https://user-images.githubusercontent.com/13990821/193394915-07fc2b12-5122-4029-b7ec-a01479614438.jpg)

Product Photo
![20221001_144538](https://user-images.githubusercontent.com/13990821/193395017-d4d9f6c9-4d53-4d76-acf0-3be15597984a.jpg)
translation
Product name: Electronic switch
Model name: PM-S240-ZW
Rating: 220V ~, 60Hz, Light 1200W (600W per circuit)
KC certification: HU02100-19003
Identification code: R-C-DaW-SSD-305
Manufacturer: Top Intercube/Vietnam

![switch](https://user-images.githubusercontent.com/13990821/193395018-72043b2a-c1dc-4d2a-a996-bbb2e76670c5.JPG)

Manual Photo
![20221001_150417](https://user-images.githubusercontent.com/13990821/193395304-b6fecc8d-e50a-465b-877c-ac9bdc71a4f2.jpg)

![20221001_150433](https://user-images.githubusercontent.com/13990821/193395307-b2d19377-5ba3-4214-89c6-3c2b2304fbe7.jpg)

I can't find in the Z-Wave Alliance.

**It's a frequency model in the US.**

Hope this helps.

thank you

**Comment by AlCalzone** [comment]
Ok it's also not detected as a known device so far. I know what we need to do to make it work but I'd really like to identify the device correctly. Your manual seems to be for 3 devices:
- pm-s140-zw
- pm-s240-zw
- pm-s340-zw

Which of those do you have?

**Comment by AlCalzone** [comment]
Should be fixed in the next release. You will have to re-interview the device after updating.

**Comment by jsj0318** [comment]
> Should be fixed in the next release. You will have to re-interview the device after updating.

Could you also add product types 57-59, 61-66?

LG U+ model : 1switch( prdNo 57), 2switch (prdNo 58), 3switch (prdNo 59)

Frequency Korea model: 1switch(prdNo 61), 2switch(prdNo 62), 3switch(prdNo 63)

Frequency US model: 1switch(prdNo 64), 2switch(prdNo 65), 3switch(prrNo 66)

Thank you for the update.

**Comment by AlCalzone** [comment]
Same manufacturer ID and product ID (first and third part of the fingerprint)?
Also could you give me the full device name for each of those like you did with the other one?

**Comment by jsj0318** [comment]
> Same manufacturer ID and product ID (first and third part of the fingerprint)?
> Also could you give me the full device name for each of those like you did with the other one?

Yes. It's Same.

My 3Button Switch Screenshot
![3button](https://user-images.githubusercontent.com/13990821/193417903-c4039d0e-28bd-4f6b-9d14-68893d57da1c.jpg)

Device Name is 
1Button: PM-S140-ZW
2Button: PM-S240-ZW
3Button: PM-S340-ZW

I have only 2 buttons and 3 buttons for Frequency US, so I can't check screenshots of other products..
