### ISSUE TITLE
Missing device configuration: Nexia  ZSENS930A

### ISSUE THREAD

**Issue by seajack0** [AlCalzone/node-zwave-js#5141]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Nexia 

### Manufacturer ID

0x0178

### Product Type

0x5253

### Product ID

0x5433

### Firmware Version

1.63

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/1939?selectedFrequencyId=2

### Do you have a manual?

Link to manual [https://wdi.rfwel.com/cdn/techdocs/ZSENS930AW00MAnual.pdf](url)

This device appears to be identical to [TH100NX](https://devices.zwave-js.io/?jumpTo=0x0178:0x5448:0x3130:0.0)

Thanks!

**Comment by seajack0** [comment]
Added configuration and submitted pull request.

**Comment by AlCalzone** [comment]
Let's keep this open until the PR is reviewed and merged
