### ISSUE TITLE
Controller does not respond in Health check

### ISSUE THREAD

**Issue by nocodehummel** [AlCalzone/node-zwave-js#5150]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug? 
Unfortunately I decided to move to 700 series at the same time I changed from OpenHab to Home Assistant.
I do however suspect that the 700 series is the cause of the problem.
I first tried a Razberry 7 shield and now a Aeotec Z-Pi 7.

What do you observe?
I tried to pinpoint the problem with a health check in which case the controller just does not respond to a Z-Wave+ device at about 5 meters from the controller. 

What did you expect to happen?
I would expect the controller to respond to the message from the device with latency between 10-100ms.

  1. Go to 'Network Graph' in Z-Wave JS UI.
  2. Click on 'Reload Graph' and select a device.
  3. Start 'Health check' with target node Aeotec P-Zi 7 controller.
  4. Often the success rating is 0/10.

### Device information

Manufacturer:  Aeotec
Model name: Z-Pi 7 shield (ZST10-700)
Node ID in your network: 1 (controller)

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

HA version: 2022.10.1
`zwave-js-ui`: 8.1.0
`zwave-js`: 10.3.0

### Did you change anything?

yes (please describe)

### If yes, what did you change?

I started with a new setup based on Home Assistant and a 700 series controller. The Z-Wave network previously worked better with a 500 series controller. The devices in the network are not changed or moved.

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwavejs_2022-10-08.log](https://github.com/zwave-js/node-zwave-js/files/9740175/zwavejs_2022-10-08.log)

**Comment by AlCalzone** [comment]
Sorry for the late response - this one slipped through the cracks. I agree with your assessment that the 700 series controller is likely the culprit.
