### ISSUE TITLE
Zooz Outdoor Motion Sensor ZSE29 - SupervisionCCReport fails - cannot change device configuration values

### ISSUE THREAD

**Issue by robertvorthman** [AlCalzone/node-zwave-js#5157]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

The Zooz Outdoor Motion sensor, ZSE29, does not appear to support supervision command class.  Attempting to update any value, such as setting motion sensitivity from 10 to 9, fails and the value returns to the previous value.  I see an error about SupervisionCCReport in the logs when attempting to update values.

```
2022-10-12T01:17:32.939Z DRIVER « [Node 091] [REQ] [BridgeApplicationCommand]
│ RSSI: -71 dBm
└─[Security2CCMessageEncapsulation]
│ sequence number: 188
└─[SupervisionCCReport]
session id: 4
more updates follow: false
status: Fail
duration: 0s
2022-10-12T01:17:32.951Z CNTRLR [Node 091] [setValue] result of SET_VALUE API call for ConfigurationCCAPI: (Su
pervisionResult)
status: Fail
2022-10-12T01:17:32.952Z CNTRLR [Node 091] [setValue] not updating value
```

This issue seems similar to issue #5139 and pull #5008.

### Device information

Manufacturer: Zooz
Model name: ZSE29
Node ID in your network: 92

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: Z-Wave JS UI Add-on version: 1.1.0
`node-zwave-js` branch: 10.3.0
`zwave-js-ui` branch: 8.1.0

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

A few months ago I was able to update the values on my ZSE29.

### Attach Driver Logfile

See last 80 lines.  I attempt to update parameter 3 to a 9 but it reverts back to 10.
[zwavejs_current (1).log](https://github.com/zwave-js/node-zwave-js/files/9761096/zwavejs_current.1.log)

**Comment by robertvorthman** [comment]
Work-around successful.  I created a [custom device file](https://zwave-js.github.io/zwave-js-ui/#/device-support/custom-device-files) by copying the ["compat" value from the ZSE19 device file](https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x027a/zse19.json#L44).  Z-Wave JS UI loads the custom file, I re-interviewed my ZSE29, and now I can once again update my motion sensor configuration values.


![zse29-patch](https://user-images.githubusercontent.com/4665046/195247050-dbabe220-4830-4d29-b40d-35d40b0c6f2a.png)

**Comment by AlCalzone** [comment]
We should let Zooz know about this.

**Comment by AlCalzone** [comment]
@robertvorthman Could you open a PR with your changes please?

**Comment by robertvorthman** [comment]
I just submitted PR #5159 with the updated device config file.

I started an email support ticket with Zooz yesterday, assuming it was an isolated problem with my device.  When I found the root cause, I emailed them a link to this Github issue.  I will email them back and ask them to notify their engineering team.  Would the goal be for Zooz to update their firmware?

**Comment by AlCalzone** [comment]
> Would the goal be for Zooz to update their firmware?

Yeah, exactly.
