### ISSUE TITLE
Z-wave JS no longer scans parameters list from Aeotec 700 series devices

### ISSUE THREAD

**Issue by iCSpotRun** [AlCalzone/node-zwave-js#5185]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Unknown.

What do you observe?
Parameter values are missing when interrogating the MultiSensor 7 from Aeotec. Support engineer has confirmed that this affects their other 700 series devices as well. A user can, however, make an adjustment to a value and that value will stick. Re-interviewing does not fix issue.

What did you expect to happen?
Values should be present

  1. In Home Assistant, go to 'Z-wave JS integration -> Devices -> Aeotec 700 device' (mine is the MultiSensor 7)
  2. Click on 'Configure'
  3. 'Notice that all parameter fields are empty'
<img width="667" alt="Screenshot 2022-10-31 at 9 22 15 AM" src="https://user-images.githubusercontent.com/6014317/199044442-b0adcd8d-96ab-4b31-a75d-38f1b18e0481.png">

### Device information

Manufacturer: Aeotec Ltd.
Model name: ZWA024
Node ID in your network: 12

Though Aeotec support has confirmed to me that this affects all their 700 series devices.

### How are you using `node-zwave-js`?

- [x] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
JS Server:  1.24.0
Z-Wave JS: 10.3.0

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Cannot recall what version of HA/Z-wave JS, but this worked earlier in the year.

### Attach Driver Logfile

See Log below in follow-up messages.

**Comment by AlCalzone** [comment]
What the bot said. This log snippet is incomplete. And please attach the logfile through drag and drop.

**Comment by iCSpotRun** [comment]
[zwave_js.log](https://github.com/zwave-js/node-zwave-js/files/9912241/zwave_js.log)

Log attached. In this log, I triggered Motion and manually adjusted Parameter 4 values from: Blank -> 11 -> 10 -> 11

Here here is a screenshot of the interface. Note that Param 4 now has a value where all others are still Blank

<img width="698" alt="Screenshot 2022-11-01 at 10 25 54 AM" src="https://user-images.githubusercontent.com/6014317/199285948-35254e9e-5235-44d7-b481-1ce71dcc8d0d.png">

**Comment by cadwizzard** [comment]
I also saw this behaviour. I solved it by moving the sensor within good direct connection range of 1m and re-interviewing. 
trying to re-interview at distance/over repeaters always left the fields empty. The sensor worked otherwise as expected though. I tried several times with the same results. On 2 sensors.

I also saw that trying to Smartstart include this sensor never worked, resulting in 3 new z wave nodes being created, but none configuring as the sensor, this was within 1m of the controller. I tested this several times, but the nodes keep incrementing x3, so tried manual inclusion, then it was fine,
The sensors were on the latest 1.4.1 firmware
( Pi4 / HA / Z-Stick 7- latest firmware )

**Comment by iCSpotRun** [comment]
I tried re-interviewing numerous times with the sensor only 1m from the radio and still no luck with the config parameters. I even excluded and included at this distance. I am using the Home Assistant Z-wave JS integration. Not sure how to do any other type of inclusion. I tried with Z-wave JS UI, but getting some strange serial port error when setting up the Z-wave controller.

**Comment by iCSpotRun** [comment]
Ok, got past the Z-wave JS UI serial port issue. I started completely from scratch and followed the UI inclusion process with the sensor no more than 1m away from the radio. Still no parameters :(

**Comment by kpine** [comment]
You should provide debug logs of the inclusion or a re-interview.

**Comment by iCSpotRun** [comment]
[zwavejs_2022-11-07.log](https://github.com/zwave-js/node-zwave-js/files/9955996/zwavejs_2022-11-07.log)

Ask requested. Inclusion via Z-wave JS UI with sensor only 1m away from radio. I did this numerous times to be sure. Configuration parameters still missing.

I think this may have something to do with security. Forced "no encryption" during inclusion and the Parameters are now present.

**Comment by iCSpotRun** [comment]
[zwavejs_2022-11-07-1.log](https://github.com/zwave-js/node-zwave-js/files/9956032/zwavejs_2022-11-07-1.log)

Here's the log with Inclusion on "No Encryption". Parameters getting pulled in successfully.

**Comment by iCSpotRun** [comment]
Additional info. I tried this with Zooz Stick and Aeotec Z-stick 7. Latest firmware: 7.18.1
Same results :(

**Comment by AlCalzone** [comment]
> [zwavejs_2022-11-07.log](https://github.com/zwave-js/node-zwave-js/files/9955996/zwavejs_2022-11-07.log)
> 
> Ask requested. Inclusion via Z-wave JS UI with sensor only 1m away from radio. I did this numerous times to be sure. Configuration parameters still missing.

That log still contains no inclusion at all.

> I think this may have something to do with security. Forced "no encryption" during inclusion and the Parameters are now present.

It may, but I can't tell why without a proper logfile.

**Comment by iCSpotRun** [comment]
@AlCalzone I think I enabled the wrong log file. I did it under Settings - Z-wave rather then Settings - General.

I will redo when I am back home later this week. Thanks.

**Comment by iCSpotRun** [comment]
Ok, let's try this again. This time with proper log:

[z-ui_2022-11-17.log](https://github.com/zwave-js/node-zwave-js/files/10034255/z-ui_2022-11-17.log)

**Comment by kpine** [comment]
Need driver debug logs, not application logs. The previous file was correct, but had no inclusion activity.

https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs

**Comment by iCSpotRun** [comment]
How about this? Thanks for your patience.

[zwave-js-ui-store.zip](https://github.com/zwave-js/node-zwave-js/files/10035214/zwave-js-ui-store.zip)

**Comment by MartinHjelmare** [comment]
I'm also seeing weird behavior from this device (firmware version 1.1.1, driver version 10.3.0) after S2 inclusion. This device is at level 2 in my house and my controller is in the basement. Maybe it's just a bad connection?

The configuration parameter values are missing from the config panel in Home Assistant after secure inclusion. After one inclusion with S2 the device didn't update measurements or trigger on motion. After an exclusion and second S2 inclusion it now reports on motion but configuration parameter values are still missing. There were also unexpected values (entities) reported after the second inclusion. These values were gone after a re-interview.

Inclusion attempt 2 with S2:
[zwave_js_inclusion_s2_multisensor_7_20221216.log](https://github.com/zwave-js/node-zwave-js/files/10246143/zwave_js_inclusion_s2_multisensor_7_20221216.log)

Including without security makes the device behave as expected.

Inclusion attempt 3 without security:
[zwave_js_inclusion_no_security_multisensor_7_20221216.log](https://github.com/zwave-js/node-zwave-js/files/10246220/zwave_js_inclusion_no_security_multisensor_7_20221216.log)
