### ISSUE TITLE
Firmware update oddity in 8.2.2

### ISSUE THREAD

**Issue by jonathanweinberg** [AlCalzone/node-zwave-js#5187]
Hi folks! I'm running the latest release of zwave-js-ui (within a current version of Home Assistant, but this issue is directly observable within the zwave-js-ui element).

Previously, I had been trying to update one of my Inovelli | Red Series Dimmer | LZW31-SN dimmers. I have several updated by manually updating them with an entirely separate infrastructure.

On the last version, it would attempt to update, show `100` in the UI and claim both updates were complete in the logs, but after refreshing values, they were not incrementing to the latest versions. 

- Tried a power cycle of the dimmer itself, no change, and the dimmer still responds normally/stays the same version in the UI (as well as in the logs). 
- Tried to re-interview the node, no change.

Now in the current 8.2.2 version it still shows the outdated version (1.56 vs. 1.57) and now no longer shows a firmware update is available for it:
![image](https://user-images.githubusercontent.com/2151251/197870757-c288936d-6bf2-47ec-9f61-e5e2ad62ca6d.png)

When looking at the values for the version *on the affected dimmer* it shows:
![image](https://user-images.githubusercontent.com/2151251/197871295-df5613f9-352f-48c4-8d02-ccbd24be43af.png)

By comparison, these are the values for a dimmer I updated externally:
![image](https://user-images.githubusercontent.com/2151251/197871493-68542772-a9aa-4315-aaae-ec25e433a99b.png)

In the UI if I try an Advanced -> Manual firmware update, it also now shows targets oddly:
![image](https://user-images.githubusercontent.com/2151251/197871812-59dbdd35-782c-4953-aa9d-cef95cd74251.png)
- Before 8.2.2 it showed Target 1 and Target 0.
- Now it shows Target 0 and Target 4660

On a previously externally updated dimmer it only shows one target now:
![image](https://user-images.githubusercontent.com/2151251/197871675-f133e84e-9926-4024-8052-4d9714293dbc.png)

Any dumps / logs I can grab for you?

**Comment by kpine** [comment]
> Now in the current 8.2.2 version it still shows the outdated version (1.56 vs. 1.57) and now no longer shows a firmware update is available for it:

For this, firmware updates for the LZW31-SN via the update service were temporarily pulled because the update doesn't work.

**Comment by robertsLando** [comment]
Targets you see there are targets reported by the device. I have no clue what could be wrong here as I think it's something on zwavejs side. Please attach zwave-js [driver logs](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=generating-log-files) with an update try to see if there is something wrong happening here

**Comment by josh-m-sharpe** [comment]
@kpine is there another thread somewhere about temporarily pulled update process?  just want to follow it so i know when it's available.  Thanks!

**Comment by josh-m-sharpe** [comment]
@robertsLando assume you want something like:
```
zwavejs2mqtt    | 17:04:20.990 CNTRLR   [Node 101] Interviewing Firmware Update Meta Data...
zwavejs2mqtt    | 17:04:20.991 CNTRLR �� [Node 101] Querying firmware update capabilities...
zwavejs2mqtt    | 17:04:21.070 CNTRLR �� [Node 101] Received firmware update capabilities:
zwavejs2mqtt    |                         firmware targets:      0, 4660
zwavejs2mqtt    |                         continues to function: unknown
zwavejs2mqtt    |                         supports activation:   unknown
```

**Comment by kpine** [comment]
The firmware update service is open source and on github. https://github.com/zwave-js/firmware-updates/

**Comment by AlCalzone** [comment]
@josh-m-sharpe https://github.com/zwave-js/firmware-updates/pull/39

**Comment by AlCalzone** [comment]
Duplicate of #5081

(closing for housekeeping purposes, one issue about this is enough)
