### ISSUE TITLE
August Pro inclusion doesn't set up S2 security, interview times out

### ISSUE THREAD

**Issue by trainman419** [AlCalzone/node-zwave-js#5194]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### What causes the bug?
When including an August Pro smart lock on my Zwave network, using the Z-Wave JS UI, the inclusion shows the S2 DSK and asks for the S2 PIN (most of the time), but when the pairing is complete, the August app warns that the lock was paired insecurely, and the Z-Wave JS UI shows that the lock does not support security.

The interview process appears to fail, as the lock manufacturer, product, product code and firmware are not detected. The log contains errors about interview steps timing out.

I'm unable to control the lock.

I've found that if I do not select the security mode quickly enough during pairing, I am not prompted for the S2 PIN.

I'm not certain if this is a Z-Wave JS or Z-Wave JS UI bug, but since this seems to affect the implementation of S2 inclusion more than the UI, I'm reporting it here.

I'm using Z-Wave JS with HomeAssistant, but my issue seems to be with the Z-Wave JS inclusion process.

I'm fairly comfortable with docker and python, but not very familiar with the Z-Wave protocol internals. I'm happy to build my own docker image and try patches or experiments to help troubleshoot.

### What do you observe?

Lock not detected correctly:
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/103991/200147536-c63027fa-ca2a-4cd0-8d8d-0cfb101a38f2.png">

August app warning:
![signal-2022-11-05-164658](https://user-images.githubusercontent.com/103991/200147564-fe4c3a50-07a1-490b-9577-89fe112493b6.jpeg)

Z-Wave JS log from pairing:
[august_pairing.log](https://github.com/zwave-js/node-zwave-js/files/9944907/august_pairing.log)

### What did you expect to happen?
I would expect S2 keys to be correctly set up during pairing, and that the interview would complete successfully.

  1. Ensure that your August Pro lock is not associated with a Zwave network.
  2. From Z-Wave JS UI, go to Actions -> Manage Nodes
  3. Select Inclusion and click Next
  4. Enter the device name and location, and click Next. I'm using Name "Front Door Lock" and Location "Front Entry" but I don't think these matter.
  5. Open the August app (I'm using the iPhone app) and navigate to Lock Settings.
  6. In the August app lock settings, select "Z-Wave Setup"
  7. In the August app, select "Add to a Z-Wave Network"
  8. In the Z-Wave JS UI, select Default and click Next
  9. In the August app, select "My Hub is in inclusion mode"
  10.  In Z-Wave JS, Inclusion should proceed to "Security Classes"
  11. In Z-Wave JS, select only S2 and click Next
  12. In Z-Wave JS, enter the device's S2 PIN and click Next
  13. Inclusion should complete.
  14. The August app should show the Security Alert
  15. Observe that the August Lock Pro is not enumerated properly in the Z-Wave JS UI.

I've found that if I don't click through the "Security Classes" prompt quickly enough, it does not prompt me for a S2 PIN, and instead shows that the node was added with security "None"

### Device information

Manufacturer: August
Model name: Smart Lock Pro
Node ID in your network: 82 (changes each time I try inclusion, so some of the screenshots may be inconsistent)

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 10.3.0
`zwave-js-ui` branch: 8.3.0.d050453

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

Log snippet from one pairing attempt:
[august_pairing.log](https://github.com/zwave-js/node-zwave-js/files/9944907/august_pairing.log)

Complete log file from today.
WARNING: I've been setting up a number of other devices, so there's a lot of other irrelevant noise in here. You asked for it, so have at it!
[zwavejs_2022-11-06.log](https://github.com/zwave-js/node-zwave-js/files/9944931/zwavejs_2022-11-06.log)

**Comment by AlCalzone** [comment]
The problem is that the lock doesn't follow the S2 specs correctly. The issue is here:
![grafik](https://user-images.githubusercontent.com/17641229/201466538-f5783ca9-dca6-448f-b209-5d61bb3cefb2.png)

specifically this part:
![grafik](https://user-images.githubusercontent.com/17641229/201466585-14b39a13-c19c-4ff9-9426-e23d9bab7d0c.png)

The logs show that the frame is sent exactly once, before we can decrypt it (no PIN entered yet) and after 240s Z-Wave JS times out.

**Comment by AlCalzone** [comment]
The interview timeout happens, because no encryption is used, yet the lock requires encryption to communicate.

**Comment by trainman419** [comment]
What do you think I should do?

Should I open a support ticket with August and try to get them to fix their firmware? It seems like their support team has not been super responsive, but I also haven't seen a bug report this specific, either.

Is it possible to modify Z-Wave JS or the Z-Wave JS UI so that I can enter the PIN code or the key before the pairing process starts, so that Z-Wave JS is able to decrypt the first KEX Set message?

I used to be able to use this lock without security enabled, but that doesn't seem to work any more; I suspect a recent firmware update disabled that functionality.

**Comment by AlCalzone** [comment]
> Should I open a support ticket with August and try to get them to fix their firmware?

IMO that's the way to go. Or return it if they won't help. From what I've heard, August aren't the most reliable.

Side note: mentioning this to the Z-Wave Alliance might also be a way to put pressure on August. I assume the lock is certified but this behavior is in violation of the specs.

> Is it possible to modify Z-Wave JS or the Z-Wave JS UI so that I can enter the PIN code or the key before the pairing process starts, so that Z-Wave JS is able to decrypt the first KEX Set message?

No but if the lock (and your stick) supports SmartStart, you can scan a QR code and have the inclusion automated, side-stepping the issue.

**Comment by trainman419** [comment]
Sadly, my lock doesn't support SmartStart, so that option is a non-starter for me.

I've submitted a support request to August; I'm hoping that they'll be able to make progress with the info here.

**Comment by wystewart** [comment]
I managed to get a August smart lock pro (3rd gen) to include with S2.  I was having the same problem, it would not include with S2 only S0.  What I did was to use the inclusion function of the Zwave-JS GUI / Control Panel, then enter the DSK number from the lock during inclusion.  It included as S2 and correctly noted the manufacturer.

**Comment by trainman419** [comment]
@wystewart interesting. Did you use the full DSK or the 5-digit DSK prefix included on the lock?
Which version of Zwave-JS and the Zwave-JS GUI are you using?
Which firmware version do you have on your August lock?

**Comment by wystewart** [comment]
latest version of Z-Wave JS UI  addon (1.4.0), the JS integration shows Driver Version: 10.3.1, Server Version: 1.24.1 
just the 5 digit, that is all the add-on asked for.    the lock app says 1.59.0-2.0.4.  Bit confusing the fw version, I believe the latest is 2.0.4, but the 1.59.0 is confusing.
In the Z-wave JS UI, click on the right, ACTIONS->MANAGE NODES then select INCLUSION.
But sure to have the lock close to the zwave hub so there are no errors in transmission,  In my experience zwave is not reliable when nodes are far until it has built the network mesh

Got a feeling if I did inclusive through the integration and entered the DSK it would probably work too.  I skipped that everytime I tried before.

**Comment by AlCalzone** [comment]
How did you skip entering the DSK?

**Comment by wystewart** [comment]
don't recall, but any case it seems to be needed to have S2

**Comment by AlCalzone** [comment]
Yeah, the only exception is S2 Unauthenticated, which is not to be used by locks.
