### ISSUE TITLE
Double tap not supported on Honeywell/Jasco 39348 switches

### ISSUE THREAD

**Issue by manonstreet** [AlCalzone/node-zwave-js#5209]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Missing configuration values in the Honey/Jasco 39348 config file

`"treatBasicSetAsEvent": true` needs to be added to the compat section of the [device config file](https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0039/39348_39455_zw4005.json)

What do you observe?
Double taps are not available for this device, but are for similar jasco/ge switches

What did you expect to happen?
An event to be fired upon double tap

1. Double tap a 39348 light switch on or off
2. Click examine the logs
3. Notice that double taps send property currentValue updates as opposed to property event

### Device information

Manufacturer: Honeywell/Jasco
Model name: 39348
Node ID in your network: 29, 32, and 51

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 10.3
`zwave-js-ui` branch: 8.4.1

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

It worked with openzwave before switching to this package.

### Attach Driver Logfile

Not applicable.  Empty log supplied.

```
N/A
````

**Comment by AlCalzone** [comment]
@zwave-js-bot add compat flag to `0x0039:0x4952:0x3036`
```jsonc
		"treatBasicSetAsEvent": true
```
