### ISSUE TITLE
Aeon Labs Garage Door Controller Gen5

### ISSUE THREAD

**Issue by TorbjornZachrisson** [AlCalzone/node-zwave-js#5219]
I´m running Zwave2mqtt in a docker container, The latest working version for my barrier operator is container with zwavejs2mqtt 6.8.0 and Z-wave JS 9.0.6. All later versions do not have a working barrier operator for the Aeon Labs Garage Door Controller Gen5. Unfortunately I do not know if it´s the zwavejs2mqtt or Z-wave JS  that has the problem.

Kind regards
Z

**Comment by robertsLando** [comment]
Please attach zwave-js [driver logs](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=generating-log-files) whit latest zwave-js version. Mind that it could be you just need to reinterview your device after the upgrade in order to make it work.

**Comment by TorbjornZachrisson** [comment]
Tried reinterview but it goes on forever. Goes fast with old version. 
[Node 010] Error during node interview: subsystemType is not a SubsystemType (
                                  ZW0322)
[zwavejs_2022-11-24.log](https://github.com/zwave-js/node-zwave-js/files/10087145/zwavejs_2022-11-24.log)

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by laguinch** [comment]
[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/10354339/zwavejs_current.log)
[zwavejs_2023-01-05.log](https://github.com/zwave-js/node-zwave-js/files/10354348/zwavejs_2023-01-05.log)
[z-ui_2023-01-05.log](https://github.com/zwave-js/node-zwave-js/files/10354353/z-ui_2023-01-05.log)
Hy, I have also a problem with the module, the interview don't finish. Nodeinfo always turn
Thanks for your help

**Comment by AlCalzone** [comment]
This should be fixed by https://github.com/zwave-js/node-zwave-js/pull/5465, which is included in v10.11.0

**Comment by TorbjornZachrisson** [comment]
Yes this works now. Many thanks!
