### ISSUE TITLE
[question] Possible to add a second controller

### ISSUE THREAD

**Issue by Slyke** [AlCalzone/node-zwave-js#5221]
Hello, is it possible to add a second master using zwaveJS somehow? I have a Zooz USB controller connected to Home Assistant running zwaveJS (main controller), but also have an old mini pc running zwaveJS with a Aeotec USB adapter plugged into it. I want to add the Aeotec controller to the network too so that it can act as a backup/secondary controller that passes zwave data to MQTT. I've tried to Include it, but it doesn't want to associate.

I couldn't find anything in the UI that would do it, but figured there's probably some script that can be pasted into the Driver function section that could do it. I don't know enough about the MQTT protocol or zwaveJS to do this myself without starting from scratch and spending a lot of time on it.

**Comment by robertsLando** [comment]
Unfortunately this is still not supported by zwave-js

**Comment by Slyke** [comment]
Hmmm, is there another way to add it without zwave-js, and would zwave-js handle it? There'd need to be 2 instances of zwave-js running, one on both machines.

**Comment by AlCalzone** [comment]
Many devices only support a single lifeline association, so this won't work like you want it to.

The secondary controller won't receive value updates.

**Comment by Slyke** [comment]
Hey @AlCalzone I was reading this and it should be possible in theory: https://www.vesternet.com/en-global/pages/understanding-z-wave-networks-nodes-devices

It mentions that only the primary master can include new slave devices, but secondary controllers act as primary controllers in all other aspects. The secondary controllers just need to have the same Home ID as the primary controller (and obviously same network).

**Comment by AlCalzone** [comment]
I mean you can add another stick as a controller and it will be able to control devices.

As I wrote above though, you won't get updates from a lot of devices, so the local state won't be correct.

And in addition, zwave-js assumes it is the primary controller and changes the lifeline associations accordingly, so this will be another problem.

**Comment by Slyke** [comment]
I don't mind giving it a try out and see what happens. Just unsure how to actually add the second controller. Is it possible to do with a Driver function? Or do I just need to run some CLI commands with the stick and it'll work then? Running CLI commands is troublesome since the HA OS is so locked down.

**Comment by AlCalzone** [comment]
You'll need to use Silabs' PC Controller or another software that supports being the secondary.
