### ISSUE TITLE
Associations are duplicated for root endpoint

### ISSUE THREAD

**Issue by Roagert** [AlCalzone/node-zwave-js#5222]
Noticed after assigning the right associations with my devices it seems to duplicate the associations to endpoint 0 ?

Looks to be duplicating something:
![image](https://user-images.githubusercontent.com/33527165/203326583-3d38b33d-62cb-410b-80fb-068c18c38e1d.png)

[zwave-js-ui-store.zip](https://github.com/zwave-js/zwave-js-ui/files/10067833/zwave-js-ui-store.zip)

I dont know if the logs is showing anything here related to endpoint 0 duplicate but this is the latests logs i have.

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by Roagert** [comment]
I just tried to delete the 0 node to associations and it kept my original endpoint associations but removed the actually association from the device so i have to re do the associations

**Comment by Roagert** [comment]
[zwave-js-ui-store.zip](https://github.com/zwave-js/node-zwave-js/files/10420444/zwave-js-ui-store.zip)
i have attached latest log here
