### ISSUE TITLE
Eurotronic Spirit ZWave device not identified correctly despite being in device config database

### ISSUE THREAD

**Issue by brenter** [AlCalzone/node-zwave-js#5227]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
unknown

What do you observe?
when added to the network or reinterviewed, Eurotronic ZWave Thermostat is not recognised but is added as unkown device by unknown manufacturer, therefore also config parameters are not correctly shown etc.

tried this also with reinterview. in closest proximitz to the controller, and with different devices of the same make and model, so it isnt just for one particular device.

What did you expect to happen?
the termostat to be added as a Eurotronic Spirit, device config details seem to be ok in the database

  1. click on add device on the integration configuration page
  2. add device to inclusion mode
  3. device gets added, entities show up but device shows up as unknown and device config parameters are now shown correctly.
 
unfortunately i was unable to download a full log from the integration, i pasted what i could get.

unknown:
![unknown](https://user-images.githubusercontent.com/33930314/204251041-91a35b91-7141-4c5d-8e6b-7cbc398557b4.png)

correctly identified devices (added prior to facing this issue):
![correct](https://user-images.githubusercontent.com/33930314/204251044-d9aa5cdb-3206-4a96-bd1b-3c3253b30d3b.png)

### Device information

Manufacturer: Eurotronics
Model name: Eurotronic Spirit Zwave thermostat
Node ID in your network: 51 and 52

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 0.1.74
`node-zwave-js` branch: master
`zwave-js-ui` branch: master

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

It worked before and was identified correctly, however not sure when and on what version i was when this happend last, as I havent been readded any such device in the past months

### Attach Driver Logfile

[log parts.txt](https://github.com/zwave-js/node-zwave-js/files/10102687/log.parts.txt)

**Comment by AlCalzone** [comment]
If this is still an issue, please re-interview the node and post that complete log.
