### ISSUE TITLE
Value changes to undefined do not get emitted 

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#5236]
It looks like the `undefined` value change doesn't get emitted. This is something I will have to investigate.

@robertsLando can the UI handle if a number gets set to "unknown"? In that case, they could enable the driver option as a workaround (can you explain how?).

_Originally posted by @AlCalzone in https://github.com/zwave-js/node-zwave-js/discussions/4804#discussioncomment-4293390_

**Comment by robertsLando** [comment]
Yep it can, answered in the discussion

**Comment by AlCalzone** [comment]
Whoops didn't mean to tag you here
