### ISSUE TITLE
Driver: options is not a MultilevelSwitchCCStartLevelChangeOptions (ZW0322) / "options":{"preserveUnknownValues":true}

### ISSUE THREAD

**Issue by arnog23** [AlCalzone/node-zwave-js#5237]
Following discusison here : [Missing commands for NICE Spa - IBT4ZWAVE - BusT4-Z-Wave interface #4804](https://github.com/zwave-js/node-zwave-js/discussions/4804#discussioncomment-4298074)

With `"options":{"preserveUnknownValues":true}`, when using Zwave commands of Nice Bidi, I have the following issue:

open or close, then stop. When opening or closing again, I have the following error message `Driver: options is not a MultilevelSwitchCCStartLevelChangeOptions (ZW0322)` and I am not able to control the Bidi anymore. I have to restart ZwaveJS.

This error do not appear when the option `preserveUnknownValues` is set to default (False).

**Comment by arnog23** [comment]
Do you need more logs or tests from my side ?

**Comment by AlCalzone** [comment]
No I think I have everything. Except time => https://github.com/zwave-js/node-zwave-js/issues/5129

**Comment by arnog23** [comment]
> Except time => #5129

Thanks for the reminder. I had not seen it.

Enjoy it :-)

**Comment by arnog23** [comment]
> No I think I have everything. Except time => https://github.com/zwave-js/node-zwave-js/issues/5129

Did you had time to look at it ?

**Comment by AlCalzone** [comment]
now I did
