### ISSUE TITLE
Problem discovery is incompleted for Schlage/Allegion BE469 & BE469ZP

### ISSUE THREAD

**Issue by carldebilly** [AlCalzone/node-zwave-js#5243]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### What causes the bug?
I was working well since a while, and one day I hit the "reinterview node" button and I lost all the codes associates with the device. Even the name/model/version of the device were lost. I tried a lot of time since and never got back the "user codes" section to be able to control codes. Seems caused by a glitch in the communication with the device.

### What do you observe?
Doing a reinterview sometimes bring back the "user codes" section with just the "master code" (but just for the newly added code), not the whole 30 codes sections.

### What did you expect to happen?
Would like it to work as before the updates where I was able to update the codes of my locks without problems.

### Related issues
Problem seems similar to https://github.com/zwave-js/node-zwave-js/issues/3933  -- but it's not exactly the same model -- it's the model not supporting ZWave+.

### More Info
Adding a code manually on the device will make the entry appears in the "User Code" section... until I click "reinterview" again.

### Device information

Manufacturer: Schlage
Model name: BE469
Node ID in your network: 37

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

## version:
`node-zwave-js` branch: 10.3.0
`zwave-js-ui` branch: 8.4.1

(Using the Z-Wave JS UI add-on from HA Community Add-ons)

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

As stated previously, it seems to stop working after an update few months ago, but can't pinpoint which one it is.

## Details in the log...

Found this in the log...
```
2022-12-06T05:25:15.668Z DRIVER « [Node 037] [REQ] [ApplicationCommand]
                                  └─[SecurityCCCommandEncapsulation] [INVALID]
                                      error: Nonce 0xb5 expired, cannot decode security encapsulated command.

[...]

2022-12-06T05:25:28.777Z DRIVER « [Node 037] [REQ] [ApplicationCommand]
                                  └─[SecurityCCNonceReport] [INVALID]
                                      error: Invalid nonce length
2022-12-06T05:25:28.777Z SERIAL » [ACK]                                                                   (0x06)
2022-12-06T05:25:28.796Z SERIAL « 0x011d00040025179880ffea9258900757b359c1506cb5cf5e30f37ffc154aff    (31 bytes)
2022-12-06T05:25:28.801Z DRIVER   Dropping message with invalid payload
2022-12-06T05:25:28.801Z DRIVER « [Node 037] [REQ] [ApplicationCommand]
                                  └─[SecurityCCNonceReport] [INVALID]
                                      error: Invalid nonce length
```

## Log files
[zwavejs_2022-12-06.log](https://github.com/zwave-js/node-zwave-js/files/10163065/zwavejs_2022-12-06.log)
[node_37.json.txt](https://github.com/zwave-js/node-zwave-js/files/10163068/node_37.json.txt)

**Comment by AlCalzone** [comment]
I don't see anything obviously wrong with the device here, but the communication is a bit weird sometimes, hinting at connectivity issues.

I suggest you work through https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting and https://zwave-js.github.io/node-zwave-js/#/troubleshooting/network-health?id=improving-the-network-health. There are some instances where a bunch of thermostats report over and over, which coincide with communication timeouts between the controller and the lock.
