### ISSUE TITLE
Vision Security ZM1602: Siren Strobe Mode doesn't work

### ISSUE THREAD

**Issue by EchoPouet** [AlCalzone/node-zwave-js#5245]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
I can't change the mode.

What do you observe?
Interface in HA indicate that change but not, I'm blocked in strobe mode.

What did you expect to happen?
The mode change.

  1. Go to Vision Security ZM1602 configuration page
  2. Click on Siren Strobe Mode combo box
  3. Change `Strobe` to `Siren`
  4. Mode change OK
  5. Turn on siren
  6. No sound !

### Device information

Manufacturer: Vision Security
Model name:  ZM1602
Firmware: 15.10
Node ID in your network: 13

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

zwave-js-server-python = 0.43.1

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile
[zwave_js.log](https://github.com/zwave-js/node-zwave-js/files/10185648/zwave_js.log)

**Comment by EchoPouet** [comment]
In HA it's the good log debug file.

**Comment by EchoPouet** [comment]
Hello, How I can help you to debug this issue ?

**Comment by AlCalzone** [comment]
Do you have a manual for that device? It may be that our config parameters are defined incorrectly.

**Comment by AlCalzone** [comment]
zwave.eu listing:
![grafik](https://user-images.githubusercontent.com/17641229/213873465-17a89758-b35c-4e37-b8ff-238fbd195f96.png)

vs. our file:
![grafik](https://user-images.githubusercontent.com/17641229/213873480-069cf873-f0c8-4724-95f7-b15808703f8a.png)

**Comment by AlCalzone** [comment]
Ok, it looks like there are two versions:
300 series, FW 1.x, label ZM1602
![grafik](https://user-images.githubusercontent.com/17641229/213873674-03f132c9-94ac-4acc-b6d2-b5c180249bf9.png)

and 500 series, FW 15.x, label ZM1602-5
![grafik](https://user-images.githubusercontent.com/17641229/213873699-1286669e-9aed-43fd-8710-90a724907763.png)

We will need to separate the definitions by FW version again.

**Comment by EchoPouet** [comment]
This this my manual -> https://doc.eedomus.com/files/ZM%201601-5%20Siren_20150602.pdf

Thanks a lot
