### ISSUE TITLE
Device stuck at Protocolinfo

### ISSUE THREAD

**Issue by boscorelly** [AlCalzone/node-zwave-js#5250]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.6.0.f033ee8

### ZwaveJS version

10.3.1

### Describe the bug

Hi,

i tried to add a new node through HomeAssistant.

The node was not added.

I have discovered a ghost device, called node 8. 
This node is reported as unknown, and stuck in Protocolinfo.
I tried to remove it, or replace it, without success.

I had a time the message "The node removal process is currently busy (ZW0360)" (i am not having it now).

I tried several times to include the node, but nothing worked.
A few hours after, i tried to re-add the node, and this time it worked. But the node has been added with ID 10. So i think there is another ghost device somewhere.

All the removal tries have been done directly through ZJSMQTT

![image](https://user-images.githubusercontent.com/3873787/206927847-597b4e57-2404-4bc4-9e89-296e617d1b5e.png)

### To Reproduce

I am not sure the problem is easily reproductible

### Expected behavior

Device added without problem, as usual and as before

**Comment by robertsLando** [comment]
Please attach zwave-js [driver logs](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=generating-log-files)

**Comment by boscorelly** [comment]
Hi,

this one ?
[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/10222878/zwavejs_current.log)

**Comment by boscorelly** [comment]
mostly this one
[zwavejs_2022-12-11.log.gz](https://github.com/zwave-js/node-zwave-js/files/10222890/zwavejs_2022-12-11.log.gz)

**Comment by boscorelly** [comment]
any update on this ?

**Comment by robertsLando** [comment]
Sorry @boscorelly Alcalzone will be back soon and will take a look at this. Based on the logs you sent I think you have a 'zombie' node here. What I suggest is to exclude the node first, factory reset it and try to run replace failed node against node id 8 to re-include it

**Comment by boscorelly** [comment]
Hi,I think you are right about the zombie node. The problem is that everything I tried to revive it never worked. Funny fact, the node has already been reset and is properly working since the next day I posted the issue 😂Message ID: ***@***.***>

**Comment by robertsLando** [comment]
Closing for now so, feel free to re open it in case the bug comes back

**Comment by boscorelly** [comment]
The bug is still present. I was able to te-add the node but the ghost node is still present !
    	
    
  

 De : Daniel Lando ***@***.***>Envoyé : lundi, janvier 2, 2023 1:45 PMÀ : zwave-js/node-zwave-js ***@***.***>Cc : Camille Ollié ***@***.***>; Mention ***@***.***>Objet : Re: [zwave-js/node-zwave-js] Device stuck at Protocolinfo (Issue #5250) 
Closing for now so, feel free to re open it in case the bug comes back

**Comment by AlCalzone** [comment]
You'll have to remove it using the "remove failed node" feature.

**Comment by boscorelly** [comment]
I already know. But it’s not working. If it was, I was not needing to create an issue !
    	
    
  

 De : AlCalzone ***@***.***>Envoyé : lundi, janvier 2, 2023 9:45 PMÀ : zwave-js/node-zwave-js ***@***.***>Cc : Camille Ollié ***@***.***>; Mention ***@***.***>Objet : Re: [zwave-js/node-zwave-js] Device stuck at Protocolinfo (Issue #5250) 
You'll have to remove it using the "remove failed node" feature.

**Comment by AlCalzone** [comment]
Then please share driver logs of your attempts. On github.com, attaching them to an email doesn't work.

**Comment by boscorelly** [comment]
they are here : https://github.com/zwave-js/node-zwave-js/issues/5250#issuecomment-1350045358

**Comment by AlCalzone** [comment]
Ok, I honestly have no idea why that is failing. The response returned by the stick when asked to remove the node (0x10) isn't even a valid one according to both the 500 (allows 0x00...0x02) and 700 (allows 0x00...0x05) series documentation.
Maybe you'll have some luck after physically re-plugging the stick. Other than that, I don't know.

**Comment by boscorelly** [comment]
thanks for your suggestion, i haven't this idea !
i'll check and tell you !
