### ISSUE TITLE
Re-interview hung because Z-Wave JS thinks the node is asleep (it's not)

### ISSUE THREAD

**Issue by kpine** [AlCalzone/node-zwave-js#5251]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Not sure. It may be device specific.

What do you observe?
Initiate a re-interview of a node. It hangs after receiving the Protocol Info message, because the driver marks the node as asleep. I can force the interview to complete by performing two different actions:
1. Successfully Ping the node within 10 seconds
2. Manually wake up the node again

In both cases, Z-Wave JS detects that the node is awake and continues the interview. Point 1 proves that the device is still awake, not asleep, otherwise it would not respond to the ping. If I wait too long, that is the case. Both ping scenarios are captured in the debug logs.

I tried another device, a Vision ZP3111-5. I noticed a slight deviation with how wake up works there. This device does not have a problem with the interview hanging. When waking up:
1. It first sends a `ApplicationUpdateRequest` message, this makes Z-Wave JS react and request protocol info.
2. Z-Wave JS thinks it's asleep after Protocol Info, same as above
3. The device then sends a `WakeUpCCWakeUpNotification` message, which continues the interview

In both cases, Z-Wave JS immediately thinks the node is asleep after handling the Protocol Info message. Is this behavior expected?

In the case of the Vision device, the wake up after the initial message cause the interview continue, much like the Ping in the "bad" case.

What did you expect to happen?
The re-interview should have hang at the Protocol Info phase.

  1. Re-interview a ZSE42, it is repeatable with this device.
  5. See the logs saying the node is asleep after Protocol Info received.
  6. Wait forever, or ping the node or wake it up to continue

I also reproduced with a Zooz ZSE41.

### Device information

Manufacturer: Zooz
Model name: ZSE42
Node ID in your network: 20

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 8.6.0.01c659b
`zwave-js-ui` branch: 10.3.1

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/10224877/zwavejs_current.log)

**Comment by kpine** [comment]
Another observation. The ZSE41 and ZSE42 support two kinds of button presses:

1. pressing 3 times is used for inclusion and exclusion
2. pressing 4 times sends a wake up notification

If you re-interview and press 3 times, it sends a `ApplicationUpdateRequest` message, but unlike the Vision device mentioned before, there is no wake up notification, so the interview hangs for this case as well.

**Comment by codahq** [comment]
I may have a related issue.  The Aeotec Multisensor 6 can be battery powered or mains (USB) powered.  Re-interview never works because zwave-js is waiting for the device to send a wake up notification but it does not do this when it is mains powered because it is already awake.  It appears that the initial interview even partially failed due to this because zwave-js does not know the node info e.g. the manufacturer or model.
