### ISSUE TITLE
ZWave Long Range Support

### ISSUE THREAD

**Issue by billyburly** [AlCalzone/node-zwave-js#5253]
**Is your feature request related to a problem? Please describe.**
With the 700 and 800 chipsets Silicon Labs added a new parallel channel/protocol to ZWave named Long Range. Devices that utilize ZWave Long Range are starting to be released.
https://community.inovelli.com/t/z-wave-800-series-2-1-switch-on-off-dimmer-project-phoenix/11428
https://atrim.co/zwave/stick-hub/
https://www.thesmartesthouse.com/products/zooz-800-series-z-wave-long-range-usb-stick-zst39

**Describe the solution you'd like**
Support for ZWave Long Range frequency and protocol on the 700 and 800 chipsets.

**Describe alternatives you've considered**
The UI allows you to select the US Long Range region and some grepping implies that initial work towards ZWave Long Range was done. Though it looks like it is not complete.

**Additional context**
https://sdomembers.z-wavealliance.org/document/dl/897 sections 5 and 6

**Comment by Hedda** [comment]
FYI, Z-Wave LR (Z-Wave Long Range) support has now been added to v12.5.0 Beta release by @jtbraun and @AlCalzone See:

https://github.com/zwave-js/node-zwave-js/pull/6401

and

https://github.com/zwave-js/node-zwave-js/releases/tag/v12.5.0-beta.0

and

https://github.com/zwave-js/node-zwave-js/blob/release-12.5.x/docs/getting-started/long-range.md
