### ISSUE TITLE
Multi Report from multiple devices

### ISSUE THREAD

**Issue by Roagert** [AlCalzone/node-zwave-js#5265]
[zwave-js-ui-store (1).zip](https://github.com/zwave-js/node-zwave-js/files/10258845/zwave-js-ui-store.1.zip)
I am seeing af multiple reports from the same device around 6-6.30 this morning.

Since im not aware of why this would suddenly happen i hereby create a case

**Comment by AlCalzone** [comment]
Hard to say just from the logs, but this typically happens when the nodes cannot "hear" the controller's acknowledgement, either due to noise or interference, or just low range/mesh
