### ISSUE TITLE
Setting Configuration parameter in Nortek GoControl PD300EMZ5-1 responds with different value

### ISSUE THREAD

**Issue by windsurferwill** [AlCalzone/node-zwave-js#5271]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug? Try to CONFIGURE Energy Monitoring reporting period (parameter 13) in PD300EMZ5-1.  The configuration screen correctly changes the value to the set value, but coming back out then going back in to the configuration menu shows the value to be entirely different.  I am not familiar enough with this zwave_js to understand if this is a device firmware issue or something else.

What do you observe?
After inclusion, parameter 13 Energy Monitoring reporting period correctly defaults to 6 minutes.  When changing the value, the response comes back different than the configuration value sent.  I cannot determine the relationship between the value sent versus the responding value. Trying to understand if this is the driver or a bug in the device firmware.  Example below sends "1" but sets as "159".
2022-12-21T12:49:45.438Z SERIAL « [ACK]                                                                   (0x06)
2022-12-21T12:49:45.442Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2022-12-21T12:49:45.442Z SERIAL » [ACK]                                                                   (0x06)
2022-12-21T12:49:45.443Z DRIVER « [RES] [SendData]
                                    was sent: true
2022-12-21T12:49:45.456Z SERIAL « 0x01050013b10058                                                     (7 bytes)
2022-12-21T12:49:45.457Z SERIAL » [ACK]                                                                   (0x06)
2022-12-21T12:49:45.458Z DRIVER « [REQ] [SendData]
                                    callback id:     177
                                    transmit status: OK
2022-12-21T12:49:45.467Z SERIAL « 0x010c000400050670060d02009f12                                      (14 bytes)
2022-12-21T12:49:45.468Z SERIAL » [ACK]                                                                   (0x06)
2022-12-21T12:49:45.476Z CNTRLR   [Node 005] [~] [Configuration] 13: 1 => 159
2022-12-21T12:49:45.478Z DRIVER « [Node 005] [REQ] [ApplicationCommand]
                                  └─[ConfigurationCCReport]
                                      parameter #: 13
                                      value size:  2
                                      value:       159

What did you expect to happen?  The value to be set correctly.

  1. Go to the device menu
  2. Click on 'configure'
  3. Scroll down to Parameter 13, Automatic Reporting Interval
  4. Change value either by using the up and down arrows or typing in a new value.  
  5. The value _does_ change on screen
  6. Go back up a level, then click on 'configure' again.
  7. See the Parameter 13 value is something entirely different.

### Device information

Manufacturer: Nortek GoControl
Model name: PD300EMZ5-1
Node ID in your network: 005

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwave-js-ui` branch:
Driver Version: 10.3.0
Server Version: 1.24.0
Home ID: 3775838400
Server URL: ws://core-zwave-js:3000
DEVICE specific version:
Device info
PD300EMZ5-1
by Nortek Security & Control LLC
Connected via [QuickStick Combo](http://192.168.1.170:8123/config/devices/device/46c4b0b787992a405789bd76d3207ead)
Firmware: 1.43
Z-Wave Info
ID: 5
Status: Alive
Ready: Yes
Highest security: None
Z-Wave Plus: Version 1

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwave_js 2022-12-21.log](https://github.com/zwave-js/node-zwave-js/files/10277939/zwave_js.2022-12-21.log)

**Comment by AlCalzone** [comment]
Looks like the value sizes were wrong for some parameters (1 instead of 2 bytes). https://github.com/zwave-js/node-zwave-js/pull/5297 should fix that.
