### ISSUE TITLE
Missing device configuration: Namron Z-Wave Termostatplugg 16A

### ISSUE THREAD

**Issue by b0ff3n** [AlCalzone/node-zwave-js#5278]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Namron Z-Wave Termostatplugg 16A

### Manufacturer ID

0x0438

### Product Type

0x0200

### Product ID

0xd004

### Firmware Version

2.6.0

### Is the device listed on the Z-Wave Alliance website?

no

### Do you have a manual?

Manual: https://www.elektroimportoren.no/docs/lib/4512725-Brukerveiledning-5.pdf

Product page: https://www.namron.com/products/namron-z-wave-termostatplugg-16a/

**Comment by AlCalzone** [comment]
fixed in #5349
