### ISSUE TITLE
Issues with Color Switch CC on v10

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#5287]
I'm having issues with all of my Logic ZDB5400 Wall Controllers. Since the update to 10.x the ColorSwitch CC does not work anymore. A reinterview does help, but only for some time (I don't know how long exactly but it's around one or two days I'd say...) or until I restart the driver. After a driver restart, the ColorSwitch CC never works, until I re-interview.

I'm currently on 10.3.0, using it with zwave-js-ui connected to MQTT.

I did the following and collected driver logs of each step:

1. Tried to send a ColorSwitch Command with no success - [1_setvalue_error_before_reinterview.log](https://github.com/zwave-js/node-zwave-js/files/9833647/1_setvalue_error_before_reinterview.log)
2. Did a reinterview of the node - [2_reinterview.log](https://github.com/zwave-js/node-zwave-js/files/9833648/2_reinterview.log)
3. Sent another (now successful) ColorSwitch Command - [3_setvalue_success_after_reinterview.log](https://github.com/zwave-js/node-zwave-js/files/9833649/3_setvalue_success_after_reinterview.log)
4. Did a node dump - [4_nodedump_working_after_reinterview.json.txt](https://github.com/zwave-js/node-zwave-js/files/9833661/4_nodedump_working_after_reinterview.json.txt)
5. Restarted the driver and sent a ColorSwitch Command with no success again - [5_setvalue_error_after_restart.log](https://github.com/zwave-js/node-zwave-js/files/9833662/5_setvalue_error_after_restart.log)
6. Did another node dump (after driver restart) - [6_nodedump_broken_again_after_restart.json.txt](https://github.com/zwave-js/node-zwave-js/files/9833663/6_nodedump_broken_again_after_restart.json.txt)

@AlCalzone I would be really happy if you could help me... 🙂

_Originally posted by @kaistierl in https://github.com/zwave-js/node-zwave-js/issues/4994#issuecomment-1286101909_

**Comment by kaistierl** [comment]
This seems to be solved in recent versions. Updated to zwave-js: 10.22.2 / zwave-js-ui: 8.17.1.fc8b65f and after four days it's still working fine. Driver restart hasn't been a problem neither.

Issue can be closed :)
