### ISSUE TITLE
Ring Retrofit Alarm Kit

### ISSUE THREAD

**Issue by webmogul1** [AlCalzone/node-zwave-js#5298]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Ring Retrofit Alarm Kit

### Manufacturer ID

0x0346

### Product Type

0x0b01

### Product ID

0x0101

### Firmware Version

1.6

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/3696?selectedFrequencyId=-1

### Do you have a manual?

[Retrofit Alarm Kit Installation Manual.pdf](https://github.com/zwave-js/node-zwave-js/files/10338371/Retrofit.Alarm.Kit.Installation.Manual.pdf)
[Ring Retrofit Alarm Kit Zwave Technical Manual.pdf](https://github.com/zwave-js/node-zwave-js/files/10338372/Ring.Retrofit.Alarm.Kit.Zwave.Technical.Manual.pdf)

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 3696 from zwa

**Comment by webmogul1** [comment]
Unfortunately, I have no idea how to do it.

**Comment by AlCalzone** [comment]
Don't worry, I just did it

**Comment by webmogul1** [comment]
> Don't worry, I just did it

Wonderful! And how do I add the new config?

**Comment by AlCalzone** [comment]
You wait for the next update

**Comment by webmogul1** [comment]
Thank you.

The info below is regarding the version without the new configuration. I don't know if the new one will solve the issues.
Maybe you can help having the information below.

It looks like there is a problem with the multi association thingy. (I am totally new to this)

I can get notifications when cover is removed. When zone 1 changes state I get the "Intrusion Notification" and that's it.
Changes in state of of zones 2 through 8 do not give me notifications. 

This is my notification table.
![image](https://user-images.githubusercontent.com/5225701/210621280-7f908812-dc9c-4d4a-bd29-23f242d3b0ad.png)

This is my group table
![image](https://user-images.githubusercontent.com/5225701/210622237-c1867cca-1ddf-48c6-834b-86a5928249ec.png)

Another fellow reports this:
https://community.home-assistant.io/t/ring-retrofit-hardwire-kit/430619
His group table looks like this:
![image](https://user-images.githubusercontent.com/5225701/210622496-79a8dd87-7e97-402e-82a6-a99462a66d18.png)

But I can't add other endpoints.
![image](https://user-images.githubusercontent.com/5225701/210622674-8f0c6606-aadf-402e-b8fc-729d38ec3d93.png)

**Comment by AlCalzone** [comment]
let's continue this in https://github.com/zwave-js/node-zwave-js/issues/5302
