### ISSUE TITLE
Unable to get Ring Retrofit device working properly

### ISSUE THREAD

**Issue by webmogul1** [AlCalzone/node-zwave-js#5302]
Hi 
Is this something you can help me with?

Can't get it to work.

https://products.z-wavealliance.org/products/3696?selectedFrequencyId=-1

**Comment by robertsLando** [comment]
Dunno if there is any known bug. BTW 
please better explain what you mean with "doens't work" and attach zwave-js [driver logs](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=generating-log-files) otherwise we cannot help

**Comment by AlCalzone** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).
While that log is running, re-interview the device. Based on what you posted in the other issue, I suspect we may either not need the association definitions in the config file or we'll have to extend them.

**Comment by webmogul1** [comment]
I will get the logs soon. In the mean time:
It looks like there is a problem with the multi association thingy. (I am totally new to this)

I can get notifications when cover is removed. When zone 1 changes state I get the "Intrusion Notification" and that's it.
Changes in state of of zones 2 through 8 do not give me notifications.
This is my notification table.
![image](https://user-images.githubusercontent.com/5225701/210936988-c3ceb182-2492-4ec2-86ec-0a7a982a23d6.png)
This is my group table
![image](https://user-images.githubusercontent.com/5225701/210937034-57c20853-45d7-40d4-8506-f6cb0583c889.png)

Another fellow reports this:
https://community.home-assistant.io/t/ring-retrofit-hardwire-kit/430619
His group table looks like this:
![image](https://user-images.githubusercontent.com/5225701/210937063-d3e53125-dfbc-4425-b552-986b37dad5b6.png)

But I can't add other endpoints.
![image](https://user-images.githubusercontent.com/5225701/210937227-56d99be8-a553-4e01-89d0-5ae2caeb362d.png)

**Comment by webmogul1** [comment]
Is this one that you need?
[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/10357622/zwavejs_current.log)

**Comment by AlCalzone** [comment]
Ok I think I know what the problem is. The driver attempts to communicate with the endpoints without S2-encryption and gets no response for its queries. I'll have to figure out why it does that.

**Comment by AlCalzone** [comment]
Ok, found the issue. The endpoints don't list S2 as supported although they expect to be addressed using S2 encryption. I thought this was a requirement, but apparently this is only a recommendation:
> Nodes supporting S2 MUST support addressing every End Point with S2 encapsulation and MAY
explicitly list S2 in the non-secure End Point capabilities.

**Comment by webmogul1** [comment]
Unfortunately, It didn't work. 
I still cannot change endpoints 1-8 associations.

![image](https://user-images.githubusercontent.com/5225701/214165331-e3484298-4b62-465d-a5f7-e374af72e39a.png)

zwave-js-ui: 8.8.0
zwave-js: 10.4.0

**Comment by webmogul1** [comment]
Device in question is Node 35

[zwavejs_current (2).log](https://github.com/zwave-js/node-zwave-js/files/10484220/zwavejs_current.2.log)

**Comment by webmogul1** [comment]
https://support.ring.com/hc/en-us/articles/360038043371-Retrofit-Alarm-Kit-Z-Wave-Technical-Manual-

Manual says:
Association
This sensor has two Association groups with only one node for each group. Group one is a lifeline group who will receive unsolicited messages relating to case tamper notifications, battery level notifications, Wake-Up notifications, and Device Reset Notifications. Group two is intended to be used with multi-channel association for a controller to subscribe to contact switch open/close notifications sent encapsulated from each of the eight endpoints one for each contact switch. Each endpoint must be enabled by putting the controller’s node ID into the device’s Association Group 2 with either an Association Set encapsulated with Multi-Channel Encapsulation OR a Multi-Channel Association Set encapsulated with Multi-Channel Encapsulation.

**Comment by AlCalzone** [comment]
hmm doesn't look like the fix did what it was supposed to.

**Comment by webmogul1** [comment]
Does it matter that the device is showing
only S2 Authenticated
instead of S2 Authenticated, S2 Unauthenticated
as Security classes?

**Comment by webmogul1** [comment]
Hope that helps
Here is the thing. I added the device using the "Z-Wave PC Controller" from SiliconLabs.
It seems that I got the correct associations showing in the controller. It shows a lot more items than when I added with ZwaveJS.

![image](https://user-images.githubusercontent.com/5225701/214627895-bb66aee9-6b98-4d76-b554-d5473d18f059.png)

![image](https://user-images.githubusercontent.com/5225701/214628123-2e731f30-7b35-47e9-9b89-ff02de863244.png)

This is when it is added with zwaveJS

![image](https://user-images.githubusercontent.com/5225701/214651866-1c8b851c-d092-47a8-8f84-653fa57a8416.png)

**Comment by webmogul1** [comment]
But then if I connect the stick to zwavejs, the node is interviewed again and there are no options for the other endpoints.

I have no idea how that works but isn't just a matter of reading the node info already included?

**Comment by AlCalzone** [comment]
I know what the issue is, I don't yet know why it happens. Unfortunately, my working hours are pretty limited atm. Give me a bit of time to reproduce and solve it.

**Comment by webmogul1** [comment]
Ok. Just wanted you to have as much info as possible.
