### ISSUE TITLE
Missing device configuration: Quby Energy Meter Reader 

### ISSUE THREAD

**Issue by IgorYbema** [AlCalzone/node-zwave-js#5315]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Quby - Energy Meater Reader

### Manufacturer ID

0x0130

### Product Type

0x0002

### Product ID

0x0000

### Firmware Version

0.25

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/1281

### Do you have a manual?

See z-wave alliance website

The newer module type (product id 0x0001) is already in the database: https://devices.zwave-js.io/?jumpTo=0x0130:0x0002:0x0001:0.0

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 1281 from zwa
