### ISSUE TITLE
Stelpro STZW402+ - ZWave Heat Mode Off (0) is Missing

### ISSUE THREAD

**Issue by baylanger** [AlCalzone/node-zwave-js#5333]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

The installation consists of 3 Stelpro Ki STZW402+ all w/ identical settings.

Per the [company's manual](https://www.stelpro.com/wp-content/uploads/2021/01/INS_STZW402_0822_13x19_EN.pdf), on page 9, the thermostat supports the following Z-Wave heat modes:
```
- OFF (0)
- HEAT (1)
- ENERGY SAVE HEAT (11)
```

Not one of the devices allow to set the mode to OFF (0).

But the manual available on [Z-Wave Alliance](ttps://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/1603/INS_STZW402_1215_EN.pdf) shows only mode 1 and 11.

It was released in 2016, still available for sale. I happen to have older ~6y and one bought this month. I can test any PR with all 3.

### Device information

Manufacturer: Stepro
Model name: STZW402+

The company's available PDF shows the device supports mode 0 but not the one on the alliance. 
 
Manual : https://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/1603/INS_STZW402_1215_EN.pdf

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwave-js-ui` branch:

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[STZW402.log](https://github.com/zwave-js/node-zwave-js/files/10418498/STZW402.log)

```
{
  "status": "Alive",
  "interviewStage": "Complete",
  "hexId": "0x0239-0x0001-0x0001",
  "dbLink": "https://devices.zwave-js.io/?jumpTo=0x0239:0x0001:0x0001:1.0",
  "manufacturerId": 569,
  "productId": 1,
  "productType": 1,
  "deviceConfig": {
    "filename": "/usr/src/app/store/.config-db/devices/0x0239/stzw402.json",
    "isEmbedded": true,
    "manufacturer": "Stelpro",
    "manufacturerId": 569,
    "label": "STZW402+",
    "description": "4000W Thermostat",
    "devices": [
      {
        "productType": 1,
        "productId": 1
      }
    ],
    "firmwareVersion": {
      "min": "0.0",
      "max": "255.255"
    },
    "metadata": {
      "inclusion": "Make sure the Z-Wave hub is in the include mode (Refer to your Z-Wave hub instruction manual).\n\nTo add (include) the thermostat to a Z-Wave network, enter the Menu 1 (Z-Wave menu) and select “On”. Then press the UP and DOWN buttons to start the inclusion process. During inclusion, “On” will be blinking and the connectivity icon will be animated in an increasing pattern. When the inclusion process has been completed, On will be displayed solid. If an error occurs, “Err” will be displayed for 3 seconds then the screen will revert to “Off” selection.",
      "exclusion": "Make sure the Z-Wave hub is in the exclude mode (Refer to your Z-Wave hub instruction manual).\nTo remove (exclude) the thermostat from a Z-Wave network, enter the Menu1 (Z-Wave menu) and select “Off”. Then press the UP and DOWN buttons to start the exclusion process. During exclusion, “Off” will be blinking and the connectivity icon will be animated in an decreasing pattern. When the exclusion process has been completed, Off will be displayed solid. If an error occurs, “Err” will be displayed for 3 seconds then the screen will revert to “On” selection.",
      "reset": "The thermostat may be manually reset to its factory state.\nWhen this is performed, all parameters are reset to their default values and the thermostat is removed (excluded) from the Z-Wave network.\nTo reset the thermostat to its default state:\n- Enter the advanced settings\n- Enter the °STELPRO menu (menu 6)\n- Navigate to the “def” screen using the UP or DOWN buttons.\n- Enter the “def” menu by pressing the UP and DOWN buttons for less than 3 seconds\n- Select “yes” and confirm the selection by pressing the UP and DOWN buttons for less than 3 seconds.\nIf the thermostat was added (included) in a Z-wave network, it will send a ‘’device reset locally’’ notification.\nThe thermostat will then reset itself.\n\nPlease use this procedure only when the network primary controller is missing or otherwise inoperable",
      "manual": "https://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/1603/INS_STZW402_1215_EN.pdf"
    }
  },
  "productLabel": "STZW402+",
  "productDescription": "4000W Thermostat",
  "manufacturer": "Stelpro",
  "firmwareVersion": "1.0",
  "protocolVersion": 3,
  "zwavePlusVersion": 1,
  "zwavePlusNodeType": 0,
  "zwavePlusRoleType": 5,
  "nodeType": 1,
  "endpointsCount": 0,
  "endpointIndizes": [],
  "isSecure": false,
  "security": "None",
  "supportsSecurity": false,
  "supportsBeaming": true,
  "isControllerNode": false,
  "isListening": true,
  "isFrequentListening": false,
  "isRouting": true,
  "keepAwake": false,
  "maxDataRate": 100000,
  "deviceClass": {
    "basic": 4,
    "generic": 8,
    "specific": 6
  },
  "firmwareCapabilities": {
    "firmwareUpgradable": false
  },
  "deviceId": "569-1-1",
  "statistics": {
    "commandsTX": 25,
    "commandsRX": 44,
    "commandsDroppedRX": 0,
    "commandsDroppedTX": 0,
    "timeoutResponse": 0,
    "rtt": 33.7
  },
  "lastActive": 1673715846306,
  "_name": "Thermostat Up",
  "lastReceive": 1673715846306,
  "lastTransmit": 1673715805289,
  "errorReceive": false,
  "errorTransmit": false
}
```

**Comment by AlCalzone** [comment]
I suspect the device incorrectly reports the supported thermostat modes. Can't confirm this without a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs) of the (re-)interview though. Make it loglevel `debug` and attach it here as a file (drag & drop into the text field).
