### ISSUE TITLE
Leviton RZP15

### ISSUE THREAD

**Issue by markiper** [AlCalzone/node-zwave-js#5355]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

RZP15

### Manufacturer ID

0x001d

### Product Type

NA

### Product ID

NA

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/517?selectedFrequencyId=2

### Do you have a manual?

[DI-000-DZPA1-02B-W.pdf](https://github.com/zwave-js/node-zwave-js/files/10482479/DI-000-DZPA1-02B-W.pdf)

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 517 from zwa

**Comment by AlCalzone** [comment]
Unfortunately, the entry in the Z-Wave alliance DB is incomplete, so we really need those IDs where you put "N/A". @markiper
