### ISSUE TITLE
HEATIT Z-SMOKE MULTISENSOR - Unknown product 0x0017 

### ISSUE THREAD

**Issue by dffffffff** [AlCalzone/node-zwave-js#5398]
zwave-js-ui: 8.8.2.b5fcc4a
zwave-js: 10.5.4

HEATIT Z-SMOKE MULTISENSOR when added will return 
Heatit Controls AB - Unknown product 0x0017 (0x0003)

<img width="1380" alt="Screenshot 2023-02-01 at 17 36 24" src="https://user-images.githubusercontent.com/33299550/216105096-097b1062-dada-4da1-8d1f-425795be9602.png">

Fingerprint:
manufacturer: Heatit Controls AB (0x019b)
product type: 0x03
product id:   0x17

driver log: http://paste.debian.net/hidden/f5b84956/
zwave log: http://paste.debian.net/hidden/39a5f4f3/

**Comment by AlCalzone** [comment]
Is this the [battery powered](https://devices.zwave-js.io/?jumpTo=0x019b:0x0003:0x3602:0.0) or the [mains powered](https://devices.zwave-js.io/?jumpTo=0x019b:0x0003:0x3601:0.0) version?

**Comment by kailampi** [comment]
I would say it is AC powered. I have very same issue with AC powered  version.

![image](https://user-images.githubusercontent.com/62675883/216158528-42028f1b-85fc-4e16-88cf-b0688cff335b.png)

**Comment by AlCalzone** [comment]
@zwave-js-bot add fingerprint `0x0003:0x0017` to `0x019b:0x0003:0x3601:0.0`
