### ISSUE TITLE
Missing Binary Switch Heatit Z-Smoke Multisensor 230VAC FW: v4.2.0

### ISSUE THREAD

**Issue by dffffffff** [AlCalzone/node-zwave-js#5406]
zwave-js-ui: 8.8.2.b5fcc4a
zwave-js: 10.5.4

Heatit Z-Smoke Multisensor 230VAC
Devices with 
FW: v4.2.0
SDK: v6.81.6

will not report the Binary Switch to activate the siren.

Devices with 
FW: v4.1.2
SDK: v6.81.3

reports the Binary Switch

![switch](https://user-images.githubusercontent.com/33299550/216370695-bf921ae0-dbe0-4d93-af50-375a33cca544.jpg)

Driver logs
[switch-NO.log](https://github.com/zwave-js/node-zwave-js/files/10570652/switch-NO.log)

[switch-YES.log](https://github.com/zwave-js/node-zwave-js/files/10570656/switch-YES.log)

**Comment by AlCalzone** [comment]
Can confirm from the logs:
### 4.1.2:
```
supported CCs:
· Z-Wave Plus Info
· Binary Switch
· Association
· Multi Channel Association
· Association Group Information
· Transport Service
· Version
· Manufacturer Specific
· Device Reset Locally
· Powerlevel
· Battery
· Notification
· Multilevel Sensor
· Security 2
· Supervision
· Firmware Update Meta Data
```

### 4.2.0
```
supported CCs unencrypted:
· Z-Wave Plus Info
· Supervision
· Transport Service
· Security 2

supported CCs (encrypted):
· Version
· Association
· Multi Channel Association
· Association Group Information
· Manufacturer Specific
· Device Reset Locally
· Powerlevel
· Battery
· Notification
· Multilevel Sensor
· Firmware Update Meta Data
```
