### ISSUE TITLE
Interview of AEON Labs ZW062 fails with subsystemType is not a SubsystemType

### ISSUE THREAD

**Issue by ccie1441** [AlCalzone/node-zwave-js#5463]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
AEON Labs ZW062 device sits at "NodeInfo". Selecting the node and advanced -> interview shows an error in the logs.

What do you observe?
Node is interviewed up to this point:
2023-02-14T02:00:06.015Z CNTRLR » [Node 024] Querying signaling capabilities...
2023-02-14T02:00:06.070Z CNTRLR « [Node 024] Received supported subsystem types:
· Visual
**· unknown (0x03)**
2023-02-14T02:00:06.073Z CNTRLR » [Node 024] Querying event signaling state for subsystem Visual...
2023-02-14 15:00:06.133 INFO Z-WAVE: [Node 024] Metadata updated: 102-0-signalingState-2
2023-02-14 15:00:06.134 INFO Z-WAVE: [Node 024] Value added: 102-0-signalingState-2 => 255
2023-02-14T02:00:06.139Z CNTRLR « [Node 024] Subsystem Visual has state On
2023-02-14T02:00:06.140Z CNTRLR » [Node 024] Querying event signaling state for subsystem unknown (0x03)...
2023-02-14T02:00:06.141Z CNTRLR [Node 024] **Error during node interview: subsystemType is not a SubsystemType (
ZW0322)**

What did you expect to happen?
Expected the interview to complete and the device to be available for use as it did in previous versions.

  1. Go to the ZW062 node in the control panel
  
  3. Click on it and advanced
  4. Click on re-interview
  5. Node sits at NodeInfo and I see the error in the logs

### Device information

Manufacturer: AEON Labs
Model name: ZW062 (Aeon Labs Garage Door Controller Gen5)
Node ID in your network: 024

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

zwave-js-ui: 8.8.3
zwave-js: 10.5.5
home id: 4287188722
home hex: 0xff894ef2

### Did you change anything?

yes (please describe)

### If yes, what did you change?

Was working with the previous z-wave JS integration and HomeAssistant

### Did this work before?

No, it never worked anywhere

### If yes, where did it work?

Worked with the previous z-wave JS integration, but failed with the z-wave JS UI

### Attach Driver Logfile

[zwavejs_2023-02-14.log](https://github.com/zwave-js/node-zwave-js/files/10728139/zwavejs_2023-02-14.log)

**Comment by AlCalzone** [comment]
Ok the root of this issue is that the device incorrectly encodes the support bitmask:
![grafik](https://user-images.githubusercontent.com/17641229/218825026-08c2ee53-5b29-4d0b-964d-92f00646fcae.png)

The specs only know the subsystem types 1 and 2, which means the bitmask should be a single byte with the lowest 2 bits set: `0b0000_0011`. The device however responds with `0b0000_0110`, which includes an invalid value.

The problem you're seeing happens because our API has a check for valid subsystem types, but the supported types returned by the device are passed in there without checking first.

**Comment by ccie1441** [comment]
Thank you for looking at this so quickly!

**Comment by kpine** [comment]
> Ok the root of this issue is that the device incorrectly encodes the support bitmask:

Any indication as to why that would be happening? I have this same device and they are reported correctly.

Also, why aren't the messages in the logs security encapsulated, is that not a problem on its own? Related?

OPs:

```text
2023-02-14T02:29:39.300Z SERIAL « 0x010900040018036605068c                                            (11 bytes)
2023-02-14T02:29:39.301Z SERIAL » [ACK]                                                                   (0x06)
2023-02-14T02:29:39.301Z CNTRLR   [Node 024] [+] [Barrier Operator] supportedSubsystemTy [Endpoint 0] [internal]
                                  pes: 2,3
2023-02-14T02:29:39.302Z DRIVER « [Node 024] [REQ] [ApplicationCommand]
                                  └─[BarrierOperatorCCSignalingCapabilitiesReport]
                                      supported types:
                                      · Visual
                                      · unknown (0x03)
2023-02-14T02:29:39.303Z CNTRLR « [Node 024] Received supported subsystem types: 
                                  · Visual
                                  · unknown (0x03)
```

Vs. mine:

```text
12:23:31.334 SERIAL « 0x012000a800012617988178e34b0d8dee561cc3bad05fecabbe9c22735c535f00c (34 bytes)
                      5fd
12:23:31.336 SERIAL » [ACK]                                                                   (0x06)
12:23:31.340 CNTRLR   [Node 038] [+] [Barrier Operator] supportedSubsystemTy [Endpoint 0] [internal]
                      pes: 1,2
12:23:31.343 DRIVER « [Node 038] [REQ] [BridgeApplicationCommand]
                      │ RSSI: -59 dBm
                      └─[SecurityCCCommandEncapsulation]
                        │ sequenced: false
                        └─[BarrierOperatorCCSignalingCapabilitiesReport]
                            supported types:
                            · Audible
                            · Visual
12:23:31.347 CNTRLR « [Node 038] Received supported subsystem types:
                      · Audible
                      · Visual
```

**Comment by AlCalzone** [comment]
No clue, maybe the implementation does something different when S0 is involved. But yeah, you're right - a barrier operator should be included securely.

**Comment by ccie1441** [comment]
The FW reported for the ZW062 is FW: v1.11 (from the Z-Wave JS UI console). Is that the same as the working one?
When setting the node up I have just included, not specifically trying to be secure (or not). I can try that if that is a difference between the node responding correctly or not.

**Comment by kpine** [comment]
Mine is v1.14, but I don't think that should matter. Z-Wave JS should include with S0 security by default, as it is required. You might try a re-interview with "Reset security classes" enabled? Otherwise, re-including might be the way to go. The device doesn't function otherwise.

**Comment by kpine** [comment]
I take it back: https://aeotec.freshdesk.com/support/solutions/articles/6000134295-garage-door-controller-firmware-v1-14

![image](https://user-images.githubusercontent.com/791794/218870709-0afb7846-5929-4748-bbaf-83df571fbe65.png)

(But you still need to fix the security problem.)

**Comment by ccie1441** [comment]
Thanks for looking into this. An upgrade to FW v1.14 on the door controller also has fixed my issue.
