### ISSUE TITLE
Locstar/KAS-600 (LS-8015-ZW) lock failed to complete interview

### ISSUE THREAD

**Issue by pazaan** [AlCalzone/node-zwave-js#5480]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug? Try to include or re-interview KAS-600 door lock.

What do you observe? The device gets stuck in `NodeInfo`. The last message from the driver log before communication stops is
```
Error during node interview: Node #11 does not support the command TimeOffsetGet! (ZW0302)
```
Some items do appear in Z-Wave JS UI, but there are a lot of `undefined` labels, and things that previously worked like battery level no longer appear.
<img width="1774" alt="Screenshot 2023-02-20 at 15 54 21" src="https://user-images.githubusercontent.com/96943/220012569-56f708ea-214c-4ca1-9f06-054a5bce90a2.png">

What did you expect to happen? Interview to complete and device be available in HomeAssistant

  1. Go to the control panel in Z-Wave JS UI
  2. Click on the node associated with the KAS-600 lock (Node 11 in my case)
  3. Click on the `Advanced` button
  4. Click on the `Re-interview Node` button
  5. Selecting the `Reset security classes` checkbox makes no difference to the outcome
  6. Click `OK`
  7. The Re-interview process begin, but the node stays stuck in `NodeInfo`.

### Device information

Manufacturer: KAS
Model name: KAS-600 (LS-8015-ZW)
Node ID in your network: 11

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [x] `HomeAssistant zwave_js` integration  2023.1.4 
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Z-Wave JS version: 10.10.0
Z-Wave JS UI version: 8.8.5.2d9d59c

### Did you change anything?

yes (please describe)

### If yes, what did you change?

I excluded the node from the network and re-added it.

### Did this work before?

Yes (please describe)

### If yes, where did it work?

This device previously worked with OpenHAB and HomeAssistant prior to the change to Z-Wave JS. It has also worked with previous versions of Z-Wave JS. I couldn't tell you which version I included the lock originally, though.

### Attach Driver Logfile

[zwavejs_2023-02-20.log](https://github.com/zwave-js/node-zwave-js/files/10779663/zwavejs_2023-02-20.log)

**Comment by AlCalzone** [comment]
Looks like we only ever tested Schedule Entry Lock CC on devices supporting V2/V3. Fix on the way
