### ISSUE TITLE
Logic Group Matrix ZRB5120 issue 

### ISSUE THREAD

**Issue by andlo** [AlCalzone/node-zwave-js#5546]
### Version

Build/Run method:
HAOS

zwave-js-ui: 8.9.0
zwave-js: 10.10.0

### Describe the bug
a Matrix ZRB5120 wall controller did work well for some time. But stoped for some reason,
It is included in the zwave network, and it is posible to ping it, and set parameters etc, but it is not posible to turn on and of the relays- Turning on and of at the wall controller it reports back on the network.

I have excluded, resat included a cupel of times but no effect. I have tryed a new (same type) wall controller and have same issue. 

I notised that some controls are missing in HomeAssistant. 

The problematic node is nodeid 40

Any advise or help would be amasing :) 

[config_entry-zwave_js-8b8d68e23e6173c74b28d5bf7d39a37b.json.txt](https://github.com/zwave-js/zwave-js-ui/files/10923625/config_entry-zwave_js-8b8d68e23e6173c74b28d5bf7d39a37b.json.txt)

[nodes_dump.json.txt](https://github.com/zwave-js/zwave-js-ui/files/10923638/nodes_dump.json.txt)

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by AlCalzone** [comment]
Make sure to capture a re-interview and one of the failing interactions in that log.

**Comment by andlo** [comment]
Great. I made a logfile as described, and made a reinterviev for node 40. Then I turned on and og the to switches (in Homeassistant) pressed Ping and turned on and of again.
And then attatched the logfile here :) 
[zwavejs_2023-03-09.log](https://github.com/zwave-js/node-zwave-js/files/10932340/zwavejs_2023-03-09.log)

**Comment by AlCalzone** [comment]
I'm not seeing anything related to turning on or off in the driver log. The rest looks okay. This might be one of the cases where we actually need logs from Z-Wave JS UI ("Application Logs").

Just capture the failing interaction in those.

**Comment by andlo** [comment]
[z-ui_2023-03-09.log](https://github.com/zwave-js/node-zwave-js/files/10932719/z-ui_2023-03-09.log)
@AlCalzone This log ?

**Comment by andlo** [comment]
I enabled the log to file and debug. Then did a turn on eand of the to entities in Homeassistant, pressed Ping and turn on and off again on the to entities.

**Comment by AlCalzone** [comment]
I'm not seeing anything there either. Are you controlling the device in Z-Wave JS UI or natively in Home Assistant? If its the latter, can you try Z-Wave JS UI, so we can maybe rule it out?

**Comment by andlo** [comment]
I am dooing it from HA as I cant do it from Z-Wave JS UI

![image](https://user-images.githubusercontent.com/3314671/224249155-a2e03503-cc38-48fa-91c4-2ba8c34e46b2.png)

**Comment by AlCalzone** [comment]
Tr re-interviewing in zwave js UI. Looks like the binary switch cc version is unknown, so Likely an interview timeout.

**Comment by andlo** [comment]
Tryed that, and also tryed activate Increase node report timeut, but result is the same :(
Would a new log show something ?

**Comment by AlCalzone** [comment]
Maybe, this time interview and capture the log in zwave-js UI please.

**Comment by andlo** [comment]
Ill reintervieved and made a new log with loglevel debug 

I really appreciate your help :) 

[zwavejs_2023-03-10.log](https://github.com/zwave-js/node-zwave-js/files/10942376/zwavejs_2023-03-10.log)

**Comment by AlCalzone** [comment]
How does it look now in Z-Wave JS UI? Which controls are you missing?
The interview looked okay.

**Comment by andlo** [comment]
I would say I am missing the binary switches 
![image](https://user-images.githubusercontent.com/3314671/224475428-1ff312d5-5fd4-4f78-9126-322c143bb4b3.png)

**Comment by AlCalzone** [comment]
I think I might have it, you will have to test next release though.
