### ISSUE TITLE
Unable to create an instance of a non-implemented CC: Cannot retrieve the version of a CC that is not implemented

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#5586]

**Comment by jef-pearlman** [comment]
My example code:
```const { CommandClass } = this.require("zwave-js");
const cc = new CommandClass(driver, {
    nodeId: 123,
    ccId: 0x92,
    ccCommand: 2,
    payload: Buffer.from([ 0x3B, 0x10, 0x00, 0x01, 0x61 ])
});
await driver.sendCommand(cc);
```

Running from ZWave JS UI's Driver function produces: `Error while calling driverFunction: Cannot retrieve the version of a CC that is not implemented (ZW0302)`

If it matters, the node is a [Nexia NX1000](https://devices.zwave-js.io/?jumpTo=0x0178:0x5343:0x4735:0.0).  Thanks!
