### ISSUE TITLE
ZMNHAD - Missing class 48

### ISSUE THREAD

**Issue by biggranben** [AlCalzone/node-zwave-js#5588]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Class 48 Instance 1, 2 and 3 are missing

What do you observe?
Can't access to the state of the input I1, I2, I3

### Device information

Manufacturer: Qubino
Model name: ZMNHAD
Node ID in your network: 64
Device ID : 345-82-2 (0x0159-0x0002-0x0052)

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
zwave-js-ui: 8.6.1.7833cd8
zwave-js: 10.3.1

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Working on OpenZWAVE

![image](https://user-images.githubusercontent.com/17392979/225822080-e52ddbfb-fde8-4aa2-b8e9-d9083ce6dfe7.png)

### Attach Driver Logfile

[file removed]

**Comment by biggranben** [comment]
[z-ui_2023-03-17.log](https://github.com/zwave-js/node-zwave-js/files/10998209/z-ui_2023-03-17.log)

**Comment by AlCalzone** [comment]
That's also not a driver log. Please read the link the bot posted again.
And to be sure, the log will need to include a re-interview.

**Comment by biggranben** [comment]
[zwave_17-03-2023.log](https://github.com/zwave-js/node-zwave-js/files/11003926/zwave_17-03-2023.log)

This one is correct ?

**Comment by biggranben** [comment]
Do you need anything else ?

**Comment by AlCalzone** [comment]
still not the correct one. The correct one is called `zwavejs_<date>.log`

**Comment by biggranben** [comment]
[zwavejs_2023-03-17.log](https://github.com/zwave-js/node-zwave-js/files/11073183/zwavejs_2023-03-17.log)

**Comment by biggranben** [comment]
Do you need anything else ?

**Comment by AlCalzone** [comment]
Now it's a driver log, but it does not include a re-interview of the problematic device like I asked [here](https://github.com/zwave-js/node-zwave-js/issues/5588#issuecomment-1473918310). Also make sure it's not filtered in any way.

**Comment by biggranben** [comment]
[zwavejs_2023-04-07.log](https://github.com/zwave-js/node-zwave-js/files/11176260/zwavejs_2023-04-07.log)

I think now this one is correct ! Ok for you ?

**Comment by AlCalzone** [comment]
According to that log:
* Endpoint 1 is a binary **switch**, which does not expose any sensor functionality.
* Endpoint 2 is a **multilevel** sensor, not a binary sensor
* Endpoint 3 does not exist.

I'm assuming you skipped over this part in the manual:
![grafik](https://user-images.githubusercontent.com/17641229/230667535-5de9687f-f2c0-4318-8e3f-fffcbccf3116.png)

Without doing this, the sensors won't show up, even if you changed the parameters.

**Comment by biggranben** [comment]
Hello,

On this devise, there are 3 imput : 
- input 1 : linked to the relay
- input 2 : sensor
- input 3 : sensor
- +temperature sensor if connected to the specific port

![image](https://user-images.githubusercontent.com/17392979/230704184-319d119c-bd7b-47a2-b9d1-80804887ef81.png)

Input 2 and 3 are configured as sensor binary : 
![image](https://user-images.githubusercontent.com/17392979/230704415-d99378bf-ef20-4997-86a8-2baf98f6aadc.png)
![image](https://user-images.githubusercontent.com/17392979/230704429-714530ce-e503-4e0b-abf8-0e3c18d62c94.png)

But no way to get the state.

It is a non documented class on the manual, but on the class 48, we could get the input state for each input (1, 2, 3). It was working on OpenZWAVE.

**Comment by biggranben** [comment]
Working after reinclusion
Thank you
