### ISSUE TITLE
Excessive commandsRX for Kwikset Home Connect 620 lock

### ISSUE THREAD

**Issue by dev77-07** [AlCalzone/node-zwave-js#5591]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Unsure, starts happening after a week or two
What do you observe?
Excessive commandsRX and repeating data in the log
```
2023-03-18T21:08:27.807Z SERIAL « 0x011a00a8000109119f035300b7ad842ba75c25c152ecbe7b3a00b3c3          (28 bytes)
2023-03-18T21:08:27.808Z SERIAL » [ACK]                                                                   (0x06)
2023-03-18T21:08:27.809Z DRIVER « [Node 009] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -77 dBm
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 83
                                    └─[SupervisionCCReport]
                                        session id:          45
                                        more updates follow: true
                                        status:              Working
                                        duration:            1s
2023-03-18T21:08:28.829Z SERIAL « 0x011a00a8000109119f035400fc11b0fb3c60bd08050d94a38e00b3d1          (28 bytes)
2023-03-18T21:08:28.829Z SERIAL » [ACK]                                                                   (0x06)
2023-03-18T21:08:28.830Z DRIVER « [Node 009] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -77 dBm
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 84
                                    └─[SupervisionCCReport]
                                        session id:          45
                                        more updates follow: true
                                        status:              Working
                                        duration:            1s
2023-03-18T21:08:29.851Z SERIAL « 0x011a00a8000109119f035500385f7ba048fe818dfa50bb3db500b3b1          (28 bytes)
2023-03-18T21:08:29.852Z SERIAL » [ACK]                                                                   (0x06)
2023-03-18T21:08:29.853Z DRIVER « [Node 009] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -77 dBm
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 85
                                    └─[SupervisionCCReport]
                                        session id:          45
                                        more updates follow: true
                                        status:              Working
                                        duration:            1s
2023-03-18T21:08:30.871Z SERIAL « 0x011a00a8000109119f035600ddaae3829b2cd17ee252d6dca600b33f          (28 bytes)
2023-03-18T21:08:30.872Z SERIAL » [ACK]                                                                   (0x06)
2023-03-18T21:08:30.873Z DRIVER « [Node 009] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -77 dBm
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 86
                                    └─[SupervisionCCReport]
                                        session id:          45
                                        more updates follow: true
                                        status:              Working
                                        duration:            1s
2023-03-18T21:08:31.894Z SERIAL « 0x011a00a8000109119f03570010ba62b7b73b489950f2c5e88d00b30c          (28 bytes)
2023-03-18T21:08:31.896Z SERIAL » [ACK]                                                                   (0x06)
2023-03-18T21:08:31.912Z DRIVER « [Node 009] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -77 dBm
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 87
                                    └─[SupervisionCCReport]
                                        session id:          45
                                        more updates follow: true
                                        status:              Working
                                        duration:            1s
```
This repeats every second. If I restart home assistant, the commandsRX keeps going up and these continue to appear in the log. If I pull the battery from the lock and put it back in the commands stop. This causes the battery in the lock to die quickly.
What did you expect to happen?
Not repeated commands so the battery lasts a normal time

### Device information

Manufacturer: Kwikset
Model name: Home Connect 620
Node ID in your network: 9

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Z-Wave JS UI addon version 1.7.2

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

This issue seems to have started a couple months ago. I first noticed an issue because the batterys went from last close to a year to lasting less than a month.

### Attach Driver Logfile

[zwavejs_2023-03-18.zip](https://github.com/zwave-js/node-zwave-js/files/11009809/zwavejs_2023-03-18.zip)

**Comment by AlCalzone** [comment]
workaround enabled by https://github.com/zwave-js/node-zwave-js/pull/6155
