### ISSUE TITLE
Wrong parameter Implementation for "ZW ESJ 300" 

### ISSUE THREAD

**Issue by gruntpartystyle** [AlCalzone/node-zwave-js#5598]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

**What causes the bug?**
Wrong config file, parameter 0 is wrongly implemented.
**What do you observe?**
The permissible values are too small, the configuration of the running time for the device is done differently than described.
**What did you expect to happen?**
Allow to enter the required value for configuration but with current config file not possible.

To solve, either allow bigger values to be entered and let the user "calculate" the required number or implement four bitmask options which will set all four values. I used the device extensively on an old Vera Lite where setting the parameter in dec or hex works fine. When migrating one device to HA in zwaveJS, I could even see that parameter 0 is configured with value 30125 (decimal) which is "illegal" as per current device file.

I am not an expert, I try to explain how it should be. The parameter 0 is configuring the runtime up and down as a bitmask with 16bits (?) like 1000111001110011.  In the device manual it is explained using hex (0x) values but I figured it is just a fancier way of saying bitmask. I tried to write a corrected version for the parameters but not sure if this is correct as I never coded anything. 
It is attached. 
[0x0064.txt](https://github.com/zwave-js/node-zwave-js/files/11077815/0x0064.txt)

Otherwise I am happy to explain how it should work and provide the original manual.
Thanks

### Device information

Manufacturer: Reitz-Group.de
Model name: ZW ESJ 300
	"manufacturer": "Reitz-Group.de",
	"manufacturerId": "0x0064",
	"label": "ZW ESJ 300",
	"description": "Duwi ZW ESJ 300 Blind Control",
[here](https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0064/zw_esj_300.json)

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwave-js-ui` branch:

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

I don't think this would serve any purpose as it is a configuration file problem.

**Comment by AlCalzone** [comment]
A link to the manual would be good

**Comment by gruntpartystyle** [comment]
Manual here https://opensmarthouse.org/zwavedatabase/563/reference/DUW-blind.pdf

**Comment by gruntpartystyle** [comment]
Maybe also see my blog where I wrote about this device with more references and more screenshots from manuals (German though) where it is explained better.... as the original manual lacks a lot of information.
https://notsoeverydaytechproblems.blogspot.com/2021/04/duwi-05436-jalousie-funk-einbauschalter.html

There it is explained in hex 0x values. Nowadays I understand it is a bitmask. 0-127 is used to set a time value and 128 is used to set the "mode", short or long mode. Short mode uses the value direct as seconds value, while long mode makes 10s steps starting from 130s. Both numbers are cramped together and then used as the parameter value (in dec it is 0 to 65535 or hex 0xFFFF).

**Comment by gruntpartystyle** [comment]
Can't help myself other than to upload as picture, wouldn't know how to type this in here.
This is the best I can do to explain it.

![image](https://user-images.githubusercontent.com/9739497/227936398-9681783e-e1bb-4cfa-b9b0-bd4006fbefa6.png)
“Short mode” allows values from 0 (see below) to 127s. With “long mode” you can get values between 130s to 1390s (23m) in 10s steps.
There are two «special values»:
- If runtime value set to 0, it will mean endless mode for that direction (Dauerbetrieb).
- Setting 0xFFFF / 1 1111111 1 1111111 / 65535 is default, means 120s up & down, despite above rules.

**Comment by AlCalzone** [comment]
Do you know if the default of 120s can be configured for up and down direction separately? So e.g. if one gets set to 0xff and one to 0, we'd have 120s in the one direction and endless mode for the other?

**Comment by gruntpartystyle** [comment]
If one would like to have 120s, one would rather programm it as 0x78 / 0b01111000 / 120 . 
Alternatively 0xFF / 0b11111111 / 255 apparently also means 120s, yes. 

If up is set to 0xFF and down to 0x00, would they go 120s up and endless down? Good question. 
I don't know. I could test this with the ESJ300 I still have paired to the Vera Lite hub and see how they behave.
Can do in a couple of days, on the road currently.

**Comment by gruntpartystyle** [comment]
Hello,
so I made a couple of tests over the Easter holidays. I can report back the following (and provide screenshots if required). The tests were done on a Micasaverde (now Ezlo) Vera Lite hub to set the desired parameter values. Setting of decimal values in the hub´s UI is easier and more reliable than hex values. Binary not possible. I always entered the decimal value as five digits, if required with leading zeros. Below I will also put the hex values in brackets but separate by an - for better readability. First pair is up movement, second pair is down movement. "The device" is the ZW ESJ 300. When I say "was accepted but re-wrote to" it means that I could set the parameter and the parameter was transmitted but the device did not save it as the given number but changed it to a different number, see below in the examples. This happened with the value xFF which was saved as x78 (120) as per manual FF is 120s.

- setting 00000 (x00-00) was accepted by the device and resulted in endless mode for up and down 
- setting 00255 (x00-FF) was accepted by the device but re-wrote to 00120 (x00-78); up **& down** movement was endless though!
- setting 65280 (xFF-00) was accepted by device but re-wrote to 30720 (x78-00); movement was 120s up and half second down [start and then immediately stop]
- setting 65535 (xFF-FF) was accepted by device but re-wrote to 30840 (x78-78); movement was 120s up and 120s down (as expected)
- setting 00025 (x00-19) was accepted but will make it run endlessly in both directions despite "down" set to x19 (25s)
- setting 08448 (x21-00) was accepted but is 33s up and only half second down, with start/stop immediately
- setting 65296 (xFF-10) was accepted but re-wrote to 30736 (x78-10) and is 120s up and 16s down (as expected)
- setting 05119 (x13-FF) was accepted but re-wrote to 04984 (x13-78) and is 19s up and 120s down  (as expected)
- setting 04112 (x10-10) was accepted, 16s up und down as expected
- setting 32382 (x7e-7e) was accepted, 126s both directions as expected
- setting 34698 (x87-89) was accepted and it showed the 200s up and 220s down as expected / described by manual

To summarize, any xFF given/sent to device was converted in the device to x78 and saved as such.
Any value starting with (x00-__) will make both directions go endlessly, despite whatever is set as second pair
xFF-00 (which will be saved as x78-00) and any regular value like x21-00 will make up movement as expected/set but down-movement will be very very short (start, then stop immediately). 

If hope this will help you to create the required config file. 

Two final notes: 
You can also set the movement times manually on the device once it is connected to a network. If you want to add this information as well to the file, let me know. I can share the procedure for manually setting the movement times as well. 
For the parameter 1, there is also some slight improvement in the description which could be done. But from the functionality it is already implemented correctly.

Thanks

**Comment by gruntpartystyle** [comment]
Any more data I can provide to help progress this?

**Comment by gruntpartystyle** [comment]
Push

**Comment by AlCalzone** [comment]
@gruntpartystyle sorry for the delay... Lots of work to do, not much time with 2 toddlers :)
Anyways, I've opened a PR with an updated config file. If you like to test, use [this file](https://raw.githubusercontent.com/zwave-js/node-zwave-js/4192405f0ac8333b19f0961ee5644aa39069d04a/packages/config/config/devices/0x0064/zw_esj_300.json) and follow [these instructions](https://zwave-js.github.io/zwave-js-ui/#/device-support/custom-device-files) (assuming you use zwave-js UI).

If everything works, I'll have this in the next release.

**Comment by gruntpartystyle** [comment]
Great. Thank you. I will test the file once I am back at the property.

**Comment by gruntpartystyle** [comment]
Can’t figure out how to load the device file. Might need a bit longer to figure that out.

**Comment by AlCalzone** [comment]
Anything unclear about the documentation I linked?

**Comment by gruntpartystyle** [comment]
Nothing you can help me with. I need to migrate from JS to JS UI first.

**Comment by AlCalzone** [comment]
I see. I can also just merge this, so you'll get it with the next update.
Then I  can make a revision if necessary.

**Comment by gruntpartystyle** [comment]
Works for me.

**Comment by gruntpartystyle** [comment]
Just to report it works fine, change finally made it into HA zwaveJS. Thanks.
