### ISSUE TITLE
Check Health - The node failed to decode the message. (ZW1405)

### ISSUE THREAD

**Issue by mkshb** [AlCalzone/node-zwave-js#5625]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

YES, BUT a Z-Wave JS UI developer has told me to come here

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
The health check does not work for S2 authenticated nodes. 

What do you observe?
If I run a health check on a node without S2, it is completed successfully. With S2 nodes the error ZW1405 occurs. 

What did you expect to happen?
Health Check 

  1. Go to Network Graph
  2. Click on S2 Node and run Health Check against Controller.
  3. See error

**Comment by AlCalzone** [comment]
The issue template is there for a reason. Please fill it out completely when opening an issue and don't just delete parts of it. That helps us investigate your issue quicker because all the necessary information is there. Otherwise, the issue will go to the bottom of the pile - and that pile is growing quickly.

**Comment by AlCalzone** [comment]
FWIW, I just completed a health check on an S2 authenticated node without issues. So this is something specific to your setup and requires a log to even begin troubleshooting.

**Comment by mkshb** [comment]
Hi there,

sorry about the form. I had filled out everything and probably misclicked somewhere.
Here is the rest of the info.

Which branches or versions?
zwave-js-ui: 8.12.0.c982de8
zwave-js: 10.12.0

Did you change anything?
No, but it's a fresh build network.

Did this work before?
Some devices respond with a time delay, but not always. 

Attach Driver Logfile
[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/11148944/zwavejs_current.log)

**Comment by AlCalzone** [comment]
Ok, looks like we need to introduce some more delays in the health check routine. The issue is caused by both parties trying to communicate at the same time, multiple times in a row.

**Comment by mkshb** [comment]
Just a little feedback and a big thank you!
Works with the current master Docker image.
