### ISSUE TITLE
Issue with Zipato mini keypad rfdi (wintop)

### ISSUE THREAD

**Issue by cokeman0** [AlCalzone/node-zwave-js#5626]
Hi,

After upgrading from zwavejs2mqtt 1.7.2 to 1.8.0 / 1.8.1 and 1.9.0

my 2 wintop keypads are acting up.

in the old 1.7.2, when entering og leaving, press home or away and hold up the rfdi tag.

in 1.8.x it's the same, BUT under 1.8.X it's like the wintop keypads wakes up, and resends the last action.

so when leaving the home, we are the alarm, but if the second keypad was last used to disarm, the the alarm are turned off and on durring the day

then event in HA (listen to events)  

there is no difference the notification in HA of a real event or the "resend"

The "resend" happens with the "wakeup", if that helps.

This was NOT an issue before 1.8.x and I had it running for at least 2.5 years

**Comment by robertsLando** [comment]
Could you tell me the zwavejs ui version please? Just press on the info icon on top right corener and paste it here

**Comment by cokeman0** [comment]
zwave-js-ui: 8.12.0
zwave-js: 10.12.0
home id: 3846378149
home hex: 0xe54312a5

tir. 4. apr. 2023 10.54 skrev Daniel Lando ***@***.***>:

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by AlCalzone** [comment]
I don't understand.

Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

In that log, make sure to capture the problem.

**Comment by cokeman0** [comment]
[zwave-js-ui-store.zip](https://github.com/zwave-js/zwave-js-ui/files/11148360/zwave-js-ui-store.zip)

logging was restricted to the 2 node id's I hope that makes it a bit faster to check.

At 13.59 and 14.05 the nodes 43 and 48, have sent events that trigger HA to disarm the alarm, but no one has used the keypad.

sometimes, it refreshes at 2 hours, some times closer to 6 hours.

looking at the triggers in HA.
today:
14:05
13:59
08:26
08:02
06:02

under HA's Zwave2mqtt ver 1.7.2 and 2.5 years back, this was never an issue.

**Comment by AlCalzone** [comment]
Okay that helps understand the problem. Please disable all filters, then re-interview one of the devices, and send send me that log. Maybe delete the logfile first, so it is shorter.

**Comment by cokeman0** [comment]
ID 43 reinterviwed

I hope you can find so errors in that log

[zwave-js-ui-store (1).zip](https://github.com/zwave-js/node-zwave-js/files/11148910/zwave-js-ui-store.1.zip)

**Comment by AlCalzone** [comment]
Yeah, I know what's wrong:
A recent update implemented a requirement that some nodes/CCs need to be polled every couple of hours. For Notification CC that is only a requirement when the node operates in "pull" mode
Your device is incorrectly detected as operating in "pull" mode, because of an edge case in the mode discovery. As a result it gets queried roughly every 6h when it wakes up and it seems to return the last notification it sent.

**Comment by cokeman0** [comment]
I do hope, that can be fixed 😄 but, yes, that sounds about right, my devices wakes up every 2 hours, and then the 6 hours pull, makes the strange pattern I can see in HA

**Comment by AlCalzone** [comment]
Fix is up at https://github.com/zwave-js/node-zwave-js/pull/5627
Once that is released, you will have to re-interview the devices again for the change to take effect.

**Comment by cokeman0** [comment]
Great... Not sure how to update, as I'm running the HA version...
