### ISSUE TITLE
Erroneous/faulty sensor reports

### ISSUE THREAD

**Issue by jkaberg** [AlCalzone/node-zwave-js#5641]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Bad network? Bad sensor?  I tried re-interviewing the devices several times. While both the devices in this screenshot is of the same model/manufacturer, I've seen this behavior across many different devices. My theory is that its due to either network congestion or just bad signal? Both devices presented below is within 3-4m range of controller.

What do you observe?
Sometimes sensors just give of bad readings like these
![image](https://user-images.githubusercontent.com/613363/230716909-30846c74-c976-4695-b580-81c61c4e3348.png)
![image](https://user-images.githubusercontent.com/613363/230716932-99b3d3a9-8056-4c69-bcaa-d67e1799fa7b.png)

What did you expect to happen?
Good readings 😄 Perhaps Zwave-js can detect and (optionally?) discard these bad readings. Are there any checksum or so one could make use of?

### Device information

Manufacturer: Heatit
Model name: Z-trm2fx 

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: main/master
`zwave-js-ui` branch: main/master

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

As this behavior is quite sporadic its hard to get logs of it. But I'll try

**Comment by andersevenrud** [comment]
Firstly, have you checked if there are any firmware updates available for your device ?

> Sometimes sensors just give of bad readings like these

> Perhaps Zwave-js can detect and (optionally?) discard these bad readings. Are there any checksum or so one could make use of?

Do other sensors outside `kWh` exhibit this behaviour ? If not, you might be running into the same issue that I've been very frustrated with.

Most of the meter readings (`kWh`) from my switches are bad (across different brands). The value reports and checksums actually are valid... my devices are just bugged with symptoms like:

* Zeroes under certain conditions
* Random negative number (as in #2692)
* Sometimes even a drop in the value (not a zero or negative, but a "reversion")
* Overshooting calculations up to ~50%

In my case I just gave up using the reported metering values and set up my own based on the `W` sensors, which seems very accurate using [Riemann sum integration](https://www.home-assistant.io/integrations/integration/) and [Utility Meter](https://www.home-assistant.io/integrations/utility_meter/) in HASS.

**Comment by jkaberg** [comment]
@andersevenrud Yeah newest available firmware on those, and AFAIK on the rest of my rig as well. 

What you describe regarding issues with sensors is very similar to what I'm seeing, pretty much the same. I might very well do what you suggest as this is quite frustrating (having to adjust bad readings)

I'll let this stew for a few days so the maintainers see it and know its out there.

**Comment by andersevenrud** [comment]
@jkaberg 

> What you describe regarding issues with sensors is very similar to what I'm seeing, pretty much the same

I suspected as much, especially when I saw which brand it was. It's one that's sold at the distributor where I got my bugged switches from (one of which I've been [documenting](https://gist.github.com/andersevenrud/5d13d30bfcc08a4e121222671f8cb9e9#file-1_zpr-111-md) because experience has been pretty bad)... and I have a suspicion that a lot of this stuff are white-label devices, which is why there's so many similar (or even *identical*) reports out there in the wild.

Seems like some of the gateways/bridges you can buy actually has some rules that drops (and/or corrects) some of these bugged values (I used this before going over to my own dongle w/HASS). But the overshooting meters is still an issue there... so there's definitively some kind of fault here.

Hope you get it sorted out.

God helg! :)

**Comment by jkaberg** [comment]
I just read @AlCalzone reply [here](https://github.com/zwave-js/node-zwave-js/issues/2692#issuecomment-1012907609) and while I perfectly agreed on his sentiment I'm afraid in the short term not much will happen (with manufacturers). 

I was thinking of an possible (but it stinks) solution would be for HASS to have some form of "ingestion filter" where before consuming new (sensor) data it would be possible to apply filter (like low-pass, outlier etc) per sensor/entity. Just an idea... 😄 The current "fix/approach" with template sensors/filters just ends up in mostly duplicated data.

With @AlCalzone's reply in mind, I will close the issue

**Comment by jkaberg** [comment]
@andersevenrud made an [feature request](https://community.home-assistant.io/t/ingestion-filters-for-sensors/557948) over at the HASS forums to continue the discussion over there.
