### ISSUE TITLE
 NIE-TECH / EVAlogik ZKS31 Rotary Dimmer

### ISSUE THREAD

**Issue by chuyskywalker** [AlCalzone/node-zwave-js#5693]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

 NIE-TECH / EVAlogik ZKS31  rotary dimmer

### Manufacturer ID

0x0312

### Product Type

0x7000

### Product ID

0x7002

### Firmware Version

1.4

### Do you have a manual?

[evalogik.pdf](https://github.com/zwave-js/node-zwave-js/files/11304128/evalogik.pdf)

Also; here is the zwave inspection from it being added into my network:

[zwave-js-add-rotary.txt](https://github.com/zwave-js/node-zwave-js/files/11304132/zwave-js-add-rotary.txt)
[zwave_js-f57d41796be23bf7406d88180740d451-Node 23-8a1ff21bc4d4dec5671eb5899c98b859.json.txt](https://github.com/zwave-js/node-zwave-js/files/11304133/zwave_js-f57d41796be23bf7406d88180740d451-Node.23-8a1ff21bc4d4dec5671eb5899c98b859.json.txt)

**Comment by AlCalzone** [comment]
fixed by #5877
