### ISSUE TITLE
Duewi 05437 - ZW ZS 3500 not pairing with Aeotec ZST10-700

### ISSUE THREAD

**Issue by Goldwing1973** [AlCalzone/node-zwave-js#5736]
Checklist

I am not using Home Assistant. Or: a developer has told me to come here.
I have checked the troubleshooting section and my problem is not described there.

    I have read the changelog and my problem is not mentioned there.

Deploy method : Docker

Z-Wave JS UI version : 8.14.2.c234053

ZwaveJS version : 10.16.0

Firmware Aeotec ZST10-700 : FW: v7.19.2

Describe the bug : Duewi 05437 - ZW ZS 3500 not pairing with Aeotec ZST10-700, the timer in zwavejs just keeps counting down to 0
It does pair with a Aeotec ZW090

To Reproduce : Try to pair ZW ZS 3500 on a Aeotec ZST10-700

Expected behavior : Succesfull pairing of the Duewi 05437 - ZW ZS 3500

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

Also if you didn't yet try to add an extension usb cable to your stick to improve connectivity

**Comment by Goldwing1973** [comment]
Here is the LOG file, i tried to add the plug 4 times in 2 inclusions
[zwavejs_2023-05-02.log](https://github.com/zwave-js/zwave-js-ui/files/11377320/zwavejs_2023-05-02.log)

"Also if you didn't yet try to add an extension usb cable to your stick to improve connectivity"
USB cable won't work, it's a GPIO connected z-wave controller.

Distance between plug and z-wave 700 controller is about 4 meters (same distance as the Z‐Stick Gen5 USB Controller where it does connect to without problems)

**Comment by AlCalzone** [comment]
Please check that the RF region is set correctly. There were some issues where that magically changed after firmware updates:
![grafik](https://user-images.githubusercontent.com/17641229/235883319-f2a1d3fe-7ac8-46b3-875e-ce6c82e903c3.png)

If that doesn't help, I'm afraid you're out of options. The EU version of the Aeotec Z-Stick 7 has measurable RF performance issues - maybe the Z-Pi 7 (GPIO module) does too.

**Comment by Goldwing1973** [comment]
RF Region was set to Europe.
And the performance issues, that could be, but why does a Fibaro Plug in the same wall socket pair without problems.
I even had battery powered motion sensors connected 15 meters away wich worked without problems.
Connecting the Deuwi to my  Z‐Stick Gen5 USB Controller works flawlessly.
Also, the Deuwi is the only device that won't connect (i have over 60 z-wave devices)

**Comment by AlCalzone** [comment]
> Connecting the Deuwi to my Z‐Stick Gen5 USB Controller works flawlessly

The Gen5 definitely has a much better antenna.

>  why does a Fibaro Plug in the same wall socket pair without problems

Maybe the Fibaro has a better antenna than the Deuwi.

---

Just to be sure, did you exclude the Deuwi from the other network before trying to include it into the new one?

**Comment by Goldwing1973** [comment]
`Just to be sure, did you exclude the Deuwi from the other network before trying to include it into the new one? `

yes, multiple times to be sure.
I’ll try to pair the Deuwi right next to the Z-Pi 7 to rule out the antenna and RF problem.

**Comment by Goldwing1973** [comment]
`The Gen5 definitely has a much better antenna.`
Apparently that is the case, i tried to pair the Deuwi right next to the Z-Pi7 and it paired immediately 

[zwave.log](https://github.com/zwave-js/node-zwave-js/files/11384818/zwave.log)

So, this is a RF/Antenna problem, i'll contact Aeotec on this.
I'll close the issue, thanks for your help.
