### ISSUE TITLE
Healed nodes not finishing re-interview

### ISSUE THREAD

**Issue by Hooverjc** [AlCalzone/node-zwave-js#5781]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.15.0.f48c52b

### ZwaveJS version

10.17.1

### Describe the bug

When I attempt to heal any (or all) nodes on my network, the healing completes successfully, but then the node's interview status changes to "none" and has a forever spining wheel and I loose all ability to control the device as all of its functions are no longer accessible. Rebooting zwave brings all this back. I looked in the logs and just after any individual node heals, I see the following (error at the end):

This is what I see before a repair:

![image](https://github.com/zwave-js/node-zwave-js/assets/42452872/e26670d5-fb51-4f0a-a8de-6a43bc4baf4c)

and after (until a reboot occurs)

![image](https://github.com/zwave-js/zwave-js-ui/assets/42452872/c9809832-17ef-4dd8-982c-e65eab0df729)

The error occurs twice in the logs once during and once just after the heal process has finished. It doesn't occur outside of this process and is referencing provisioning which I believe is related to the interview process this is stuck on.

2023-05-09 08:35:00.965 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot use 'in' operator to search for 'provisioning' in undefined

### To Reproduce

Heal any node and wait for the heal to complete

### Expected behavior

I'd expect to be able to use the node after healing and for the interview to complete as expected.

### Additional context

Not sure if this is the UI or the driver, but we'll start here since the error is "APP". Below is an extract from my logs of the start of the heal and the error after it is successful.

[z-ui_current.log](https://github.com/zwave-js/zwave-js-ui/files/11433031/z-ui_current.log)

**Comment by robertsLando** [comment]
@AlCalzone I think that unhandled rejection comes from zjs? I never use `in` operator on my side

**Comment by AlCalzone** [comment]
That's super strange. The error comes from a method that's called during inclusion, it accesses a value that should be set (and it seems never gets unset).

```
2023-05-09 08:33:50.285 INFO Z-WAVE: [Node 004] Found
```
This looks like there's another (or the same???) node getting included via SmartStart using the same node ID as the problematic one. Driver logs may give a better hint what's going on, but something fishy is happening in that network.

**Comment by Hooverjc** [comment]
You did assist me with migrating from a 500 series stick to a 700 series, so not sure if that's related. You had to modify a backup from my stick because there was something screwy going on. This issue is new in that as of a few releases ago I could heal without issue (at least from a gui perspective). I'll roll back a few versions and see if I can confirm this.

I don't use smart start at all, but I'd be happy to grab the driver logs. Where can those be found?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hooverjc** [comment]
I did roll back to a January release and no change, so I had that wrong. In case its related, the issue you helped me with the migrating from the 500 stick to the 700 stick: https://github.com/zwave-js/node-zwave-js/issues/5549. 

Here is the driver log. Its after a fresh reboot. Node being healed is 004

[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/11444015/zwavejs_current.log)

**Comment by Hooverjc** [comment]
I'd still like to get this looked at if at all possible to avoid having to rebuild the network entirely, but if this isn't something others are seeing, which appears to be the case, it can be changed form a bug to some other classification.

**Comment by Hooverjc** [comment]
Also, not seeing any options to reopen this, so not sure what to do there.

**Comment by AlCalzone** [comment]
This seems like a bug in the controller firmware, but no one else seems to run into it. I'll change our code so it just ignores those inclusion messages for nodes that are clearly part of the network already.
