### ISSUE TITLE
`treatBasicSetAsEvent`: only expose the `event` value, not current/target value if BasicCC should normally be hidden

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#5784]
ref: https://github.com/home-assistant/core/issues/92789

**Comment by kpine** [comment]
Interview of affected device: [zwave_js.log](https://github.com/zwave-js/node-zwave-js/files/13217652/zwave_js.log)

HA device diagnostic: [zwave_js-3aea29d0aede8f900a111601a3df8501-In-Wall Paddle Dimmer, 500S-3ce0c3bd1edb94a31040ea866af06cd1.json.txt](https://github.com/zwave-js/node-zwave-js/files/13217665/zwave_js-3aea29d0aede8f900a111601a3df8501-In-Wall.Paddle.Dimmer.500S-3ce0c3bd1edb94a31040ea866af06cd1.json.txt)
