### ISSUE TITLE
Qubino flush dimmer 0-10V (ZMNHVD) included but do not want to use repeaters

### ISSUE THREAD

**Issue by Kratax** [AlCalzone/node-zwave-js#5799]
Hi,
I have an issue with one ZMNHVD flush dimmer. Although alive and connected (included and seems to be working well), it is not willing to use any repeaters although should be available and better connection. On the map is shown as grey (named wallbox)... Healing does not help neither....
Any advice how to solve this?
Thanks a lot.
Regards,
Kratax

![image](https://github.com/zwave-js/zwave-js-ui/assets/25452697/2e0d698e-8124-4497-ab17-8c7610a0d694)

![image](https://github.com/zwave-js/zwave-js-ui/assets/25452697/1f8c5277-d8d6-4f19-bef0-664b5b769afd)

![image](https://github.com/zwave-js/zwave-js-ui/assets/25452697/68d4a9cf-2eb4-4e3e-b5fe-e272f7843bf6)

**Comment by robertsLando** [comment]
@Kratax try to heal device

**Comment by robertsLando** [comment]
@Kratax try to heal device

**Comment by Kratax** [comment]
> @Kratax try to heal device

I did it twice.... Still the same...

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by AlCalzone** [comment]
Another case of "don't trust that map" --> https://github.com/zwave-js/zwave-js-ui/issues/2517

In the 2nd screenshot you can see that it does route through nodes 34 and 39, but apparently they are not considered neighbors by the stick or device firmware 🤷‍♂️

**Comment by robertsLando** [comment]
Just for info, now with latest zwave-js-ui version you can set priority routes on nodes from network graph
