### ISSUE TITLE
zw_programmer 

### ISSUE THREAD

**Issue by hassan-xy** [AlCalzone/node-zwave-js#5804]
Hi,
I wanted to know if zw_programmer is needed for updating the zwave source code using zwave-js firmware update feature. I dont have it on my board yet and tried to use the firmware update feature but it returned error message. similiar to chipset not in bootloader mode.
Sorry I dont remember it clearly, but if you guys know whats wrong, please let me know. 

Thanks

**Comment by AlCalzone** [comment]
This repository is for the over-the-air firmware update service of end-devices.

**Comment by AlCalzone** [comment]
To answer your question: Z-Wave JS only supports over-the-wire updates of controllers that already have a bootloader. It does not support the initial flashing of the bootloader.
