### ISSUE TITLE
Missing device configuration: NEO Cool Cam Repeater NAS-RP01Z1

### ISSUE THREAD

**Issue by bramboot** [AlCalzone/node-zwave-js#5824]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

NAS-RP01Z1

### Manufacturer ID

0x0258

### Product Type

0x0010

### Product ID

0x0716

### Firmware Version

1.40.0

### Do you have a manual?
[NEO_NAS-RP01Z1_download_1.pdf](https://github.com/zwave-js/node-zwave-js/files/11530587/NEO_NAS-RP01Z1_download_1.pdf)

**Comment by AlCalzone** [comment]
fixed by https://github.com/zwave-js/node-zwave-js/pull/6332
