### ISSUE TITLE
Issue with 10.21.0 and zooz zen31 devices

### ISSUE THREAD

**Issue by msandrofJC** [AlCalzone/node-zwave-js#5841]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

After upgrading to 1.28.0-10.21.0 (using the kpine/zwave-js-server docker image), my zooz zen31 RGBW dimmer devices started misbehaving.
By misbehaving, I mean their state reflected in HA would not match the physical state of the device. For example, turning off the device in HA would physically work, but HA would still show it as on. The devices were also very slow to react to state changes as well, but the main issue appears to be the mismatch between HA state and physical state. Reverting to 1.28.0-10.20.0 fixed the problem. Not sure if other devices were similarly affected.  Also tested in the most current version 10.22.1, but the problem is the same.

What did you expect to happen?
Expected behavior of the ZEN31 devices  should be the same in 10.21.0 as it is in previous versions.

 Not sure how to describe a problem that requires a specific device. 

### Device information

Manufacturer: Zooz
Model name: ZEN31
Node ID in your network: 51, 53, and 59

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [X] Other _(please describe)_

### Which branches or versions?

version:  1.28.0-10.22.1 of docker.io/kpine/zwave-js-server       

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

It worked in 1.28.0-10.20.0, but hasn't worked since.

### Attach Driver Logfile

[zwave_current.log](https://github.com/zwave-js/node-zwave-js/files/11558929/zwave_current.log)

**Comment by kpine** [comment]
I would try [`1.28.0-10.22.2`](https://github.com/kpine/zwave-js-server-docker/pkgs/container/zwave-js-server/95980845?tag=1.28.0-10.22.2).

**Comment by msandrofJC** [comment]
Looks like things are working again with 1.28.0-10.22.2! Looks like this issue can be closed! Thanks!
