### ISSUE TITLE
Missing device configuration: Qubino Shades Remote Controller, ZMNKGD1

### ISSUE THREAD

**Issue by KattenJansson1974** [AlCalzone/node-zwave-js#5846]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Qubino Shades Remote Controller, ZMNKGD1

### Manufacturer ID

0x015A

### Product Type

0x2000

### Product ID

0x0003

### Is the device listed on the Z-Wave Alliance website?

No

### Do you have a manual?

[Qubino_Shades_Remote.pdf](https://github.com/zwave-js/node-zwave-js/files/11578179/Qubino_Shades_Remote.pdf)

**Comment by AlCalzone** [comment]
The product ID should either be shown in Z-Wave JS UI when you open the dropdown for the node, or in a diagnostics dump in Home Assistant.

**Comment by KattenJansson1974** [comment]
Updated with correct Manufacturer ID, Product Type and Product ID
