### ISSUE TITLE
Missing device configuration: PM-B400ZW-N

### ISSUE THREAD

**Issue by techinpark** [AlCalzone/node-zwave-js#5849]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

PM-B400ZW-N

### Manufacturer ID

396

### Product Type

66

### Product ID

0x5

### Firmware Version

78.40

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/1870

### Do you have a manual?

<img width="1789" alt="image" src="https://github.com/zwave-js/node-zwave-js/assets/45546296/abdfadc2-61af-47f4-87c5-b5fa984b1dde">

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 1870 from ZWA

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 1870 from zwa
