### ISSUE TITLE
Improve handling of unknown (254) values

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#5864]
In reference to https://github.com/zwave-js/node-zwave-js/discussions/4804

The current solution of using the string `"unknown"` or `undefined` for numbers is not ideal (one is not a number, the other does not get emitted in events). On the other hand, the signal value 254 lies outside of the min/max range which applications need to be able to rely on.

The preferred solution is using two different signal values:
- `null` for (known to be) unknown --> 254
- `undefined` for not (yet) known --> not queried/no response

**Comment by sanderlv** [comment]
What's the point of these unknown entities that spoil my entities database?

<img width="555" height="192" alt="Image" src="https://github.com/user-attachments/assets/7cf28ecd-5f9d-429a-8558-2a924691bc32" />

<img width="1695" height="777" alt="Image" src="https://github.com/user-attachments/assets/9e8aa8ca-dd0f-4f8e-ad9f-be9207f1fea6" />

They suddenly just "appeared" on many of my devices... can't they be just left way if it's nothing (as before)?

**Comment by AlCalzone** [comment]
Please open a new issue and share the device diagnostics
