### ISSUE TITLE
New Zooz ZST10-700 with 7.19.2 firmware not identified after NVM restore from 500 controller

### ISSUE THREAD

**Issue by ridizy** [AlCalzone/node-zwave-js#5910]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Zooz ZST10-700

### Manufacturer ID

0x027a

### Product Type

0x0001

### Product ID

0x000d

### Firmware Version

7.19.2

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4260?selectedFrequencyId=2

### Do you have a manual?

https://cdn.shopify.com/s/files/1/0218/7704/files/zooz-700-series-z-wave-plus-usb-stick-zst10-700-manual.pdf?v=1609159024

I restored the NVM from a HUSBZ-1 controller to a new Zooz ZST10-700 controller.  The new controller came with v7.19.2 firmware.

It's showing as an unknown product, although it does appear to be functioning correctly:
![image](https://github.com/zwave-js/node-zwave-js/assets/33641/81d9512d-0709-4fa0-8fdb-7ad4b30da461)

It is listed in the configuration DB, but under Silicon Labs with a different hexId

**Comment by AlCalzone** [comment]
Let me clarify with Zooz if that's their new fingerprint for the stick now.

**Comment by MarcusSteen** [comment]
I have the same problem - the stick shows up according to picture above. Got the USB stick from Amazon with US frequency and would like to update firmware to have EU frequency instead. When trying to do the update of firmware the feedback that the controller is not in boot loader mode.

<img width="1249" alt="Control Panel" src="https://github.com/zwave-js/node-zwave-js/assets/76737950/f9e9ba59-8941-4b13-ba11-f831e5a8814b">


<img width="512" alt="Error Message" src="https://github.com/zwave-js/node-zwave-js/assets/76737950/9cb9cd0e-24b7-4cb6-b7c8-91db413acdef">

**Comment by AlCalzone** [comment]
> Got the USB stick from Amazon with US frequency and would like to update firmware to have EU frequency instead.

AFAIK you can just switch the region in the settings on that firmware.

**Comment by AlCalzone** [comment]
FWIW, Zooz have just confirmed the changed IDs, will fix on Monday.
