### ISSUE TITLE
Z-Wave JS driver regression causing device misconfiguration

### ISSUE THREAD

**Issue by qwertymodo** [AlCalzone/node-zwave-js#5923]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Adding or re-interviewing a device causes the driver to misconfigure the endpoint for receiving messages.

What do you observe?
My z-wave thermostat, which was previously working perfectly in Home Assistant, no longer reports the correct temperature, or any changes made from the thermostat touchpad after a recent update.  Sending commands such as setpoint changes or HVAC mode changes from the HA web UI DO correctly execute on the thermostat, so HA->thermostat communications are working correctly.  It is only the thermostat->HA communications that are not working.

What did you expect to happen?
I expect Home Assistant to properly display the current temperature as reported by my thermostat, as well as other information such as active/idle status, or setpoint changes made using the thermostat touchpad.

  1. Re-interview a device that was previously working
  2. The device no longer functions properly
  3. Logs show that the device is configured to listen on a different endpoint than it is actually receiving messages on

### Device information

Manufacturer: Radio Thermostat
Model name: CT32
Node ID in your network: 12

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Driver Version: 10.23.2
Server Version: 1.28.0

### Did you change anything?

yes (please describe)

### If yes, what did you change?

I updated Home Assistant to the latest version, along with the Z-Wave integration.  At the same time, I also needed to reset my thermostat, which required me to re-add it to Home Assistant.  This is in-line with the troubleshooting I attempted with another user, who noted that re-interviewing their device using the latest version caused a similar misconfiguration.

### Did this work before?

Yes (please describe)

### If yes, where did it work?

This worked when I initially set up my device approximately around October 2022.  During troubleshooting on Discord, it was reported that it appears the last working version was ZUI 8.15.0, driver 10.17.1

### Attach Driver Logfile

[zwave_js (1).log](https://github.com/zwave-js/node-zwave-js/files/11766884/zwave_js.1.log)

**Comment by kpine** [comment]
I have the same device, which was working with 10.23. After a re-interview, I have the same issue. I went back a few versions and found the following:

10.17.1 is working. Value IDs are using endpoint 0, device reports on endpoint 0.
Re-interview -> [zwavejs_10.17.1.log](https://github.com/zwave-js/node-zwave-js/files/11767019/zwavejs_10.17.1.log)
HA Device diagnostic -> [thermostat-10.17.0.json.txt](https://github.com/zwave-js/node-zwave-js/files/11767024/thermostat-10.17.0.json.txt)

10.18.0 is not working. Value IDs are using endpoint 1, device reports on endpoint 0.
Re-interview -> [zwavejs_10.18.0.log](https://github.com/zwave-js/node-zwave-js/files/11767022/zwavejs_10.18.0.log)
HA Device diagnostic -> [thermostat-10.18.0.json.txt](https://github.com/zwave-js/node-zwave-js/files/11767028/thermostat-10.18.0.json.txt)

The 10.18 changelog is pretty short, perhaps #5747 isn't working right for this device?

**Comment by AlCalzone** [comment]
On one hand I'm not sure why the endpoints are now no longer considered unnecessary. If I make one of you a test build of the driver, can you make a new log with that, e.g. by building a custom Z-Wave JS UI container?

On the other hand, we already use this compat flag for the `CT100`:
```jsonc
	"compat": {
		// The device has two endpoints. The temperature gets reported via the root, humidity is on endpoint 2.
		"mapRootReportsToEndpoint": 1,
```
Maybe it's the same for this device, especially this: _The temperature gets reported via the root, humidity is on endpoint 2_?

**Comment by kpine** [comment]
I can try a debug build.

As for the compat flag, that could work, I'll give it a try also. The devices are similar. In this case, everything is reported on endpoint 0. Endpoint 2 is not used and the values are redundant.

**Comment by kpine** [comment]
```json
		"preserveRootApplicationCCValueIDs": true,
		"removeEndpoints": "*"
```
seems to restore the previous behavior. I don't think I've ever seen any reports for endpoints 1 and 2. I don't know why they exist.

**Comment by AlCalzone** [comment]
I just finished v11, so test builds are a bit complicated for the moment.
I'm gonna just merge the PR you put up. If there's another device where the heuristic fails in a similar way, I'll give it a look.
