### ISSUE TITLE
Add compat flag to treat any SET command as a report

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#5937]
re https://github.com/AlCalzone/ioBroker.zwave2/issues/1011
or https://github.com/zwave-js/node-zwave-js/issues/6290, using a controlling device as input

**Comment by XLDom** [comment]
Hello, I'm not a big user of git.... (i don't understand the errors)
@AlCalzone if you can see what is blocking please: https://github.com/zwave-js/node-zwave-js/pull/6415

thanks for all
