### ISSUE TITLE
Node interview stuck at "node info" for Ring Keypad V2 and server not responding

### ISSUE THREAD

**Issue by Charles-HL** [AlCalzone/node-zwave-js#6012]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

YES, BUT a Z-Wave JS UI developer has told me to come here

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Description:
I am encountering an issue while attempting to pair a Ring Keypad V2 with my setup consisting of a Raspberry Pi 4 and an AEOTEC ZW090-C Gen5 Plus. Following the official documentation, I deployed the Docker using Docker Compose and configured the S2 and S0 keys.
When I initiate the pairing process through the "manage node" feature, the keypad is successfully detected, and I am prompted to enter the DSK pin. However, in the node table, the interview status of the keypad remains stuck at "node info" with a yellow status. Subsequently, the processor utilization spikes to 60% to 100%, and after some time, the status at the top right of the UI turns red, indicating disconnection. Attempting to refresh the page yields no response, while the CPU usage remains persistently high. Even after restarting the Docker, I can briefly connect to the UI for a few seconds before encountering the same problem again.

To reproduce:
Set up a Raspberry Pi 4 and an AEOTEC ZW090-C Gen5 Plus
Deploy the Docker environment using Docker Compose.
Access the user interface (UI) of the Docker deployment.
Navigate to the "manage node" section.
Initiate the pairing process for the Ring Keypad V2.
When prompted, enter the DSK pin for the keypad.
Observe the node table in the UI and notice that the interview status of the keypad remains at "node info" with a yellow status.
Monitor the CPU usage, which may increase to 60% to 100%.
After some time, the status at the top right of the UI changes to red, indicating disconnection.
Attempt to refresh the page, but observe that there is no response.
Note that the CPU usage continues to remain high.
Restart the Docker environment.
Briefly connect to the UI for a few seconds after the restart.
Notice that the issue reoccurs, with the keypad remaining disconnected and the CPU usage spiking again.

### Device information

Manufacturer: Ring
Model name: Keypad Gen 2 Model 5B28S8
Node ID in your network: 2

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwave-js-ui` branch:

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwavejs_2023-07-13.log](https://github.com/zwave-js/node-zwave-js/files/12038155/zwavejs_2023-07-13.log)

**Comment by AlCalzone** [comment]
This always seems to happen when parameter 23 gets queried and the response is received. Is it possible to include the device without security? It's probably not functional then, but I'd like to see if that gives us some more info about what happens.

**Comment by Charles-HL** [comment]
@AlCalzone  Those are the logs when I pair the device without security. On those logs, the node id is 3, the pairing works sucessfully with the status complete, but the device is unusable as expected
[z-ui_2023-07-13.log](https://github.com/zwave-js/node-zwave-js/files/12040124/z-ui_2023-07-13.log)
[zwavejs_2023-07-13.log](https://github.com/zwave-js/node-zwave-js/files/12040125/zwavejs_2023-07-13.log)

**Comment by AlCalzone** [comment]
Damn, that's a different kind of unusable than I intended. In this scenario, most of the CCs aren't even available.

Please try again, this time specifically choose **Security S0** when including, so we can narrow it down to the S2 code being the culprit or not. I may need your S0 key to work with the logs, which you can send to the email in my profile.

If that doesn't work either, we can enable further debug logging for Security S2, which is unfortunately more difficult to debug.

**Comment by Charles-HL** [comment]
@AlCalzone  With only S0 security, the device is still unusable but the device name and model are detected.
When I pair the device I have this message
![image](https://github.com/zwave-js/node-zwave-js/assets/61110764/43e97146-f8b3-431e-bd58-bb657cd003ff)
I have this S0 key BDA6C4737BEA173D1FCA0650A890424B and the node id is 4.
The logs: [zwavejs_2023-07-14.log](https://github.com/zwave-js/node-zwave-js/files/12050284/zwavejs_2023-07-14.log)

**Comment by Indianb0y016** [comment]
I knew something was wrong when I issued a reinterview command to my second ring keypad today and the network just crashed.
This behavior is completely abnormal, since it didnt give issues like this before. I used to be able to pair the devices just fine before. Sadly I dont have logs or dates of when I paired them. I can try and check my various backups for any logs or info. 
Since I am also facing this issue, let me know if I can provide any logs that may help.

For anybody having issues getting their network back, what worked for me was resetting the keypad. There will be some waiting time for the zwavejs container to start, but with the keypad no longer pinging the network, the network should eventually restart. Another method is to put the keypad in the microwave (not microwaving it! Just blocking rf), as mentioned in the duplicate issue thread. 

One more update. I had a prior version of zwavejs ui, in my backups. Specifically, ZwaveJs 1.18.1. After restoring it, I tried to add my keypads back and it was successful, as well as being usable. There was a change in 1.19 that must've broken the interview portion, especially hitting this device hard.

**Comment by AlCalzone** [comment]
> the device is still unusable

Something is off with the S0 communication here - I need to look into that.
FWIW, I just bought the device so I can debug more easily - will update here when there's something to share.

**Comment by Charles-HL** [comment]
I switched to zwavejs/zwave-js-ui:8.16.1 , in this version all works fine

**Comment by Indianb0y016** [comment]
I just wanted to add something else as well. Although NOT specific to the ring keypad, version 1.19 also changed how some of my devices report configuration parameters. My radio CT100 thermostat, with the current configuration file reports every available configuration parameter as defined in the config file in the db. This is on version 1.18.1.
HOWEVER, on version 1.19, the configuration parameters are all messed up and not respecting the file anymore. Even after tweaking with the file to determine why it wasn't respecting it, I couldn't figure out why. But after yesterdays rollback to 1.18.1, the configuration is perfectly fine. Heres an example.
Parameter 2 is a partial parameter, so it has multiple options.

**1.18.1**
2[0xff0000000] 
value: 1
Reports HVAC type correctly with the respective label

**1.19**
2[0xff0000000]
Unable to identify this, and instead, a new configuration parameter in the zwavejs is found, under "param002" with value: 1
The original HVAC type parameter entry is now blank and unknown. There are other configuration parameters that popup and report "undefined"

I hope this may be of some use

**Comment by andltayl** [comment]
I also have this exact issue. If there is anything I can do to help I'd be happy to do so.

**Comment by AlCalzone** [comment]
Took way longer to get the device than figuring out what the issue is - but I would never have guessed it without debugging...
https://github.com/zwave-js/node-zwave-js/pull/6029 fixes the issue by simply replacing a left-shift with a multiplication by 2.

Apparently, bit-shifting in JS operates on signed integers, which effectively created an infinite loop.
