### ISSUE TITLE
Missing device configuration: Inovelli NZW31T

### ISSUE THREAD

**Issue by kmccb** [AlCalzone/node-zwave-js#6052]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Inovelli NZW31T

### Manufacturer ID

0x015d

### Product Type

0x1f02

### Product ID

0x1f02

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/2679

**Comment by kmccb** [comment]
I may have submitted the ticket wrong because it's still not working.. The device is an Inovelli NZW31T which is listed: https://devices.zwave-js.io/?jumpTo=0x0312:0x0111:0x261c:0.0#

However, in HA the device is discovered as 0x015d-0x1f02-0x1f02.. 

0x015d is Willis Electric Co which looks like another name for Inovelli.. 

0x1f02 needs to be moved under 0x015d (Willis)..

**Comment by AlCalzone** [comment]
Are you sure your application has been updated to `node-zwave-js` version `11.6.0` yet?
I guess not, since at the time of writing only Z-Wave JS UI standalone has updated: https://zwave-js.github.io/which-version/

> Z-Wave JS UI (HA Addon)
> 
> Latest version:
>     v1.15.1
> Z-Wave JS UI version:
>     v8.21.1
> Driver version:
>     v11.5.3
> 
> Z-Wave JS UI (Standalone)
> 
> Latest version:
>     v8.21.2
> Driver version:
>     v11.6.0
> 
> HA Core Addon
> 
> Latest version:
>     0.1.84
> Driver version:
>     10.23.2

**Comment by kmccb** [comment]
So it's nothing on my end? I just need to wait until Z-Wave JS UI HA Addon is updated?
