### ISSUE TITLE
Missing device configuration: Leviton RZM10-1L 

### ISSUE THREAD

**Issue by andyp05** [AlCalzone/node-zwave-js#6078]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Leviton RZM10-1L

### Manufacturer ID

0x1d

### Product Type

0x0601

### Product ID

0x0206

### Firmware Version

0.3

### Do you have a manual?

This dimmer switch is virtually identical to the supported Leviton RZI10-1L
The switch listed here is for magnetic dimmers and the supported switch is the same except it supports incandescent dimmers.

The only difference is product type. One is product type: 0x0601 and below it is 0x0501. The manufacture id and product id's are the same.

```
// Leviton RZI10-1L
// Dimmer switch 1000w incandescent
{
	"manufacturer": "Leviton",
	"manufacturerId": "0x001d",
	"label": "RZI10-1L",
	"description": "Dimmer switch 1000w incandescent",
	"devices": [
		{
			"productType": "0x0501",
			"productId": "0x0206"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"associations": {
		"1": {
			"label": "Lifeline",
			"maxNodes": 1,
			"isLifeline": true
		}
	}
}
```

https://www.smarthome-products.com/productspecs/ViziaRZ106Spec.pdf

Proposed config file:
```
// Leviton RZM10-1L
// Dimmer switch 1000w magnetic
{
	"manufacturer": "Leviton",
	"manufacturerId": "0x001d",
	"label": "RZM10-1L",
	"description": "Dimmer switch 1000w magnetic",
	"devices": [
		{
			"productType": "0x0601",
			"productId": "0x0206"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"associations": {
		"1": {
			"label": "Lifeline",
			"maxNodes": 1,
			"isLifeline": true
		}
	}
}
```

**Comment by AlCalzone** [comment]
Adding it in https://github.com/zwave-js/node-zwave-js/pull/6080
