### ISSUE TITLE
Zooz ZEN72 firmware update process times out after update is successful

### ISSUE THREAD

**Issue by kpine** [AlCalzone/node-zwave-js#6079]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

A ZEN72 is included with S2 Auth. I updated the firmware. Z-Wave JS discards an insecure firmware update success report, so it doesn't realize it completed. With 100% progress, eventually the process times out. As a result, the device is not automatically re-interviewed.

Well, I guess this is probably a device bug (sending an insecure report?), but I thought I'd start here.

What do you observe?

I updated a Zooz ZEN72 to the latest firmware. It completed, but Z-Wave JS reports it as timed out. This means it isn't automatically re-interviewed.

What did you expect to happen?

A successful completion is reported and the device re-interviewed.

Update a Zooz ZEN72 firmware?

### Device information

Manufacturer: Zooz
Model name: ZEN72
Node ID in your network: 43

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 11.6.0
`zwave-js-ui` branch: 8.21.2

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

You can see at the end of the firmware update there's a success report that is discarded due to being insecure. I re-interviewed after the timeout was reported and the version is updated.

[zwave_js.log](https://github.com/zwave-js/node-zwave-js/files/12180697/zwave_js.log)

**Comment by AlCalzone** [comment]
Yep, seems like a device bug.

**Comment by jeffjensen** [comment]
Zooz ZEN17 firmware update hit this morning (node 43) and it timed out at finish.  Upgraded from 1.4.1 to 1.40.2.  As prior, a reinterview corrects the fw version display.  Attached zwjs driver log covering that time.
[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/14884336/zwavejs_current.log)

**Comment by AlCalzone** [comment]
Yep, same issue. The device is included with S2, but then sends the report without encryption:
```
2024-04-05T11:12:34.078Z DRIVER » [Node 043] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ callback id:      113
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 200
                                    │ security class:  S2_Authenticated
                                    └─[FirmwareUpdateMetaDataCCReport]
                                        report #: 6006
                                        is last:  true

...

2024-04-05T11:12:43.662Z CNTRLR   [Node 043] command was received at a lower security level than expected - disc
                                  arding it...
2024-04-05T11:12:43.663Z DRIVER « [Node 043] [REQ] [BridgeApplicationCommand]                        [discarded]
                                  │ RSSI: -69 dBm
                                  └─[FirmwareUpdateMetaDataCCStatusReport]
                                      status:    OK_RestartPending
                                      wait time: 0 seconds
```

**Comment by AlCalzone** [comment]
According to Zooz, this issue is fixed in newer firmware versions. Not worth working around IMO.
