### ISSUE TITLE
Security info not showing correctly

### ISSUE THREAD

**Issue by bostjane** [AlCalzone/node-zwave-js#6098]
Hi,

I wanted to move Aetoec multisenzor 6 from S0 security to no security, but wanted to keep the same node ID. So I manually reset the device and proceed with "Replace failed node" process. Device was successfully added, it works fine, but in GUI I see question mark in security column. I tried also re-interview node, but nothing helped.

How can I fix this? Version is 8.21.2
[Capture](https://github.com/zwave-js/zwave-js-ui/assets/7306524/428291f8-ee46-482f-a9b5-34aedbfba20e)

**Comment by jmgiaever** [comment]
Did you also tick the "reset security classes" checkbox for the re-interview?

**Comment by bostjane** [comment]
Yes I did.

**Comment by bostjane** [comment]
Maybe some mismatch data in config files, which also prevents re-interview to rewrite/fix it?

**Comment by robertsLando** [comment]
> So I manually reset the device and proceed with "Replace failed node" process.

When you factory reset the device ensure your stick is not connected, then use replace failed node against that node, also some nodes have a specific procedure to put them in secure inclusion, check you did that correctly. Also please enable debug logs so in case this fails we can check what's going on

Make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

cc @AlCalzone

**Comment by AlCalzone** [comment]
Will try to reproduce later and see what's going on.

**Comment by AlCalzone** [comment]
Ok I cannot reproduce. I even tried removing all security keys but S0. What I did:

- include device using S0, wait for interview to finish
- shut down Z-UI
- factory reset device
- start Z-UI
- replace failed node, select "no encryption"

Result:
![grafik](https://github.com/zwave-js/node-zwave-js/assets/17641229/187b8dc8-9814-4c34-90f8-b68c1cfae83a)

**Comment by bostjane** [comment]
> > So I manually reset the device and proceed with "Replace failed node" process.
> 
> When you factory reset the device ensure your stick is not connected, then use replace failed node against that node, also some nodes have a specific procedure to put them in secure inclusion, check you did that correctly. Also please enable debug logs so in case this fails we can check what's going on
> 
> Make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).
> 
> cc @AlCalzone

Yes, I manually reset the device while stick was disconnected. Maybe the problem is because I needed to go with Replace failed node" process twice as it failed for the first time - I can't remember exactly why.
In case log doesn't tell you what is the problem maybe I can send you cache or other configuration file that cold be causing the problem.


[zwavejs_2023-08-01.log](https://github.com/zwave-js/node-zwave-js/files/12224728/zwavejs_2023-08-01.log)

**Comment by AlCalzone** [comment]
The connection to that device is terrible - 9.6kbit/s, latencies upwards of 300ms and several timeouts during the interview. I would not be surprised if that's the reason.

**Comment by bostjane** [comment]
True, but I suppose devices with no security retry mechanism should do the trick.
Anyway, further I tried the following. I put controller and device only 20cm apart, checked option "Increase node report timeout" and made the re-interview again. This time GUI showed none timeouts and dropped packets, but the problem persists.
Is the re-interview equivalent to initial inlusion or may there be something left from initial inclusion with S0 security...just a wild guess.
![Capture](https://github.com/zwave-js/node-zwave-js/assets/7306524/12001fae-faf6-45bb-a2df-1bb7dcb3c023)
[zwavejs_2023-08-01.log](https://github.com/zwave-js/node-zwave-js/files/12232516/zwavejs_2023-08-01.log)

**Comment by AlCalzone** [comment]
Ok that interview looks totally fine. There should be a `<homeid>.jsonl` file in the store, homeid is a 8-digit hex number. Can you send me that one?

**Comment by bostjane** [comment]
[zwave.zip](https://github.com/zwave-js/node-zwave-js/files/12248114/zwave.zip)

**Comment by AlCalzone** [comment]
Ok looks like the info about security classes isn't being stored for that one for whatever reason.

**Comment by bostjane** [comment]
Yesterday I tried another thing. I restarted ZWave JS and deleted all three configuration files that contained my HomeID. Therefore Zwave JS had to re-interview all the nodes. So it was practically the same when I moved from OZW to Zwave JS.
This time maybe 1/3 of devices got question mark on security column. But when I moved from OZW it got them all correctly (same network and devices).

I guess something changed along the way in Zwave JS that introduced a bug which prevents security info to be stored.

**Comment by AlCalzone** [comment]
> This time maybe 1/3 of devices got question mark on security column.

have you got a driver log of this?

**Comment by bostjane** [comment]
I tried again with my test network with just 3 nodes, actually 2 (num 3 and 5), because node 7 has dead battery and it's normal that it didn't respond.
As you can see, security info for both nodes was not saved.

[zwavejs_2023-08-17.log](https://github.com/zwave-js/node-zwave-js/files/12372055/zwavejs_2023-08-17.log)
![Capture](https://github.com/zwave-js/node-zwave-js/assets/7306524/8b06710a-bd40-43f1-8bc5-403e5989eaa3)

**Comment by bostjane** [comment]
And here are config files if you need them too.
[store.zip](https://github.com/zwave-js/node-zwave-js/files/12372066/store.zip)

**Comment by AlCalzone** [comment]
Should be fixed in the next release (after another re-interview)
