### ISSUE TITLE
Binary Switch vundefined

### ISSUE THREAD

**Issue by MickaelC26** [AlCalzone/node-zwave-js#6105]
Hello everyone, 
I added this json (customized)
[mh-s411-7102.zip](https://github.com/zwave-js/zwave-js-ui/files/12226090/mh-s411-7102.zip)

Then, I included a MCOHome MH-S411 panel switch to Zwave JS UI.
Everything seems fine, but when I turn On the switch (using targetValue or currentValue), the currentVallue change to True then to False one sec later, but the light stay On.
If I turn Off the switch (using targetValue or currentValue), the light switch Off.

I also remarked that, just after the inclusion, I only have the Binary Switch v2 command class, but as soon as I change the switch state once, a new command class appear (Binary Switch vundefined). Those currentValue doesn't have the same problem as Binary Switch v2, but I can't trigger anything using them. (37-1-currentValue or target value won't trigger my switch, they are just following 37-0- state)
 
I also tried witthout the MH-S411's json loaded, but I get the same result.
Could someone enlight me on this issue ?

Thanks in advance !
![image](https://github.com/zwave-js/zwave-js-ui/assets/123379128/2a34e81a-dd49-4852-b800-48f07cae439d)

![image](https://github.com/zwave-js/zwave-js-ui/assets/123379128/7e50db45-f177-4cb0-aede-e81df37c17a6)

[mh-s411 debug info.txt](https://github.com/zwave-js/zwave-js-ui/files/12226184/mh-s411.debug.info.txt)

**Comment by robertsLando** [comment]
@MickaelColombieSnC Did you tried to re-interview your device?

**Comment by MickaelC26** [comment]
Many times, I even tried to exclude/include with three differents controllers, always getting the same issue

**Comment by AlCalzone** [comment]
Seems like the device is reporting from endpoints 1 and 2 after you control endpoint 0. The info above seems to indicate that the device only has one binary switch on endpoint 0 though.

Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs) of a re-interview, loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by MickaelC26** [comment]
[z-ui_2023-08-01.log](https://github.com/zwave-js/node-zwave-js/files/12228767/z-ui_2023-08-01.log)

Hi, here are the log, I made the reinterview, and then triggered the endpoint 0 that made the 1 and 2 appear.

**Comment by AlCalzone** [comment]
That's the wrong log. Check the link I sent you again :)

**Comment by MickaelC26** [comment]
[zwave-js-ui-store.zip](https://github.com/zwave-js/node-zwave-js/files/12229476/zwave-js-ui-store.zip)
Sorry :)

**Comment by AlCalzone** [comment]
And now the latest driver log contains no interview and is not on loglevel "debug"

**Comment by MickaelC26** [comment]
[zwave-js-ui-store (1).zip](https://github.com/zwave-js/node-zwave-js/files/12230049/zwave-js-ui-store.1.zip)
I confused zwave js ui log and driver log sorry again, this one might be good ;)

**Comment by AlCalzone** [comment]
Ok it looks like the device really wants to report from endpoint 1 - although I'm not sure why they even bothered to make it have an additional endpoint. Maybe that makes the firmware more similar to the variants with more than 1 button.

We'll have to try some things to get this working properly.
Please add
```
"preserveEndpoints": [1]
```
under the `"compat"` field, then restart Z-UI so it picks up the new file, and re-interview the device again. Ideally make a log of this too in case we have to do more tests.

You should now have values on endpoint 1 to control the device instead of endpoint 0 like previously. If everything works as expected, this should also reflect the correct state.

**Comment by MickaelC26** [comment]
Hello I've tried what you said, but it doesn't solve the issue (log attached). And endpoint 1 doesn't control 0. Maybe I wrongly added the "preserveEndpoints": [1] outside the "compat" field, did you mean like this ?


```
					"label": "Normal Operation",
					"value": 0
				},
				{
					"label": "Reset",
					"value": 85
				}
			]
		}
	],
	"compat": {
                "commandClasses" : {
                        "remove" : {
                                "0x2c": {
                                        "endpoints": "*"
                                },
                                "0x80": {
                                        "endpoints": "*"
                                }
                        }
                }
        },
	"preserveEndpoints": [1]
}
``` 




[mh-s411-7102.zip](https://github.com/zwave-js/node-zwave-js/files/12241105/mh-s411-7102.zip)
[zwave-js-ui-store (2).zip](https://github.com/zwave-js/node-zwave-js/files/12241112/zwave-js-ui-store.2.zip)

**Comment by AlCalzone** [comment]
Eh, I wasn't clear. `preserveEndpoints` is another `compat` flag, so it needs to go inside the `"compat"` object. LIke this:
```jsonc
	"compat": {
                "commandClasses" : {
                        "remove" : {
                                "0x2c": {
                                        "endpoints": "*"
                                },
                                "0x80": {
                                        "endpoints": "*"
                                }
                        }
                },
                "preserveEndpoints": [1]
        },
```

**Comment by MickaelC26** [comment]
[zwavejs_2023-08-02.log](https://github.com/zwave-js/node-zwave-js/files/12241554/zwavejs_2023-08-02.log)

Well, it works now ! Thank you :)

**Comment by AlCalzone** [comment]
Not much in that log, but I trust that it works. Would you be willing to provide a pull request with that config file? We don't seem to have one with that ID yet.
