### ISSUE TITLE
Nortek/GoControl PD300EMZ5-1 parameters 7 & 8 stuck similar to zwave-js/node-zwave-js#5271.

### ISSUE THREAD

**Issue by windsurferwill** [AlCalzone/node-zwave-js#6118]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

What do you observe? Change parameters 7 or 8 in the zwave device config menu.  They change but when exiting the UI and coming back in they didn't stick.
kpine had me submit diagnostic logs which show the parameter size sent vs expected don't match
See https://github.com/zwave-js/node-zwave-js/issues/5271.
Using Developer Tools to set the state works.

What did you expect to happen?

  2. Click on '...'
  3. Scroll down to '...'

### Device information

Manufacturer: nortek / goControl
Model name: PD300EMZ5-1
Node ID in your network: 12

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:Driver Version:
11.6.0
Server Version:
1.30.0
`node-zwave-js` branch:
`zwave-js-ui` branch:

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwave_js (1).log](https://github.com/zwave-js/node-zwave-js/files/12245973/zwave_js.1.log)

**Comment by AlCalzone** [comment]
Looks like I made a change in the wrong parameter in that PR (7 instead of 8). #6124 should fix it.
