### ISSUE TITLE
Missing device configuration: SHELLY WAVE 1PM

### ISSUE THREAD

**Issue by chma73** [AlCalzone/node-zwave-js#6147]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

SHELLY WAVE 1PM

### Manufacturer ID

0x0460

### Product Type

0x0002

### Product ID

0x0084

### Firmware Version

10.13.0

### Do you have a manual?

[Wave_1PM_multilang_2023_v06.pdf](https://github.com/zwave-js/node-zwave-js/files/12322496/Wave_1PM_multilang_2023_v06.pdf)

**Comment by 33Fraise33** [comment]
I found the following files on other places:
https://opensmarthouse.org/zwavedatabase/1577 => #6147
https://opensmarthouse.org/zwavedatabase/1578 => #6214
https://products.z-wavealliance.org/products/4922?selectedFrequencyId=-1 => No issue created yet

These are the 3 new devices that Shelly has brought out. I am unsure how to get started on this but I just wanted to let you know.

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4922 from zwa

**Comment by 33Fraise33** [comment]
Today I onboarded the shelly devices. All the values seem to be there except for Manufactur and Product. 
![image](https://github.com/zwave-js/node-zwave-js/assets/6802744/371d3e20-f1df-4fd0-9d0c-a30331a62dd6)
![image](https://github.com/zwave-js/node-zwave-js/assets/6802744/71dbae0e-5474-4dc2-b078-e2b81e6426b7)

**Comment by 33Fraise33** [comment]
Shelly also already has documentation on HA and Zwave JS: https://support.shelly.cloud/en/support/solutions/folders/103000553456

**Comment by AlCalzone** [comment]
These appear to be the auto-discovered config parameters. Someone from Shelly/Qubino is working on a cleaned up config file here: https://github.com/zwave-js/node-zwave-js/pull/6289
