### ISSUE TITLE
Missing device configuration: Zooz Zen77 800LR

### ISSUE THREAD

**Issue by NightTrain** [AlCalzone/node-zwave-js#6151]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Zooz Zen77 800LR

### Manufacturer ID

0x027a

### Product Type

0x7000

### Product ID

0xa007

### Firmware Version

4.10

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4904?selectedFrequencyId=-1

### Do you have a manual?

https://cdn.shopify.com/s/files/1/0218/7704/files/zooz-800-series-z-wave-plus-s2-dimmer-zen77-800lr-manual.pdf

**Comment by AlCalzone** [comment]
fixed by https://github.com/zwave-js/node-zwave-js/pull/6218
