### ISSUE TITLE
switching to 16-bit node IDs is currently done twice during startup

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6158]
... once before and once after soft-reset.

**Comment by Hedda** [comment]
@jtbraun did your PR https://github.com/zwave-js/node-zwave-js/pull/6401 include a fix for this too?

**Comment by jtbraun** [comment]
Not that I wrote or know of, but @AlCalzone rearranged some things to do long-range controller capability detection better, which may have changed this behavior. You can ask them, or just check the beta.

I haven't read the specs, but I normally would assume a soft-reset would/should reset the node-id size, and that you'd expect there to be a switch back to 16-bit nodes after the reset operation. Is that not the case?

**Comment by AlCalzone** [comment]
All the issues linked from the PR should be fixed. But as the PR hasn't landed on the master branch yet, Github hasn't closed them.

And yes, I've reordered the initialization sequence to make a bit more sense.

**Comment by AlCalzone** [comment]
This is merged since v12.5.0
