### ISSUE TITLE
CT100 Thermostat Showing as two climate entities, and no fan

### ISSUE THREAD

**Issue by txwindsurfer** [AlCalzone/node-zwave-js#6184]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug? See https://github.com/zwave-js/node-zwave-js/issues/6017.  The CT100 has the same issue that was just fixed on the CT101.  I have 3 CT101 thermostats and all are now fixed however my 1 CT100 still exhibits the same behavior as the CT101s did before the recent update.

What do you observe?  Same outcome as was reported in https://github.com/zwave-js/node-zwave-js/issues/6017

What did you expect to happen?  Only 1 thermostat and a fax

Steps to reproduce the behavior:  Re-interview node
  2. Click on '...'
  3. Scroll down to '...'

### Device information

Manufacturer:  Radio Thermostat of America
Model name:  CT100
Node ID in your network: 9 

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 2023-08-02
`node-zwave-js` branch: stable
`zwave-js-ui` branch: stable

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwave_js (1).log](https://github.com/zwave-js/node-zwave-js/files/12372769/zwave_js.1.log)

**Comment by txwindsurfer** [comment]
Opps, new log file uploaded

**Comment by minchinweb** [comment]
Came across this problem, even though I'd updated ZWave-JS (plus, it was showing a Radon sensor??). Solution was to **Re-interview the node**, and then delete the "extra" entries in Home Assistant.

(Hopefully this helps someone else...)

**Comment by AlCalzone** [comment]
> plus, it was showing a Radon sensor??

https://zwave-js.github.io/node-zwave-js/#/troubleshooting/nonsensical-values
