### ISSUE TITLE
Rename "HEAL" to better match what it does

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6203]
...and update wording on UI to manage expectations.

Users regularly run network heals which best case does nothing, worst case messes up working routes. We should avoid that.

- [ ] Bandaid icon in Z-UI
- [ ] "better connections" -> "new routes"
- [ ] explain downsides and alternatives

**Comment by balloob** [comment]
It sounds like a good name would be rebuild?

**Comment by AlCalzone** [comment]
I like "rebuild routes"

**Comment by balloob** [comment]
Or Rebuild Network

**Comment by balloob** [comment]
Or Rebuild Network
