### ISSUE TITLE
Missing device configuration: Shelly Qubino wave 1PM

### ISSUE THREAD

**Issue by nberlee** [AlCalzone/node-zwave-js#6213]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Shelly Qubino Wave 1PM

### Manufacturer ID

0x0460

### Product Type

0x0002

### Product ID

0x0084

### Firmware Version

FW: v10.13.0 SDK: v7.19.1

### Do you have a manual?

https://kb.shelly.cloud/knowledge-base/wave-1pm

**Comment by AlCalzone** [comment]
Why close?

**Comment by nberlee** [comment]
Duplicate of https://github.com/zwave-js/node-zwave-js/issues/6147, which i failed to notice before creating it

**Comment by AlCalzone** [comment]
oh, yeah
