### ISSUE TITLE
FGK101 inclusion issue with UI 8.23.1

### ISSUE THREAD

**Issue by ScratMan** [AlCalzone/node-zwave-js#6217]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
I'm using a FIBARO FGK101 with a DSB18B20 sensor to monitor my pool's temperature. I recently updated Zwave JS UI to 8.23.1 and after that the battery of the FGK101 died, and after replacing the external temperature sensor value went down to -1800°C 👀.
I tried several time to wake up the device, I managed to get a correct temperature readout, but it was not automatically updating after that. So I decided to exclude the device and included it again, but the temperature sensor never came back.

What did you expect to happen?
The device should be included with the external temperature sensor added.

What do you observe?
I had to go back to 8.22 to be able to include the device and get the temperature sensor back.

  1. Exclude the FGK101
  2. Update Zwave JS UI to 8.23.1
  3. Include the FGK101
  4. See the external temperature sensor is missing
  5. Exclude the FGK101
  6. Downgrade Zwave JS UI to 8.22
  7. Include the FGK101
  8. See the external temperature sensor is here

### Device information

Manufacturer: 
Model name: 
Node ID in your network: 

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 11.13.0
`zwave-js-ui` branch: 8.23.1

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Works fine with Zwave JS UI 8.22

### Attach Driver Logfile

[zwavejs_2023-08-27.log.txt](https://github.com/zwave-js/node-zwave-js/files/12448833/zwavejs_2023-08-27.log.txt)

**Comment by AlCalzone** [comment]
> included it again, but the temperature sensor never came back.

I think this is the same bug as https://github.com/zwave-js/node-zwave-js/issues/6215
