### ISSUE TITLE
Missing device configuration: Hoppe eHandle ConnectSense

### ISSUE THREAD

**Issue by memphi2** [AlCalzone/node-zwave-js#6264]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Hoppe eHandle ConnectSense

### Manufacturer ID

0x0313

### Product Type

0x0701

### Product ID

0x0002

### Firmware Version

1.1.0

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4504

### Do you have a manual?

[2022-04-HOPPE-MA-eFenstergriff-ConnectSense-DE-EN-FR(1).pdf](https://github.com/zwave-js/node-zwave-js/files/12563409/2022-04-HOPPE-MA-eFenstergriff-ConnectSense-DE-EN-FR.1.pdf)

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4504 from zwa
