### ISSUE TITLE
Ignore when node reports Security S2 has version 0

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6305]
... especially when that report is S2 encapsulated.
```
2023-09-22T08:51:00.246Z CNTRLR » [Node 060]   querying the CC version for Security 2...
2023-09-22T08:51:00.255Z DRIVER » [Node 060] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ callback id:      215
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 111
                                    │ security class:  S2_Unauthenticated
                                    └─[VersionCCCommandClassGet]
                                        CC: Security 2
...
2023-09-22T08:51:00.308Z DRIVER « [Node 060] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -87 dBm
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 23
                                    │ security class:  S2_Unauthenticated
                                    └─[VersionCCCommandClassReport]
                                        CC:      Security 2
                                        version: 0
2023-09-22T08:51:00.309Z CNTRLR   [Node 060]   does NOT support CC Security 2 (0x9f)
```

Originally reported in https://github.com/home-assistant/core/issues/100705

**Comment by martyn-vesternet** [comment]
@AlCalzone I'm just picking up some testing on the latest versions of Vesternets' Sunricher based Z-Wave devices and see that you've already highlighted this issue based on one of Vesternets' customers reporting the problem on the HA github issues list.

I don't believe that anything has changed in the devices themselves (certainly my latest test devices report the same firmware revision as those that I originally submitted configuration .js files for).

So if I assume this bug has always been present in the device, is there some recent(ish) changes in Z-Wave JS that now bring that to the surface and prevent the device from working?

I could go back and retest with my older devices and older builds of Z-Wave JS to see if / when the problem started, but figured you might know off hand?

Is there anything that I can do in our configuration .js files to workaround this for the time being?


Thanks for your help!

**Comment by AlCalzone** [comment]
> So if I assume this bug has always been present in the device, is there some recent(ish) changes in Z-Wave JS that now bring that to the surface and prevent the device from working?

I assume that this bug has been present before, but was never noticed, because Z-Wave JS would skip version queries for CCs it only supports in version 1 - including Security S2.
I'm certain this is caused by [this change](https://github.com/zwave-js/node-zwave-js/pull/5746) in `v10.18.0` which I did because the certification testing tool explicitly tests that the version for all CCs is queried.


A device-specific workaround would be a compat flag akin to this:
https://github.com/zwave-js/node-zwave-js/blob/6e2a9a1881d5dd9ea93d034b7d467e2b03c72f89/packages/config/config/devices/0x0005/pe653.json#L488-L495

Unless you distribute the custom config files yourself, both the workaround and the fix would require a release, so I'd just fix it properly.

**Comment by martyn-vesternet** [comment]
Thanks @AlCalzone that's great, I'll retest in the next few days.
