### ISSUE TITLE
Missing device configuration: Alloy Contact Sensor 2

### ISSUE THREAD

**Issue by swampjedi** [AlCalzone/node-zwave-js#6323]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Alloy Contact Sensor 2

### Manufacturer ID

0x0131

### Product Type

0x0004

### Product ID

0x1118

### Firmware Version

2.19.0

### Is the device listed on the Z-Wave Alliance website?

No

### Do you have a manual?

[File.PDF](https://github.com/zwave-js/node-zwave-js/files/12720779/File.PDF)

**Comment by apella12** [comment]
Same question here re: IDs

**Comment by swampjedi** [comment]
> Same question here re: IDs

Fixed via edit, apologies for being imprecise.

**Comment by apella12** [comment]
this should be closed with #6331 merge
