### ISSUE TITLE
Missing device configuration: McoHome Technology Co., Ltd. MH8-FC4

### ISSUE THREAD

**Issue by tbiel5** [AlCalzone/node-zwave-js#6346]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

McoHome Technology Co., Ltd. MH8-FC4 Fan Coil Thermostat

### Manufacturer ID

0x015f

### Product Type

0x0802

### Product ID

0x5101

### Firmware Version

3.2

### Is the device listed on the Z-Wave Alliance website?

No

### Do you have a manual?

[MCO Home MH8-FC4 Fan Coil Thermostat.pdf](https://github.com/zwave-js/node-zwave-js/files/12771273/MCO.Home.MH8-FC4.Fan.Coil.Thermostat.pdf)

**Comment by apella12** [comment]
This should be closed with merged #6358

**Comment by AlCalzone** [comment]
Oh I didn't see this wasn't linked. If you write `fixes: #<pr-number>` or `closes: #<pr-number>` in your PR description, that's done automatically.

**Comment by tbiel5** [comment]
Thanks for your work on this @apella12 and @AlCalzone!
