### ISSUE TITLE
encourage specific nodes to be neighbors

### ISSUE THREAD

**Issue by josh-m-sharpe** [AlCalzone/node-zwave-js#6365]
**Is your feature request related to a problem? Please describe.**
Standard heal/re-route produces a network map that physically makes zero sense.  Nodes that are far apart with many physical obstacles in between them are neighbors when there are more obvious pathways that make sense.

**Describe the solution you'd like**
I'd think that some way to say "hey NodeA you're like right next to NodeB you should probably be friends (er, uh, 'neighbors')" could possibly improve network performance.

**Describe alternatives you've considered**
Network-wide healing and hoping for the best.  Unsuccessfully.

**Additional context**

I've attempted (poorly) to highlight two routes in the screenshot below.

1) My controller is in the basement
2) Office Light is an in-wall switch on the 1st floor
3) The two "master bathroom" are in the same electrical box on the 2nd floor.

The two routes:
1) Controller -> Office Light -> Master Bathroom Overhead Light
2) Controller -> Master bathroom -> Vanity Light

The 2nd route here makes zero sense to me.  It's physically very distant.  Anecdotally, I ran an OTA update for the distant switch and it took a loooong time.  15-20 minutes maybe.  

The node with the "better" route didn't seem to take nearly as long.  

![Z-Wave_JS_UI](https://github.com/zwave-js/node-zwave-js/assets/39473/98e15b05-7cb4-40c0-8d38-1cf6264dd1f0)

**Comment by kpine** [comment]
Are you aware the the network map no longer has anything to do with node neighbors? For quite awhile now, the map reflects the actual routes your devices are using to communicate. If you click on a particular node you will get the last working route (and next-last working route if it exists) information. Details are at https://zwave-js.github.io/zwave-js-ui/#/usage/nodes_healthcheck.

> Starting from 8.17.0 version Network Graph shows nodes connection based on known routes instead of using neighbors informations as before.

Additionally, you can configure specific routes for specific nodes. Is that what you are asking for?

**Comment by AlCalzone** [comment]
You're asking for a feature that already exists. Click the node and assign a priority route and priority return route in the panel that appears.
