### ISSUE TITLE
ZST39 is probably corrupting the ACK after a soft reset

### ISSUE THREAD

**Issue by jtbraun** [AlCalzone/node-zwave-js#6399]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
The issue of a soft reset to a ZST39 during the startup phase.

What do you observe?
Soft reset is issued, and an 0x86 byte is immediately received and discarded. Then the SerialAPIStarted message comes in, and later the driver complains that an ACK was never received.

What did you expect to happen?
ACK would be received.

  1. Get a Zooz ZST39 800-series stick
  2. Update to latest (7.19 I think?)
  3. Run the `test/run.ts` aka "Debug locally" test in vscode
  4. See screenshotted below.

![image](https://github.com/zwave-js/node-zwave-js/assets/1192545/14bf6b6d-3032-40cc-9e3b-bbaf1976ee83)

Modifying `packages/serial/src/parsers/SerialAPIParser.ts` to also accept 0x86 as "ACK" gets past the error.

NOTE: I've reported the issue to Zooz, if I hear back from them I'll let you know. In the meantime, there probably needs to be a quirk flag or something that is set in the serialAPIParser specifically when softreset is waiting on an ACK, that treats a discarded byte as the missing ACK. :-/

### Device information

Manufacturer: ZOOZ
Model name: ZST39
Node ID in your network: 1

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [X] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: master (9818c58c9cb0e4451a8856b8d69330c4a03fbd03)
`node-zwave-js` branch: master
`zwave-js-ui` branch: n/a

### Did you change anything?

yes (please describe)

### If yes, what did you change?

I changed the COM port to COM3 instead of COM5 in run.ts

### Did this work before?

Don't know, this is a new device

### If yes, where did it work?

n/a

### Attach Driver Logfile

[zwave.log](https://github.com/zwave-js/node-zwave-js/files/12909655/zwave.log)

**Comment by AlCalzone** [comment]
Hmm, I've seen something similar with the "official" USB controllers too: https://community.silabs.com/s/question/0D58Y00009pca5bSAA/bug-in-firmware-7191-softreset-is-no-longer-answered-with-ack?language=en_US

The 7.19 firmware is just broken :(

**Comment by jtbraun** [comment]
Oh how annoying. Is the firmware something that silicon labs mostly writes and distributes to stick vendors, they customize it (with LEDs, buttons, etc), and ship it?

**Comment by AlCalzone** [comment]
Correct. I have a semi-direct contact to Silabs and made them aware of it again. Hopefully this gains some traction now.

**Comment by AlCalzone** [comment]
Fix is up here: https://github.com/zwave-js/node-zwave-js/pull/6409
I have seen different values (`c6`, `e6`) on other controllers, so my strategy for now is to ignore the high nibble of the ACK byte completely, but only once.
