### ISSUE TITLE
unkown manufacturer

### ISSUE THREAD

**Issue by zeev-mindali** [AlCalzone/node-zwave-js#6418]
Dear all,

node 18 and node 13 reporting that it not recognise the manufacturer
<img width="1260" alt="Screenshot 2023-10-18 at 7 25 19" src="https://github.com/zwave-js/zwave-js-ui/assets/23069323/01762e20-bb5f-4c83-93e2-99582fbf2422">

but in pc controller, i get the manufacturer : 0x015f

here are the logs files:
[z-ui_2023-10-18.log](https://github.com/zwave-js/zwave-js-ui/files/12981694/z-ui_2023-10-18.log)

is it a bug from zwave-js or as usual the McoHome product

**Comment by robertsLando** [comment]
@zeev-mindali Tried to do a re-interview? Also please attach the correct logs, those are application logs, we need driver logs to debug that problem.

Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by zeev-mindali** [comment]
made re-interview with no success,
deleted old log and make reboot to the device to get a clean log.
[zwavejs_2023-10-18.log](https://github.com/zwave-js/node-zwave-js/files/12998708/zwavejs_2023-10-18.log)

**Comment by AlCalzone** [comment]
I don't see an interview attempt in that log. Is this a battery-powered device? If so it needs to be woken up manually, usually by pressing a button on the device.

**Comment by zeev-mindali** [comment]
it's a glass switch 1 gang
i attching latest driver log again.

[zwavejs_2023-10-18.log](https://github.com/zwave-js/node-zwave-js/files/12999488/zwavejs_2023-10-18.log)

it's node 023

**Comment by AlCalzone** [comment]
I see an interview for node 24, but we don't have a config file for that one either - so no labels.

**Comment by zeev-mindali** [comment]
i can make the config file, but it's doesn't give me manufactorer, product id, product type
if i had those numbers, i could write one

**Comment by AlCalzone** [comment]
Your log did include them, so they should also be available via the UI

**Comment by zeev-mindali** [comment]
if it was simple :(

the ui don't give me any information for building the config file
<img width="1643" alt="Screenshot 2023-10-18 at 14 42 00" src="https://github.com/zwave-js/node-zwave-js/assets/23069323/035d44bd-7192-4220-8242-a409df15a976">

maybe i can get the manufactorer id, product id and product type somehow from the log?

**Comment by zeev-mindali** [comment]
<img width="1462" alt="Screenshot 2023-10-18 at 14 43 42" src="https://github.com/zwave-js/node-zwave-js/assets/23069323/5ab980bd-6760-41b1-b0cc-0e941a70fba4">

**Comment by AlCalzone** [comment]
Ok I take that back. I still haven't seen a log of node 23 being re-interviewed. Only node 24, but we don't have a config file for that.

**Comment by zeev-mindali** [comment]
here is the updated log:
[zwavejs_2023-10-18.log](https://github.com/zwave-js/node-zwave-js/files/13024727/zwavejs_2023-10-18.log)

as i said, i can build the config file as i built for other items.
basiclly it's mco-home 1 gang glass button

**Comment by AlCalzone** [comment]
Ok Node 23 is not responding at all to any queries. I think you may have to exclude it, factory reset it and include it again.

**Comment by apella12** [comment]
There is this in your log file.
```
2023-10-18T07:48:00.555Z DRIVER « [Node 024] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -57 dBm
                                  └─[ManufacturerSpecificCCReport]
                                      manufacturer id: 0x015f
                                      product type:    0x2221
                                      product id:      0x5106
```

**Comment by zeev-mindali** [comment]
@apella12  , node 24 working fine, node 23 is the problematic.
i will try to exclude it, and factory reset it.

**Comment by zeev-mindali** [comment]
Factory reset solved the issue :)

you are the best

**Comment by AlCalzone** [comment]
We don't have a config file for node 24 though. I'd appreciate it if you could at least share the manual for it. Or write a config file if you have the time.
