### ISSUE TITLE
Fibaro universal binary sensor (FGBS001) spawning non-existent sensors

### ISSUE THREAD

**Issue by TomMalfrere** [AlCalzone/node-zwave-js#6461]
I have 2 FGBS001 sensors.
I use them to read temperature values of DS18B20 temperature sensors.
The DS18B20 sensors are detected correctly and the temperature values I get are OK.

But, from time to time new sensor are detected on these FGBS001 sensors.
some examples (straight out of the GUI of Z-wave JS UI) under Multi-level-sensor 0:
[25-49-3-Air temperature] Air temperature
11.31 °C
**[25-49-3-Illuminance] Illuminance
15.93 %**
**[25-49-3-UNKNOWN (0x00)] UNKNOWN (0x00)
17.31**
**[25-49-3-Carbon dioxide (CO₂) level] Carbon dioxide (CO₂) level
54.02 ppm**
[25-49-4-Air temperature] Air temperature
11.25 °C
**[25-49-4-UNKNOWN (0x00)] UNKNOWN (0x00)
674.86**
[25-49-5-Air temperature] Air temperature
10.68 °C
**[25-49-5-UNKNOWN (0x00)] UNKNOWN (0x00)
14**
**[25-49-5-Time] Time
12.04 s** 

The "Air temperature" items are correct, the other are not!
I noticed they have the same ID as the "Air temperature" sensors.

Why are these suddenly seen as a different type of sensor?

REMARK: I measure water temperatures with these probes. So for me "Air temperature" should be "water temperature"

**Comment by AlCalzone** [comment]
https://zwave-js.github.io/node-zwave-js/#/troubleshooting/nonsensical-values explains this.
