### ISSUE TITLE
Missing device configuration: NewOne N4014

### ISSUE THREAD

**Issue by SirGoodenough** [AlCalzone/node-zwave-js#6475]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

NewOne

### Manufacturer ID

786

### Product Type

44033

### Product ID

16387

### Firmware Version

1.0

### Is the device listed on the Z-Wave Alliance website?

no

### Do you have a manual?

JSON files that I downloaded from the device:
https://gist.github.com/SirGoodenough/e0ac881e3c3262732629b2266dad21ec

Pictures of the manual:
https://github.com/SirGoodenough/stuffThatDontGoElsewhere

Amazon Link:  (Zwave Plug With Energy Monitor)
https://www.amazon.com/dp/B0BRSMZ2JH

Model listed is N4013 and that one is not in your database.

The device shows up, some stuff works.  However there does not seem to be any energy reported from the device at all.  Amazon said it's energy monitoring, unless that just means it shuts down if current too high, don't know.

If I push power button on the device, Home Assistant does not change status.

Ha can turn it on and off and the config that is in zwave-js is also in Home Assistant.

**Comment by apella12** [comment]
The model number is different than the one in the DB, but the MFG and TYPE:ID are the same (Once converted to hex) as this device.
[n4003.json](https://github.com/zwave-js/node-zwave-js/files/13220869/n4003.json) and appears fully discovered (to my eye).

The only meter related parameter seems to be a reset. Although parameters 5-8 define the reporting configurations for power, energy and amps.
