### ISSUE TITLE
Missing device configuration: FAKRO ZWG1

### ISSUE THREAD

**Issue by janneman001** [AlCalzone/node-zwave-js#6544]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

FAKRO ZWG1

### Manufacturer ID

0x0085

### Product Type

not found in logs

### Product ID

not found

### Firmware Version

not found

### Is the device listed on the Z-Wave Alliance website?

no

### Do you have a manual?

[zwg1 (1).pdf](https://github.com/zwave-js/node-zwave-js/files/13589257/zwg1.1.pdf)
![zwg1picture](https://github.com/zwave-js/node-zwave-js/assets/7555596/8eca3407-ea90-4085-83de-c811b41297f8)

De device is a stylish zwave cover controller it can act as a primary or secondary controller.
I tried to add it with zwavejsui the interview completed however nothing functional came from it.

I have used the device with a fakro roller shutter. However i want to integrate it in home assistant. 

It have tried to do so in a test setup with only zwavejsui a gen5 aeotec stick but no dice.
![Schermafdruk van 2023-12-06 18-00-51](https://github.com/zwave-js/node-zwave-js/assets/7555596/170aba54-8389-4824-9994-d0f877176bb7)

if more tests should be done or info is neccesary please let me know.

regards
Jan
[interview.log](https://github.com/zwave-js/node-zwave-js/files/13589344/interview.log)

**Comment by apella12** [comment]
This really is not enough to go on.  To me the interview is a not complete.  Did you try waking the device a few times?
