### ISSUE TITLE
Support ZIP files for firmware updates

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6567]
This will have to be limited to ZIP files containing a single firmware update file.

**Comment by sdrsdr** [comment]
As a whole the process of firmware update is not documented. At least I could not find any clue. My **feeling** is that I (as a zwave-js library user)  need to extend the `Firmware Update Meta Data CC` to somehow provide `sendFirmwareFragment` and then trigger the process via `requestUpdate` OR is there a magic registry that will allow simple `requestUpdate` and then the library will find all it need and do the dance ending with `activateFirmware`.  If there is a registry with known udpates-to-specific-device simply unpacking and publishing from the zip to it will be enough

**Comment by AlCalzone** [comment]
As a library user you shouldn't deal with the CCs directly for this.
--> https://zwave-js.github.io/node-zwave-js/#/api/controller?id=updating-the-firmware-of-a-node-ota

**Comment by sdrsdr** [comment]
Thank you very much for the link. I see now how ota is supposed to work. Having some pointers in the source code and in the  'Advanced usage' or 'FAQ'  section of the documentation wold be very usefull.
