### ISSUE TITLE
Missing device configuration: Zooz ZEN37

### ISSUE THREAD

**Issue by W90W2A** [AlCalzone/node-zwave-js#6571]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

Zooz ZEN37

### Manufacturer ID

0x027a

### Product Type

0x7000

### Product ID

0xf003

### Firmware Version

1.0.0

### Is the device listed on the Z-Wave Alliance website?

No

### Do you have a manual?

https://cdn.shopify.com/s/files/1/0218/7704/files/zooz-800-series-z-wave-long-range-wall-remote-zen37-800lr-manual.pdf

**Comment by zackbcom** [comment]
I'll submit this config I have this device now.
