### ISSUE TITLE
Update project description to include 800-series devices

### ISSUE THREAD

**Issue by TheKorn2** [AlCalzone/node-zwave-js#6645]
On project main landing page https://github.com/zwave-js , description currently reads:

"Built on Node.js and compatible with all known 500 and 700 series Z-Wave controller hardware adapters, the Z-Wave JS driver runs on almost anything with a little bit of computing power and a serial port."

Should be updated to read:

Built on Node.js and compatible with all known 500, 700 and 800 series Z-Wave controller hardware adapters, the Z-Wave JS driver runs on almost anything with a little bit of computing power and a serial port.

I know it's trivial, but might as well squash the easy ones!

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by AlCalzone** [comment]
Go for it!

**Comment by TheKorn2** [comment]
@AlCalzone  It was? Still says 700 here.

**Comment by AlCalzone** [comment]
Ohhh, I only updated the Readme of this repo. Not the organization Readme.

**Comment by TheKorn2** [comment]
Looks good this time! :D
