### ISSUE TITLE
Disallow associating a node with itself

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6660]
...and skip preexisting self-associations in health checks

**Comment by 0ff** [comment]
@AlCalzone sorry for digging up this ancient issue!

Would be able to explain why you disallowed self-associations? I do have a use-case that would require them, but zwave-js does not allow me to set it up.

I have a light switch with two inputs (S1, S2) and two outputs (Q1, Q2) - S1 controlling Q1 and S2 controlling Q2 (on-device). I now would love to setup a self-association between the On/Off of S1 and the Output Q2:
<img width="499" height="605" alt="Image" src="https://github.com/user-attachments/assets/52eee1ea-13fa-4b91-ab55-c15c9ba1d42a" />

I can do the exact same thing successfully as long as I set this up with a different Node (i.e. a second switch), just not for the same Node. I wonder if there is a specific reason you disallowed this particular use-case or of this issue (and PR) were more generally "a good idea"?

**Comment by AlCalzone** [comment]
Associations work by telling a device where to send a command to when a certain condition is met.

Sending a command to oneself is not possible in Z-Wave.
Disallowing this in Z-Wave JS is meant to avoid the confusion (_"I've set it up, why doesn't it work?"_)
