### ISSUE TITLE
Heltun HE-ZW-THERM-FL2: Override supported scales

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6680]
### Discussed in https://github.com/zwave-js/node-zwave-js/discussions/6666

<div type='discussions-op-text'>

<sup>Originally posted by **@steve-hodgkiss** February  8, 2024</sup>
### Checklist

- [X] I have read and followed the above instructions
- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there or the fix **did not work**.

### Describe the issue

What is happening?
Heltun thermostat is causing "unsupported scale or corrupted data" errors in log file. Other values in CC report such as power are being updated fine. 

What did you expect to happen instead?
Illuminance values should be updated to correct light level

  1. Go to 'node'
  2. Click on 're-interview'
  3. Scroll down to 'multilevel sensor'
  4. After re-interview after power cycle, illuminance is shown but never updated. Additional re-interview causes illuminance to disappear from sensor. In either case, illuminance value never gets updated.

Log file shows entries for illuminance and multiple recurring log messages
```
DRIVER   dropping CC with invalid values (Reason: Unsupported scale Lux or corrupted da
                                  ta)
```

Anything else we should know?

Only applies to this model of Heltun Thermostat. More recent model HE-HT01 does not suffer from this issue.

### Software versions

Z-Wave JS UI: v9.8..3

Home Assistant Z-Wave JS Addon: Add-on version: 3.3.2

### Device information

Manufacturer: Heltun
Model name: HE-ZW-THERM-FL2
Node ID: 062

### Checklist

- [X] I [made sure](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index?id=rule-1-use-the-driver-log-luke) to provide a **driver log** on level **debug**.

- [X] The log includes a re-interview of the problematic device _(if applicable)_.

- [X] The log includes the problematic interaction with the device _(if applicable)_.

- [X] I provided the node ID of the problematic device _(if applicable)_.

### Upload Logfile

[zwavejs_current.log](https://github.com/zwave-js/node-zwave-js/files/14210361/zwavejs_current.log)
</div>

**Comment by AlCalzone** [comment]
The device reports support for the percentage scale, not Lux:
```
2024-02-08T12:37:24.612Z SERIAL « 0x010c0004003e0431060301cf0037                                      (14 bytes)
2024-02-08T12:37:24.614Z SERIAL » [ACK]                                                                   (0x06)
2024-02-08T12:37:24.616Z CNTRLR   [Node 062] [+] [Multilevel Sensor] supportedScales[3]: [Endpoint 0] [internal]
                                   0
2024-02-08T12:37:24.617Z DRIVER « [Node 062] [REQ] [ApplicationCommand]
                                  └─[MultilevelSensorCCSupportedScaleReport]
                                      sensor type:      Illuminance
                                      supported scales:
                                      · Percentage value
```
I'm assuming this is an off-by-one error in the support bitmask. Here, `0x01` means that scale 0 (percentage) is supported. For scale 1 (Lux), the value should be `0x02`.

We should override this with a compat flag

**Comment by maxime-scher** [comment]
Hello,
To add to the topic, I believe I'm experiencing the same error (same symptoms) with the HELTUN WALL TOUCH PANEL SWITCH HE-ZW-SW-5A-1.
Device ID: `0x0344 0x0003-0x0003`

The brightness value only appears once out of every 30 node interviews and never updates after.

Debug info for this parameter on the node:
```
{
      "id": "37-49-0-Illuminance",
      "nodeId": 37,
      "toUpdate": false,
      "commandClass": 49,
      "commandClassName": "Multilevel Sensor",
      "endpoint": 0,
      "property": "Illuminance",
      "propertyName": "Illuminance",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Illuminance",
      "ccSpecific": {
        "sensorType": 3,
        "scale": 1
      },
      "stateless": false,
      "commandClassVersion": 11,
      "unit": "Lux",
      "list": false,
      "value": 291,
      "lastUpdate": 1709882279374,
      "newValue": 291
    },
```
Thanks a lot for considering this issue.

**Comment by AlCalzone** [comment]
That sounds different. Please open another request for investigation (under discussions) and share all the information requested there.

**Comment by maxime-scher** [comment]
Thanks for your answer. I opened it : [#6692]
