### ISSUE TITLE
Zwave-JS-UI rejects OTA firmware file that Simplicity Studio is happy to program

### ISSUE THREAD

**Issue by TheKorn2** [AlCalzone/node-zwave-js#6690]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

zwave-js-ui: 9.9.0.09b107a

### ZwaveJS version

zwave-js: 12.4.4

### Describe the bug

AEON labs ZW095 Gen5 HEM...  OTZ update file supplied directly from Aeotec is rejected with "Unable to extract firmware from file: No EOF record at end of file" message.

Load OTZ file in Simplicity Studio and it's more than happy to load it and program the end device with it.

### To Reproduce

Select a node (preferably a zw095, but should be trigger-able by just about anything). Go to advanced, firmware update, begin. Select attached OTZ file (which has been zipped for upload to github, but should be unzipped before attempting). 

See unhappy message.
<img width="1017" alt="firmware_woes" src="https://github.com/zwave-js/zwave-js-ui/assets/6579539/bc983792-c092-47fe-9b09-e48d2d090ec7">

### Expected behavior

[ZW095_HEM_G5_2P_200A_US_V1_33.zip](https://github.com/zwave-js/zwave-js-ui/files/14456156/ZW095_HEM_G5_2P_200A_US_V1_33.zip)

OTA update should proceed.

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by apella12** [comment]
On an unrelated note, your screen shot shows FW 1.37 which is the latest (I believe) and your file appears to be for FW1.33.  Are you sure you want to do this? ;-)

**Comment by TheKorn2** [comment]
@apella12 I have more than one. One is limited to 1.33 max, the other can handle 1.37. (I already upgraded both with SS.)

**Comment by duylong** [comment]
I had a similar problem when I did my Aeotec updates. It seems to me that this is a problem with the otz file provided. Depending on the module, some files pass, others do not. I finally went through their EXE to do the update (Zensys.*).

**Comment by robertsLando** [comment]
Zwave-js expects OTZ to be in Intel HEX format

**Comment by TheKorn2** [comment]
@duylong The funny thing is the 1.37 update goes through just fine, but the 1.32 and 1.33 updates get kicked back. I wouldn't expect they'd change formats between those, but I guess anything is possible. (I have all of these if they'd help.)

**Comment by robertsLando** [comment]
The only one that can tell you something about this is @AlCalzone

**Comment by AlCalzone** [comment]
I'll look at the files when I find the time. If you can share both (one working, one not), that's definitely helpful.

**Comment by TheKorn2** [comment]
@AlCalzone And with a waive of the magic wand...  This one updates just fine with zwave-js. (previous one is the one that gets kicked out.)  
[ZW095_HEM_G5_2P_200A_US_V1_37.zip](https://github.com/zwave-js/node-zwave-js/files/14509178/ZW095_HEM_G5_2P_200A_US_V1_37.zip)

**Comment by TheKorn2** [comment]
This one also gets rejected.  
[ZW095_HEM_G5_2P_200A_US_V1_32.zip](https://github.com/zwave-js/node-zwave-js/files/14509183/ZW095_HEM_G5_2P_200A_US_V1_32.zip)

**Comment by kpine** [comment]
v1.32 and v1.33 are technically invalid Intel HEX files:

```console
❯ tail -n3 ZW095_HEM_G5_2P_200A_US_V1_37.otz
:107FF000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF91
:01800000037C
:00000001FF

❯ tail -n3 ZW095_HEM_G5_2P_200A_US_V1_33.otz
:107FE000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA1
:107FF000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF91
:01800000037C

❯ tail -n3 ZW095_HEM_G5_2P_200A_US_V1_32.otz
:107FE000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA1
:107FF000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF91
:01800000037C
```

The node.js HEX parser fails because the End of File (EOF) record `:00000001FF` is missing. https://en.wikipedia.org/wiki/Intel_HEX#Record_types

Maybe PC Controller has a workaround for this and allows the file EOF to indicate the same.

**Comment by AlCalzone** [comment]
Yeah, I don't think it's worth going through the trouble to work around this.

@aeotec-ccheng FYI, this seems like an easy fix on your side - see the comment above mine.

**Comment by Aeotec-ccheng** [comment]
I'll forward it up the teams - thanks @kpine @AlCalzone .
