### ISSUE TITLE
Indicate why adding an association is not allowed or failed

### ISSUE THREAD

**Issue by duylong** [AlCalzone/node-zwave-js#6772]
Hi,

I recently tried to add an association between 2 devices that did not have the same level of security. I got the errors below:

![error1](https://github.com/zwave-js/zwave-js-ui/assets/3019703/e2028d53-6359-493c-af0a-2ee7eeba1fc2)

![error2](https://github.com/zwave-js/zwave-js-ui/assets/3019703/5b253dfe-2352-4035-955a-3f16c13a5ef8)

Once you know the problem it's easy, but if you don't, the message doesn't help.

Is it possible to improve the error message?

**Comment by robertsLando** [comment]
@AlCalzone What are the possible reasons why an association could not be allowed apart of security?

**Comment by AlCalzone** [comment]
I've been thinking of adding an enum with possible reasons, since there are a few actually. Should I move this to my repo as a feature request?

**Comment by robertsLando** [comment]
Yeah I think it makes sense 👍🏼

**Comment by AlCalzone** [comment]
The driver will include the reason for the failure in the thrown error starting with version 13.

**Comment by robertsLando** [comment]
Nice! No changes required on my side so as I already show the error thrown :)

**Comment by AlCalzone** [comment]
do you use `isAssociationAllowed`?

**Comment by robertsLando** [comment]
Yes:

```ts
for (const a of associations) {
					if (
						this._driver.controller.isAssociationAllowed(
							source,
							groupId,
							a,
						)
					) {
						this.logNode(
							zwaveNode,
							'info',
							`Adding Node ${a.nodeId} to Group ${groupId} of ${sourceMsg}`,
						)

						await this._driver.controller.addAssociations(
							source,
							groupId,
							[a],
						)

						return true
					} else {
						this.logNode(
							zwaveNode,
							'warn',
							`Unable to add Node ${a.nodeId} to Group ${groupId} of ${sourceMsg}, association not allowed`,
						)
					}
				}
```

**Comment by AlCalzone** [comment]
Then you'll need to change something, see linked PR. I'll also write migration docs for v13 like usual.
