### ISSUE TITLE
Walli Controller FGWCEU-201 not accepting some config changes

### ISSUE THREAD

**Issue by kilian-f-za** [AlCalzone/node-zwave-js#6776]
Hallo, ich habe seit gestern einen Walli Controller FGWCEU-201, die Einbindung hat funktioniert aber die Configuration v4 funktioniert nicht. 
Die Parameter werden nicht übernommen und es kommt die Fehlermeldung Value update failed. Ich kann kein Parameter einstellen. 
Gibt es dazu einen Lösungsansatz oder kann ich noch was zu diesem Fehler beitragen? Ist ein zusätzliches Log hilfreich?

![Screenshot_20240416-193853.png](https://github.com/zwave-js/zwave-js-ui/assets/87258544/dfeb1454-a317-40f1-a4c3-33a5d49c2171)

![Screenshot_20240416-193951.png](https://github.com/zwave-js/zwave-js-ui/assets/87258544/9135c69e-df52-4fda-ae3f-5fc3d343885b)

zwave-js-ui: 9.10.3
zwave-js: 12.5.4

**Comment by kilian-f-za** [comment]
Hier ist das Log:
2024-04-17 16:24:22.349 INFO Z-WAVE: Calling api writeValue with args: [
  { nodeId: 19, commandClass: 112, endpoint: 0, property: 150 },
  3,
  null,
  [length]: 3
]
2024-04-17 16:24:22.349 INFO Z-WAVE: Writing 3 to 19-112-0-150
2024-04-17 16:24:42.520 INFO Z-WAVE: [Node 019] Is now awake
2024-04-17 16:24:42.561 ERROR Z-WAVE: Unable to write 3 on 112-0-150: Fail
2024-04-17 16:24:42.562 INFO Z-WAVE: Success zwave api call writeValue { status: 2 }
2024-04-17 16:24:43.601 INFO Z-WAVE: [Node 019] Value updated: 112-0-150 1 => 1

Hilfst das weiter?

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by AlCalzone** [comment]
Likely we'll have to disable Supervision for this device. I'll wait for the log to confirm though.

**Comment by kilian-f-za** [comment]
[zwavejs_2024-04-18 (1).log](https://github.com/zwave-js/zwave-js-ui/files/15027553/zwavejs_2024-04-18.1.log)
It's Node 022
I've just retrained him.

**Comment by AlCalzone** [comment]
Ok that confirmed my hunch.

**Comment by kilian-f-za** [comment]
What can I do now or what needs to be changed?

**Comment by robertsLando** [comment]
@kilian-f-za Wait for @AlCalzone to update the device configuration to disable supervision on that device as it doens't support it correctly

**Comment by AlCalzone** [comment]
You can look up how we disabled supervision on other problematic devices and use a custom config file with the same applied.

Otherwise you'll have to wait for me to fix it on Monday, and then new releases of node-zwave-js and zwave-js-ui.

**Comment by AlCalzone** [comment]
@kilian-f-za it looks like for parameter 150 we have an incorrect value size (1 byte instead of 2) in our config file. Parameters 13, 20, 152 and 153 should be correct.
Can you try setting them please? And please make a driver log of that.

**Comment by kilian-f-za** [comment]
Yes, I can set the parameters 13, 20, 152 and 153. However, parameter 13 does not change the brightness on the device. When I press the current button, the switch lights up green.

It's Node 023
[zwavejs_2024-04-22.log](https://github.com/zwave-js/node-zwave-js/files/15062008/zwavejs_2024-04-22.log)

**Comment by AlCalzone** [comment]
Ok those look good, so it's not the Supervision CC, but our incorrect config file. We can't do anything about the config parameters not behaving as they should though.

Side note: You don't have to remove and include the device to make a log, unless I ask you to :)

**Comment by kilian-f-za** [comment]
What can I do now? So I can't set the parameters?

**Comment by AlCalzone** [comment]
I'm fixing our config file, so you can set 150 and 151 as expected.
Setting the others appears to be working according to your log.

But if parameter 13 doesn't change the brightness even if the manual says so, that's nothing we can fix.

**Comment by kilian-f-za** [comment]
Okay, thank you very much. Will there be a new release or how do I get the config file?

**Comment by AlCalzone** [comment]
yep

**Comment by kilian-f-za** [comment]
When is the new release expected to be published?
I currently still have the right to return the Switch. 😄

**Comment by AlCalzone** [comment]
Likely today, then Z-Wave JS UI will have to follow up with a release. And if you're using the Home Assistant addon, that will also need one.

If you can't wait, you can also test the file in advance. See https://zwave-js.github.io/zwave-js-ui/#/device-support/custom-device-files for an explanation how. Save [this](https://raw.githubusercontent.com/zwave-js/node-zwave-js/54cd24019942a89e0a166a524b253356a5a4f046/packages/config/config/devices/0x010f/fgwceu-201.json) as a `.json` file and put it into the folder mentioned in the documentation.

Don't forget to remove the custom file again after updating Z-Wave JS UI, otherwise you won't get any future fixes to that file.
