### ISSUE TITLE
Heatit Z-Temp2 FW 1.2.1: disable Supervision, add warning

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6780]
Followup to https://github.com/zwave-js/node-zwave-js/issues/6563 - apparently that firmware is just broken

**Comment by slappyslap** [comment]
Same problem as https://github.com/zwave-js/node-zwave-js/issues/6563#issuecomment-2069191509

No update is possible

**Comment by ackjewtn** [comment]
@slappyslap (and @duylong) Try now. Seems to be working for me now, with `Z-Wave JS UI 9.12.0` and `Z-Wave JS 12.5.6`

**Comment by duylong** [comment]
Yes, I tested yesterday, everything seems to work. I also solved my problem with updating the values: https://github.com/zwave-js/node-zwave-js/discussions/6657, a little slow in modifying the parameters, but it works afterward several tests.

Thank you for all your efforts, too bad it spoils the zwave experience for those who purchased this module.

**Comment by slappyslap** [comment]
Working for me too
