### ISSUE TITLE
Fibargroup roller shutter 4 FGR-224

### ISSUE THREAD

**Issue by radhoo2k10** [AlCalzone/node-zwave-js#6811]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

Fibargroup

### Manufacturer ID

271

### Product Type

772

### Product ID

4096

### Firmware Version

v8.0.0

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4992?selectedFrequencyId=-1

### Do you have a manual?

  "status": "Alive",
  "interviewStage": "Complete",
  "priorityReturnRoute": {},
  "customReturnRoute": {},
  "customSUCReturnRoutes": [],
  "applicationRoute": false,
  "hexId": "0x010f 0x0304-0x1000",
  "dbLink": "https://devices.zwave-js.io/?jumpTo=0x010f:0x0304:0x1000:8.0.0",
  "manufacturerId": 271,
  "productId": 4096,
  "productType": 772,
  "productLabel": "Unknown product 0x1000",
  "productDescription": "0x0304",
  "manufacturer": "Fibargroup",
  "firmwareVersion": "8.0.0",
  "sdkVersion": "7.18.3",
  "protocolVersion": 3,
  "zwavePlusVersion": 2,
  "zwavePlusNodeType": 0,
  "zwavePlusRoleType": 5,
  "nodeType": 1,
  "endpointsCount": 0,
  "endpoints": [
    {
      "index": 0,
      "label": "Root Endpoint"

https://www.elektroimportoren.no/docs/lib/95019-Brukerveiledning-5.pdf

![image](https://github.com/zwave-js/node-zwave-js/assets/78762281/a10863de-a8c4-4721-bc25-30777a5b2a97)

![image](https://github.com/zwave-js/node-zwave-js/assets/78762281/d204bc47-73d7-4158-a2c0-015a932c0983)

![image](https://github.com/zwave-js/node-zwave-js/assets/78762281/39e919f8-7e7c-4e16-bbea-326c15eaa55b)

[node_115.json](https://github.com/zwave-js/node-zwave-js/files/15224099/node_115.json)

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4992 from zwa

**Comment by radhoo2k10** [comment]
@AlCalzone Thanks for completing this. Got a question. I'm using zwave-js ui with mqtt and home assistant. 
Zwave-js ui just updated with zwave-js 12.9.1. But the controlls in Home assistant is still missing. Is it here I have to create an issue or is it Zwave-js ui? 

![image](https://github.com/zwave-js/node-zwave-js/assets/78762281/3c9c8a95-5851-4ff5-aab7-30e382fe9838)

![image](https://github.com/zwave-js/node-zwave-js/assets/78762281/cb4eb143-9823-42b0-b8c6-412dbca33bdc)

Unlike the other covers that I have, it seems like fibaro 4 is missing the "set" topic.
This is a qubino flush shutter:
![image](https://github.com/zwave-js/node-zwave-js/assets/78762281/21cb29bf-75c5-457a-93e4-7c6013440a38)

**Comment by AlCalzone** [comment]
If you're connecting HA to Z-Wave JS UI via MQTT and not the more tightly coupled Z-Wave integration, I can't really help. 

The new shutter uses the Window Covering CC, which might not have the corresponding discovery support yet.

This might be an issue for Z-Wave JS UI then (which includes the MQTT discovery).
