### ISSUE TITLE
Add soft-reset to recovery routine from jammed controller

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6814]
The latest release mentions this as a workaround.

**Comment by zackbcom** [comment]
source: https://www.silabs.com/documents/public/release-notes/SRN14930-7.21.3.0.pdf

This low occurrence issue can be miti-gated by the host. When the controller is locked replying with the status, TRANSMIT_COMPLETE_FAIL, the host should reset the controller.

**Comment by bjornarfjelldal** [comment]
Hi! Any chance we could see this soon? :) not sure it is as "low occurring" as SI themselves believe.

https://community.silabs.com/0D7Vm0000024mCz

**Comment by webmogul1** [comment]
I have not tried Release v12.10.1 yet, but when I had the jamming problem manually soft resetting the stick did not work. It would get jammed again.

I mean clicking here:
![image](https://github.com/zwave-js/node-zwave-js/assets/5225701/282f2dd3-cbdb-4654-ad54-1f5cc0d6117a)
