### ISSUE TITLE
Everspring - EH403 - Cannot change default configuration

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6829]
### Discussed in https://github.com/zwave-js/node-zwave-js/discussions/6828

<div type='discussions-op-text'>

<sup>Originally posted by **@s8109csa** May  8, 2024</sup>
### Checklist

- [X] I have read and followed the above instructions
- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there or the fix **did not work**.

### Describe the issue

What is happening?
I cannot change default configuration on Everspring EH403. I have 3 of them, same issue on all. There are 3 parameters and for me the important would be the auto report lux value. I wanted to change 0 to 3 and when I clicked somewhere else in the Home Assisstant, there was only an error message: Error happened. Other Z-Wave devices are working as expected.

What did you expect to happen instead?
Update parameters

  1. Go to Devices -> Z-Wave -> Everspring EH403 -> Settings -> Edit parameter 3 -> click out from the cell.
  2. See error

Anything else we should know?
The devices are securely connected to Aeotec USB Z-Stick 7 - again, I can edit other devices. FW is default, I don't think there was ever a firmware update on these flood lights.

### Software versions

Driver (node-zwave-js): ...

Z-Wave JS UI: ...

Home Assistant Z-Wave Integration: ...

Home Assistant Z-Wave JS Addon: ...newest but it was always the case

ioBroker.zwave2 Adapter: ...

If you are using something non-standard, tell us here: ...

### Device information

Manufacturer: EverSpring
Model name: EH-403
Node ID: 11

### Checklist

- [X] I [made sure](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index?id=rule-1-use-the-driver-log-luke) to provide a **driver log** on level **debug**.

- [X] The log includes a re-interview of the problematic device _(if applicable)_.

- [X] The log includes the problematic interaction with the device _(if applicable)_.

- [X] I provided the node ID of the problematic device _(if applicable)_.

### Upload Logfile

[home-assistant_zwave_js_2024-05-08T15-09-55.901Z.log](https://github.com/zwave-js/node-zwave-js/files/15250841/home-assistant_zwave_js_2024-05-08T15-09-55.901Z.log)
</div>

**Comment by AlCalzone** [comment]
Fix: Disable Supervision CC for this device.

**Comment by s8109csa** [comment]
Hi,

I see you created an issue but what is happening now? Shall I wait for a
new revision of the node-zwave-js? Can you explain what is disable
supervision cc for this device?

Thank you
Peter

AlCalzone ***@***.***> ezt írta (időpont: 2024. máj. 8., Sze,
19:58):

**Comment by AlCalzone** [comment]
Yeah that's something I have to do in Z-Wave JS.

**Comment by AlCalzone** [comment]
@zwave-js-bot add compat flag to `0x0060:0x0012:0x0001`
```jsonc
"commandClasses": {
	"remove": {
    	// The device does not support Supervision correctly
        "Supervision": {
			"endpoints": "*"
		},
	}
}
```

**Comment by s8109csa** [comment]
Hi, thank you for your efforts, I just want to inform you that I have just
installed 0.6.0 of Z-Wave JS and tested Everspring EH-403 parameter update,
it is still doesn't work, it just says error. Logs shows nothing at all, no
communication seen in the JS log file.

Can it be that it is S2 connected?

Thanks
Peter

AlCalzone ***@***.***> ezt írta (időpont: 2024. máj. 14., K,
9:12):

**Comment by AlCalzone** [comment]
Did you re-interview the device after updating?

**Comment by s8109csa** [comment]
Great Support, that solved it, didn't know I have to do that.

Thank you
Peter

AlCalzone ***@***.***> ezt írta (időpont: 2024. jún. 18., K,
19:31):
