### ISSUE TITLE
Allow Manual Region Specification for automatic firmware updates on older controllers

### ISSUE THREAD

**Issue by mwaterbu** [AlCalzone/node-zwave-js#6891]
I noticed that I was not being offered an update which should have been available (for a Zooz ZSE43). I believe the issue is that I do not have a region specified by my ZWave stick, so the update cannot match.

In cases like this, could it be possible to manually specify a region (for older sticks)?

Also, just to check that my assumption is correct, where would I see this region, if my stick did allow retrieving it?

As a sidenote, zwave-js/firmware-updates#82 would be useful here, as at first glance, it simply looked like my device was up to date, when in reality, the update check could not be properly executed.

**Comment by AlCalzone** [comment]
The region would have to be provided by the client application, most likely https://github.com/zwave-js/node-zwave-js/ - I'll move the feature request there.

> Also, just to check that my assumption is correct, where would I see this region, if my stick did allow retrieving it?

You should see it either in the logs during startup, or in Z-Wave JS UI for example if you open the dropdown for the controller device.

**Comment by mwaterbu** [comment]
So I see this in the changelog for the Z-Wave JS HA Add-on (v 0.10.0):
> Z-Wave JS: Allow specifying RF region for OTA firmware updates if the region is unknown or cannot be queried

But I don't see a way to set this through the add-on configuration. Is it a hidden setting somewhere?

**Comment by AlCalzone** [comment]
It should be right next to the OTA update controls, but only if your controller does not allow querying the region.

**Comment by mwaterbu** [comment]
I don't see any OTA update controls. To be clear, I am using the Z-Wave JS HA add-on, not Z-Wave JS UI.

The logs list my controller as a legacy controller, which I thought meant it cannot query the region:
```
CNTRLR   querying additional controller information...
CNTRLR   received additional controller information:
         Z-Wave API version:         5 (legacy)
         Z-Wave chip type:           ZW050x
         node type                   Controller
         controller role:            primary
         controller is the SIS:      true
         controller supports timers: false
```

**Comment by AlCalzone** [comment]
HA hasn't added any UI to use this feature yet. It's only in Z-Wave JS UI right now.

**Comment by mwaterbu** [comment]
Got it, thanks for confirming.
