### ISSUE TITLE
Missing device configuration: <Sensative Strips Guard 800 >

### ISSUE THREAD

**Issue by czdanika** [AlCalzone/node-zwave-js#6960]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

Sensative Strips Guard 800

### Manufacturer ID

0x019a

### Product Type

0x0700

### Product ID

0004.0004

### Firmware Version

36.27

### Do you have a manual?

[Sensative Strips Guard 800
](https://manual.zwave.eu/backend/make.php?lang=en&sku=SENEGUARD800&cert=)

**Comment by AlCalzone** [comment]
> ### Manufacturer ID
> 
> 0x019a
> ### Product Type
> 
> 0x0700
> ### Product ID
> 
> 0004.0004

Where did you get those? 0004.0004 is not a format that's exposed in Z-Wave JS UI or Home Assistant.
Please report what's shown in the UI, so we can be sure to have the right ID.

**Comment by czdanika** [comment]
Hello!

Id from Z-Wave Europe manual. 
<img width="1165" alt="Képernyőfotó 2024-06-25 - 10 42 19" src="https://github.com/zwave-js/node-zwave-js/assets/117216860/8357929a-a9af-44ff-a95c-87de9ec19126">

The interesting thing is that I know it responds to ping, this is paired to a Gen5+ stick.

Today I brought it to the work and paired it to a DUSUN HA gateway that has a 700/800 chip. This successfully paired and received the niFs. please find the attached files. 
[node_3_dump.json](https://github.com/user-attachments/files/15967740/node_3_dump.json)
[node_3.json](https://github.com/user-attachments/files/15967741/node_3.json)

In your opinion, what could be the problem, at home 60+ Z-wave devices work flawlessly, there is now a problem with this for some reason.

Daniel

**Comment by AlCalzone** [comment]
According to the dump it is recognized already, so no need to add it.
```
  "manufacturer": "Sensative AB",
  "label": "11-01-022",
  "description": "Strips Guard 700",
  "fingerprint": {
    "manufacturerId": "0x019a",
    "productType": "0x0004",
    "productId": "0x0004",
    "firmwareVersion": "56.41.0",
    "hardwareVersion": 3
  },
  "interviewStage": "Complete",
  "ready": true,
```

To understand why it doesn't work with the other stick, please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs) on loglevel `debug`. While making the log, please try including it again. Afterwards attach the log here as a file (drag & drop into the text field).

**Comment by czdanika** [comment]
Hello!

After today's  JS updates, i tried to include it, now it recognized the device. But I made the log, please find attached. 
[zwave-js-ui-store.zip](https://github.com/user-attachments/files/15973905/zwave-js-ui-store.zip)

**Comment by AlCalzone** [comment]
Sounds like another case of the bug fixed in https://github.com/zwave-js/node-zwave-js/releases/tag/v12.11.2
