### ISSUE TITLE
Route rebuilding of battery powered nodes cause issues

### ISSUE THREAD

**Issue by jfhautenauven** [AlCalzone/node-zwave-js#7077]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.16.4

### ZwaveJS version

13.0.3

### Describe the bug

Upon asking a battery powered node to rebuild its routes (here, a fibaro eye motion sensor), the command seems to be queued correctly and will for sure be executed upon the next wake up of the battery powered device.
Rebuild route is asked via the "network" page of ZWJSUI. 

Problem : while we are waiting for the battery powered node to wake up, the next commands we will send for rebuilding routes of other nodes will fail and display an error message saying rebuilding routes failed for that other node (battery powered of not).

### To Reproduce

Go to the network page.
Click on a battery powered node.
That will open the node properties widget.
Down on the widget, click "Rebuild routes".

Wait a few seconds.

Go back on the main network page view (with all the nodes).
Click another node, doesn't matter if battery powered or not.
On the widget of that node, click "Rebuild routes".

You get the error message.

After that, no matter where from you try to ask for a route rebuild (main page, node page, etc.), you'll always get a rebuild route error until either the battery powered node you asked the rebuild for has done it, either until you fully restart ZWJSUI.

### Expected behavior

The rebuild node command is queued for the battery powered device but does not prevent to ask for rebuilding routes of other nodes

**Comment by AlCalzone** [comment]
Like I mentioned in your other issue, this is part of a larger problem: https://github.com/zwave-js/node-zwave-js/issues/3707

Right now, rebuilding routes is not considered as a block of commands, but rather a parallel process that can send commands when it needs to. As a workaround, those tasks like rebuilding, firmware updating, etc. prevent other instances of those tasks to be started in parallel, because they would interfere with each other.
