### ISSUE TITLE
Missing device configuration: Zooz 800 Series Z-Wave Long Range Outdoor Motion Sensor ZSE70 800LR

### ISSUE THREAD

**Issue by ccurzio** [AlCalzone/node-zwave-js#7082]
### Checklist

- [x] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

Zooz ZSE70 800LR

### Manufacturer ID

0x027A

### Product Type

0x0004

### Product ID

0x0006

### Firmware Version

1.20

### Do you have a manual?

[zooz-zse70-800lr-manual.pdf](https://github.com/user-attachments/files/16487384/zooz-zse70-800lr-manual.pdf)

**Comment by craiglahote** [comment]
Device is not yet listed on Z-Wave Alliance website.

**Comment by AlCalzone** [comment]
Tracking this in https://github.com/zwave-js/node-zwave-js/issues/7123
