### ISSUE TITLE
Missing device configuration: Aeotec ZWA045

### ISSUE THREAD

**Issue by AlanMDicks** [AlCalzone/node-zwave-js#7121]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

Aeotec ZWA045-C

### Manufacturer ID

0x0371

### Product Type

0x0002

### Product ID

0x002d

### Firmware Version

2.7.1

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/5016?selectedFrequencyId=1

### Do you have a manual?

[Engineering Spec - Aeotec TriSensor 8 .pdf](https://github.com/user-attachments/files/16680069/Engineering.Spec.-.Aeotec.TriSensor.8.pdf)

**Comment by AlCalzone** [comment]
Tracking this in https://github.com/zwave-js/node-zwave-js/issues/7200
