### ISSUE TITLE
Fibaro FGR-224 command cover.open cover.up not working 

### ISSUE THREAD

**Issue by Loic691** [AlCalzone/node-zwave-js#7277]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

last one

### ZwaveJS version

last one

### Describe the bug

After 15 or 30 days randomly, commands cover.open and cover.up are not working from the HA zwave integration
The set set_cover_position works perfectly.
When I have the issues, I can close or open my cover with set_cover_position.
I tested in zwave JS UI and the command works
![image](https://github.com/user-attachments/assets/382c5c7e-c8fd-488f-9462-6fc9a866afca)
Cover calibration is OK

EDIT : I saw open and closed are inverted after few time....
When the cover is closed (0%) I can click on the UP arrow but nothing happens
If I call the actions cover.open=> nothing happens
If I call the actions cover.close => The cover opens.... => STRANGE

If I manually set the position to 100%, the cover is opening => OK
When the cover is opened, if I click on the Down arrow, nothing happens
If I call the actions cover.closen=> nothing happens
If I call the actions cover.open => The cover opens.... => STRANGE

The command are also inverted into ZWAVE-JS UI
![image](https://github.com/user-attachments/assets/5cbfb544-34db-4f61-b297-dfbb96c9e626)

### To Reproduce

Difficult to reproduce.
The issues appears between 15 or 30 days.
When I reboot the Fibaro FGR-224, the issues is no present
I don't know if it's a Fibaro bug or ZWave JS UI bug...

### Expected behavior

Commands works

**Comment by robertsLando** [comment]
@Loic691 Are you using HA Zwave-JS integration or mqtt discovery?

**Comment by Loic691** [comment]
Oh sorry @robertsLando 
Yes zwave-js intégration !

**Comment by Loic691** [comment]
After analyse this issue, I founded that action cover.open / close are inverted.
Strange because I haven't this behaviour before and I didn't change any parameters in ZWAVE...
The state in % of the cover is good
0% closed 100% opened
I edited the original post to update these informations

The command are also inverted into ZWAVE-JS UI

**Comment by mguyard** [comment]
Hello,

I've the same issue since HA 2024.10 (tested .1 and .2 with same behavior - don't have test .0)
All works great with 2024.9.3

What i've seen :

In 2024.9.3 this is received by ZwaveJS-UI :

> 2024-10-12 17:26:17.019 INFO Z-WAVE: [Node 028] Value updated: 106-0-targetValue-13 0 => 99
> 2024-10-12 17:27:05.994 INFO Z-WAVE: [Node 028] Value updated: 106-0-targetValue-13 99 => 0

In 2024.10.X, this is received by ZwaveJS-UI :
> 2024-10-12 17:20:06.160 INFO Z-WAVE: [Node 028] Value updated: 106-0-levelChangeUp-13 true => true
> 2024-10-12 17:17:02.978 INFO Z-WAVE: [Node 028] Value updated: 106-0-levelChangeDown-13 true => true

Following @Loic691 message, i've also tested in ZwaveJS UI and i've the same behavior by using Zwave WebUI :
![CleanShot 2024-10-12 at 17 31 29](https://github.com/user-attachments/assets/a89b65a7-45eb-45be-9b61-506f3161ab00)
 
For information, these parameters are not the defaults in my configuration :
![CleanShot 2024-10-12 at 17 33 21](https://github.com/user-attachments/assets/fb3c06ee-8980-4864-94f5-df09ddf27703)
I don't know if this can change something

On my side, issue is everytime here in ZwaveJS-UI but by HA, only in 2024.10 version (due to method change between version as explain above)

zwave-js-ui: 9.22.0
zwave-js: 13.8.0

**Comment by kpine** [comment]
Looks like this is due to a Home Assistant change added in 2024.10. https://github.com/home-assistant/core/pull/125827.

Have you tried changing parameter 25 to change the direction as a workaround?

![image](https://github.com/user-attachments/assets/2d65d1af-cae4-46bc-80c6-f9801d0cd001)

Setting to brightness to 99% is supposed to be the same as level change "Up", possibly a device bug?

**Comment by Loic691** [comment]
Hi @kpine 
I tried to change this 25 settings but it's not good...
After this change, the state in % of opening is inverted.... 0% for opened state and 99% for closed state...
In my case, the default parameter is good due to electrical connection with the covering motor (a garage shutter in my case wich have mecanical end stroke)

The first time I had the issue, I tried to reboot the FGR-224 and  everything return to normal...
I have 8 FGR-223 without issue.
I added 1 FGR-224 this summer and I have this issues twice since. It's strange.
I'm in the second time and i didn't reboot the FGR-224 to try to debug this issues.
Temporaly I resolved this issyes in my dashboard by calling set position To 0 and 100% instead fo calling cover_stop or cover_open (which are inverted)

**Comment by mguyard** [comment]
Hello,

I don't think issue is on HA side.
Ha 2024.10 just now use 106-0-targetValue-13 to move cover. The main issue is that 106-0-targetValue-13 in Zwave-JS-UI are inverted.

Changing param 25 will just stop my physical switch to works. 

I've also test with another FGR-224 where all parameters are defaults, same behavior when using levelChangeUp and LevelChangeDown in Zwave UI, actions are inverted

**Comment by kpine** [comment]
According to the Z-Wave specification, you're supposed to use position (`targetValue`) to set parameter 13:

![image](https://github.com/user-attachments/assets/1eeae031-71bf-476c-9d07-bb10702150b4)

Whereas parameter 12 is for level start/stop:

![image](https://github.com/user-attachments/assets/fd652a59-259d-4ebf-aba3-3285f70804a0)

So it's conceivable the device is not supporting level start/stop in this configuration.

**Comment by mguyard** [comment]
Hello @kpine,

Yes but if module don't support parameter 12, why this works when i use button on ZwaveUI for **[28-106-0-levelChangeUp-13] Open - Outbound Bottom** and **[28-106-0-levelChangeDown-13] Close - Outbound Bottom** but inverted.

When i click on start button for **[28-106-0-levelChangeUp-13] Open - Outbound Bottom** when it's already open, cover close. When already close, nothing is done.
When i click on start button for **[28-106-0-levelChangeDown-13] Close - Outbound Bottom** when it's already close, cover open. When already open, nothing is done.

**Comment by kpine** [comment]
> Yes but if module don't support parameter 12, why this works when i use button on ZwaveUI for [28-106-0-evelChangeUp-13] Open - Outbound Bottom and [28-106-0-levelChangeDown-13] Close - Outbound Bottom but inverted.

I don't understand the question. By your observation the cover is inverted. How is that "working"?

**Comment by mguyard** [comment]
My observation was, if module don't support levelChangeUp and levelChangeDown, why cover move when i use these buttons on ZwaveJS-UI ?

Cover move when i use it, but are inverted. levelChangeUp down the cover and levelChangeDown up the cover.

PS : Stop button works on each (levelChangeUp and levelChangeDown)

**Comment by kpine** [comment]
You will have to ask Fibaro that question, they designed it. "Supported" doesn't necessarily the command won't even work. Clearly it's not working, I'd say that's not supported.

The point is, you aren't supposed to use level change commands with parameter 13, as I understand it. Or, I'm incorrect and all window covering devices must support level changes, and in that case it's a device bug?

**Comment by mguyard** [comment]
So you mean that Fibaro don't support this or have inverted in his side ? Possible, i will try to see with Fibaro.

If i use the [28-106-0-targetValue-13] Target value - Outbound Bottom it's works great. And that was the usage before HA 2024.10 (and this is HA change).
I don't know how HA and ZwaveJS interract to this but don't have issue with FGR-221 who don't have levelChangeUp/levelChangeDown. Is it possible that as we have levelChangeUp/levelChangeDown available (in ZwaveJS-UI), HA identify they need to use it and in this case, if it's don't works, is it possible to remove these options for FGR-224 ?

I'm sorry if my question can be stupid, as i don't know how it's works behind the scene and how ZwaveJS identify which parameters are available for each modules

**Comment by kpine** [comment]
Prior to HA version 2024.10, all Window Covering devices were controlled by position 0/99 for close/open. Now in HA version 2024.10, all Window Covering devices are controlled by level change down/up for close/open.

It looks like this change was implemented for an [uncalibrated FGR-224](https://github.com/zwave-js/certification-backlog/issues/32), which uses parameter 12. Your calibrated devices (yes?) are using parameter 13. This is explained in the Fibaro docs:

![image](https://github.com/user-attachments/assets/6bedd464-eea5-48be-84bb-0eaf0abebb9e)

As I posted earlier, parameter 12 uses level start/stop to move the cover while parameter 13 is supposed to use position 0-99. I don't see anywhere in the Z-Wave spec that says when parameter 13 is supported then level start/stop commands are also supported. It's entirely possible I'm missing that or interpreting it wrong. So the way I see it,  either a) Z-Wave JS should not be allowing level commands for parameter 13, or b) the device has a bug and doesn't handle level change commands correctly for parameter 13. Or, a & b are correct, but the device should fail for level commands with parameter 13 instead of moving the cover.

Also, the Z-Wave spec does say that if parameter 13 is supported, then parameter 12 must not be.

You could ask Fibaro about this behavior as well, and see what they say.

**Comment by mguyard** [comment]
Thanks for your analysis.
I will work on 2 ways :
- Looking with Fibaro
- Working to understand why this change in HA generate a regression for all my FGR-224 and how to avoid this

**Comment by kpine** [comment]
Here's one more from the Z-Wave spec regarding level commands:

![image](https://github.com/user-attachments/assets/454293be-2031-4cf0-9752-67f6ba6a3fd5)

Based on this reading, even parameter 13 must support the level commands. Given that, I'd it would seem to be a device bug, as "up" always means open and "down" always means close.

**Comment by kpine** [comment]
> Working to understand why this change in HA generate a regression for all my FGR-224 and how to avoid this

I had explained this in the previous comments. In 2024.10 HA uses level commands to open and close. Before that it used position. You can avoid it by using [`cover.set_cover_position`](https://www.home-assistant.io/integrations/cover/#action-coverset_cover_position) actions (with 0 and 100% position) in HA, as posted in the previous comment. https://github.com/zwave-js/node-zwave-js/issues/7277

In HA:
set position == use targetValue with position value
open/close == use start level up and down

The open/close buttons in the UI use the open/close commands.

**Comment by mguyard** [comment]
I will try this but i suppose that i will have issue with up/down button in dashboard with this situation

**Comment by kpine** [comment]
Also, I think if you want proper support for this issue from the maintainers, I would suggest you provide the following information:

First, [driver debug logs](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs) (not application) of the following:

1. A re-interview of an affected device
2. Controlling the device both with a) targetValue and b) level commands

Second, a driver debug dump file, which can be downloaded from Control Panel -> Device -> Advanced -> Export json -> Driver.

Attach both as files in a comment (not text).

**Comment by mguyard** [comment]
All logs recommanded in attachment.
For the device control, i've done a Open and a close with targetValue 
and after that a open/close/open with level commands (who trigger a close/open/close move on cover)

[Z-Wave JS log 2024-10-13.log](https://github.com/user-attachments/files/17356737/Z-Wave.JS.log.2024-10-13.log)
[node_28_dump.json](https://github.com/user-attachments/files/17356738/node_28_dump.json)

**Comment by AlCalzone** [comment]
The device works as intended. It looks like Z-Wave JS has a bug where the up/down flag is sent inverted.

**Comment by Loic691** [comment]
Hi guys
Another tests this morning form ZWAVE JS UI only :

- Initial test : The shutter is closed and [47-106-0-currentValue-13] Current value - Outbound Bottom => 0%
- Click on [47-106-0-levelChangeUp-13] Open - Outbound Bottom => nothing happens
- [47-106-0-levelChangeDown-13] Close - Outbound Bottom => shutter opens to 99%

So at this instant, Open and Close command are inverted on ZWAVE JS UI
while the currentValue and TargetValue are OK

Reboot the FGR-224 :

Same behaviour

**Comment by AlCalzone** [comment]
The bug is in `node-zwave-js` which both HA and Z-UI use. v13.9.0 fixes the issue, so you'll have to wait for a new release of Z-UI and/or the addon.

**Comment by Loic691** [comment]
Thx

**Comment by MUN0X** [comment]
Was this issue resolved?

I’m about to buy 9 FGR-224 modules but wondering if i should go for 223 instead.
